web/components/FocusTrappedSidebar.tsx
web/components/navbar/NavBarLoggedInMobile.tsx
web/styles/left-nav.scss

Design team suggested making the animation quicker. Changed duration from .5s to .3s.

[#362] changed the duration of the open/close animation

---

web/components/tasks/LicenseTask.tsx
web/components/tasks/SearchBusinessName.tsx
web/components/tasks/UnlockedBy.tsx
web/display-content/tasks/TaskDefaults.ts
web/lib/async-content-fetchers/fetchTaskByFilename.ts
web/lib/roadmap/fixtures/add-ons/blocking.json
web/lib/roadmap/fixtures/task-dependencies.json
web/lib/roadmap/fixtures/tasks/blocked-task.md
web/lib/roadmap/fixtures/tasks/blocking-task-1.md
web/lib/roadmap/fixtures/tasks/blocking-task-2.md
web/lib/roadmap/roadmapBuilder.test.ts
web/lib/static/loadTasks.test.ts
web/lib/static/loadTasks.ts
web/lib/types/types.ts
web/lib/utils/helpers.ts
web/lib/utils/markdownReader.ts
web/pages/tasks/[urlSlug].tsx
web/roadmaps/task-dependencies.json
web/roadmaps/tasks/form-business-entity.md
web/test/factories.ts
web/test/pages/[urlSlug].test.tsx

468 show unlocked by

---

CHANGELOG.md
package.json

* **deps:** update aws-amplify ([333c42a](https://github.com/newjersey/navigator.business.nj.gov/commit/333c42a9fdd79b4c9ec469f03856a274c36b1824))
* **deps:** update emotion monorepo to v11.6.0 ([3381c8d](https://github.com/newjersey/navigator.business.nj.gov/commit/3381c8d16201080544f3987df1961b43cc770a79))
* **deps:** update material-ui monorepo ([b3b1b40](https://github.com/newjersey/navigator.business.nj.gov/commit/b3b1b405ff0b166fed9b0b51d5d7b07444933ecc))
* use env var for intercom hash ([05adbe6](https://github.com/newjersey/navigator.business.nj.gov/commit/05adbe68f470afae5b42e6210188f57b72aba3f1))
* [[#925](https://github.com/newjersey/navigator.business.nj.gov/issues/925)] add checkboxes to opt-out of newsletter and user testing …

chore(release): 1.2.0 [skip ci]

---

.circleci/config.yml
CHANGELOG.md
package.json

- build: set prod env vars for prepare release step
- chore(release): 1.3.0 [skip ci]

release 20211130

---

CHANGELOG.md
package.json

* [[#947](https://github.com/newjersey/navigator.business.nj.gov/issues/947)] corrected existing employees field validation issue ([a7f564f](https://github.com/newjersey/navigator.business.nj.gov/commit/a7f564fb50f348680d275ed96227c38f93e4ad51))
* [[#948](https://github.com/newjersey/navigator.business.nj.gov/issues/948)] wrap text & remove SDVOB ([cde6a5b](https://github.com/newjersey/navigator.business.nj.gov/commit/cde6a5b6516622863160243f20d827afed2bf8ba))
* update the netlify config for the updated roadmap config ([6141db5](https://github.com/newjersey/navigator.business.nj.gov/commit/6141db55ce3f20359ad3f7a4aa732fc2bba083c4))
* [[#947](https://github.com/newjersey/navigator.business.nj.gov/issues/947)] existing employees field added to onboarding …

chore(release): 1.4.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#1187](https://github.com/newjersey/navigator.business.nj.gov/issues/1187)] fix duplicate external sync issues ([f3a1d93](https://github.com/newjersey/navigator.business.nj.gov/commit/f3a1d93641b87fa84f90a624474b855adf78aa4d))
* **deps:** update aws-amplify ([a534db0](https://github.com/newjersey/navigator.business.nj.gov/commit/a534db034d4cbf3a823d7614cd95fb59cbb53d63))
* **deps:** update dependency @emotion/react to v11.7.1 ([9a22346](https://github.com/newjersey/navigator.business.nj.gov/commit/9a22346d1b87e216e5f616dce869e4666a36a00b))
* **deps:** update dependency express to v4.17.2 ([a01a162](https://github.com/newjersey/navigator.business.nj.gov/commit/a01a16206ee868ff6d974022df68cb8527f7c4ff))
* **deps:** update material-ui monorepo …

chore(release): 1.6.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#1226](https://github.com/newjersey/navigator.business.nj.gov/issues/1226)] correct the data being passed to the myNJ log message ([3ca0970](https://github.com/newjersey/navigator.business.nj.gov/commit/3ca0970a7818a583f7c7446d6942405335f53751))
* [[#977](https://github.com/newjersey/navigator.business.nj.gov/issues/977)] await all the submits to fix act error ([bf483a9](https://github.com/newjersey/navigator.business.nj.gov/commit/bf483a95500462b0a9e4bc02964dbca8514c7a75))
* [[#977](https://github.com/newjersey/navigator.business.nj.gov/issues/977)] ensure it logs the request/response properly ([c0052b6](https://github.com/newjersey/navigator.business.nj.gov/commit/c0052b68f6c29eafccd6bf4936da87cc2c004b75))
* corrected spacing on profile page …

chore(release): 1.7.0 [skip ci]

---

CHANGELOG.md
package.json

* **deps:** update material-ui monorepo ([24ce4a7](https://github.com/newjersey/navigator.business.nj.gov/commit/24ce4a77e18a3d2d94b3fcd805f7805c0fc4889a))
* [[#876](https://github.com/newjersey/navigator.business.nj.gov/issues/876)] google analytics improvements ([e2856c5](https://github.com/newjersey/navigator.business.nj.gov/commit/e2856c5a2821c596208243582db46834f6b86471))
* [[#977](https://github.com/newjersey/navigator.business.nj.gov/issues/977)] business formation - updated response error logic ([7bd9124](https://github.com/newjersey/navigator.business.nj.gov/commit/7bd9124af95490777fab520e8b604dd8e2a116cf))
* [[#977](https://github.com/newjersey/navigator.business.nj.gov/issues/977)] fixed accessability issues on business formation …

chore(release): 1.8.0 [skip ci]

---

CHANGELOG.md
package.json
web/src/pages/_app.tsx

- fix: Google analytics dimension
- chore(release): 1.8.1 [skip ci]

release 20220110

---

CHANGELOG.md
package.json

* [[#1072](https://github.com/newjersey/navigator.business.nj.gov/issues/1072)] auto-fill validation on submit ([4816e81](https://github.com/newjersey/navigator.business.nj.gov/commit/4816e8135e70eaee04d7b077497b13434651ad89))
* [[#1072](https://github.com/newjersey/navigator.business.nj.gov/issues/1072)] display dependency alert on first tab only ([7c60b62](https://github.com/newjersey/navigator.business.nj.gov/commit/7c60b62ad8b04c1c71a0fadec30d688b5eb6adb4))
* [[#1072](https://github.com/newjersey/navigator.business.nj.gov/issues/1072)] hide response alert when submit page is revisited ([b669d52](https://github.com/newjersey/navigator.business.nj.gov/commit/b669d527de49e47792f217dfafb58b725e57d597))
* [[#1072](https://github.com/newjersey/navigator.business.nj.gov/issues/1072)] remove …

chore(release): 1.9.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#1188](https://github.com/newjersey/navigator.business.nj.gov/issues/1188)] correct the placeholder for the legal structure dropdown ([4eb6da8](https://github.com/newjersey/navigator.business.nj.gov/commit/4eb6da8ddb150a98525578d7311d7a4ff654ae00))
* [[#1326](https://github.com/newjersey/navigator.business.nj.gov/issues/1326)] create archive for funding markdowns ([6a32a53](https://github.com/newjersey/navigator.business.nj.gov/commit/6a32a53ed1ae641a875ac1c9e556add8e0380479))
* [[#1326](https://github.com/newjersey/navigator.business.nj.gov/issues/1326)] move archived-opportunities folder ([422e5c1](https://github.com/newjersey/navigator.business.nj.gov/commit/422e5c10f7ca905812bf6436010879b8fbf329a7))
* [[#1364](https://github.com/newjersey/navigator.business.nj.gov/issues/1364)] …

chore(release): 1.11.0 [skip ci]

---

CHANGELOG.md
package.json

* **deps:** update aws-amplify ([1cebef9](https://github.com/newjersey/navigator.business.nj.gov/commit/1cebef939c7fba184ecd71b00b2a4ee06e5e6ab8))
* **deps:** update dependency next-seo to v5.1.0 ([57100c2](https://github.com/newjersey/navigator.business.nj.gov/commit/57100c2c6f56680321aa4c8c8810769f4382dc72))
* **deps:** update dependency winston to v3.5.1 ([32756e4](https://github.com/newjersey/navigator.business.nj.gov/commit/32756e419708faac681c798d2a96770ac2ca1a8e))
* **deps:** update material-ui monorepo ([40af36d](https://github.com/newjersey/navigator.business.nj.gov/commit/40af36d826f3f5ecbe25f212d9f052c89045f25b))
* make fields optional for funding in netlify ([a86490f](https://github.com/newjersey/navigator.business.nj.gov/commit/a86490f5e47e09ad6496bb07bb23d259bc592438))
* …

chore(release): 2.0.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#1439](https://github.com/newjersey/navigator.business.nj.gov/issues/1439)] update beta bar color and remove tag ([bc008e5](https://github.com/newjersey/navigator.business.nj.gov/commit/bc008e583de2bc9525bf606d59f8667f8b46f1d6))
* [[#1443](https://github.com/newjersey/navigator.business.nj.gov/issues/1443)] favicon transparency ([db71f90](https://github.com/newjersey/navigator.business.nj.gov/commit/db71f900d1f635a66d4faaf1d41284359579589d))
* [[#1557](https://github.com/newjersey/navigator.business.nj.gov/issues/1557)] do not show tax filing if date of formation empty ([b2410ac](https://github.com/newjersey/navigator.business.nj.gov/commit/b2410acedf73ec55a58771ea7617bbfdfcaa2443))
* [[#1853](https://github.com/newjersey/navigator.business.nj.gov/issues/1853)] required text showing …

chore(release): 2.2.0 [skip ci]

---

CHANGELOG.md
package.json
web/package.json

- fix: correct build step
- chore(release): 2.2.1 [skip ci]

release 20220225

---

CHANGELOG.md
package.json

* [[#1204](https://github.com/newjersey/navigator.business.nj.gov/issues/1204)] add feature flag logic to business name check in formation ([b83978f](https://github.com/newjersey/navigator.business.nj.gov/commit/b83978f1b3d70499563c727a240288f4f1e6a83d))
* [[#1561](https://github.com/newjersey/navigator.business.nj.gov/issues/1561)] require industry field for new business owners ([802b749](https://github.com/newjersey/navigator.business.nj.gov/commit/802b7490baae4e7f969f010959fa8d93afa0caa0))
* [[#1648](https://github.com/newjersey/navigator.business.nj.gov/issues/1648)] fix funding sorting ([11273e6](https://github.com/newjersey/navigator.business.nj.gov/commit/11273e68afacee3e2037febb89901597e2d05bf7))
* [[#1648](https://github.com/newjersey/navigator.business.nj.gov/issues/1648)] fix …

chore(release): 2.3.0 [skip ci]

---

content/src/roadmaps/tasks/conversionlicense-cannabis.md

fix: updating Tasks conversionlicense-cannabis

chore: creating Tasks conversionlicense-cannabis

---

content/src/roadmaps/tasks/annual-license-cannabis.md

fix: updating Tasks annual-license-cannabis

chore: creating Tasks annual-license-cannabis

---

content/src/roadmaps/tasks/conditional-permit-cannabis.md

Automatically generated. Merged on Netlify CMS.

fix: updating Tasks conditional-permit-cannabis (#2035)

---

CHANGELOG.md
package.json

* update corporation names ([27773af](https://github.com/newjersey/navigator.business.nj.gov/commit/27773af6abdc203734becfc662b7fde4e42ecde9))
* updating General Config config ([#2204](https://github.com/newjersey/navigator.business.nj.gov/issues/2204)) ([5998220](https://github.com/newjersey/navigator.business.nj.gov/commit/5998220d889502213f29a90a666d3f382fb0ba53))
* updating General Config config ([#2242](https://github.com/newjersey/navigator.business.nj.gov/issues/2242)) ([bf44e89](https://github.com/newjersey/navigator.business.nj.gov/commit/bf44e89a3f7aa551a2b99d65be9d4d0157bce3b0))
* updating General Config config ([#2259](https://github.com/newjersey/navigator.business.nj.gov/issues/2259)) ([9831369](https://github.com/newjersey/navigator.business.nj.gov/commit/98313694c0f28ea2f9c …

chore(release): 3.1.1 [skip ci]

---

content/src/roadmaps/add-ons/physical-location.json

Automatically generated. Merged on Netlify CMS.

fix: updating Roadmap Add-ons physical-location (#2397)

---

CHANGELOG.md
package.json

* updating General Config config ([#2369](https://github.com/newjersey/navigator.business.nj.gov/issues/2369)) ([e4a44f2](https://github.com/newjersey/navigator.business.nj.gov/commit/e4a44f2b9a6971372b623180c09df1319902b0d6))
* updating Industry Roadmaps auto-body-repair ([#2371](https://github.com/newjersey/navigator.business.nj.gov/issues/2371)) ([ac881ea](https://github.com/newjersey/navigator.business.nj.gov/commit/ac881eaf51f059d4bd6e80de74f823e51ce2dd84))
* updating Industry Roadmaps cannabis ([#2373](https://github.com/newjersey/navigator.business.nj.gov/issues/2373)) ([2cdfe43](https://github.com/newjersey/navigator.business.nj.gov/commit/2cdfe43babad3bd2b63e7bede3ffc30d21cf78b8))
* updating Industry Roadmaps cannabis ([#2407](https://github.com/newjersey/navigator.business.nj.gov …

chore(release): 3.2.2 [skip ci]

---

CHANGELOG.md
package.json

* **deps:** update dependency swr to v1.3.0 ([bb6897d](https://github.com/newjersey/navigator.business.nj.gov/commit/bb6897d62fac204fa9c43c4aeeeafcc2f6b2f7a2))
* [[#1444](https://github.com/newjersey/navigator.business.nj.gov/issues/1444)] add analytics events for Formation ([045f135](https://github.com/newjersey/navigator.business.nj.gov/commit/045f135dbdabc51dfea1fdb4e9102760fbc28e88))

chore(release): 3.3.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#1909](https://github.com/newjersey/navigator.business.nj.gov/issues/1909)] email validation on onboarding last step ([7b44234](https://github.com/newjersey/navigator.business.nj.gov/commit/7b44234e8ae46e288a47c1952c097aa500e8b850))
* [[#2004](https://github.com/newjersey/navigator.business.nj.gov/issues/2004)] always show roadmap header from user name ([09c7f6b](https://github.com/newjersey/navigator.business.nj.gov/commit/09c7f6bf2344b0040ee6d1005dadc0feb34f7ff1))
* [[#2004](https://github.com/newjersey/navigator.business.nj.gov/issues/2004)] fix email validation onboarding test ([a2d756a](https://github.com/newjersey/navigator.business.nj.gov/commit/a2d756a08d1fe26a6b0e976b4a124924e92e3466))
* cypress onboarding bug ([f2d8352](https://github.com/newjersey/navigator.business.nj.gov/c …

chore(release): 3.4.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#2463](https://github.com/newjersey/navigator.business.nj.gov/issues/2463)] add spinner button to NAICS save button ([3761a19](https://github.com/newjersey/navigator.business.nj.gov/commit/3761a19778173f557c8e04a6227144fd0e46489b))
* [[#2463](https://github.com/newjersey/navigator.business.nj.gov/issues/2463)] handle naics update race condition ([3d2e6cb](https://github.com/newjersey/navigator.business.nj.gov/commit/3d2e6cb8872a9140a5efab489c7a7388366056cc))
* [[#2636](https://github.com/newjersey/navigator.business.nj.gov/issues/2636)] submit Members modal with municipality name (not displayname) ([968604d](https://github.com/newjersey/navigator.business.nj.gov/commit/968604db9f5c7455868a57d4edce3bf21877f711))
* checkbox styling on CMS …

chore(release): 3.6.0 [skip ci]

---

CHANGELOG.md
package.json

* enable business purpose and provisions for llc formation ([90b8151](https://github.com/newjersey/navigator.business.nj.gov/commit/90b81512888b296252d62e3e90423e96ac5a00a9))

chore(release): 3.8.1 [skip ci]

---

CHANGELOG.md
package.json

* **deps:** pin dependency @types/ua-parser-js to 0.7.36 ([955ac5a](https://github.com/newjersey/navigator.business.nj.gov/commit/955ac5aa94062b27312a81af3e6b42d1c7586415))
* **deps:** update aws-sdk ([0c5bd4b](https://github.com/newjersey/navigator.business.nj.gov/commit/0c5bd4b981d00e41868bbac14748d1c3fc3dcbc7))
* [[#2247](https://github.com/newjersey/navigator.business.nj.gov/issues/2247)] request a feature feedback modal ([d422076](https://github.com/newjersey/navigator.business.nj.gov/commit/d422076a1ba5e0b297662df2ac16f67b32a1e397))

chore(release): 3.9.0 [skip ci]

---

CHANGELOG.md
package.json
web/src/components/tasks/NaicsCodeInput.tsx

- fix: correct issue with NAICS code descriptions not properly displaying
- chore(release): 3.9.1 [skip ci]

release 20220524

---

CHANGELOG.md
package.json

* [[#2246](https://github.com/newjersey/navigator.business.nj.gov/issues/2246)] both validations fire on report an issue modal ([b0426f9](https://github.com/newjersey/navigator.business.nj.gov/commit/b0426f9690f003b3052e73c5280c88172b7279cc))
* [[#2761](https://github.com/newjersey/navigator.business.nj.gov/issues/2761)] check for undefined in onboarding ([7e7069b](https://github.com/newjersey/navigator.business.nj.gov/commit/7e7069b4991536bbf32a2d7e06fe9080f2f6324b))
* [[#2913](https://github.com/newjersey/navigator.business.nj.gov/issues/2913)] adjust content for remote seller ([bee6727](https://github.com/newjersey/navigator.business.nj.gov/commit/bee67272ae045bff8341b4041d7656c4a92e8aeb))
* [[#2913](https://github.com/newjersey/navigator.business.nj.gov/issues/2913)] adjust content …

chore(release): 3.11.0 [skip ci]

---

CHANGELOG.md
api/src/api/formationRouter.test.ts
api/src/api/formationRouter.ts
api/src/client/ApiFormationClient.test.ts
api/src/client/ApiFormationClient.ts
package.json
web/src/components/tasks/business-formation/BusinessFormation.tsx
web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx

- fix: correct field for business formation name
- chore(release): 3.12.1 [skip ci]

release 20220613

---

CHANGELOG.md
package.json

* add register text to forms that show the register modal ([b37def5](https://github.com/newjersey/navigator.business.nj.gov/commit/b37def5d7d44fe5f7533b8a69f3a81c4efe8ae0a))
* **deps:** update aws-sdk ([db06245](https://github.com/newjersey/navigator.business.nj.gov/commit/db06245b7fc2b3794341c75d60616e043d2ba7b7))
* **deps:** update dependency focus-trap-react to v9 ([43c758c](https://github.com/newjersey/navigator.business.nj.gov/commit/43c758c663a45c173c8fe9e57b002f600573d114))
* **deps:** update emotion monorepo to v11.9.3 ([d6aa140](https://github.com/newjersey/navigator.business.nj.gov/commit/d6aa140dd22ec512d27f2adfcea2b206cd5584b7))
* improved error messaging for business name search when searching with designators ([2c04811](https://github.com/newjersey/navigator.business.nj.gov/c …

chore(release): 3.12.2 [skip ci]

---

CHANGELOG.md
package.json

* [[#182374961](https://github.com/newjersey/navigator.business.nj.gov/issues/182374961)] nexus business profile ([933450a](https://github.com/newjersey/navigator.business.nj.gov/commit/933450addc922aa1a269270d58038122711073dd))

chore(release): 4.2.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#182374942](https://github.com/newjersey/navigator.business.nj.gov/issues/182374942)] only trigger sign-in from loading if no code provided ([82371ee](https://github.com/newjersey/navigator.business.nj.gov/commit/82371ee35660b82c1d55b0067fc0788b1f480e64))
* [[#182795535](https://github.com/newjersey/navigator.business.nj.gov/issues/182795535)] remove business plan step from nexus roadmap ([0f762a4](https://github.com/newjersey/navigator.business.nj.gov/commit/0f762a4ebc74f6cde86a9b275d8ae7ea75eea154))
* [[#182809081](https://github.com/newjersey/navigator.business.nj.gov/issues/182809081)] update how the naics code is dynamically rendered to add the title ([da9a6d3](https://github.com/newjersey/navigator.business.nj.gov/commit/da9a6d34200052eed3d6d6f2ad1dedebb975bc54))
* …

chore(release): 4.4.0 [skip ci]

---

CHANGELOG.md
api/src/db/migrations/migrations.ts
api/src/db/migrations/v75_fix_trade_name_operating_phase.test.ts
api/src/db/migrations/v75_fix_trade_name_operating_phase.ts
api/src/db/migrations/v76_fix_trade_name_operating_phase_round_2.test.ts
api/src/db/migrations/v76_fix_trade_name_operating_phase_round_2.ts
api/src/domain/user/updateOperatingPhase.test.ts
api/src/domain/user/updateOperatingPhase.ts
package.json
web/src/pages/onboarding.tsx

- fix: correct logic for switching legal structures when in the needs_to_form operating phase
- chore(release): 4.4.2 [skip ci]

release 20220801

---

CHANGELOG.md
package.json

* [[#182918196](https://github.com/newjersey/navigator.business.nj.gov/issues/182918196)] trigger guest sign-in for myNJ login user bug ([e071b78](https://github.com/newjersey/navigator.business.nj.gov/commit/e071b78bb4fd56fdbd05add00760184e82dcad72))
* [[#183002925](https://github.com/newjersey/navigator.business.nj.gov/issues/183002925)] broken nexus formation link ([8f4d7f6](https://github.com/newjersey/navigator.business.nj.gov/commit/8f4d7f6bd3d32e838558fbe92891a301f48425d5))
* [Finishes [#183012790](https://github.com/newjersey/navigator.business.nj.gov/issues/183012790)] url-encoding for special characters in business name search ([1283194](https://github.com/newjersey/navigator.business.nj.gov/commit/12831944905bc77ebc6cc4265bce19cba9032e03))
* **deps:** update aws-sdk to v3.145.0 …

chore(release): 5.1.0 [skip ci]

---

CHANGELOG.md
api/src/client/MyNjSelfRegClient.ts
package.json

- fix: add additional logging for MyNJ requests
- chore(release): 5.1.1 [skip ci]

release 20220818

---

CHANGELOG.md
api/src/db/migrations/migrations.ts
api/src/db/migrations/v84_fix_completed_filing.ts
package.json

- fix: set completedFilingPayment to false if user has no successful getFiling response
- chore(release): 5.2.1 [skip ci]

release 20220901

---

CHANGELOG.md
package.json

* [[#183014824](https://github.com/newjersey/navigator.business.nj.gov/issues/183014824)] tax filings modal open after registration redirect ([7767d95](https://github.com/newjersey/navigator.business.nj.gov/commit/7767d9544486d11fdfbe7f653702972834d73f48))
* corrected spelling error ([caec846](https://github.com/newjersey/navigator.business.nj.gov/commit/caec846c6f2b3b588f0d25ff91a3a4f73324cd2f))
* **deps:** update aws-amplify ([029ca08](https://github.com/newjersey/navigator.business.nj.gov/commit/029ca08b81eb13334874e8466f7cff4329cac1ec))
* **deps:** update dependency next-seo to v5.6.0 ([56ee838](https://github.com/newjersey/navigator.business.nj.gov/commit/56ee83841f12cfad2c47e8f4be33297f420cc8db))
* **deps:** update dependency ua-parser-js to v1.0.32 …

chore(release): 5.7.0 [skip ci]

---

CHANGELOG.md
package.json
shared/src/test/formationFactories.ts
web/src/components/tasks/business-formation/contacts/ContactsStep.test.tsx
web/src/components/tasks/business-formation/contacts/ContactsStep.tsx
web/src/components/tasks/business-formation/contacts/Members.tsx

- fix: [#184035288] send town name (not display name) for members in formation
- chore(release): 5.9.1 [skip ci]

release 20221212

---

CHANGELOG.md
package.json

- fix: production re-deploy
- chore(release): 5.10.1 [skip ci]

release 20230110

---

CHANGELOG.md
package.json

* updating Contextual Information animal-facilities ([#5039](https://github.com/newjersey/navigator.business.nj.gov/issues/5039)) ([82d6563](https://github.com/newjersey/navigator.business.nj.gov/commit/82d65633a1d1edf6be6c17ab509d094a5327e83b))
* updating Roadmaps - Industries petcare ([#5052](https://github.com/newjersey/navigator.business.nj.gov/issues/5052)) ([fb9d292](https://github.com/newjersey/navigator.business.nj.gov/commit/fb9d292dde2c01c01769b4622316496453e4b3b9))
* updating Tasks - All detective-employees ([#5045](https://github.com/newjersey/navigator.business.nj.gov/issues/5045)) ([6b44655](https://github.com/newjersey/navigator.business.nj.gov/commit/6b4465510d320460a3bb7b0aaa15cb566cb25cf5))
* updating Tasks - All petcare-license …

chore(release): 5.11.0 [skip ci]

---

CHANGELOG.md
content/src/fieldConfig/nexus-dba-formation.json
package.json
web/public/mgmt/config.yml
web/src/components/onboarding/ProfileNexusBusinessNameField.tsx

- fix: updating business-name-search-nexus links
- chore(release): 5.11.1 [skip ci]

release 20230111

---

CHANGELOG.md
package.json

* [[#183677932](https://github.com/newjersey/navigator.business.nj.gov/issues/183677932)] tax id show/hide hover and split field width in profile ([43a11d8](https://github.com/newjersey/navigator.business.nj.gov/commit/43a11d85f54ff139ed2bf198ee667188b8301934))
* [[#183901658](https://github.com/newjersey/navigator.business.nj.gov/issues/183901658)] calendar year selector visual treatments ([e2c2bdd](https://github.com/newjersey/navigator.business.nj.gov/commit/e2c2bddfa2318734cd504c721ee6b21655238868))
* [[#184162422](https://github.com/newjersey/navigator.business.nj.gov/issues/184162422)] add env vars to next.config for basic auth ([e851211](https://github.com/newjersey/navigator.business.nj.gov/commit/e851211e10b5dcce759f73dac0457bbd14f1154b))
* …

chore(release): 5.13.0 [skip ci]

---

api/src/client/ApiBusinessNameClient.test.ts
api/src/client/ApiBusinessNameClient.ts
shared/src/businessNameSearch.ts
web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/getErrorStateForField.test.ts
web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx
web/src/components/tasks/business-formation/name/BusinessNameStep.tsx
web/src/components/tasks/business-formation/name/NexusSearchBusinessNameStep.test.tsx
web/src/components/tasks/search-business-name/SearchBusinessNameForm.test.tsx
web/src/components/tasks/search-business-name/SearchBusinessNameForm.tsx

chore: [#184587677] refactor name search status to reflect error

---

CHANGELOG.md
package.json

* [[#183314453](https://github.com/newjersey/navigator.business.nj.gov/issues/183314453)] import fix to meet dependency check ([b17291f](https://github.com/newjersey/navigator.business.nj.gov/commit/b17291fac5a3d89ee12e31b0f0147c56c2ed6fd7))
* [[#183314453](https://github.com/newjersey/navigator.business.nj.gov/issues/183314453)] welcome-up-and-running card close button ([7c51b3b](https://github.com/newjersey/navigator.business.nj.gov/commit/7c51b3b936439a63e811c9869d6a1fc51a206dff))
* [[#184506340](https://github.com/newjersey/navigator.business.nj.gov/issues/184506340)] display LLC name NOT id in locked profile field ([c944814](https://github.com/newjersey/navigator.business.nj.gov/commit/c9448141ebeb0d5a3e27729924e773898f88aab4))
* …

chore(release): 5.15.0 [skip ci]

---

CHANGELOG.md
package.json
web/src/components/tasks/business-formation/business/ForeignStateOfFormation.tsx
web/src/components/tasks/business-formation/business/FormationDate.tsx

- fix: [#184688502] fix nexus formation date label
- chore(release): 5.15.1 [skip ci]

release 20230313

---

.github/pull_request_template.md

Creates a simple pull request template. Pasted below to conveniently render markdown.
---
This is a basic pull request template. I am making this in response to a Techtro action item.
[#123456](https://www.pivotaltracker.com/n/projects/2573455)
This is a fairly common template pattern that I've used and seen used on other projects. You can be as detailed as you want to in each of these sections while none of them are required. Use this space as you see necessary to create a paper trail for yourself and others.
I purposely am submitting this pull request template as a PR so others can comment and make suggestions on it.

chore(pr-template): create simple pull request template

---

CHANGELOG.md
package.json

* [[#184700586](https://github.com/newjersey/navigator.business.nj.gov/issues/184700586)] increase option limit for netlify relations dropdowns ([6653e92](https://github.com/newjersey/navigator.business.nj.gov/commit/6653e92fa198ed4a87aa65f11b05400e1587b691))
* [[#184718036](https://github.com/newjersey/navigator.business.nj.gov/issues/184718036)] welcome card now closes when the close button is hit ([84e9225](https://github.com/newjersey/navigator.business.nj.gov/commit/84e9225a3c2d01ed790f2260390e78f60f1ef930))
* added updated inline error validations on profile dakota nexus fields ([c2b570b](https://github.com/newjersey/navigator.business.nj.gov/commit/c2b570b466e15fb119845bf17c1b88f56059ded4))
* adding missing apt package for chrome installation …

chore(release): 5.16.0 [skip ci]

---

content/src/fieldConfig/dashboard-calendar.json
web/public/mgmt/config.yml
web/src/components/filings-calendar/EmptyCalendar.tsx
web/src/components/filings-calendar/FilingsCalendar.test.tsx
web/src/components/filings-calendar/FilingsCalendar.tsx
web/test/factories.ts

[#184432275](https://www.pivotaltracker.com/story/show/184432275)
also broke out EmptyCalendar as its own component

feat: [#184432275] add formation date prompt to calendar

---

api/src/db/migrations/v106_added_pet_care_housing_essential_question.test.ts

I removed an unnecessary pet care essential question migration test because it was testing for a new user, which doesn't exist in migration.
https://www.pivotaltracker.com/n/projects/2573455/stories/184327505
N/A
N/A
N/A

fix: [#184327505] remove unneccessary petcare migration test for new user

---

content/src/fieldConfig/config.json
content/src/fieldConfig/dashboard-calendar.json
shared/src/operatingPhase.ts
web/public/mgmt/config.yml
web/src/components/profile/ProfileField.tsx
web/src/components/profile/ProfileOpportunitiesAlert.tsx
web/src/lib/domain-logic/opportunityFields.ts
web/src/lib/utils/helpers.ts
web/src/pages/profile.tsx
web/test/pages/profile.test.tsx

[#184432315](https://www.pivotaltracker.com/story/show/184432315)

feat: [#184432315] add opportunities alert to profile

---

web/src/components/filings-calendar/FilingsCalendarTaxAccess.tsx

I updated the Get Access calendar button type and border color.
[184439900](https://www.pivotaltracker.com/n/projects/2573455/stories/184439900)
N/A
N/A
N/A

feat: [#184439900] update get access button type and color

---

web/src/lib/domain-logic/essentialQuestionHelpers.test.ts

Updated `essentialQuestionsHelpers.test.ts` to add mock industries so that if the content team ever changes a toggle, those tests will not fail.
[184533882](https://www.pivotaltracker.com/n/projects/2573455/stories/184533882)
Added mock industries to the test file.
N/A

refactor essential questions tests

---

web/public/intercom/identity.js
web/src/components/IntercomScript.tsx
web/src/contexts/intercomContext.ts
web/src/lib/data-hooks/useUserData.ts
web/src/pages/_app.tsx

Added the legal structure and industry to the intercom in an effort to phase out the Airtable model we are currently using.
[184533765](https://www.pivotaltracker.com/n/projects/2573455/stories/184533765)
N/A
Once you go through a persona and select an industry and legal structure, use the dev inspector tools to check that the data is present in the `src` attribute of the `script` tag that points to **intercom/identity.js**.
I need some guidance/context as to how to check for for user data in Airtable to ensure we add all of the user data we want present in the intercom to ensure a successful migration from the Airtable model. If you can provide this guidance/context, please let me know. Thanks!

feat: [184533765] add legal structure and industry to intercom

---

api/.eslintrc.json
api/src/domain/updateSidebarCards.ts
shared/.eslintrc.json
web/.eslintrc.json
web/src/components/tasks/business-formation/DbaFormationPaginator.tsx
web/src/lib/data-hooks/useFormationErrors.tsx

Add ESLint rule to require the use of === and !== (over == and !=)
[#184814236](https://www.pivotaltracker.com/story/show/#184814236)
N/A
Run `yarn eslint` to determine whether == and != is being used in the codebase.
N/A

chore: [#184814236] add ESLint rule to require use of === and !== (over == and !=)

---

CHANGELOG.md
api/src/api/userRouter.test.ts
api/src/api/userRouter.ts
package.json

- fix: remove await licenseCheck and check in background only
- chore(release): 5.17.1 [skip ci]

release 20230411

---

web/public/intercom/identity.js

Change variable declarations in the from `let` back to`var` to fix the bug to allow user data to flow to the intercom.
[184533765](https://www.pivotaltracker.com/story/show/184533765)
N/A
N/A
N/A

fix: [#184533765] change variable declarations back to var b/c user data is not going to intercom

---

.github/pull_request_template.md

chore: pull request template update

---

web/public/intercom/identity.js

Fix to send legal structure, industry, & business persona to Intercom
[#184533765](https://www.pivotaltracker.com/story/show/184533765)
N/A
Via Intercom: go through formation in dev and check to see that legal structure, industry, & business persona populate

fix: [#184533765] update getAttribute send legal structure, industry, & business persona to Intercom

---

api/src/db/migrations/migrations.ts
api/src/db/migrations/v110_rename_form_progress_to_onboarding_form_progress.ts
api/test/factories.ts
shared/src/domain-logic/onboarding.ts
shared/src/userData.ts
web/cypress/support/commands.js
web/src/components/PageSkeleton.test.tsx
web/src/components/PageSkeleton.tsx
web/src/components/feedback-modal/FeedbackModal.test.tsx
web/src/components/feedback-modal/SelectFeedbackModal.tsx
web/src/lib/auth/signinHelper.test.ts
web/src/lib/auth/signinHelper.ts
web/src/lib/data-hooks/useRoadmap.test.tsx
web/src/lib/data-hooks/useRoadmap.ts
web/src/pages/dashboard.tsx
web/src/pages/index.tsx
web/src/pages/onboarding.tsx
web/test/factories.ts
web/test/pages/dashboard.test.tsx
web/test/pages/index.test.tsx
web/test/pages/loading.test.tsx
web/test/pages/onboarding/helpers-onboarding.tsx
web/test/pages/onboarding/onboarding-foreign.test.tsx
web/test/pages/onboarding/onboarding-owning.test.tsx
web/test/pages/onboarding/onboarding-shared.test.tsx
web/test/pages/onboarding/onboarding-starting.test.tsx
web/test/pages/profile.test.tsx

Rename `formProgess` to `onboardingFormProgress` in `userData` to increase clarity.
[#184939425](https://www.pivotaltracker.com/story/show/184939425)

chore: [#184939425] rename formProgress to onboardingFormProgress

---

web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/src/components/tasks/business-formation/review/section/ReviewSection.tsx

Refactor heading for stepper
[#184305952](https://www.pivotaltracker.com/story/show/184305952)
N/A
N/A
N/A

chore: [#184305952] formation review section refactor

---

web/src/components/njwds-extended/FileInput.tsx
web/src/styles/base/global.scss

Updates to #5603 based on design feedback.
[183443674](https://www.pivotaltracker.com/story/show/183443674)

Update: feat: [#183443674] update c-corp formation

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx
web/src/components/tasks/business-formation/business/ForeignCertificate.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.test.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx
web/src/components/tasks/business-formation/review/ReviewMainBusinessLocation.tsx
web/src/components/tasks/business-formation/review/ReviewMembers.tsx
web/src/components/tasks/business-formation/review/ReviewRegisteredAgent.tsx
web/src/components/tasks/business-formation/review/ReviewSignatures.tsx
web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/section/ReviewLineItem.tsx
web/src/lib/utils/formatters.test.ts
web/src/lib/utils/formatters.ts
web/src/styles/base/global.scss

Fixes for the formation review page reorganization
1. Standardized labels to match within steps and review page
2. Broke address apart into multiple fields
3. Added missing signer name field in the review page
4. Added more width to review line items to avoid wrapping  
[184305952](https://www.pivotaltracker.com/story/show/184305952)

fix: [#184305952] review page address and label fixes

---

web/src/components/search/ConfigMatchList.tsx
web/src/lib/search/helpers.ts
web/src/lib/search/searchConfig.ts
web/src/lib/search/typesForSearch.ts
web/src/lib/static/loadCmsConfig.ts
web/src/pages/mgmt/search.tsx

chore: [#182479557] add config search to cms search

---

web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/src/components/tasks/business-formation/review/section/ReviewLineItem.tsx

Fixed spacing on review page fields. 
[184305952](https://www.pivotaltracker.com/story/show/184305952)

fix: [#184305952] review page fields spacing

---

.circleci/config.yml
web/next.config.js
web/src/pages/_app.tsx
web/src/pages/_document.tsx

fix: hide gtm iframe for accessibility

---

web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx

Update logic and test for signers section
[#184998185](https://www.pivotaltracker.com/story/show/184998185)
N/A
N/A

fix: [#184305952] update logic and test for signers

---

content/src/fieldConfig/business-formation.json
web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx
web/src/components/tasks/business-formation/review/ReviewBillingContact.tsx
web/src/components/tasks/business-formation/review/ReviewBillingServices.tsx
web/src/components/tasks/business-formation/review/ReviewBusinessSuffixAndStartDate.tsx
web/src/components/tasks/business-formation/review/ReviewForeignCertificate.tsx
web/src/components/tasks/business-formation/review/ReviewMainBusinessLocation.tsx
web/src/components/tasks/business-formation/review/ReviewMembers.tsx
web/src/components/tasks/business-formation/review/ReviewPartnership.tsx
web/src/components/tasks/business-formation/review/ReviewRegisteredAgent.tsx
web/src/components/tasks/business-formation/review/ReviewSignatures.tsx
web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/src/components/tasks/business-formation/review/ReviewWillPracticeLaw.tsx
web/src/components/tasks/business-formation/review/section/ReviewLineItem.tsx
web/src/components/tasks/business-formation/review/section/ReviewNotEntered.tsx
web/src/components/tasks/business-formation/review/section/ReviewText.tsx
web/src/styles/base/global.scss

The empty fields on the review page are now highlighted and display the text `Not Entered`.
[184305929](https://www.pivotaltracker.com/story/show/184305929)

feat: [#184305929] review page highlighted empty fields

---

web/package.json

Fix pathname for licenseSync in `package.json`.
[#184847518](https://www.pivotaltracker.com/story/show/#184847518)
N/A
N/A
N/A

fix: [#184847518] update file path to add webflow sync for licenses

---

web/src/pages/mgmt/cms.tsx

We wanted to add webflow licenses to content preview
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185126593)

feat: [#185126593] webflow Licenses Content Preview

---

web/src/scripts/webflow/licenseSync.mjs

fix: license sync import

---

web/src/scripts/webflow/licenseSync.mjs

fix: license sync import exact path to file

---

.circleci/config.yml

fix: added content build to circleci sync flows

---

.circleci/config.yml

fix: build order fix in circleci sync flow

---

.circleci/config.yml
web/src/scripts/webflow/licenseSync.mjs

Created a local lookupByIndustryId function in the license sync to fix import errors.

fix: created local lookupByIndustryId function in license sync

---

.circleci/config.yml

Update production deploy job to include Webflow sync tasks
[185149976](https://www.pivotaltracker.com/story/show/185149976)
Created in response to conversation at team retro.

chore: [#185149976] include webflow tasks in prod deploy job

---

web/src/components/navbar/NavBarDesktop.tsx
web/src/components/navbar/NavBarLogoOnly.tsx

Updated the navbar to be sticky on desktop.
[#184870963](https://www.pivotaltracker.com/story/show/184870963)

feat: [#184870963] desktop navbar updated to be sticky

---

web/src/components/navbar/NavBarDesktop.tsx
web/src/components/navbar/NavBarLogoOnly.tsx

Updated the navbar to be sticky on desktop.
[#184870963](https://www.pivotaltracker.com/story/show/184870963)

feat: [#184870963] updated desktop navbar to sticky

---

web/src/components/tasks/LicenseTask.test.tsx
web/src/components/tasks/LicenseTask.tsx
web/src/lib/data-hooks/useUserData.ts

Makes the license checkbox editable before a search is initiated
[#184306538](https://www.pivotaltracker.com/story/show/184306538)

feat: [#184306538] Make license checkbox editable

---

web/src/components/dashboard/SectorModal.tsx
web/src/components/dashboard/SidebarCardFundingNudge.test.tsx

fix: [#185214380] sector modal was not updating profile data

---

CHANGELOG.md
api/src/client/ApiFormationClient.test.ts
api/src/client/ApiFormationClient.ts
package.json

- fix: hotfix - only use text/plain in formation api when has good-standing file
- chore(release): 5.20.1 [skip ci]

release 20230519

---

web/src/components/tasks/business-formation/BusinessFormation.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/lib/data-hooks/useUserData.ts
web/test/mock/withStatefulData.tsx

refactor: [#184882700] use updateQueue in BusinessFormation

---

shared/src/operatingPhase.ts
web/src/components/dashboard/SectorModal.tsx
web/src/components/onboarding/OnboardingSectors.tsx
web/src/components/profile/ProfileTabHeader.tsx
web/test/pages/onboarding/onboarding-owning.test.tsx
web/test/pages/profile.test.tsx

fix: [#185214511] do not require sector in profile until up-and-running

---

web/src/lib/UpdateQueue.ts
web/src/lib/auth/signinHelper.test.ts
web/src/lib/data-hooks/useUserData.ts
web/src/lib/types/types.ts
web/src/pages/onboarding.tsx
web/test/mock/mockUseUserData.ts
web/test/mock/withStatefulUserData.tsx

refactor: [#184882700] remove update from onboarding

---

content/src/fieldConfig/profile.json
shared/src/legalStructure.ts
shared/src/profileData.ts
shared/src/test/factories.ts
web/cypress/e2e/check-license-status.spec.ts
web/cypress/e2e/dashboard.spec.ts
web/src/components/profile/ProfileTradeName.tsx
web/src/pages/profile.tsx
web/test/pages/profile.test.tsx

[184258256](https://www.pivotaltracker.com/story/show/)
I introduced a helper function for detecting whether to check for the "Business Name" or "Trade Name" field. I was hoping to rely on a field that we know to be always present but some of the behavior was expecting a text box so I think this was the next best approach. And it standardized how we can check for these fields for arbitrary legal structures

feat: [#184258256] add trade name and responsible owner name to profile

---

web/src/lib/data-hooks/useUserData.test.tsx
web/src/lib/data-hooks/useUserData.ts
web/test/mock/mockUseUserData.ts
web/test/mock/withStatefulData.tsx
web/test/mock/withStatefulUserData.tsx
web/test/pages/onboarding/onboarding-shared.test.tsx

refactor: [#184882700] remove update fn from useUserData return val

---

web/src/components/dashboard/HideableTasks.tsx
web/src/components/dashboard/OpportunityCard.tsx
web/src/components/dashboard/SectionAccordion.tsx
web/src/components/dashboard/SectorModal.tsx
web/src/components/dashboard/SidebarCardFundingNudge.tsx
web/src/components/filings-calendar/FilingsCalendarTaxAccess.tsx
web/src/components/post-onboarding/RadioQuestion.tsx
web/src/components/roadmap/MiniRoadmap.tsx
web/src/components/tasks/TaskCheckbox.tsx
web/src/components/tasks/business-formation/BusinessFormation.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/components/tasks/cannabis/CannabisPriorityTypes.tsx
web/src/components/tasks/cannabis/MicrobusinessRadioQuestion.tsx
web/src/lib/data-hooks/useContentModifiedByUserData.ts
web/src/lib/data-hooks/useUserData.test.tsx
web/src/lib/data-hooks/useUserData.ts

refactor: [#184882700] use updateQueue as userData in hook

---

README.md
web/cypress/e2e/verify-industry-configuration-1.spec.ts
web/cypress/e2e/verify-industry-configuration-2.spec.ts

Fixes flaky test by dividing them into two sets of test, less prone to memory issues
[185234167](https://www.pivotaltracker.com/story/show/)

chore: [#185234167] split flaky test and update readme for local testing

---

content/src/roadmaps/license-tasks/bus-inspection.md
content/src/roadmaps/license-tasks/car-rental-vehicle-registration.md
content/src/roadmaps/license-tasks/certified-interior-designer.md
content/src/roadmaps/license-tasks/detective-employees.md
content/src/roadmaps/license-tasks/family-daycare-register.md
content/src/roadmaps/license-tasks/food-safety-course.md
content/src/roadmaps/license-tasks/petcare-license.md
content/src/roadmaps/license-tasks/register-vehicle.md
content/src/roadmaps/license-tasks/verify-license-massage-therapy.md

Chore requested by content team.

chore: move tasks to license tasks

---

web/public/mgmt/config.yml

Added an internal notes field to all markdown files.
[185212121](https://www.pivotaltracker.com/story/show/185212121)

chore: [#185212121] adding internal notes field to markdown files

---

web/public/mgmt/config.yml

Made internal notes not required.
[#185212121](https://www.pivotaltracker.com/story/show/185212121)

chore: [#185212121] make internal notes not required

---

content/src/licenses/architecture.md
content/src/licenses/certified-public-accountant.md
content/src/licenses/cosmetology.md
content/src/licenses/home-contractor.md
content/src/licenses/hvac-contractor.md
content/src/licenses/moving-company.md

feat: [#185386798] punctuation update for license expired

---

web/public/mgmt/config.yml

Renamed title of the internal notes.
[#185212121](https://www.pivotaltracker.com/story/show/185212121)

feat: [#185212121] internal notes for markdown files

---

CHANGELOG.md
package.json

* [[#184726710](https://github.com/newjersey/navigator.business.nj.gov/issues/184726710)] add defaults for first half of licenses ([b485a65](https://github.com/newjersey/navigator.business.nj.gov/commit/b485a65d40ad2a50d510511aab766c28848063ca))
* [[#184726710](https://github.com/newjersey/navigator.business.nj.gov/issues/184726710)] add preselected industry for cannabis license ([7c68b3d](https://github.com/newjersey/navigator.business.nj.gov/commit/7c68b3dfd06412aea91c8ede3b08be27789e45c0))
* [[#184726710](https://github.com/newjersey/navigator.business.nj.gov/issues/184726710)] add preselected to multiselect for second half of licenses ([9b2ab0a](https://github.com/newjersey/navigator.business.nj.gov/commit/9b2ab0aea4f7e6ea0906645777137b23645f4649))
* …

chore(release): 5.21.0 [skip ci]

---

CHANGELOG.md
content/src/roadmaps/license-tasks/bus-inspection.md
content/src/roadmaps/license-tasks/car-rental-vehicle-registration.md
content/src/roadmaps/license-tasks/certified-interior-designer.md
content/src/roadmaps/license-tasks/detective-employees.md
content/src/roadmaps/license-tasks/family-daycare-register.md
content/src/roadmaps/license-tasks/food-safety-course.md
content/src/roadmaps/license-tasks/petcare-license.md
content/src/roadmaps/license-tasks/register-vehicle.md
content/src/roadmaps/license-tasks/verify-license-massage-therapy.md
package.json
web/src/scripts/webflow/licenseSync.mjs

- fix: webflow license sync and update license-task files
- chore(release): 5.21.1 [skip ci]

release 20230614

---

web/src/components/TaskProgressCheckbox.tsx
web/src/components/dashboard/SidebarCardRegisteredForTaxesNudge.tsx
web/src/lib/utils/analytics.ts

**Analytics**
- Update 'tax_registration_nudge_button.click' to result with 'show_tax_registration_success_snackbar'
- Update 'tax_registration_status_set_to_complete.click' to result with 'show_tax_registration_success_snackbar'
[#184643224](https://www.pivotaltracker.com/story/show/184643224)
N/A
N/A
N/A

chore: [#184643224] update tax registration analytics from modal to snack bar

---

web/src/components/navbar/NavBarPopupMenu.tsx
web/src/styles/sections/nav-bar.scss

Minor QA stuff for pre ethan nav re-design
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185461947)

feat: [#185461947] minor styling QA for pre ethan nav

---

content/src/certifications/lgbtq-1.md
content/src/mappings/ownershipTypes.json
web/public/mgmt/config.yml

We wanted to add LGBTQ+ as an ownershipType and a specific cert for it. 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185211995)

feat: [#185211995] adding LGBTQ cert and ownershipTypes

---

content/src/roadmaps/license-tasks/Haul-Waste.md
content/src/roadmaps/license-tasks/authorization-architect-firm.md
content/src/roadmaps/license-tasks/auto-body-repair-license.md
content/src/roadmaps/license-tasks/bus-inspection.md
content/src/roadmaps/license-tasks/certified-interior-designer.md
content/src/roadmaps/license-tasks/conversion-license-cannabis.md
content/src/roadmaps/license-tasks/detective-employees.md
content/src/roadmaps/license-tasks/electrical-business-license.md
content/src/roadmaps/license-tasks/family-daycare-register.md
content/src/roadmaps/license-tasks/food-safety-course.md
content/src/roadmaps/license-tasks/individual-staff-licenses-cosmetology.md
content/src/roadmaps/license-tasks/pharmacy-license.md
content/src/roadmaps/license-tasks/register-vehicle.md
content/src/roadmaps/license-tasks/school-bus-license.md
content/src/roadmaps/license-tasks/spray-paint-booth-permit-auto-body-repair.md
content/src/roadmaps/license-tasks/town-mercantile-license.md

Syntax for summary description was faulty in a few license tasks files causing them to not render properly in the CMS.
[#185492036](https://www.pivotaltracker.com/story/show/185492036)

fix: [#185492036] license tasks summary description syntax

---

web/src/components/tasks/business-formation/contacts/Addresses.tsx

[#184198991](https://www.pivotaltracker.com/story/show/#184198991)

chore: [#184198991] clean up BOD & signers error message code

---

api/src/db/migrations/migrations.ts
api/src/db/migrations/v117_add_onboarding_nonprofit.ts
content/src/fieldConfig/profile.json
content/src/roadmaps/add-ons/nonprofit.json
content/src/roadmaps/task-dependencies.json
content/src/roadmaps/tasks/search-business-name.md
shared/src/legalStructure.ts
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/public/mgmt/config.yml
web/src/components/filings-calendar/FilingsCalendarTaxAccess.test.tsx
web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.test.tsx
web/src/components/onboarding/OnboardingFlows.tsx
web/src/components/onboarding/OnboardingNonprofit.tsx
web/src/components/tasks/business-formation/BusinessFormation.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts
web/src/pages/onboarding.tsx
web/src/pages/tasks/[taskUrlSlug].tsx
web/test/helpers/helpers-formation.tsx
web/test/pages/onboarding/helpers-onboarding.tsx
web/test/pages/onboarding/onboarding-foreign.test.tsx
web/test/pages/onboarding/onboarding-owning.test.tsx
web/test/pages/onboarding/onboarding-starting.test.tsx

Added nonprofit 
[#184822307](https://www.pivotaltracker.com/story/show/#184822307)
The additions to Business Formation with `searchOnly` prop are intended to be quick & temporary, since that will be replaced and removed in the upcoming nonprofit formation story

feat: [#184822307] add nonprofit onboarding and roadmap

---

api/src/db/migrations/migrations.ts
api/src/db/migrations/v117_add_onboarding_nonprofit.ts
api/src/db/migrations/v118_set_operating_phase_remote_seller_worker.test.ts
api/src/db/migrations/v118_set_operating_phase_remote_seller_worker.ts
api/src/domain/user/updateOperatingPhase.test.ts
api/src/domain/user/updateOperatingPhase.ts
shared/src/userData.ts
web/src/pages/onboarding.tsx
web/test/pages/onboarding/onboarding-foreign.test.tsx

[#185512025](https://www.pivotaltracker.com/story/show/#185512025)

fix: [#185512025] do not show biz structure prompt for foreign remote seller/worker

---

content/src/fieldConfig/business-formation.json
web/src/components/tasks/business-formation/contacts/Addresses.tsx
web/src/styles/components/tables.scss

Re-add zebra pattern to signers section and a line to the bottom of the table once the BOD and signers sections are complete.
[#184198991](https://www.pivotaltracker.com/story/show/184198991)

chore: [#184198991] re-add zebra pattern to signers section

---

.gitignore
scripts/get-user-location.sh
scripts/update-airtable.sh

Create a script that can be used to populate user location information in BFS Users Table
[185396010](https://www.pivotaltracker.com/story/show/185396010)
The script added in this PR scans DynamoDB and prints all users' email and provided location to a CSV file. This is sensitive information, so the output file is included in `.gitignore`.
Running this script requires AWS session keys which can be acquired through the AWS login console. Additionally, you must provide the name of the table you want to query.
I was running into issues with `ProvisionedThroughputExceededException`. Tried a couple different things, but the best solution I was able to come up with short of modifying our DynamoDB instance was to just add a pause in the script. Every 10000 records, the script pauses for 5 …

Create script to get user locations

---

web/src/pages/index.tsx
web/test/pages/index.test.tsx

Removed the code that handles the redirect to the webflow landing page.
[#185543521](https://www.pivotaltracker.com/story/show/185543521)
Follow up: remove the following environment variables in Circle Ci: `FEATURE_LANDING_PAGE_REDIRECT` and  `ALTERNATE_LANDING_PAGE_URL`

feat: [#185543521] remove landing page redirect to webflow

---

CHANGELOG.md
content/src/roadmaps/license-tasks/food-safety-course.md
content/src/roadmaps/license-tasks/petcare-license.md
package.json

* [[#185355437](https://github.com/newjersey/navigator.business.nj.gov/issues/185355437)] roadmap part of license tasks not rendering in the CMS ([dab9c99](https://github.com/newjersey/navigator.business.nj.gov/commit/dab9c99d00cc1d24cb46f1766e81dd4651e4b0da))
* [[#185512025](https://github.com/newjersey/navigator.business.nj.gov/issues/185512025)] do not show biz structure prompt for foreign remote seller/worker ([fc3b08d](https://github.com/newjersey/navigator.business.nj.gov/commit/fc3b08d2382835453a2ab2d5e2a0b71ef8051326))
* [[#185519654](https://github.com/newjersey/navigator.business.nj.gov/issues/185519654)] businessStartDate field correctly shows error bar in mobile ([35cbfc3](https://github.com/newjersey/navigator.business.nj.gov/commit/35cbfc3a763edf543b9ac3ba0ebfb27a9778a8cb)) …

chore(release): 5.23.0 [skip ci]

---

api/package.json
content/package.json
package.json
shared/package.json
web/package.json
yarn.lock

Upgraded prettier to v2.8.8
Install the new dependencies and run yarn build

chore(deps): update dependency prettier to v2.8.8

---

api/package.json
content/package.json
package.json
shared/package.json
web/package.json
yarn.lock

update rimraf to v5
update rimraf to v5
yarn install, yarn build

chore(deps): update dependency rimraf to v5

---

shared/src/businessUser.ts

Fix unit tests that are failing bc of linter

[chore] - Fix unit tests that are failing bc of linter

---

CHANGELOG.md
package.json

- fix: disable outage bar
- chore(release): 5.23.4 [skip ci]

release 20230711

---

web/src/components/CountryDropdown.tsx
web/src/components/FormationDateModal.tsx
web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.tsx
web/src/components/njwds-extended/GenericButton.tsx
web/src/components/onboarding/OnboardingEssentialQuestion.tsx
web/src/components/profile/ProfileField.tsx
web/src/components/tasks/TaxInput.tsx
web/src/components/tasks/business-formation/business/MainBusiness.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx

chore: [#184500023] update spacing in modals

---

content/src/fieldConfig/business-formation.json

[#185628795](https://www.pivotaltracker.com/story/show/185628795)

chore: [#185628795] update add'l provisions copy for all legal types

---

web/src/lib/domain-logic/getNavBarBusinessTitle.test.tsx
web/src/lib/domain-logic/getNavBarBusinessTitle.tsx

[#185629976](https://www.pivotaltracker.com/story/show/#185629976)
[#185641164](https://www.pivotaltracker.com/story/show/#185641164)

Fix navbar business title

---

web/src/components/navbar/NavBar.test.tsx
web/src/components/navbar/NavBarPopupMenu.test.tsx
web/src/lib/domain-logic/getNavBarBusinessTitle.test.tsx
web/src/lib/domain-logic/getNavBarBusinessTitle.tsx

chore: [#185629976] fix nav behavior when legal structure not entered

---

web/src/components/DeferredOnboardingQuestion.tsx

fix: [#185641143] municipality field not full width in deferred question

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/lib/domain-logic/getNavBarBusinessTitle.test.tsx
web/src/lib/domain-logic/getNavBarBusinessTitle.tsx

[#185649292](https://www.pivotaltracker.com/story/show/#185649292)
Reorganized test code to make it easier to understand the different cases that cause different outputs
Rewrote prod code to support Oscar
Interested in feedback on the readability of this test reorganization

feat: [#185649292] add navbar business name logic for OWNING businesses

---

web/src/components/LegalStructureDropDown.tsx
web/src/components/StateDropdown.tsx
web/src/components/profile/ProfileOwnership.tsx
web/src/components/tasks/business-formation/billing/BillingStep.tsx
web/src/components/tasks/business-formation/business/MainBusiness.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx
web/src/components/tasks/business-formation/business/PartnershipRights.tsx
web/src/components/tasks/business-formation/business/PracticesLaw.tsx
web/src/components/tasks/business-formation/business/SuffixDropdown.tsx
web/src/components/tasks/business-formation/contacts/AddressModal.tsx
web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx
web/src/components/tasks/search-business-name/SearchBusinessNameForm.tsx
web/src/styles/components/grid.scss
web/src/styles/main.scss

chore: [#184606533] fix grid layout in formation

---

web/src/lib/static/admin/findDeadLinks.test.ts
web/src/lib/static/admin/findDeadLinks.ts

We wanted to update the broken link checker which is now updated
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185355762)
spin up local and then go to this URL
http://localhost:3000/mgmt/deadurls
NOTE it will take like 10 - 12 minutes to load / run

Update Broken Link Checker

---

web/src/lib/domain-logic/filterFundings.test.ts
web/src/lib/domain-logic/filterFundings.ts

fix: updating filterFundings to handle undefined certification values

---

web/src/components/njwds-extended/UnStyledButton.tsx
web/src/components/onboarding/taxId/DisabledTaxId.test.tsx
web/src/components/onboarding/taxId/DisabledTaxId.tsx
web/src/components/tasks/TaxInput.tsx
web/src/components/tasks/TaxTask.test.tsx
web/test/pages/profile/profile-shared.test.tsx
yarn.lock

[#185084111](https://www.pivotaltracker.com/story/show/)
Added tax masking on register for taxes

chore: [#185084111] Add a locked tool tip to tax

---

web/src/components/njwds-extended/HelpButton.tsx

Follow up for design with regards to seperate mobile specific padding that wasn't mentioned in the ticket. 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185617852)

feat: [#185617852] increase help button padding mobile

---

web/src/lib/static/admin/findDeadLinks.ts

updating broken link checker to hopefully account for auth correctly 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185355762)

feat: [#185355762] update broken link checker to account for basic auth

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormationTextBox.tsx
web/src/components/tasks/business-formation/business/BusinessStep.tsx
web/src/components/tasks/business-formation/business/IsVeteranNonprofit.tsx
web/src/components/tasks/business-formation/business/MainBusiness.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx
web/src/components/tasks/business-formation/business/NonprofitProvisions.tsx
web/src/components/tasks/business-formation/review/ReviewNonprofitProvisions.tsx
web/src/components/tasks/business-formation/review/section/ReviewLineItem.tsx

chore: [#185153256] design review fixes for nonprofit formation

---

content/src/display-content/post-onboarding/construction-renovation.md
web/src/components/TaskElement.tsx
web/src/components/post-onboarding/PostOnboardingRadioQuestion.test.tsx
web/src/components/post-onboarding/PostOnboardingRadioQuestion.tsx
web/src/lib/domain-logic/postOnboardingCheckboxes.ts
web/test/factories.ts

[#184770173](https://www.pivotaltracker.com/story/show/#184770173)
This pertains to the post-onboarding question in "Prepare for Site Renovation, if Applicable" task in Step 3.
To get this task, be a location with a physical location, either by being a physical-location-only industry, or by selecting "No" for home-based-business

feat: [#184770173] update postOnboarding to change task status with checkboxes

---

web/src/lib/static/admin/findDeadLinks.ts
web/src/pages/mgmt/deadurls.tsx

We resolved to have the link checker run locally by a dev once a quater or at the request of content. So this PR is to add a downloadable option to the link checker to facilitate hand off to content as well as reverting to the version where it worked on local (as opposed to the way we hoped might work on dev)
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185355762)
If you test this locally it will take 10 minutes to run

Update broken link checker revision 2

---

web/src/components/tasks/business-formation/business/BusinessStep.test.tsx

Update the required fields tests so they explicitly describe what the tests do (`BusinessStep.test.tsx`).
[#185729893](https://www.pivotaltracker.com/story/show/185729893)

chore: [#185729893] update businessStep tests' names

---

web/src/components/auth/SignUpModal.tsx
web/src/lib/auth/signinHelper.test.ts
web/src/lib/auth/signinHelper.ts

refactor: remove extra returnToLink option in selfRegister

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/lib/domain-logic/getNavBarBusinessTitle.test.ts
web/src/lib/domain-logic/getNavBarBusinessTitle.ts

Updated navbar text for Dakota remoter worker/seller to say `Unnamed Out-of-State Business`
[#185680966](https://www.pivotaltracker.com/story/show/185680966)

feat: [#185680966] dakota remote worker/seller navbar text

---

shared/src/operatingPhase.ts
web/cypress/e2e/deferred-onboarding.spec.ts
web/test/pages/dashboard.test.tsx

[#185681496](https://www.pivotaltracker.com/story/show/#185681496)

feat: [#185681496] remove home-based prompt for up-and-running

---

content/src/fieldConfig/profile.json
content/src/roadmaps/nonEssentialQuestions.json
web/public/mgmt/config.yml
web/src/components/profile/ProfileNonEssentialQuestion.tsx

Styling fix for non essential question text.
[#185307864](https://www.pivotaltracker.com/story/show/185307864)

fix: [#185307864] non essential question text styling

---

web/src/components/dashboard/SidebarCardsContainer.test.tsx

Removing welcome and welcome up and running from sodebarcontainertests
[#185681556 ](https://www.pivotaltracker.com/story/show/)

feat: 185681556 remove sidebarcontainer tests for welcome

---

web/src/components/dashboard/SidebarCardsContainer.test.tsx

Removing welcome and welcome up and running from sodebarcontainertests
[#185681556 ](https://www.pivotaltracker.com/story/show/)

feat: 185681556 sidebar test removal

---

web/src/components/profile/ProfileNonEssentialQuestion.test.tsx
web/src/components/profile/ProfileNonEssentialQuestion.tsx
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts
web/src/lib/search/cmsCollections.ts
web/src/lib/search/searchNonEssentialQuestions.ts
web/src/lib/types/types.ts
web/src/pages/mgmt/search.tsx

- fix to only add a task corresponding to a non essential question if the id is present in the industry file
- fix for string to boolean typing on the radio question answers
- added test for displaying both question text and option text suffix
- added non essential questions to search
[#185307864](https://www.pivotaltracker.com/story/show/185307864)

[#185307864] [#185815263] non essential questions fixes and add to search

---

shared/src/operatingPhase.ts

Remove feedbackFormToDisplay from operatingPhase as it's not being used anymore.
[#185779852](https://www.pivotaltracker.com/story/show/185779852)

chore: [#185779852] remove feedbackFormToDisplay from operatingPhase

---

content/src/fieldConfig/profile.json
web/public/mgmt/config.yml
web/src/components/CannabisLocationAlert.test.tsx
web/src/components/CannabisLocationAlert.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx
web/src/components/tasks/business-formation/business/MainBusinessForeignAddressFlow.tsx
web/src/lib/cms/previews/ProfileMiscPreview.tsx
web/src/lib/utils/helpers.ts
web/src/pages/profile.tsx
web/test/pages/profile/profile-owning.test.tsx
web/test/pages/profile/profile-shared.test.tsx

Adds an alert message to formation and the profile page for new (Poppy and Dakota) cannabis businesses.
[184992648](https://www.pivotaltracker.com/story/show/184992624) [184992624](https://www.pivotaltracker.com/story/show/184992648)

Cannabis location validation alert

---

web/src/lib/data-hooks/useUserData.ts
web/src/pages/onboarding.tsx
web/test/mock/mockUseUserData.ts
web/test/mock/withStatefulUserData.tsx

fix: [#185403995] wait for fetch before handling onboarding reroute

---

content/src/roadmaps/tasks/register-trade-name.md
content/src/roadmaps/tasks/town-mercantile-license.md
web/cypress/e2e/dashboard.spec.ts
web/src/components/CannabisLocationAlert.test.tsx
web/src/components/CannabisLocationAlert.tsx
web/src/components/Content.tsx
web/src/components/PureMarkdownContent.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx
web/src/components/tasks/business-formation/business/MainBusinessForeignAddressFlow.tsx
web/src/lib/cms/editors/cannabisLocationAlert.tsx
web/src/pages/mgmt/cms.tsx
web/src/pages/profile.tsx

Create CMS widget to place existing cannabis location alert. Add to mercantile and trade name tasks.
[184992602](https://www.pivotaltracker.com/story/show/184992602)

Create cannabis location alert CMS component

---

web/src/components/tasks/EinInput.tsx
web/src/components/tasks/EinTask.test.tsx

Changed the EIN task to display registration modal when the field is edited or the save button is clicked.
[#185757071](https://www.pivotaltracker.com/story/show/185757071)

feat: [#185757071] EIN task updated to trigger modal on edit

---

web/src/pages/filings/[filingUrlSlug].tsx

feat: [#184702075] remove mini-roadmap for filings page

---

web/src/components/tasks/business-formation/review/ReviewMembers.tsx
web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/src/components/tasks/business-formation/review/section/ReviewSubSection.tsx

title is self-explanatory
[#185588284](https://www.pivotaltracker.com/story/show/185588284)

Consolidate conditional rendering logic for nonprofit legal-type in formation Review step

---

api/src/domain/updateSidebarCards.ts
shared/src/domain-logic/opportunityFields.test.ts
shared/src/domain-logic/opportunityFields.ts
shared/src/operatingPhase.ts
web/src/components/profile/ProfileOpportunitiesAlert.test.tsx
web/src/components/profile/ProfileOpportunitiesAlert.tsx
web/test/pages/profile/profile-helpers.tsx
web/test/pages/profile/profile-owning.test.tsx
web/test/pages/profile/profile-shared.test.tsx

Fix errors showing when go to profile nudge is displayed
[#184643298](https://www.pivotaltracker.com/story/show/)

fix: [#184643298] fix errors showing when go to profile nudge is displayed

---

content/src/fieldConfig/config.json
content/src/fieldConfig/profile.json
web/public/mgmt/config.yml
web/src/components/onboarding/OnboardingEssentialQuestion.tsx
web/src/components/profile/ProfileErrorAlert.test.tsx
web/src/components/profile/ProfileErrorAlert.tsx
web/src/components/profile/ProfileField.tsx
web/src/lib/cms/previews/ProfileMiscPreview.tsx
web/src/lib/data-hooks/useFormContextHelper.ts
web/src/pages/profile.tsx
web/src/styles/components/errors.scss
web/test/pages/onboarding/onboarding-foreign.test.tsx
web/test/pages/onboarding/onboarding-starting.test.tsx
web/test/pages/profile/profile-foreign.test.tsx
web/test/pages/profile/profile-owning.test.tsx
web/test/pages/profile/profile-shared.test.tsx
web/test/pages/profile/profile-starting.test.tsx

Added an error alert at the top of the profile page which displays the headers of the fields that need to be fixed.
[#184662027](https://www.pivotaltracker.com/story/show/184662027)

feat: [#184662027] profile error alert

---

api/src/client/ApiFormationClient.test.ts

Refactored non profit tests to be more concise in ApiFormationClient
[#185729798](https://www.pivotaltracker.com/story/show/185729798)

chore: [#185729798] refactor ApiFormationClient nonprofit tests

---

web/src/lib/search/searchCertifications.ts
web/src/lib/search/searchFundings.ts
web/src/lib/search/searchLicenseEvents.ts
web/src/lib/search/searchTasks.ts
web/src/lib/search/searchTaxFilings.ts
web/src/lib/search/searchWebflowLicenses.ts

Add url slug name and filename to search for other types in cms.
[#185931150](https://www.pivotaltracker.com/story/show/)
Went through each search collection in the cms and see if the type has a url slug and/or a filename.
Go on the search in cms and find other types besides quick actions that have a url slug or filename and search by their term.

Chore: [#185931150] Add url slug name and filename to search for other types in cms

---

web/cypress/e2e/dashboard.spec.ts
web/cypress/support/helpers/helpers.ts

fix: remove flaky wait from dashboard test

---

api/.dependency-cruiser.js
api/package.json
api/src/domain/s3Writer.ts
package.json
yarn.lock

Implemented a node handler with a tls v1.2.
[#185729739](https://www.pivotaltracker.com/story/show/)

chore: [#185729739] Update AWS S3 from deprecated v1 calls

---

CHANGELOG.md
package.json

- chore: empty commit for release v5.26.0
- chore(release): 5.26.0 [skip ci]

release 20230905

---

web/stories/Atoms/Colors.stories.tsx

chore: [#185250601] fix typo in storybook colors story

---

web/test/pages/onboarding/onboarding-owning.test.tsx

Add test coverage for changes to persona and operating phase
**Updated from original PR:** Make sector selection required for Oscar personas, https://github.com/newjersey/navigator.business.nj.gov/pull/6317#pullrequestreview-1601171436
[#185834867](https://www.pivotaltracker.com/story/show/185834867)

Update oscar onboarding sector bug test #185834867

---

web/src/components/dashboard/OpportunityCard.test.tsx
web/src/components/dashboard/OpportunityCard.tsx
web/src/components/dashboard/SidebarCardsContainer.test.tsx
web/src/lib/utils/analytics-legacy.ts
web/src/lib/utils/analytics.ts

Add custom analytics events for when clicking the title link for any Funding opportunities and Certifications cards in the For You section.
Analytics Events
legacy_event_category: opportunity_card
legacy_event_action: click
legacy_event_label: go_to_opportunity_screen
event: link_clicks
item: opportunity_card
Insights
Suggested Analytics (New):
Clickthrough rate of opportunities (certs and funding)
Suggested Analytics (Existing):
Clickthrough rate of phase action cards
[#185788142](https://www.pivotaltracker.com/story/show/)

chore: [#185788142] for you analytics

---

web/src/components/tasks/business-formation/contacts/ContactsStep.test.tsx

chore: [#185975594] fix flaky test in contacts step

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/contacts/ContactsStep.tsx
web/src/components/tasks/business-formation/contacts/Signatures.test.tsx
web/src/components/tasks/business-formation/contacts/Signatures.tsx

Updated errors for signers in formation.
[#183536833](https://www.pivotaltracker.com/story/show/183536833)

feat: [#183536833] signers and checkbox error message

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/contacts/ContactsStep.tsx
web/src/components/tasks/business-formation/contacts/Signatures.test.tsx
web/src/components/tasks/business-formation/contacts/Signatures.tsx

Reverts newjersey/navigator.business.nj.gov#6333

Revert "feat: [#183536833] signers and checkbox error message"

---

web/src/components/tasks/business-formation/contacts/Signatures.test.tsx
web/src/components/tasks/business-formation/contacts/Signatures.tsx

Fix to inline error for missing signature for dakota nexus.
[#183536833](https://www.pivotaltracker.com/story/show/183536833)

fix: [#183536833] inline error for missing signature for dakota nexus

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormation.test.tsx
web/src/components/tasks/business-formation/billing/getCost.test.ts
web/src/components/tasks/business-formation/business/BusinessStep.test.tsx
web/src/components/tasks/business-formation/business/ForeignCertificate.tsx
web/src/components/tasks/business-formation/business/MainBusiness.tsx
web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/src/components/tasks/business-formation/validatedFieldsForUser.test.ts
web/src/components/tasks/business-formation/validatedFieldsForUser.ts
web/src/lib/utils/helpers.ts

feat: [#185167013] enable foreign nonprofit formation

---

web/src/components/tasks/business-formation/billing/BillingStep.tsx
web/src/components/tasks/business-formation/business/BusinessStep.tsx
web/src/components/tasks/business-formation/business/MainBusiness.tsx
web/src/components/tasks/business-formation/contacts/ContactsStep.tsx
web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx

chore: [#185742102] fix hr line spacing in formation

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormation.test.tsx
web/src/components/tasks/business-formation/billing/getCost.test.ts

[186052121](https://www.pivotaltracker.com/story/show/#186052121)

feat: [#186052121] $25 cert of good standing for domestic nonprofit

---

web/src/components/tasks/NaicsCodeInput.tsx
web/src/components/tasks/NaicsCodeTask.test.tsx

When users are in guest mode, a modal will now appear when they click either of the NAICS code radio buttons and the task progress will remain as NOT STARTED.
[#185801876](https://www.pivotaltracker.com/story/show/185801876)

feat: [#185801876] display modal on NAICS code task for guest mode users

---

content/src/fieldConfig/naics-code.json
content/src/fieldConfig/profile.json
web/public/mgmt/config.yml
web/src/components/field-labels/FieldLabelProfile.tsx
web/src/components/tasks/NaicsCodeInput.tsx
web/src/components/tasks/NaicsCodeTask.tsx
web/src/lib/cms/previews/ProfileFieldsPreview.tsx
web/src/pages/mgmt/cms.tsx
web/src/styles/components/errors.scss

Added error bar to input and updated labels on task page
Refactored/ moved around the NaicsInput component so the code is easy to read.
Consolidated input content to profile.json and updated cms previews.
https://www.pivotaltracker.com/story/show/185715307

chore: [#185715307] refactor and add error bar to naics code input

---

api/src/api/taxFilingRouter.ts
api/src/api/userRouter.ts

Removed chained updates to the same variable to follow the patten from book club.
[#186065986](https://www.pivotaltracker.com/story/show/186065986)

chore: [#186065986] remove chained updates to the same variable

---

content/src/fieldConfig/profile.json
shared/src/operatingPhase.ts
web/public/mgmt/config.yml
web/src/components/data-fields/ExistingEmployees.tsx
web/src/pages/profile.tsx
web/stories/Molecules/textfields/OneFieldTextField.stories.tsx
web/test/pages/profile/profile-starting.test.tsx

[#186092347](https://www.pivotaltracker.com/story/show/#186092347)

fix: [#186092347] Business Name and Number of Employees no longer required in profile

---

web/src/components/tasks/business-formation/business/FormationRadio.tsx
web/src/components/tasks/business-formation/business/FormationTextArea.tsx
web/src/components/tasks/business-formation/business/NonprofitProvisions.tsx
web/src/components/tasks/business-formation/business/PartnershipRights.tsx

[#185628613](https://www.pivotaltracker.com/story/show/#185628613)

refactor: [#185628613] combine nonprofit provisions and partnership rights fields

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/components/Header.test.tsx
web/src/components/Header.tsx

[#186099467](https://www.pivotaltracker.com/story/show/#186099467)
- [ x] I have not used any relative imports

Starter kit title #186099467

---

web/src/styles/base/global.scss

[#186123034](https://www.pivotaltracker.com/story/show/#186123034)

chore: [#186123034] add paragraph spacing

---

CHANGELOG.md
package.json

* [[#186092347](https://github.com/newjersey/navigator.business.nj.gov/issues/186092347)] Business Name and Number of Employees no longer required in profile ([f57118a](https://github.com/newjersey/navigator.business.nj.gov/commit/f57118a38f5d9ba80fa223330ca0f15a35feab75))
* **deps:** update aws-sdk to v3.413.0 ([2515207](https://github.com/newjersey/navigator.business.nj.gov/commit/2515207352abe01ce0d0f1838bbab8b3adabde63))
* **deps:** update aws-sdk to v3.414.0 ([004c6f3](https://github.com/newjersey/navigator.business.nj.gov/commit/004c6f396a0395b73da574afa6b99de24de9efe2))
* **deps:** update aws-sdk to v3.415.0 ([ae8cd9f](https://github.com/newjersey/navigator.business.nj.gov/commit/ae8cd9ff293039eed3eba375f7460388fb475db9))
* **deps:** update aws-sdk to v3.417.0 …

chore(release): 5.30.0 [skip ci]

---

content/src/quick-actions/registry-update-brc-amendment.md
web/src/styles/base/global.scss

Context: https://njcio.slack.com/archives/C04SS2KJCCA/p1695311458063769
Solution: add 1rem bottom margin to paragraph elements.
Attempted fix:
```
.usa-prose {
p {
margin-bottom: 1rem !important;
margin-top: 0 !important;
```
Problem: it increased ALL paragraphs on the page, like in the roadmap tasks, and in the alert. Need to find a better way
[186126038](https://www.pivotaltracker.com/story/show/)

chore: [#186126038] fix paragraph spacing

---

content/src/roadmaps/license-tasks/moving-company-license.md

chore: Update latest from content repo

---

api/src/client/ApiFormationClient.test.ts
api/src/client/ApiFormationClient.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v125_rename_provisions_to_additional_provisions.ts
content/src/fieldConfig/business-formation.json
shared/src/formationData.ts
shared/src/test/formationFactories.ts
shared/src/userData.ts
web/cypress/e2e/business-formation.spec.ts
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormation.test.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/components/tasks/business-formation/business/AdditionalProvisions.tsx
web/src/components/tasks/business-formation/business/BusinessStep.test.tsx
web/src/components/tasks/business-formation/business/BusinessStep.tsx
web/src/components/tasks/business-formation/review/ReviewAdditionalProvisions.tsx
web/src/components/tasks/business-formation/review/ReviewStep.test.tsx
web/src/components/tasks/business-formation/review/ReviewStep.tsx
web/stories/Molecules/textfields/LockedTextField.stories.tsx

[#185628600](https://www.pivotaltracker.com/story/show/185628600)

chore: [#185628600] rename FormationFormData provisions to additional provisions

---

web/src/components/dashboard/HideableTasks.tsx
web/src/components/dashboard/OpportunityCard.tsx
web/src/components/filings-calendar/FilingsCalendar.tsx
web/src/components/njwds-extended/GenericButton.tsx
web/src/components/njwds-extended/PrimaryButton.tsx
web/src/components/njwds-extended/SecondaryButton.tsx
web/src/styles/components/buttons.scss
web/stories/Molecules/Button/Calendar.stories.tsx
web/stories/Molecules/Button/PrimaryLarge.stories.tsx
web/stories/Molecules/Button/PrimaryRegular.stories.tsx
web/stories/Molecules/Button/Quaternary.stories.tsx
web/stories/Molecules/Button/SecondaryButton.stories.tsx
web/stories/Molecules/Button/Tertiary.stories.tsx
web/stories/Molecules/Button/Unstyled.stories.tsx

Storybook Molecules for getting Buttons up to date with the design system,
Also refactored the quaternary button a bit 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/184606443)
run storybook via the `yarn run storybook` command from the we folder and check out the button section

Storybook molecules buttons

---

.circleci/config.yml
package.json
web/package.json
yarn.lock

Bump cache version to hopefully fix failing Cypress tests.

Bump CircleCI Cache Version

---

web/src/components/dashboard/SidebarCardsList.tsx

Padding update as part of revisions

feat: [#185932056] padding evening

---

web/src/components/njwds-extended/GenericButton.tsx
web/src/components/njwds-extended/PrimaryButton.tsx
web/src/components/njwds-extended/PrimaryButtonDropdown.tsx
web/src/components/njwds-extended/SecondaryButton.tsx

chore: [#186203159] clean up generic button prop

---

web/src/components/tasks/cannabis/CannabisApplicationRequirementsTab.tsx
web/src/components/tasks/cannabis/CannabisPriorityRequirements.tsx

chore: [#182906192] reverse stack buttons on cannabis tasks

---

web/stories/Molecules/Alerts/DefaultAlert.stories.tsx

We wanted to update the alerts section to be inline with the design system
This from what I can tell means just adding the note variant explicitly and then moving it from the WIP section to the molecules seciton
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/184606376)

feat: [#184606376] added alert variant for notes to storybook

---

web/src/components/Content.tsx
web/src/components/dashboard/SidebarCardsList.test.tsx
web/src/components/dashboard/SidebarCardsList.tsx
web/src/components/dashboard/TwoTabDashboardLayout.tsx
web/src/lib/domain-logic/getForYouCardCount.test.ts
web/src/lib/domain-logic/getForYouCardCount.ts
web/src/styles/base/global.scss
web/stories/Atoms/Typography.stories.tsx
web/test/pages/dashboard.test.tsx

As a Navigator user, I need to be able to differentiate the For You header in the hierarchy in order to understand which header is generally applicable to the page vs the For You section specifically, and have a consistent Opportunity counter in mobile and desktop in order to understand if my Opportunities have changed
AC
Given I am a Navigator user
When viewing my For You section in a desktop viewport
Then the "For You" header uses unbolded H2 styling
And it is followed by parenthetical counter of unhidden opportunities + cards in the for you section using "base" color
(works the same as it does in mobile currently)
Given i am user
when viewing in mobile Viewport
The the For You column Header and the header line underneath is removed
Note: Storybook typography will also need to be …

feat: [#185931949] For you header updates and counter

---

web/src/components/filings-calendar/FilingsCalendar.test.tsx

- Updated two failing tests in `FilingCalendar.tests.tsx`:
1. `shows 5 more events when the view more button is clicked`
2. `resets view more button when year is changed`
**Issue**: The way our tests were set up, we get the current date and go two months into the future and populate `x` number of events (for the current year). In the case of the failing tests, there are 10 events. 
On Friday, October 20th, these tests passed, because two months out brings us you to December 20th, and 10 events would be December 30th. However, on Monday, October 23rd, the tests failed because two months out brings us to December 23rd, and 10 events brings us to January 1st (the following year).
**Resolution**: Set up a `currentDateMock` with April as the current date (versus using the actual current date) …

chore: fix failing FilingCalendar tests

---

content/src/licenses/moving-company.md

Content repo

---

CHANGELOG.md
package.json

* [[#185151322](https://github.com/newjersey/navigator.business.nj.gov/issues/185151322)] support CTA dropdowns as well as buttons for tasks with post-onboarding ([b3cd95e](https://github.com/newjersey/navigator.business.nj.gov/commit/b3cd95ed8bb192414956bea6937af47d49b2c055))
* [[#185151322](https://github.com/newjersey/navigator.business.nj.gov/issues/185151322)] support CTA dropdowns as well as buttons for tasks with post-onboarding ([539f051](https://github.com/newjersey/navigator.business.nj.gov/commit/539f051e25297ffd4c1667b1fd168f78878d62a3))
* [[#185681031](https://github.com/newjersey/navigator.business.nj.gov/issues/185681031)] added note alert when businesses formed outside the Navigator in profile ([2a5e425](https://github.com/newjersey/navigator.business.nj.gov/commit/2a5e425f …

chore(release): 5.35.0 [skip ci]

---

web/src/components/njwds-extended/FormationHelpButton.test.tsx
web/src/components/njwds-extended/FormationHelpButton.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/components/tasks/business-formation/DbaFormationPaginator.tsx
web/src/lib/utils/analytics-legacy.ts
web/src/lib/utils/analytics.ts

We need analytics on the formation help buttons
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/186366473)
Look at formation pages and hit help button and look at network tab
Also DBA version

fix: [#186366473] added Analytics for formation task help button

---

web/src/components/dashboard/SidebarCardsList.test.tsx
web/src/components/dashboard/SidebarCardsList.tsx
web/src/lib/utils/helpers.ts

The `View Hidden Items` accordion in the `For You` section scrolls to the top below the nav bar when the accordion opens up.
[#185932083](https://www.pivotaltracker.com/story/show/185932083)

feat: [185932083] view hidden items accordion scrolls to top when opened

---

web/src/components/LandingPageActionTile.tsx
web/src/components/njwds/Hero.tsx
web/src/pages/index.tsx

Removal of alternative text on the Navigator landing page for eligible decorative images, and amendment of alternative text for eligible informative images.
This does not include any changes to the "Made with ❤️ by the" text, as that will be covered in a different pull request.
[#186084930](https://www.pivotaltracker.com/story/show/186084930)
Cues were taken from [W3C's guide on Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/), specifically with regard to `alt=""` and `role="presentation"`. The decision matrix used was:
- If image was both decorative and illustrative in nature, it got both `alt=""` and `role="presentation"`.
- If image was decorative, it got `alt=""`.
- If image was informative, its alternative text was updated.
Verify that the alt text matches the …

feat: [#186084930] Hide landing page presentational images from screen readers

---

CHANGELOG.md
package.json

* [[#185931982](https://github.com/newjersey/navigator.business.nj.gov/issues/185931982)] action card styling updates ([5a7569b](https://github.com/newjersey/navigator.business.nj.gov/commit/5a7569b353ceb484f001e201b8359a28c2363cc9))
* [[#185931982](https://github.com/newjersey/navigator.business.nj.gov/issues/185931982)] Action card styling updates ([fbde2fd](https://github.com/newjersey/navigator.business.nj.gov/commit/fbde2fd97a057a408813e8ec7423d3532954d37c))

chore(release): 5.36.0 [skip ci]

---

CHANGELOG.md
package.json

* [[#185893614](https://github.com/newjersey/navigator.business.nj.gov/issues/185893614)] circle ci config env vars ([a04d085](https://github.com/newjersey/navigator.business.nj.gov/commit/a04d085409652aa382277c743c3c00d6415fd920))
* [[#185893614](https://github.com/newjersey/navigator.business.nj.gov/issues/185893614)] remove duplicate field from licenseSearchTask in CMS ([a847a18](https://github.com/newjersey/navigator.business.nj.gov/commit/a847a183baa79feb6e5af20afc5beef74c3d46dc))
* [[#186366473](https://github.com/newjersey/navigator.business.nj.gov/issues/186366473)] added Analytics for formation task help button ([f7efe5a](https://github.com/newjersey/navigator.business.nj.gov/commit/f7efe5ae32ac7faa995510ddde6096dd81a45b1c))
* …

chore(release): 5.37.0 [skip ci]

---

scripts/clear-ports.sh

feat: [#186448388] add 8081 to clear ports script

---

CHANGELOG.md
package.json

* [[#186429361](https://github.com/newjersey/navigator.business.nj.gov/issues/186429361)] dynamics license status application id filtering to account for null ([e7f37cf](https://github.com/newjersey/navigator.business.nj.gov/commit/e7f37cfa1cf24023c367d38df28513d2b7f9e775))
* [[#186094556](https://github.com/newjersey/navigator.business.nj.gov/issues/186094556)] add more helpful aria-labels to EDIT buttons ([0a5ff73](https://github.com/newjersey/navigator.business.nj.gov/commit/0a5ff73d238fb895ae70a56a756fd59624189bf2))
* [[#186448388](https://github.com/newjersey/navigator.business.nj.gov/issues/186448388)] add 8081 to clear ports script ([4cdb043](https://github.com/newjersey/navigator.business.nj.gov/commit/4cdb04314ac4982a54cf8bf97bf395815e87b8fe))

chore(release): 5.38.0 [skip ci]

---

.circleci/config.yml

Add enable-dashboard to all integration-tests step in CI

---

web/src/components/PageFooter.tsx
web/src/components/PageSkeleton.tsx

chore: [#186384501] update name of footer component

---

web/cypress/support/page_objects/landingPage.ts
web/src/lib/static/admin/findDeadLinks.test.ts
web/src/lib/static/admin/findDeadLinks.ts

bug: fix landing test

---

web/src/lib/utils/helpers.ts

[#185932083](https://www.pivotaltracker.com/story/show/185932083)
Update scroll on View Hidden Items Accordion such that it does not go past the navbar.

chore: [#185932083] update hidden opps to not pass navbar on scroll

---

.editorconfig
.vscode/extensions.json
.vscode/settings.json

To improve intra-team collaboration when pair programming, this pull request provides some quality-of-life improvements to enhance the experience of using VSCode when working on this repository. This is done with two enhancements:
- improvements to files in the `.vscode` directory
- the addition of an `.editorconfig` file
(The `.editorconfig` file is added to improve quality-of-life for anyone using editorconfig-aware editors.
These have been borrowed from prior open-source projects I've worked on, carefully curated to the technologies we use here in this repository. Where there were conflicting extension recommendations between the prior projects and with the recommended extensions from Next.js, the ones from Next.js were used.
Make sure to close VSCode before switching to this branch in …

chore: quality-of-life improvements for VSCode

---

web/src/components/PageFooter.tsx

chore: [#186384501] update bg color of footer component

---

CHANGELOG.md
package.json

* [[#185555573](https://github.com/newjersey/navigator.business.nj.gov/issues/185555573)] state contracting quick action ([726c63a](https://github.com/newjersey/navigator.business.nj.gov/commit/726c63a3f45a39aeb73229d9c2d2806e0f9dd100))
* [[#185932019](https://github.com/newjersey/navigator.business.nj.gov/issues/185932019)] opportunity card styling ([d02ac44](https://github.com/newjersey/navigator.business.nj.gov/commit/d02ac449952c522425e08d7fa38aa3c84b1d9e55))
* [[#186093180](https://github.com/newjersey/navigator.business.nj.gov/issues/186093180)] HTML Page Titles should reference page content ([9db0f16](https://github.com/newjersey/navigator.business.nj.gov/commit/9db0f167785e42578c8ead80d778b26be75f62c8))

chore(release): 5.39.0 [skip ci]

---

web/src/components/dashboard/QuickActionTaskLink.tsx
web/src/components/dashboard/QuickActionTaskTile.tsx
web/src/pages/dashboard.tsx
web/src/styles/components/quick-action-tile.scss

chore: [#185555573] fix spacing in mobile for quick action

---

package.json
web/.storybook/main.js
web/package.json
yarn.lock

chore: remove storybook-addon-pseudo-states

---

CHANGELOG.md
content/src/roadmaps/license-tasks/general-appraiser-certification.md
content/src/roadmaps/license-tasks/home-inspector-license.md
package.json

* [[#185932083](https://github.com/newjersey/navigator.business.nj.gov/issues/185932083)] update hidden opps to not pass navbar on scroll ([2fb04f2](https://github.com/newjersey/navigator.business.nj.gov/commit/2fb04f25268a968356589a6c4b70a8759905a445))
* **deps:** update dependency @smithy/node-http-handler to v2.1.9 ([9a3dc8b](https://github.com/newjersey/navigator.business.nj.gov/commit/9a3dc8b18dbc77840c7beebbad6a1c29b411359c))
* **deps:** update dependency @types/mdast to v4 ([77c7947](https://github.com/newjersey/navigator.business.nj.gov/commit/77c7947194fe68bf818bc39ef0f984fe4231b515))
* **deps:** update dependency axios to v1 [security] ([cc69a1b](https://github.com/newjersey/navigator.business.nj.gov/commit/cc69a1b38649d198872a58636bfaae857e3ad76c))
* **deps:** update dependency …

chore(release): 5.40.0 [skip ci]

---

content/src/display-content/roadmap-sidebar-cards/not-registered-existing-account.md
content/src/display-content/roadmap-sidebar-cards/not-registered.md

Given that I am a Home Improvement Contractor Poppy, when I first visit my dashboard, then I should see a For You card with a white title.
[186537095](https://www.pivotaltracker.com/story/show/)

fix: [#186537095] fix side bar card title to white

---

web/src/components/data-fields/BusinessPersonaQuestion.tsx
web/test/pages/onboarding/helpers-onboarding.tsx
web/test/pages/onboarding/onboarding-owning.test.tsx
web/test/pages/onboarding/onboarding-starting.test.tsx

feat: [#186374749] remove aria labels from onboarding step one radios

---

web/src/components/TaskProgressTagLookup.tsx
web/src/components/dashboard/OpportunityCard.tsx
web/src/components/njwds-extended/Tag.tsx
web/src/styles/base/border-colors.scss
web/src/styles/base/variables.scss
web/stories/Atoms/Tag/TagLabel.stories.tsx
web/stories/Atoms/Tag/TagStatus.stories.tsx

Storybook Tag Revisions

---

web/src/components/profile/ProfileTabHeader.tsx

feat: [#186363219] guest disclaimer in profile margin revisions

---

web/src/components/FieldEntryAlert.test.tsx
web/src/components/FieldEntryAlert.tsx
web/src/components/profile/ProfileField.tsx
web/src/components/tasks/business-formation/FormationField.tsx
web/src/components/tasks/business-formation/contacts/Signatures.tsx
web/src/styles/base/global.scss

https://www.pivotaltracker.com/story/show/185757752

fix: [#185757752] fix scrolling behavior on alert with href routing

---

CHANGELOG.md
package.json

* [[#186478423](https://github.com/newjersey/navigator.business.nj.gov/issues/186478423)] fix header white colors on sidebar card ([5d603ac](https://github.com/newjersey/navigator.business.nj.gov/commit/5d603acde7f788d440a4ae516105876cdceb5527))
* [[#186537095](https://github.com/newjersey/navigator.business.nj.gov/issues/186537095)] fix side bar card title to white ([b7958e7](https://github.com/newjersey/navigator.business.nj.gov/commit/b7958e7e7a3889e34ee2b58fda13855c7a411122))
* [[#186561090](https://github.com/newjersey/navigator.business.nj.gov/issues/186561090)] Govt Contracting quick action showing for construction sector id ([ee39001](https://github.com/newjersey/navigator.business.nj.gov/commit/ee39001ac153684bf8cb640040cb38d8398c032a))
* **deps:** update dependency …

chore(release): 5.41.0 [skip ci]

---

web/src/lib/domain-logic/getLicenseCalendarEvents.test.ts
web/src/styles/base/global.scss

Revert scroll change for green ci

---

web/src/components/dashboard/SidebarCardGeneric.tsx

fix: [#186609639] SidebarCard header margin fixed

---

web/src/components/dashboard/QuickActionTaskLink.tsx
web/src/styles/base/flex.scss

https://www.pivotaltracker.com/story/show/186569515

feat: [#186569515] consistent quick action heights

---

CHANGELOG.md
content/src/roadmaps/license-tasks/life-hazard-use-registration.md
content/src/roadmaps/license-tasks/non-life-hazard-use-registration.md
package.json

- chore: webflow license sync [skip-ci]
- chore(release): 5.42.0 [skip ci]

release 20231206

---

web/src/components/dashboard/QuickActionTaskLink.tsx
web/src/components/dashboard/QuickActionTaskTile.tsx
web/src/styles/components/quick-action-tile.scss
web/stories/Molecules/QuickActions.stories.tsx

feat: [#185606709] storybook - quick action

---

web/stories/Atoms/Typography.stories.tsx
web/stories/Molecules/QuickActions.stories.tsx

feat: [#186203974] storybook - h2 unbolded

---

content/src/fieldConfig/business-formation.json
shared/src/formationData.ts
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/business/BusinessStep.test.tsx
web/src/components/tasks/business-formation/business/FormationRadio.tsx
web/src/components/tasks/business-formation/business/SuffixDropdown.tsx
web/src/components/tasks/business-formation/business/WillPracticeLaw.tsx

feat: [#185994565] Foreign Corp Business Designators

---

web/src/components/tasks/business-formation/business/MainBusiness.tsx

[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185994565)

feat: [#185994565] revisions to foreign corp designator

---

.circleci/config.yml
CHANGELOG.md
package.json

* updating Tasks - All daycare-evaluate-location ([#5665](https://github.com/newjersey/navigator.business.nj.gov/issues/5665)) ([e37c188](https://github.com/newjersey/navigator.business.nj.gov/commit/e37c1888a8f3b7482e6a0271d2017fe485609c14))
* updating Taxes Filings - All nj-927_927-w ([#4472](https://github.com/newjersey/navigator.business.nj.gov/issues/4472)) ([514e060](https://github.com/newjersey/navigator.business.nj.gov/commit/514e0602cabb123ee20d04383009f90f26070913))
* [[#184606287](https://github.com/newjersey/navigator.business.nj.gov/issues/184606287)] storybook - action bar ([f2f0f23](https://github.com/newjersey/navigator.business.nj.gov/commit/f2f0f23c5862d28a1f8ddb45981790b74fb9391f))
* [[#185606709](https://github.com/newjersey/navigator.business.nj.gov/issues/185606709)] …

chore(release): 5.43.0 [skip ci]

---

web/src/components/tasks/LicenseStatusReceipt.tsx

While working on the ticket mentioned below, an update to the `UnstyledButton` did not take effect so I made the update. I also removed a `console.log` that inadvertently got merged into main.
[#186263393](https://www.pivotaltracker.com/story/show/186263393)

fix: remove style attribute from UnstyledButton and inadvertent console.log

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/components/ChecklistTag.tsx
web/src/components/TaskElement.tsx
web/src/components/tasks/LicenseStatusReceipt.tsx
web/src/components/tasks/LicenseTask.test.tsx
web/src/components/tasks/LicenseTask.tsx
web/src/lib/utils/helpers.ts

Updates to license status check redesign
[#186263393](https://www.pivotaltracker.com/story/show/186263393)

fix: [#186263393] update license status check tab redesign

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/components/PageFooter.tsx

chore: [#186659137] add aria label to footer

---

api/src/api/healthCheckRouter.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyHealthCheckClient.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyInspectionClient.ts
api/src/client/dynamics/elevator-safety/types.ts
api/src/domain/types.ts
api/src/functions/express/app.ts

Add healthcheck endpoint for DCA Dynamics Elevator Safety
[186741011](https://www.pivotaltracker.com/story/show/)
Injected the client into the healthcheck router
Run locally and hit '/health/dynamics/elevators'

refactor: [#186741011]: DCA Dynamics Elevator Health Check Setup

---

content/src/roadmaps/add-ons/foreign-remote-seller.json

https://www.pivotaltracker.com/story/show/186569187
Remove "Update Your Insurance Policy" Task for Dakota Remote Sellers by updating the roadmap add on json file

feat: [#186569187] remove insurance policy task for Remote Sellers

---

web/src/lib/domain-logic/getNavBarBusinessTitle.ts
web/src/lib/domain-logic/isRemoteWorkerOrSeller.test.ts
web/src/lib/domain-logic/isRemoteWorkerOrSeller.ts
web/src/lib/domain-logic/shouldShowDisclaimerForProfileNotSubmittingData.test.ts
web/src/lib/domain-logic/shouldShowDisclaimerForProfileNotSubmittingData.ts
web/src/pages/profile.tsx
web/test/pages/profile/profile-foreign.test.tsx

to remote seller remote worker in profile
Add Business Name field to Profile for Dakota Remote Sellers and Dakota Remote Workers  
https://www.pivotaltracker.com/story/show/185681159

feat: [#185681159] add business name field and note

---

content/src/fieldConfig/dashboard-snackbars.json
web/public/mgmt/config.yml
web/src/pages/dashboard.tsx
web/test/pages/dashboard.test.tsx

**Undesired Behavior:**
When the user manually marks the Tax Registration task complete, the certification snackbar is displayed regardless of the user's formation status. If the user hasn't completed the Formation task, the For You section doesn't display certifications, but the snackbar still states certifications have been added.
**Current Behavior:**
When the user has not formed and marks the Tax Registration task complete, they are routed to the dashboard and a snackbar stating certifications have been added is displayed even though they not been added since the user hasn't yet formed.
**Expected Behavior:**
When the user has not formed and marks the Tax Registration task complete, they are routed to the dashboard
[#186682632](https://www.pivotaltracker.com/story/show/#186682632)

fix: [#186682632] update certifications snackbar to display after formation

---

content/src/quick-action-tasks/apprenticeship-program-intake.md
content/src/quick-action-tasks/njstart-registration.md
content/src/quick-action-tasks/prevailing-wage.md
content/src/quick-action-tasks/public-works-contractor-registration.md
web/src/components/tasks/government-contracting/GovernmentContractingPaginator.tsx
web/src/pages/actions/[quickActionTaskUrlSlug].tsx

feat: [#186150128] Poppy and Oscar HIC State Contracting

---

content/src/quick-action-tasks/apprenticeship-program-intake.md
content/src/quick-action-tasks/njstart-registration.md
content/src/quick-action-tasks/prevailing-wage.md
content/src/quick-action-tasks/public-works-contractor-registration.md

feat: [#186150128] poppy and hic

---

web/src/components/filings-calendar/FilingsCalendarSingleGrid.test.tsx
web/src/lib/domain-logic/getLicenseCalendarEvents.ts

fix: [#186765441] prevent feb license renewals appearing in jan

---

web/src/components/data-fields/IndustryDropdown.tsx

[#186798269](https://www.pivotaltracker.com/story/show/)

fix: [#186798269] Industry search bold text

---

web/src/components/LandingPageActionTile.tsx
web/src/components/njwds-extended/PrimaryButton.tsx
web/src/styles/base/drop-shadows.scss
web/src/styles/components/buttons.scss
web/src/styles/main.scss
web/src/styles/sass-files/mixin.scss
web/src/styles/sass-files/variables.scss
web/stories/Atoms/DropShadows.stories.tsx

https://www.pivotaltracker.com/story/show/186303948
Refactored drop shadows to use mixin feature so box shadow can be included in existing classes.

chore: [#186303948] refactor drop shadows scss to use mixins

---

web/src/components/profile/ProfileTab.tsx
web/src/components/profile/ProfileTabNav.tsx

chore: [#186393974] update props in ProfileTab component

---

web/src/components/tasks/business-formation/NexusFormationFlow.tsx

Follow up to increase readability by creating explicit variable names.
[#185001723](https://www.pivotaltracker.com/story/show/185001723)

refactor: [#185001723] explicit variables to increase readability

---

content/src/fieldConfig/config.json
web/public/mgmt/config.yml
web/src/components/PageFooter.tsx
web/src/lib/static/admin/findDeadLinks.ts

Removed twitter icon and facebook icon in the footer.
[#186494878](https://www.pivotaltracker.com/story/show/186494878)

feat: [#186494878] remove twitter icon and add facebook icon in footer

---

.circleci/config.yml
content/src/fieldConfig/business-formation.json
cspell.json
web/src/components/filings-calendar/FilingsCalendarSingleGrid.test.tsx
web/src/lib/domain-logic/getLicenseCalendarEvents.ts

Update myNJ account link.
[#186818972](https://www.pivotaltracker.com/story/show/186818972)
I knew this was going to happen. Just didn't know when. Thank you me in the past for doing the work, regardless of how small it was.
There are other instances of the old URL in the code. For example see `MyNjSelfRegClient.ts`. We previously confirmed with OIT that these are not changing. See screenshot of email conversation below:

Update myNJ Account Link

---

web/src/components/dashboard/QuickActionTile.tsx

Amanda asked if the tile could span the whole browser window on mobile and tablet.
[#186810093](https://www.pivotaltracker.com/story/show/186810093)

Uniform Quick Action tile height - design qa update

---

.gitignore
scripts/get-matching-users.sh

Create a script to query for Dakota cannabis businesses.
[#186827102](https://www.pivotaltracker.com/story/show/186827102)

Find Dakota Cannabis Businesses

---

CHANGELOG.md
package.json

* [[#186620499](https://github.com/newjersey/navigator.business.nj.gov/issues/186620499)] no nav menu for onboarding authenticated users ([376eb9f](https://github.com/newjersey/navigator.business.nj.gov/commit/376eb9faf710b4ef6f3c1dd37a1e31b18026de08))
* [[#186682632](https://github.com/newjersey/navigator.business.nj.gov/issues/186682632)] update certifications snackbar to display after formation ([d7500e7](https://github.com/newjersey/navigator.business.nj.gov/commit/d7500e771c38ed6440bcd3cf1bf0aa1a6def1713))
* [[#186765441](https://github.com/newjersey/navigator.business.nj.gov/issues/186765441)] prevent feb license renewals appearing in jan ([05248a7](https://github.com/newjersey/navigator.business.nj.gov/commit/05248a7d1c27f389b4ca48fe486d9b7748bfa6ff))
* …

chore(release): 2024.1.0 [skip ci]

---

api/src/functions/express/app.ts

[#185977080](https://www.pivotaltracker.com/story/show/)

revert: [#185977080] ordering of userFactory api

---

web/cypress/e2e/deferred-onboarding.spec.ts

[#185977080](https://www.pivotaltracker.com/story/show/)

revert: [#185977080] revert cypress tests

---

web/src/components/dashboard/QuickActionContainer.tsx
web/src/lib/types/types.ts

feat: [#186352406] quickaction find match refactor

---

web/src/pages/dashboard.tsx
web/src/pages/loading.tsx

[#185977080](https://www.pivotaltracker.com/story/show/)

fix: [#185977080] link account card bug

---

web/src/pages/loading.tsx

fix: [#185977080] window.location.assign debugging

---

web/src/pages/loading.tsx

fix: [#185977080] link card bug fix updateQueue

---

CHANGELOG.md
content/src/roadmaps/industries/commercial-construction.json
package.json

- chore: add updated files from webflow sync [skip-ci]
- chore(release): 2024.2.1 [skip ci]

release 20240130

---

web/src/components/CountryDropdown.tsx
web/src/components/GenericTextField.tsx
web/src/components/StateDropdown.tsx

https://www.pivotaltracker.com/story/show/186393520
FIND, THEN SQUASH THE BUG  :muscle:
The Address modal is a great place to test this. Or any place where your browser allows you to select a previously saved value and has an error state.

chore: wip [skip ci]

---

CHANGELOG.md
content/src/roadmaps/license-tasks/career-consultant-agency-reg.md
content/src/roadmaps/license-tasks/career-counseling-firm-reg.md
content/src/roadmaps/license-tasks/consulting-firm-headhunter-reg.md
content/src/roadmaps/license-tasks/entertainment-agency-reg.md
content/src/roadmaps/license-tasks/fire-safety-inspection.md
content/src/roadmaps/license-tasks/fire-safety-key-box.md
content/src/roadmaps/license-tasks/fire-safety-smoke-detectors.md
content/src/roadmaps/license-tasks/job-listing-service-reg.md
content/src/roadmaps/license-tasks/temporary-help-service-firm-reg.md
package.json

- chore: add updated files from webflow sync [skip-ci]
- chore(release): 2024.3.0 [skip ci]

release 20240202

---

web/public/mgmt/config.yml

chore: [#186986810] update fund opps labels in cms

---

web/src/components/navbar/NavBarDashboardLink.test.tsx
web/src/components/navbar/NavBarDashboardLink.tsx

Fix that routes the user to onboarding from the landing page when my account is clicked.
[#186444137](https://www.pivotaltracker.com/story/show/186444137)
[#186444230](https://www.pivotaltracker.com/story/show/186444230)

fix: [#186444137] [#186444230] route to onboarding from landing page

---

content/src/quick-action-tasks/apprenticeship-program-intake.md
content/src/quick-action-tasks/architecture-license-reinstatement.md
content/src/quick-action-tasks/authorization-certificate-reinstatement.md
content/src/quick-action-tasks/electrical-contracting-business-permit-reactivation.md
content/src/quick-action-tasks/electrical-contracting-business-permit-update.md
content/src/quick-action-tasks/government-contracting.md
content/src/quick-action-tasks/hic-registration-reinstatement.md
content/src/quick-action-tasks/njstart-registration.md
content/src/quick-action-tasks/prevailing-wage.md
content/src/quick-action-tasks/public-works-contractor-registration.md
content/src/quick-action-tasks/registry-update-brc-amendment.md
web/public/mgmt/config.yml
web/src/lib/async-content-fetchers/fetchQuickActionByFilename.ts
web/src/lib/search/searchQuickActionTasks.ts
web/src/lib/types/types.ts
web/src/lib/utils/markdownReader.ts
web/src/pages/actions/[quickActionTaskUrlSlug].tsx
web/test/factories.ts

This adds a `summaryDescriptionMd` field to Quick Action Tasks, similar to our other pieces of content. Also included with this pull request:
- Migration of content that makes sense into the new `summaryDescriptionMd` field.
- Modified the content by adding line breaks so it would render in the CMS preview properly.
- Made the new `summaryDescriptionMd` field for this content searchable.
- Fixes to the content so it has the proper heading order (h2 -> h3 -> h4).
[#186820573](https://www.pivotaltracker.com/story/show/186820573)
Nothing new here. Very similar task to the headings updates.
Verify each piece of content in the CMS to ensure it renders properly. Not sure if each content item can be triggered to display manually within the app.
Will need verification from content that some of …

[#186820573] Add summaryDescriptionMd field to Quick Action Tasks

---

web/public/mgmt/config.yml
web/src/lib/cms/previews/FundingsPreview.tsx

https://www.pivotaltracker.com/story/show/186993249

chore: [#186993249] add funding card preview in cms

---

web/public/mgmt/config.yml

Increase option limit for relations drop downs and update search functionality
[#186994934](https://www.pivotaltracker.com/story/show/186994934)

chore: [#186994934] increase option limit for relations drop downs and update search functionality

---

web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx
web/src/components/tasks/business-formation/getErrorStateForField.test.ts
web/src/components/tasks/business-formation/getErrorStateForField.ts
web/src/components/tasks/business-formation/name/BusinessNameStep.tsx

- CMS: Sector and Industry Dropdowns Not Populating All Items [#186994934](https://www.pivotaltracker.com/story/show/186994934)
- Formation: Change Error from Alert to Inline in Business Name Search for Non-Dakota [#184764052](https://www.pivotaltracker.com/story/show/184764052)

Cherry-picked commits to fix merges to main and reverts of merges

---

content/src/roadmaps/license-tasks/fire-safety-inspection.md
content/src/roadmaps/license-tasks/fire-safety-key-box.md
content/src/roadmaps/license-tasks/fire-safety-smoke-detectors.md

Merge content-repo into main

---

CHANGELOG.md
package.json

* [[#186444137](https://github.com/newjersey/navigator.business.nj.gov/issues/186444137)] [[#186444230](https://github.com/newjersey/navigator.business.nj.gov/issues/186444230)] navbar link to my new jersey styling and semi bold font-weight ([b4dc32b](https://github.com/newjersey/navigator.business.nj.gov/commit/b4dc32b6109398886efc67a12cd597ac068a8b76))
* [[#186444137](https://github.com/newjersey/navigator.business.nj.gov/issues/186444137)] [[#186444230](https://github.com/newjersey/navigator.business.nj.gov/issues/186444230)] route to onboarding from landing page ([7f5ff75](https://github.com/newjersey/navigator.business.nj.gov/commit/7f5ff7569a8733292220c8a28aa3d0a9b826a80b))
* increase operations per run in workflow ([1527181](https://github.com/newjersey/navigator.business.nj.gov/com …

chore(release): 2024.4.0 [skip ci]

---

api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v129_add_elevator_owning_business_to_profile.ts
content/src/display-content/contextual-information/elevator-device.md
content/src/fieldConfig/profile.json
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/next.config.js
web/src/components/data-fields/ElevatorOwningBusiness.tsx
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts
web/src/pages/profile.tsx

Setup non-essential question for elevator-owners and a corresponding task to be added to the roadmap
[186982853](https://www.pivotaltracker.com/story/show/186982853)
The "elevator_registration" task is still in review, so all of this content is behind a feature flag until that is merged into main

refactor: [#186982853] add elevator non essential question behind feature flag

---

CHANGELOG.md
package.json

* [[#186775240](https://github.com/newjersey/navigator.business.nj.gov/issues/186775240)] Add health checks for Formation ([911688e](https://github.com/newjersey/navigator.business.nj.gov/commit/911688ec8381a816265ac26643d8ddf3f864730c))

chore(release): 2024.5.0 [skip ci]

---

api/src/functions/express/app.ts
shared/src/dateHelpers.ts

Add health checks to formation
[#186775240](https://www.pivotaltracker.com/story/show/)

feat: [#186775240] Add health checks to formation

---

content/src/roadmaps/tasks/sign-lease-food-truck.md

[#187064247](https://www.pivotaltracker.com/story/show/#187064247)

fix: [#187064247] change sign-lease urlSlug so correct task renders for non-food truck industries

---

web/public/mgmt/config.yml

Addition of hint tags to fields in `Config.yml` to help Content understand what the fields are for.
[#187099108](https://www.pivotaltracker.com/story/show/187099108)

chore: [#187099108] add hints to navigator with webflow mappings license tasks

---

web/cypress/e2e/onboarding-as-starting-business.spec.ts

https://www.pivotaltracker.com/story/show/186966376
Add cypress mobile test for 1 industry/ starting a business. We also created specific describe blocks for desktop and mobile to improve readability

test: [#187091927] cypress poppy onboarding mobile

---

content/src/roadmaps/add-ons/elevator-owning-business.json
content/src/roadmaps/license-tasks/elevator-registration.md
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts
web/src/pages/profile.tsx

Connect elevator registration task to non-essential question
[#187116541](https://www.pivotaltracker.com/story/show/187116541)
Register as a non-home based business and you should see the elevator non-essential question in profile. If you select "yes" and save, you will see the new task in Section 4 if you've selected a business structure.

refactor: [#187116541] connect elevator registration task to roadmap

---

CHANGELOG.md
package.json

* **deps:** update dependency axios to v1.6.7 ([393c2cd](https://github.com/newjersey/navigator.business.nj.gov/commit/393c2cdf80bb4f4aaae614dd78b95d737137710d))
* **deps:** update material-ui ([d5924a4](https://github.com/newjersey/navigator.business.nj.gov/commit/d5924a47aa2c440139b52e554af0aed280c8602b))
* **deps:** update material-ui ([1421665](https://github.com/newjersey/navigator.business.nj.gov/commit/14216656219c842528df735f894db7a248b431c2))

chore(release): 2024.7.1 [skip ci]

---

CHANGELOG.md
package.json

* [[#185761403](https://github.com/newjersey/navigator.business.nj.gov/issues/185761403)] set initial business effective date relative to NJ local date ([2198218](https://github.com/newjersey/navigator.business.nj.gov/commit/2198218c6cbace705d437313a45ce926634ed886))
* [[#186781958](https://github.com/newjersey/navigator.business.nj.gov/issues/186781958)] change homebasedBusiness value based on officeInNJ ([1bb3e2e](https://github.com/newjersey/navigator.business.nj.gov/commit/1bb3e2e8a0f953b6d1645e90e86e1b2bd5521636))
* **deps:** update dependency @emotion/react to v11.11.4 ([40d9eba](https://github.com/newjersey/navigator.business.nj.gov/commit/40d9ebaa9f492de3602c46dddd239c6488c14fba))
* **deps:** update dependency unist-util-visit to v5 …

chore(release): 2024.8.0 [skip ci]

---

web/src/components/tasks/CheckStatus.tsx
web/src/components/tasks/LicenseTask.test.tsx

[#186896489](https://www.pivotaltracker.com/story/show/186896489)

feat: [#186896489] pre-populate license task check status business info

---

content/src/roadmaps/license-tasks/career-consultant-agency-reg.md
content/src/roadmaps/license-tasks/career-counseling-firm-reg.md
content/src/roadmaps/license-tasks/consulting-firm-headhunter-reg.md
content/src/roadmaps/license-tasks/cosmetology-license.md
content/src/roadmaps/license-tasks/cosmetology-school-license.md
content/src/roadmaps/license-tasks/cosmetology-teacher-license.md
content/src/roadmaps/license-tasks/elevator-registration.md
content/src/roadmaps/license-tasks/entertainment-agency-reg.md
content/src/roadmaps/license-tasks/fire-safety-inspection.md
content/src/roadmaps/license-tasks/fire-safety-key-box.md
content/src/roadmaps/license-tasks/fire-safety-smoke-detectors.md
content/src/roadmaps/license-tasks/general-appraiser-certification.md
content/src/roadmaps/license-tasks/job-listing-service-reg.md
content/src/roadmaps/license-tasks/life-hazard-use-registration.md
content/src/roadmaps/license-tasks/non-life-hazard-use-registration.md
content/src/roadmaps/license-tasks/temporary-help-service-firm-reg.md

Steps to Reproduce:
Onboard as an employment agency industry and complete the business structure task
In step 4 of the roadmap, go to the "register your" task details page
Current Behavior:
In the roadmap, there are multiple Active/Current tasks instead of one. Also, the tasks are displaying the same content.
Expected Behavior:
One active task in the mini roadmap, and each task routes/renders the correct information.
Dev Note
Since the impact of this bug is currently not clear, it would be helpful to first ensure that triage is completed to help understand whether or not this bug has significant impact (i.e. can impact any/all users) or if the impact is limited (i.e. certain set of circumstances or narrow use cases). If the impact is limited and/or if the fix requires significant effort …

fix: [#187004657] Employment Agency Tasks are not rendering correctly

---

CHANGELOG.md
package.json

- **chore: update @types/node to 20.x**
- **chore(release): 2024.9.0 [skip ci]**

release 20240308

---

content/src/fundings/film-tax-credit.md
cspell.json

fix linting issues
[#187212042](https://www.pivotaltracker.com/story/show/)
fix linting issues

chore: [#187212042] fix linting issues

---

web/cypress/e2e/dashboard.spec.ts
web/cypress/e2e/performance-and-accessability.spec.ts
web/src/pages/_app.tsx

This sets the minimum viewport size to 360px, and initial scale of the page to 1. ([The former is required by the latter](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag#viewport_width_and_screen_width).)
[#187239241](https://www.pivotaltracker.com/story/show/187239241)
Tested with the following:
- iPhone 15 Pro (portrait and landscape)
- Galaxy S21 FE (portrait and landscape)
- iPhone SE (2nd generation) (simulated)
- iPad Pro (12.9-inch, 6th generation) (simulated)
However, I wasn't able to test with any devices smaller than 360px because those devices are actually no longer supported in the latest versions of iOS.

feat: [#187239241] set minimum viewport size to 360px

---

web/src/components/navbar/mobile/NavBarMobile.tsx
web/src/components/navbar/mobile/NavBarMobileAccountSlideOutMenu.tsx
web/src/components/navbar/mobile/NavBarMobileQuickLinksSlideOutMenu.tsx

Some of the various nav bar revisions
Mainly, getting the correct BusinessTitle to show up on the mobile menu
Also getting the correct BusinessTItle to show up on the mobile nav bar header
Color fix for hamburger
Aria-label corrections for mobile menu icons
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/186811252)
^ see comments

Navbar revisions

---

api/serverless.ts
api/src/functions/healthCheck/app.ts
api/src/functions/healthCheck/index.ts
api/src/libs/healthCheck.test.ts
api/src/libs/healthCheck.ts

Added a lambda function that runs a healthCheck on all of the endpoints.
[#186665645](https://www.pivotaltracker.com/story/show/186665645)

chore: [#186665645] add healthCheck lambda function

---

web/src/lib/cms/helpers/applyTheme.tsx

chore: apply correct theme to CMS preview

---

web/cypress/e2e/onboarding-as-existing-business.spec.ts
web/cypress/e2e/onboarding-as-starting-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts

Updated tests under starting/Poppy to reflect a new objects file.
Added a new objects file to combine duplicate functions that are used by the new cypress spec files
[#187166174](https://www.pivotaltracker.com/story/show/187166174)
###
Open Cypress
Run the onboarding-as-existing-business.spec.ts file
- [ x] I have performed a self-review of my code

feat: [#187166174] Update Cypress Tests for Oscar Onboarding

---

web/src/components/FocusTrappedSidebar.tsx
web/src/components/navbar/desktop/NavBarDesktop.tsx
web/src/components/navbar/desktop/NavBarDesktopWrapper.tsx
web/src/components/navbar/mobile/NavBarMobile.tsx
web/src/components/navbar/mobile/NavBarMobileAccountSlideOutMenu.tsx
web/src/lib/cms/previews/NavBarPreview.tsx

chore: [#187202751] fix navbar preview in cms

---

CHANGELOG.md
package.json

* [[#187133827](https://github.com/newjersey/navigator.business.nj.gov/issues/187133827)] add check to reroute user to the landing page if userData has not populated ([7f060b1](https://github.com/newjersey/navigator.business.nj.gov/commit/7f060b1d5fc2c0b87963a1db7ff5396d9880345a))
* [[#187166174](https://github.com/newjersey/navigator.business.nj.gov/issues/187166174)] Update Cypress Tests for Oscar Onboarding ([6c8892a](https://github.com/newjersey/navigator.business.nj.gov/commit/6c8892a112b1869125a21059c0a16d36620c7740))
* Revert "feat: [#187097677] Consistent title tags" ([4197c20](https://github.com/newjersey/navigator.business.nj.gov/commit/4197c2081d9ac424dbafd484d382813e78b37573)), closes [#187097677](https://github.com/newjersey/navigator.business.nj.gov/issues/187097677)

chore(release): 2024.11.0 [skip ci]

---

api/src/api/elevatorSafetyRouter.ts
api/src/api/housingRouter.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyInspectionStatusClient.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationClient.test.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationClient.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationStatusClient.test.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationStatusClient.ts
api/src/client/dynamics/elevator-safety/types.ts
api/src/client/dynamics/housing/DynamicsHousingClient.test.ts
api/src/client/dynamics/housing/DynamicsHousingClient.ts
api/src/client/dynamics/housing/DynamicsHousingPropertyInterestClient.test.ts
api/src/client/dynamics/housing/DynamicsHousingPropertyInterestClient.ts
api/src/client/dynamics/housing/types.ts
api/src/domain/types.ts
api/src/functions/express/app.ts
shared/src/elevatorSafety.ts

Updates the Elevator and Housing APIs to expose elevator device registration
[187116541](https://www.pivotaltracker.com/story/show/187116541)
Can hit the new /api/elevator/registration endpoint

refactor: [#187116541] add elevator registration API changes

---

content/src/roadmaps/add-ons/cpa.json
content/src/roadmaps/industries/certified-public-accountant.json

fix: [#187315826] fix duplicate acct tasks

---

content/src/roadmaps/industries/certified-public-accountant.json

Reverts newjersey/navigator.business.nj.gov#7434

Revert "chore: updating Roadmaps - Industries certified-public-accountant"

---

web/src/components/navbar/mobile/NavBarMobile.tsx
web/src/lib/cms/previews/NavBarPreview.tsx

Fix scrolling behavior in mobile. The issue arose due to `CMS_PREVIEW_ONLY_SHOW_MENU` prop being undefined in Dev, which resulted in scrolled being set to `true` because of `!CMS_PREVIEW_ONLY_SHOW_MENU`
https://www.pivotaltracker.com/story/show/187296259

chore: [#187296259] fix scrolling behavior in mobile

---

web/src/components/dashboard/DashboardAlerts.test.tsx
web/src/components/dashboard/DashboardAlerts.tsx
web/src/pages/dashboard.tsx
web/test/pages/dashboard.test.tsx

Prefactor for another ticked, moving dashboard alerts into their own component

feat: dashboard alert component

---

api/serverless.ts

[#186665645](https://www.pivotaltracker.com/story/show/186665645)

fix: [#186665645] aws healthcheck lambda policy

---

content/src/fieldConfig/config.json
content/src/page-metadata/page-metadata.json
web/public/mgmt/config.yml
web/src/components/dashboard/quick-actions/QuickActionPage.tsx
web/src/contexts/configContext.ts
web/src/lib/cms/previews/PageMetadataPreview.tsx
web/src/lib/domain-logic/getNextSeoTitle.ts
web/src/lib/search/cmsCollections.ts
web/src/lib/static/loadPageMetadata.ts
web/src/lib/types/types.ts
web/src/lib/utils/markdownReader.ts
web/src/pages/_app.tsx
web/src/pages/certification/[certificationUrlSlug].tsx
web/src/pages/dashboard.tsx
web/src/pages/filings/[filingUrlSlug].tsx
web/src/pages/funding/[fundingUrlSlug].tsx
web/src/pages/index.tsx
web/src/pages/licenses/[licenseUrlSlug].tsx
web/src/pages/mgmt/cms.tsx
web/src/pages/mgmt/deadlinks.tsx
web/src/pages/mgmt/deadurls.tsx
web/src/pages/mgmt/feature-flags.tsx
web/src/pages/mgmt/search.tsx
web/src/pages/onboarding.tsx
web/src/pages/profile.tsx
web/src/pages/tasks/[taskUrlSlug].tsx

User Story
As a user, I need to understand what each page is about and how Business.NJ.gov and My Account are associated so that I can navigate to the page I need.
AC
My Account
Given I am a My Account user
When viewing a title tag on the B.NJ site or on a search engine
Then I see title tag in a ‘[Page Title] | Business.NJ.gov’ structure
ADO
https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/4112
Design
https://app.mural.co/t/officeofinnovation7132/m/officeofinnovation7132/1696256683563/f7a1fb2ad83905d88317b7acf172d3fbb059480b?wid=23-1705959231746
[#187097677](https://www.pivotaltracker.com/story/show/)

chore: [#187097677] Consistent title tags

---

api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationClient.test.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationClient.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationStatusClient.test.ts
api/src/client/dynamics/elevator-safety/types.ts
content/src/fieldConfig/config.json
shared/src/elevatorSafety.ts
shared/src/index.ts
web/src/components/TaskPageSwitchComponent.tsx
web/src/components/tasks/CheckElevatorRegistrationStatus.tsx
web/src/components/tasks/ElevatorRegistrationStatusSummary.tsx
web/src/components/tasks/ElevatorRegistrationTask.test.tsx
web/src/components/tasks/ElevatorRegistrationTask.tsx
web/src/lib/api-client/apiClient.ts
web/src/lib/types/types.ts

Updates the elevator registration task to be dynamic and dependent on API data
[187116541](https://www.pivotaltracker.com/story/show/187116541)

feature: [#187116541] dynamic elevator status search

---

CHANGELOG.md
content/src/roadmaps/license-tasks/health-club-registration.md
package.json

* [[#186665645](https://github.com/newjersey/navigator.business.nj.gov/issues/186665645)] aws healthcheck lambda policy ([e7ac693](https://github.com/newjersey/navigator.business.nj.gov/commit/e7ac69377358e6e2869fe84699ac699f7823d0b6))
* [[#187315826](https://github.com/newjersey/navigator.business.nj.gov/issues/187315826)] fix duplicate acct tasks ([6f48494](https://github.com/newjersey/navigator.business.nj.gov/commit/6f48494e81d5050d10e5425b2705d30647afb36e))
* [[#187357115](https://github.com/newjersey/navigator.business.nj.gov/issues/187357115)] update elevator copy ([7acdb64](https://github.com/newjersey/navigator.business.nj.gov/commit/7acdb647cc8cfe8650af368d4551c52c82947104))
* **deps:** update dependency express to v4.19.2 [security] …

chore(release): 2024.12.0 [skip ci]

---

.circleci/config.yml
content/src/roadmaps/industries/health-club.json
web/package.json
web/src/scripts/fundingExport.mjs
web/src/scripts/webflow/fundingSync.mjs
web/src/scripts/webflow/industrySync.mjs
web/src/scripts/webflow/licenseSync.mjs
web/src/scripts/webflow/methods.mjs
web/src/scripts/webflow/sectorSync.mjs
web/src/scripts/webflow/webflowIds.mjs
web/src/scripts/webflow/webflowSync.test.js

Update Webflow to [version 2](https://docs.developers.webflow.com/data/docs/migrating-to-v2) to ensure we are able to access the most up-to-date endpoints.
I implemented the following changes, per the documentation:
- Renamed property _id to id (object)
- Renamed property _archived to isArchived
- Renamed property _draft to isDraft
- Deleted property fields (object)
- Deleted: live in query
[#186964023](https://www.pivotaltracker.com/story/show/186964023)

chore: [#186964023] update webflow to v2

---

web/src/lib/static/admin/findDeadLinks.ts

chore: [#187348102] dead link checker log added

---

web/cypress/e2e/onboarding-as-existing-business.spec.ts
web/cypress/e2e/onboarding-as-starting-business.spec.ts
web/cypress/support/helpers/helpers.ts

Cypress Existing Business Mobile Tests
[#187166173](https://www.pivotaltracker.com/story/show/)
Run Cypress tests

feat: [#187166173] Cypress Existing Business Mobile Tests

---

content/src/fieldConfig/elevator-registration.json
web/public/img/access_time_filled.svg
web/public/mgmt/config.yml
web/src/components/tasks/ElevatorRegistrationStatusSummary.tsx
web/src/components/tasks/ElevatorRegistrationTask.test.tsx
web/src/lib/async-content-fetchers/fetchTaskByFilename.ts

Update display of elevator registration status returns to use carded designs
[187354337](https://www.pivotaltracker.com/story/show/187354337)

feat: [#187354337] use cards for elevator registration task

---

api/src/libs/healthCheck.ts

Make the health check api fail in dev and prod
[#186665645](https://www.pivotaltracker.com/story/show/)

chore: [#186665645] make api fail

---

.github/pull_request_template.md

fix: [#187354337] match content from elevator registration task

---

CHANGELOG.md
package.json

* [[#187354337](https://github.com/newjersey/navigator.business.nj.gov/issues/187354337)] add reference to CMS additions documentation in PR template ([0674ed1](https://github.com/newjersey/navigator.business.nj.gov/commit/0674ed101b82d725dbfb4261510a24293989dba7))
* [[#187354337](https://github.com/newjersey/navigator.business.nj.gov/issues/187354337)] match content from elevator registration task ([f8bd3a8](https://github.com/newjersey/navigator.business.nj.gov/commit/f8bd3a8cdbc338d7f4026d45a95f06ea37a0fe35))
* [[#187380461](https://github.com/newjersey/navigator.business.nj.gov/issues/187380461)] restore elevator registration task to cms ([c3d9a38](https://github.com/newjersey/navigator.business.nj.gov/commit/c3d9a3834f0f5081c6597e6f34269703ce8b96f3))
* change formation test to …

chore(release): 2024.13.0 [skip ci]

---

api/src/libs/healthCheck.ts

revert health apis to back to success
[#186665645](https://www.pivotaltracker.com/story/show/)

fix: [#186665645] revert health apis back to success

---

web/src/components/filings-calendar/FilingsCalendar.tsx

fix: [#187450950] align calendar icon

---

api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v131_add_construction_type_essential_question.ts
content/src/fieldConfig/profile.json
content/src/roadmaps/add-ons/construction-home-renovation.json
content/src/roadmaps/add-ons/construction-new-home-construction.json
content/src/roadmaps/industries/commercial-construction.json
shared/src/industry.ts
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/public/mgmt/config.yml
web/src/components/data-fields/Industry.test.tsx
web/src/components/data-fields/Industry.tsx
web/src/lib/domain-logic/essentialQuestions.ts
web/src/lib/roadmap/buildUserRoadmap.ts

adds two essential questions for construction onboarding, one of which only appears dependent on the answer to the other
[#187464224](https://www.pivotaltracker.com/story/show/187464224)
Added a new filtering question to essential questions appearing that enables conditional appearance. Filtering right now is based on fieldName for the essential question and just looks at profileData.

feat: [#187464224] add essential questions for construction onboarding

---

web/cypress/e2e/onboarding-as-starting-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts

Adds essential questions for construction onboarding to cypress
[187464224](https://www.pivotaltracker.com/story/show/187464224)

fix: [#187464224] fix construction onboarding

---

web/src/styles/components/profile-tab-nav.scss

feat: [#187476824] profile side navigation wraps when bolded

---

.circleci/config.yml

This change allows automation of deployment to the testing environment on weekends.
[187039768](https://www.pivotaltracker.com/story/show/187039768)
- Updates `.circleci/config.yml` by adding a schedule to run the `build-accessibility-testing-weekly` on weekends at Noon Saturday.

chore: automate deploy to testing environment on weekends

---

CHANGELOG.md
content/src/roadmaps/industries/lodging.json
package.json

- **chore: add updated files from webflow sync [skip ci]**
- **re-trigger CI build**
- **chore(release): 2024.14.0 [skip ci]**

release 20240425

---

web/cypress/e2e/onboarding-as-existing-business.spec.ts
web/cypress/e2e/onboarding-as-starting-business.spec.ts

Remove the query string from `dashboard?fromOnboarding=true` to coincide with feature work implementation to ensure that the `onboarding-as-starting-business` and `onboarding-as-existing-business` Cypress tests aren't flaky.
[#187263740](https://www.pivotaltracker.com/story/show/187263740)

fix: [#187263740] update dashboard URL in onboarding-as Cypress tests

---

CHANGELOG.md
content/src/roadmaps/license-tasks/hotel-registration.md
package.json

* [[#187554142](https://github.com/newjersey/navigator.business.nj.gov/issues/187554142)] extra close-bolding in json markdown ([220d515](https://github.com/newjersey/navigator.business.nj.gov/commit/220d5159cc4ec1732fff3b2b5c5210eb333d0d8f))
* **deps:** update dependency @emotion/styled to v11.11.5 ([3cc73a2](https://github.com/newjersey/navigator.business.nj.gov/commit/3cc73a2c5761e8f4e314b9cebbe8e77bac75c64f))

chore(release): 2024.15.1 [skip ci]

---

scripts/get-matching-users.sh
scripts/get-user-location.sh

This adds tests to check if `jaq` or `gojq` is installed for faster JSON parsing. If found, it switches to the faster tool.
1. Set `DEBUG` to true within the script.
2. `brew install gojq`, then test a sample query against just one page of results of our database.
3. `brew install jaq`, then test a sample query against just one page of results of our database.

chore: update get-matching-users to use jaq or gojq if available

---

.circleci/config.yml
web/package.json

The CI job was trying to use the old API token with the new V2 API endpoints. Replaced the token and updated CircleCI job to reference the new token. Additionally, added a dedicated `webflow-sync` CI job.
[#187570052](https://www.pivotaltracker.com/story/show/187570052)

Fix Webflow sync CI job

---

web/cypress/e2e/onboarding-as-foreign-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts

[#187166165](https://www.pivotaltracker.com/story/show/187166165) 
[#187166161](https://www.pivotaltracker.com/story/show/187166161)

feat: [#187166165][#187166161] Cypress Out of state remote worker desktop and mobile Tests

---

api/src/domain/user/updateLicenseStatusFactory.test.ts
api/src/domain/user/updateLicenseStatusFactory.ts
web/src/components/TaskPageSwitchComponent.tsx
web/test/pages/taskUrlSlug.test.tsx

Given I am a Poppy or Dakota and I am in the Accounting industry
When accessing the Public Accountant license task in the roadmap
Then I can check the status of my license with Consumer Affairs Dynamics system
[#187611792](https://www.pivotaltracker.com/story/show/187611792)
1. Access the site as a Poppy or Dakota in the Accounting Industry. 
2. Click the `Apply for a Certified Public Accountant License` in the roadmap. 
3. Enter the contact information for an expired business. 
4. Go back to the dashboard.
5. Click the Deadlines and Opportunities card and complete the information in the modal.
6. Click the Funding Opportunities card.
The quick action tiles will appear on the dashboard.

feat: [#187611792] enable public accountant license

---

api/src/db/migrations/migrations.ts
api/src/db/migrations/v135_use_interstate_logistics_and_transport_fields.test.ts
api/src/db/migrations/v135_use_interstate_logistics_and_transport_fields.ts
shared/src/userData.ts

UserData and the versioned UserData in the migrations folder got misaligned in this commit: https://github.com/newjersey/navigator.business.nj.gov/commit/4f574aaf6314b94b9a67246a475ece020589d66e
Basically, `interstateLogistics` and `interstateMoving` are the profileData fields that are being referenced in the application, but they are called `isInterstateLogisticsApplicable` and `isInterstateMovingApplicable` in the migrations version of user data. This restores the two to the same property name.
As for populating data, these fields were only assigned on industry assignment. Therefore, the migration can just apply the same industry check to set the correct values for these two fields

fix: [#187636181] synchronize migration and userData for interstate moving and logistics

---

CHANGELOG.md
package.json

* [[#187553558](https://github.com/newjersey/navigator.business.nj.gov/issues/187553558)] Remove elevator feature flag ([53d4352](https://github.com/newjersey/navigator.business.nj.gov/commit/53d4352550892f34d152b6e56d89f08b12dac150))
* **deps:** update dependency dayjs to v1.11.11 ([ab56f9e](https://github.com/newjersey/navigator.business.nj.gov/commit/ab56f9e58d5982b84963329c05e2cea2263e56d9))
* **deps:** update material-ui to v5.15.16 ([f432e65](https://github.com/newjersey/navigator.business.nj.gov/commit/f432e65a4fed1aadb9f07fc9eab14d9ea1588e2e))
* [[#186897265](https://github.com/newjersey/navigator.business.nj.gov/issues/186897265)]change registered agent office from dropdown to field text ([319bdd3](https://github.com/newjersey/navigator.business.nj.gov/commit/319bdd34425713e7b83df …

chore(release): 2024.16.0 [skip ci]

---

web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx
web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx
web/src/components/tasks/business-formation/business/MainBusinessForeignAddressFlow.tsx

There a number of places in the codebase where the file name differs from the React component that it exports. This is an  anti-pattern as the file name should match the name of the React component it exports.
**_*Examples:*_**
- `MainBusinessAddressUs.tsx`
- `MainBusinessAddressIntl.tsx`
[#187662283](https://www.pivotaltracker.com/story/show/187662283)
There may be other instances of this naming inconsistency in the code, but `MainBusinessAddressUs.tsx` and `MainBusinessAddressIntl.tsx` are the two instances I am aware of at this time.

chore: [#187662283] update file name to match React component

---

CHANGELOG.md
content/src/roadmaps/license-tasks/authorization-landscape-architect-firm_1.md
content/src/roadmaps/license-tasks/landscape-architect-license.md
content/src/roadmaps/license-tasks/multiple-dwelling-registration.md
content/src/roadmaps/license-tasks/ticket-broker-reseller-registration.md
package.json

* [[#187636181](https://github.com/newjersey/navigator.business.nj.gov/issues/187636181)] synchronize migration and userData for interstate moving and logistics ([e21e025](https://github.com/newjersey/navigator.business.nj.gov/commit/e21e0253f4a137fd2516ef45ab01251f0304cc46))
* [[#187642582](https://github.com/newjersey/navigator.business.nj.gov/issues/187642582)] move multiple dwelling and ticket broker to license tasks ([2d641f3](https://github.com/newjersey/navigator.business.nj.gov/commit/2d641f378feefc63f41cfdb2e4a2e89f7ae027c2))
* additional callout code fixes ([51bcd14](https://github.com/newjersey/navigator.business.nj.gov/commit/51bcd14c6c9f77e399c37a55ca5d78edff8e8a3b))
* callout code cleanup [skip ci] ([370d972](https://github.com/newjersey/navigator.business.nj.gov/commit/370d9 …

chore(release): 2024.17.0 [skip ci]

---

web/cypress/e2e/onboarding-as-foreign-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts

Updated cypress onboarding tests for remote seller business
[#187166158](https://www.pivotaltracker.com/story/show/187166158)
[#187166156](https://www.pivotaltracker.com/story/show/187166156)
Run cypress tests for Onboarding Foreign Business
All tests should pass.

feat: [#187166158][#187166156] Cypress Out of state remote seller desktop and mobile Tests

---

web/src/components/dashboard/DashboardHeader.tsx

removal of a tiny peice of CSS

feat: [#187414334] remove white fill from for you column header

---

api/src/api/elevatorSafetyRouter.ts
api/src/api/externalEndpointRouter.ts
api/src/api/fireSafetyRouter.ts
api/src/api/formationRouter.test.ts
api/src/api/formationRouter.ts
api/src/api/guestRouter.test.ts
api/src/api/guestRouter.ts
api/src/api/healthCheckRouter.test.ts
api/src/api/housingRouter.ts
api/src/api/licenseStatusRouter.test.ts
api/src/api/licenseStatusRouter.ts
api/src/api/selfRegRouter.test.ts
api/src/api/selfRegRouter.ts
api/src/api/taxDecryptionRouter.ts
api/src/api/taxFilingRouter.test.ts
api/src/api/taxFilingRouter.ts
api/src/api/userRouter.test.ts
api/src/api/userRouter.ts
api/src/client/ApiFormationClient.test.ts
api/src/client/ApiTaxFilingClient.test.ts
api/src/client/ApiTaxFilingClient.ts
api/src/client/WebserviceLicenseStatusClient.test.ts
api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyHealthCheckClient.test.ts
api/src/client/dynamics/fire-safety/DynamicsFireSafetyHealthCheckClient.test.ts
api/src/client/dynamics/housing/DynamicsHousingHealthCheckClient.test.ts
api/src/client/dynamics/license-status/DynamicsLicenseHealthCheckClient.test.ts
api/src/domain/s3Writer.test.ts
api/src/domain/s3Writer.ts
api/src/functions/express/app.ts
api/src/functions/githubOauth2/app.ts

Replace hardcoded status codes and message phrases to improve code readability, clarity, and maintainability.
[#186855108](https://www.pivotaltracker.com/story/show/186855108)

chore: [#186855108] replace hardcoded status codes and message phrases

---

.github/pull_request_template.md

chore: update pr template to include rebasing from latest main branch

---

requirements.txt

- updates the requirements.txt file to include the `python-dotenv` dependency/package that was missing. 
- Updates the requirements.txt file to add required installation package.

fix: update requirements.txt to install python-dotenv

---

.circleci/config.yml

- Change updates the  `set-content-env-vars` section of the Config.yml but removing a redudant Env variable as well as exporting the COGNITO_WEB_CLIENT_ID_CONTENT. 
- Updates config.yml

chore: updates content environment variables

---

CHANGELOG.md
package.json

* [[#187652148](https://github.com/newjersey/navigator.business.nj.gov/issues/187652148)] resolved issues with see your tax due dates modals ([0bb5f2f](https://github.com/newjersey/navigator.business.nj.gov/commit/0bb5f2fab2c625622245acac3567c168e853f1dc))
* **deps:** update dependency @types/mdast to v4.0.4 ([125f08d](https://github.com/newjersey/navigator.business.nj.gov/commit/125f08d39f0db44f2e23123c68bf2854f2bffb11))
* **deps:** update material-ui to v5.15.19 ([e83c063](https://github.com/newjersey/navigator.business.nj.gov/commit/e83c063f25b3efae4ed728bb123280014f46b299))
* update lower env deploys to target correct ECS clusters ([d22126c](https://github.com/newjersey/navigator.business.nj.gov/commit/d22126c5f2871526438466862c0c40010cc19dd6))
* …

chore(release): 2024.18.0 [skip ci]

---

web/cypress/e2e/check-license-status.spec.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-existing-business.spec.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-starting-business.spec.ts
web/cypress/e2e/performance-and-accessability.spec.ts
web/cypress/e2e/profile.spec.ts
web/cypress/tsconfig.json

https://www.pivotaltracker.com/story/show/187790105
The goal of this ticket is to create a folder structure for new cypress tests that Marques is working on. This will help separate the old tests that will likely be deleted/ refactored. It will also help workflow management in Circle Ci. There are specific commands in the describe block that identify the workflow the tests will execute in. Reassigning all onboarding tests to group 1. And all group 1 tests to group 4 (temp assignment).
It's not the final state, but a pivot that will help with organization.

chore: [#187790105] add folder structure to cypress tests

---

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx

chore: [#187815500] fix buggy tests in formation

---

web/src/pages/profile.tsx
web/test/pages/profile/profile-owning.test.tsx

chore: [#187194184] save address in profile on save

---

web/src/components/profile/getErrorStateForAddressField.test.ts
web/src/components/profile/getErrorStateForAddressField.ts
web/test/pages/profile/profile-owning.test.tsx

chore: [#187194184] fix max char error label in oscar profile

---

web/src/components/navbar/NavBarLogoOnly.tsx

fix: design QA for myNJ logo

---

api/src/api/formationRouter.test.ts
api/src/api/licenseStatusRouter.test.ts
api/src/api/taxFilingRouter.test.ts
api/src/db/dynamoUserDataMigration.test.ts
api/src/domain/tax-filings/taxFilingsInterfaceFactory.test.ts
api/src/domain/user/fetchMunicipalityByName.ts
web/src/lib/auth/signinHelper.test.ts

This is a _continuation_ of the remove relative imports work from [Reduce Relative Import Use in API Folder](https://github.com/newjersey/navigator.business.nj.gov/pull/6511#pullrequestreview-1704739481).
I updated as many imports as I could (given some just won't work and present build errors/issues), and specifically the ones (see below) that we called out in the **Reduce Relative Import Use in API Folder** PR:
- formationRouter.test.ts
- taxFiliingsInterfaceFactory.test.ts
- fetchMunicipalityByName.ts
This pull request resolves [#186365752](https://www.pivotaltracker.com/story/show/186365752).

chore: [#186365752] remove relative imports from mocks

---

CHANGELOG.md
api/src/client/ApiFormationClient.test.ts
api/src/client/ApiFormationHelpers.ts
package.json

- **fix: redeploy for formation API content-type changes**
- **chore(release): 2024.19.1 [skip ci]**

release 20240618

---

api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.ts
api/src/domain/license-status/searchLicenseStatusFactory.test.ts
api/src/domain/license-status/searchLicenseStatusFactory.ts
api/src/domain/user/updateLicenseStatusFactory.test.ts
api/src/domain/user/updateLicenseStatusFactory.ts
content/src/roadmaps/industries/telemarketing.json
web/src/components/TaskPageSwitchComponent.tsx
web/test/pages/taskUrlSlug.test.tsx

Given I am a Poppy or Dakota
and I am in the Telemarketing industry
when accessing the license task in the roadmap
then I can check the status of my license with Consumer Affairs Dynamics system
This pull request resolves [#187708192](https://www.pivotaltracker.com/story/show/187708192).

feat: [#187708192] add check status to telemarketing license

---

api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.ts
api/src/domain/license-status/searchLicenseStatusFactory.test.ts
api/src/domain/license-status/searchLicenseStatusFactory.ts
api/src/domain/user/updateLicenseStatusFactory.test.ts
api/src/domain/user/updateLicenseStatusFactory.ts
content/src/roadmaps/industries/retail.json
web/src/components/TaskPageSwitchComponent.tsx
web/test/pages/taskUrlSlug.test.tsx

Enable ticket broker license status check.
This pull request resolves [#187790535](https://www.pivotaltracker.com/story/show/#187790535).
1. Access the site as a Poppy or Dakota as a Health Club (industry).
2. Once you are directed to the dashboard, click the `Business Profile` link.
3. In the business profile, respond `yes` to the non-essential question, _Do you plan to resell admission tickets to places of entertainment and charge more than the original price?_, and save your response.
4. Click the `Register Your Business as a Ticket Broker (Ticket Reseller)` task in the roadmap.
5. Enter the contact information for a business.
6. The license status will display for the business.

feat: [#187790535] enable ticket brokers and resellers license status check

---

api/src/client/ApiFormationClient.test.ts

This pull request resolves [#187870088](https://www.pivotaltracker.com/story/show/187870088).

chore: [#187870088] poppy formation business address optional

---

content/src/roadmaps/industries/domestic-employer.json

chore: add missing key industryOnboardingQuestions to domestic employer industry

---

content/src/fieldConfig/profile.json
content/src/roadmaps/add-ons/employment-agency-employers-both.json
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts

Adding the newly created employment task for the Employment industry essential question when the selection option is `BOTH` to the roadmap. 
This pull request resolves [#186948523](https://www.pivotaltracker.com/story/show/186948523).
1. Access the site as a Poppy or Dakota with a business in the  _Employment Agency_ industry.
2. **Answering the essential question:** Select 'Employers' and 'Both'.
3. Click `Show Your Guide`.
4. The `Register Your Temporary Help Service Firm` task will appear in the roadmap.
**NOTE:** At this time there is no license status for this industry.

chore: [#186948523] update roadmap tasks for employment both selection

---

content/src/roadmaps/industries/employment-agency.json
content/src/roadmaps/license-tasks/consulting-firm-headhunter-reg.md
content/src/roadmaps/license-tasks/pharmacy-cds.md
content/src/roadmaps/license-tasks/search-licenses-employment-agency.md
content/src/roadmaps/license-tasks/temporary-help-service-firm-reg.md

Merge content repo into main

---

content/src/fieldConfig/formation-interim-success-page.json

Copy update to fix an alertText typo.

fix: update alertText copy to eliminate typo

---

web/src/components/HorizontalLine.tsx
web/src/components/dashboard/anytime-actions/AnytimeActionDropdown.tsx

Responds to design feedback marking the anytime action horizontal divider as aria hidden
This pull request resolves [#187754524](https://www.pivotaltracker.com/story/show/187754524).

fix: [#187754524] update anytime action horizontal line to be aria hidden

---

web/src/components/OutageAlertBar.tsx

- Addresses contrast related accessibility violation for the outage alert bar
This pull request resolves [#187871332](https://www.pivotaltracker.com/story/show/187871332).
- Trigger outage alert bar locally

feat: [#187871332] use error dark for outage alert background 💅

---

content/src/fieldConfig/config.json

Updates the copy for InvestNewark consent checkbox
This pull request resolves [#187934580](https://www.pivotaltracker.com/story/show/187934580).

Update invest newark checkbox to content

---

CHANGELOG.md
package.json
web/src/components/tasks/business-formation/BusinessFormation.test.tsx
web/src/components/tasks/business-formation/BusinessFormation.tsx

- **fix: [#186334874] api responses inconsistently received**
- **chore(release): 2024.21.1 [skip ci]**

release 20240716

---

content/src/mappings/fundingAgency.json
web/public/mgmt/config.yml

This pull request resolves [#187977335](https://www.pivotaltracker.com/story/show/187977335).

feat: [#187977335] add municipality field to fundings and investNewark as agency source

---

web/src/components/dashboard/DashboardHeader.tsx
web/src/components/dashboard/DashboardOnDesktop.tsx
web/src/components/dashboard/ElevatorViolationsCard.tsx
web/src/components/data-fields/EssentialQuestionField.tsx
web/src/components/data-fields/Industry.tsx
web/src/components/navbar/desktop/NavBarLogoOnlyDesktop.tsx
web/src/components/tasks/business-formation/contacts/Addresses.tsx
web/src/styles/components/line.scss

_**This PR addresses the following Design QA tickets:**_
1. [Update Spacing Between Additional Onboarding Questions](https://www.pivotaltracker.com/story/show/187978546) (#187978546)
**- Issue:** When an additional question appears below the Industry drop down, no additional padding is there to separate the question.
**- Fix:** Added 24px padding between each question displayed and ensured that the questions are evenly spaced out.
2. [Elevator Violation Prompt Button Alignment](https://www.pivotaltracker.com/n/projects/2573455/stories/187929362) (#187929362)
**- Issue:** The button is top aligned with container.
**- Fix:** Updated styling to be center aligned.
3. [Update For You Line Height From 2px to 1px](https://www.pivotaltracker.com/story/show/187979026) (#187979026)
**- Issue:** The …

chore: [#187979026] update for you line height 

---

web/test/pages/profile/profile-starting.test.tsx

fix: update flakey failing profile test

---

api/package.json
api/serverless.ts
yarn.lock

This pull request resolves an issue where we get an error with our serverless deployment 
```
Error:
CREATE_FAILED: HealthCheckLambdaVersionz9IHjgn7hHYx8yggarqcnHf27uKk9Xn2pgzKVTxLw (AWS::Lambda::Version)
Resource handler returned message: "Code storage limit exceeded. (Service: Lambda, Status Code: 400, Request ID: 5b04b30c-6a3e-4926-ba3a-d36a6b0373bb)" (RequestToken: 18354a6c-981d-a350-41be-d494faa857ab, HandlerErrorCode: GeneralServiceException)
```

chore: prune Lambda versions to a maximum of 5

---

CHANGELOG.md
api/package.json
api/serverless.ts
package.json
web/src/components/navbar/shared-submenu-components.test.tsx
web/src/components/navbar/shared-submenu-components.tsx
yarn.lock

- **bug: [#188028980] link with myNewJersey error in dropdown**
- **chore: prune Lambda versions to a maximum of 5**
- **chore(release): 2024.22.1 [skip ci]**

release 20240730

---

.circleci/config.yml

This change updates the `set-accessibility-testing-env-vars`  and `set-content-env-vars` sections of  the `config.yml` to point the environment variables to the right values.

chore: update env variables for testing and content repo

---

api/src/domain/user/updateOperatingPhase.test.ts
api/src/domain/user/updateOperatingPhase.ts
shared/src/domain-logic/businessPersonaHelpers.test.ts
shared/src/domain-logic/businessPersonaHelpers.ts
shared/src/operatingPhase.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts
web/src/components/data-fields/IndustryDropdown.test.tsx
web/src/components/data-fields/IndustryDropdown.tsx
web/src/components/onboarding/OnboardingFlows.tsx
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts
web/src/pages/onboarding.tsx
web/src/pages/profile.tsx
web/test/pages/onboarding/onboarding-starting.test.tsx
web/test/pages/profile/profile-starting.test.tsx

<br>
**Streamline the Domestic Employer experience, so users are not overwhelmed or confused by many of the operations/tasks that are not applicable to this industry.**
<br>
_Update the domestic employer industry experience such that:_
1.  a Poppy Domestic Employer cannot form, and will not have access to the onboarding nonprofit question nor the business structure question in the profile 
2. a Poppy Domestic Employer will have an empty "For You" column
3. a Poppy Domestic Employer will have only the `Business Name` and `Industry` fields in its Business Information in the 
profile
4. a Poppy Domestic Employer will NOT have the `Entity Id` field in its Reference Numbers tab in the profile
5. a Dakota will not have Domestic Employer as an industry to select
This pull request resolves …

feat: [#187901632] update domestic employer experience

---

web/src/scripts/webflow/fundingSync.mjs

This adds Invest Newark as a funding agency for the Webflow sync, and it improves logging for which files might be triggering an issue.
This pull request resolves [#188043304](https://www.pivotaltracker.com/story/show/188043304).
- [collection details](https://developers.webflow.com/data/reference/collection-details) Webflow API endpoint

chore: [#188043304] add Invest Newark Funding Agency for Webflow sync

---

.circleci/config.yml

Update Content Env Variables

---

web/test/pages/onboarding/helpers-onboarding.tsx

Fix flaky onboarding test
This pull request resolves [#188051113](https://www.pivotaltracker.com/story/show/188051113).

fix: [#188051113] Fix flaky onboarding test

---

content/src/roadmaps/license-tasks/Haul-Waste.md
content/src/roadmaps/license-tasks/annual-license-cannabis.md
content/src/roadmaps/license-tasks/apply-for-food-truck-license.md
content/src/roadmaps/license-tasks/apply-for-shop-license.md
content/src/roadmaps/license-tasks/appraiser-certification.md
content/src/roadmaps/license-tasks/appraiser-company-register.md
content/src/roadmaps/license-tasks/authorization-landscape-architect-firm.md
content/src/roadmaps/license-tasks/conditional-permit-cannabis.md
content/src/roadmaps/license-tasks/conversion-license-cannabis.md
content/src/roadmaps/license-tasks/family-daycare-register.md
content/src/roadmaps/license-tasks/home-health-aide-license.md
content/src/roadmaps/license-tasks/landscape-architect-license.md
content/src/roadmaps/license-tasks/license-acupuncture.md
content/src/roadmaps/license-tasks/license-broker.md
content/src/roadmaps/license-tasks/license-engineer.md
content/src/roadmaps/license-tasks/license-massage-therapy.md
content/src/roadmaps/license-tasks/moving-company-license.md
content/src/roadmaps/license-tasks/multiple-dwelling-registration.md
content/src/roadmaps/license-tasks/notary-register.md
content/src/roadmaps/license-tasks/register-consumer-affairs.md
content/src/roadmaps/license-tasks/search-licenses-employment-agency.md
content/src/roadmaps/license-tasks/spray-paint-booth-permit-auto-body-repair.md
content/src/roadmaps/license-tasks/ticket-broker-reseller-registration.md
content/src/roadmaps/license-tasks/town-mercantile-license.md
content/src/webflow-licenses/health-care-services-firm-renewal.md
web/package.json
web/src/scripts/licenseLoader.mjs
web/src/scripts/webflow/helpers.mjs
web/src/scripts/webflow/licenseSync.mjs

Somehow we had a bunch of extra licenses in webflow, turns out we didn't have a webflow delete licenses function. 
This pull request resolves [#187809299](https://www.pivotaltracker.com/story/show/187809299).
Run the preview script added to package json and see that there are no files to be deleted.

Fixed extra webflow licenses

---

web/src/pages/starter-kits/general.tsx

feat: [#187738760] button width increased on mobile

---

web/src/pages/starter-kits/general.tsx

Create general starter kit revisions revisions

---

content/src/filings/nj-927_927-w.md

Fixing a filing identifier to allow events to render properly on the tax calendar.

chore: update nj-927_927-w filing id

---

web/src/lib/domain-logic/sidebarCardsHelpers.test.ts

https://www.pivotaltracker.com/story/show/188073076
Added an agency field to staged data to override the generator value (which randomly selects from a list). This change fixes the flakey failing tests.

fix: [#188073076] fix flakey agencyFundingSorting tests

---

web/public/mgmt/config.yml

https://www.pivotaltracker.com/story/show/188073424
Content not able to create new Industry due to industryOnboardingQuestions field missing. Fix: set defaults within each sub-field's configuration to false. This will force the object to be created.

fix: [#188073424] industryOnboardingQuestions widget

---

CHANGELOG.md
package.json

* [[#187809299](https://github.com/newjersey/navigator.business.nj.gov/issues/187809299)] license and sync certification delete issues ([9f9a428](https://github.com/newjersey/navigator.business.nj.gov/commit/9f9a4287fe1e1954065c8158fd506dcb730e75e3))
* [[#187973765](https://github.com/newjersey/navigator.business.nj.gov/issues/187973765)] potential CMS bug with callouts ([debd562](https://github.com/newjersey/navigator.business.nj.gov/commit/debd562271d859f257634f7f88b7efe04221210b))
* [[#187978546](https://github.com/newjersey/navigator.business.nj.gov/issues/187978546)] update styling for add'l onboarding questions ([0f6e67c](https://github.com/newjersey/navigator.business.nj.gov/commit/0f6e67c80a51b54074e39764f519b55daefe066d))
* …

chore(release): 2024.23.0 [skip ci]

---

web/public/sitemap.xml

Add sitemap.xml to Navigator as a static asset to tell search engines which pages to index within the application. When adding a new page, you should follow this formula:
```xml
<url>
<loc>https://navigator.business.nj.gov/{page}</loc>
<lastmod>{ISO 8601 date}</lastmod>
<changefreq>{yearly, monthly weekly}</changefreq>
<priority>{1.0 for main page, 0.5 is default}</priority>
</url>
```
This pull request resolves [#187432804](https://www.pivotaltracker.com/story/show/187432804).
1. Visit https://dev.navigator.business.nj.gov/sitemap.xml
2. Ensure the page responds with content type of XML and HTTP status of 200.

Add sitemap.xml to Navigator

---

web/.dependency-cruiser.js
web/package.json
web/public/sitemap.xml
web/src/lib/domain-logic/routes.ts
web/src/lib/utils/starterKits.ts
web/src/pages/starter-kits/[starterKitsUrl].tsx
web/src/pages/starter-kits/index.tsx
web/src/scripts/generateSitemap.ts
web/tsconfig.json

We wanted to dynamically generate our sitemap.xml file to include all our starterkits paths.
This pull request resolves [#188121854](https://www.pivotaltracker.com/story/show/188121854).
We decided to use a .ts script to call the generating functions that create the starter-kits urls and generate the xml for the sitemap.
Also added it to our package json so it runs automatically
delete the sitemap.xml file, 
run the build
see that the sitemap is regenerated
You will need to run the install script before testing locally, as this adds a new dependency, [tsx](https://tsx.is).

Links for industry specific starter kits

---

content/src/roadmaps/license-tasks/cemetery-branch.md
content/src/roadmaps/license-tasks/cemetery-certificate.md
content/src/roadmaps/license-tasks/raffle-license-step-1.md
content/src/roadmaps/license-tasks/raffle-license-step-2.md
web/src/scripts/webflow/helpers.mjs
web/src/scripts/webflow/licenseSync.mjs

This fixes the errors with creating new licenses in Webflow due to a JSON serialization issue. The content field is not actually used in Webflow and therefore we can just omit it.
This pull request resolves [#188117562](https://www.pivotaltracker.com/story/show/188117562).
Run a license sync against main.
When we [rewrite the sync scripts in TypeScript](https://www.pivotaltracker.com/story/show/186624811), we should align our markdown conversion pipeline with the one we use in web/ to display the components. That way we don't need custom stripping logic.

fix: [#188117562] fix license sync serialization issue

---

web/src/components/profile/ProfileNewJerseyAddress.tsx

spacing between state and muni for tablet
This pull request resolves [#187003755](https://www.pivotaltracker.com/story/show/187003755).

fix: [#187003755] spacing between state and muni for tablet

---

web/public/mgmt/config.yml

https://www.pivotaltracker.com/story/show/188136291

chore: [#188136291] update anytime action collection labels

---

BuilderImage.Dockerfile

This pull request resolves [#187476515](https://www.pivotaltracker.com/story/show/187476515). The change updates the `BuilderImage.DockerFile` to dynamically pull the latest versions of browsers, replacing the previously hard-coded versions. This enhancement ensures that our build environment always utilizes the most recent browser releases, improving compatibility and security.
Updated the `BuilderImage.DockerFile` for the 3 listed browsers. Edge, Chrome and Firefox.

feat: [#187476515] Implement auto update of browser in builderImage

---

scripts/report-users-with-tax-ids.py

The script added in this work will read in user data and generate a report containing `email`, `business name`, and `has tax id`. 
This pull request resolves [#188103179](https://www.pivotaltracker.com/story/show/188103179).

Add Report to Determine if User Supplied Tax ID

---

api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v139_own_carnival_rides.ts
content/src/anytime-action-tasks/carnival-ride-supplemental-modification.md
content/src/fieldConfig/profile.json
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/public/mgmt/config.yml
web/src/components/dashboard/anytime-actions/AnytimeActionDropdown.tsx
web/src/pages/profile.tsx

Adds a non-essential question to profile for Oscars which triggers new anytime action
This pull request resolves [#188064481](https://www.pivotaltracker.com/story/show/188064481).
1. Create a new Oscar business or take a Poppy to up-and-running
2. Choose an industry other than `Arts, Entertainment, and Recreation` and verify the "Modify Your Carnival or Amusement Ride" isn't in the Anytime Actions
3. Switch to `Arts, Entertainment, and Recreation` in the profile (and optionally verify that this itself doesn't trigger the anytime action)
4. Answer yes to the Carnivals question
5. Verify the expected task appears in the Anytime Actions

feat: [#188064481] Add anytime action from carnival non-essential question for Oscars

---

web/src/components/tasks/LicenseDetailReceipt.tsx

chore: [#188072347] remove padding on license checklist text

---

content/src/mappings/sectors.json

This pull request resolves [#188178510](https://www.pivotaltracker.com/story/show/188178510).

chore: [#188178510] Update real estate sector title

---

CHANGELOG.md
package.json

* [[#187003755](https://github.com/newjersey/navigator.business.nj.gov/issues/187003755)] spacing between state and muni for tablet ([b0866c5](https://github.com/newjersey/navigator.business.nj.gov/commit/b0866c5e5bee8b3a530c4cee7fa1637e4639a049))
* [[#187809299](https://github.com/newjersey/navigator.business.nj.gov/issues/187809299)] deleted now unused webflow licenses ([3740035](https://github.com/newjersey/navigator.business.nj.gov/commit/374003525c512c2177e9c085a9b3d96975388ed8))
* [[#188117562](https://github.com/newjersey/navigator.business.nj.gov/issues/188117562)] fix license sync serialization issue ([f73cfaa](https://github.com/newjersey/navigator.business.nj.gov/commit/f73cfaa70864f8c66f5f644cdc82aa7fc8e814a8))
* [[#188129133](https://github.com/newjersey/navigator.business.nj. …

chore(release): 2024.25.0 [skip ci]

---

scripts/report-users-with-tax-ids.py

Filter emails that contain `"@fearless", "@innovation", "@example", "@test"` or have a single character (e.g. test@a.com)
This pull request resolves [#188103179](https://www.pivotaltracker.com/story/show/188103179).

Update DOL report to filter emails from staff

---

api/src/api/userRouter.test.ts
api/src/api/userRouter.ts

If a license check was last performed over an hour ago, or if a user has provided a business name and address automatically query the DCA databases for license information.
This pull request resolves [#186879778](https://www.pivotaltracker.com/story/show/186879778).
All updates are made to the userRouter. When a user requests data from the backend, if conditions are correct the check is performed. The check is dependent on either having previously performed a successful license check or providing the information necessary to conduct a check via the profile.
**Using information from a previous license check**
- Create a business that can conduct a license check
- Ex: Poppy with cosmetology industry
- Conduct a license search that successfully returns license data
- Wait one hour (or fudge …

Reintroduce automatic check for license data

---

CHANGELOG.md
package.json

* **deps:** update dependency axios to v1.7.5 ([291f8ec](https://github.com/newjersey/navigator.business.nj.gov/commit/291f8ec5dd4a3d2d4d4d139042562537b2b8f9c4))
* **deps:** update dependency dayjs to v1.11.13 ([37a1fb9](https://github.com/newjersey/navigator.business.nj.gov/commit/37a1fb96c1d101b8ca578c7d332a23b7d4ae9e46))
* [[#186879778](https://github.com/newjersey/navigator.business.nj.gov/issues/186879778)] autocheck for license data ([af39fb1](https://github.com/newjersey/navigator.business.nj.gov/commit/af39fb167a251691726cc903797798ded50e8baf))
* [[#187792208](https://github.com/newjersey/navigator.business.nj.gov/issues/187792208)] test for new unaccounted-for essential question, and step vs steps ([94ee389](https://github.com/newjersey/navigator.business.nj.gov/commit/94ee38970d2 …

chore(release): 2024.26.0 [skip ci]

---

CHANGELOG.md
api/src/db/migrations/migrations.ts
api/src/db/migrations/v140_modify_home_health_industry.ts
package.json
shared/src/userData.ts
web/src/lib/domain-logic/getLicenseCalendarEvents.ts

- **fix: [#188214352] add migration to solve relative import issue**
- **chore(release): 2024.26.1 [skip ci]**

release 20240903

---

api/src/db/migrations/migrations.test.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v0_user_data.ts
api/src/db/migrations/v141_sync_migrated_and_newly_created_users.ts
shared/src/userData.ts

Updates the generators and migration files to synchronize the fields present in each
This pull request resolves [#187702425](https://www.pivotaltracker.com/story/show/187702425).

chore: [#187702425] Sync migrations with generators

---

web/src/components/tasks/HousingRegistrationStatusSummary.tsx

Respond to design feedback on multiple dwelling work
This pull request resolves [#188135142](https://www.pivotaltracker.com/story/show/188135142).

chore: [#188135142] Fix multiple dwelling alignment issues

---

web/src/pages/_app.tsx

Add default option to baseURL.
This pull request resolves [#188163509](https://www.pivotaltracker.com/story/show/188163509).

fix: [#188163509] add fallback default to baseURL

---

.circleci/config.yml

This pull request resolves [#187578669](https://www.pivotaltracker.com/story/show/187578669).
- Update `config.yml` by:
- Disabling the auto test for content on commits
-  Adding a scheduled job to run the `build and test` suit against the `content-repo` daily

chore: [#187578669] disable auto tests in content-repo on commits

---

content/src/roadmaps/add-ons/permanent-location-business-landlord.json
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts

Adds the "permanent-location-business-landlord" add-on to the residential landlord industry
This pull request resolves [#188285486](https://www.pivotaltracker.com/story/show/188285486).
Sign up as a Poppy with the residential landlord industry
See the tasks from the permanent location business landlord add on in your dashboard

feat: [#188285486] Add permanent-location-business-landlord add-on to residential-landlord industry

---

CHANGELOG.md
content/src/roadmaps/license-tasks/electrologist-license.md
content/src/roadmaps/license-tasks/electrologist-office-license.md
package.json

- **chore(release): 2024.28.0 [skip ci]**

release 20240917

---

.circleci/config.yml

fix: [#187578669] remove docker and build with image jobs

---

content/src/roadmaps/license-tasks/electrologist-office-license.md

Fix ill-formed meta data and add missing display name.

fix: fix meta data in electrologist-office-license

---

CHANGELOG.md
content/src/roadmaps/license-tasks/cds-healthcare.md
content/src/roadmaps/license-tasks/cemetery-sales.md
content/src/roadmaps/license-tasks/landlord-registration.md
content/src/roadmaps/license-tasks/short-term-rental-registration.md
package.json

- **chore(release): 2024.29.0 [skip ci]**

release 20240924

---

content/src/roadmaps/license-tasks/cemetery-sales.md

Fix missing and malformed metadata.

fix: update missing metadata in cemetery-sales.md

---

.circleci/config.yml

Updates the information associated with the GH user used in the `merge-content` CI job.
Recently we had to change out the CI user information. It was previously tied directly to a developer. This is now associated with a "bot" user. The email address was updated to match.

Update CircleCI user git info

---

.circleci/config.yml

This pull request addresses the integration test failures observed in the CI/CD pipeline by updating the cron job configuration and modifying the associated workflow `scheduled-daily-tests-content-repo` 
The key changes include
- Updated Cron Job Schedule (Note this is a temp change and would revert once I'm confident that tests pass).
-  Workflow Modification
This pull request resolves [#187578669](https://www.pivotaltracker.com/story/show/187578669).

fix: [#187578669] disable auto test in content-repo

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/billing/BillingStep.test.tsx
web/src/components/tasks/business-formation/billing/BillingStep.tsx
web/src/components/tasks/business-formation/billing/PaymentTypeTable.tsx

Add disclaimer to billing step
This pull request resolves [#188332488]](https://www.pivotaltracker.com/story/show/188332488]).

feat: [#188332488] Add disclaimer to billing step

---

.circleci/config.yml

This change is updated the workflow to run on content-repo at 1:40EST. This is to validate whether the test currently works.  
This pull request resolves [#187578669](https://www.pivotaltracker.com/story/show/187578669).

fix: [#187578669] run scheduled daily test at 140 EST

---

.circleci/config.yml

Change updates the cron Job for the  scheduled daily test workflow.
This pull request resolves [#187578669](https://www.pivotaltracker.com/story/show/187578669).

fix: [#187578669] update cron job for scheduled daily test workflow

---

web/src/components/tasks/cannabis/CannabisPriorityRequirements.tsx
web/src/styles/base/height.scss

chore: [#188284207] fix cannabis action bar position

---

web/public/mgmt/config.yml

https://www.pivotaltracker.com/story/show/188361409
Removing required header fields for two fields in profileDefaults; removing b/c the empty header field prevents content from saving.

chore: [#188361409] remove headers from non essential questions in cms

---

content/src/fieldConfig/config.json
web/src/components/PageFooter.tsx

This change updates removes the feedback reference from the footer. 

chore: remove feedback ref from footer

---

api/src/client/dynamics/license-status/RegulatedBusinessDynamicsLicenseStatusClient.test.ts
api/src/client/dynamics/license-status/RegulatedBusinessDynamicsLicenseStatusClient.ts
api/src/client/dynamics/license-status/formatRegulatedBusinessDynamicsApplications.test.ts
api/src/client/dynamics/license-status/formatRegulatedBusinessDynamicsApplications.ts
api/src/client/dynamics/license-status/regulatedBusinessDynamicsLicenseStatusTypes.ts
api/src/domain/user/updateLicenseStatusFactory.ts
content/src/license-calendar-events/independent-artist.md
content/src/roadmaps/industries/independent-artist.json
content/src/roadmaps/license-tasks/entertainment-agency-reg.md
shared/src/license.ts
web/src/components/TaskPageSwitchComponent.tsx
web/test/factories.ts
web/test/pages/taskUrlSlug.test.tsx

Note: It might be helpful to review each commit individually.
https://www.pivotaltracker.com/story/show/188259811
The nonessential question was previously created but was not mapped to the correct industry. I went ahead and added the nonessential question to the entertainment industry. Separately, I added the license name to the appropriate task and license calendar event files. I also created a test to validate the list of task ids that render the license task for completeness.
https://www.pivotaltracker.com/story/show/188339189
We noticed that there are many users that have multiple records with the same business name and address combo in RGB db. Because of our existing logic, those license searches would result in an error. We removed the logic around the error. …

feat: [#188079116] add license status to license calendar events

---

api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v143_add_property_type_and_rental_unit_count.ts
content/src/fieldConfig/profile.json
content/src/roadmaps/add-ons/multiple-dwelling-registration.json
content/src/roadmaps/add-ons/residential-landlord-long-term-few-units.json
content/src/roadmaps/add-ons/residential-landlord-long-term-many-units.json
content/src/roadmaps/add-ons/short-term-rental-registration.json
content/src/roadmaps/industries/residential-landlord.json
shared/src/industry.ts
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts
web/cypress/e2e/group_1_onboarding/onboarding-as-starting-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts
web/public/mgmt/config.yml
web/src/components/data-fields/Industry.test.tsx
web/src/components/data-fields/Industry.tsx
web/src/lib/domain-logic/essentialQuestions.ts
web/src/lib/domain-logic/starterKits.tsx
web/src/lib/roadmap/buildUserRoadmap.ts
web/test/pages/onboarding/helpers-onboarding.tsx

Adds two essential questions to the landlord industry, one dependent on the other
This pull request resolves [#188251182](https://www.pivotaltracker.com/story/show/188251182).
Start a new business in the landlord industry
A new essential question should pop up. If you choose "Short Term Rental" no follow up should appear. If you choose either of the other options a second non-essential question should appear.
If you answer "Short Term" to the first question, you should see the short term rental task in roadmap step 4
If you answer "Long Term" to the first question and "Yes" to the second, you should see the multiple dwelling registration task in step 4
If you answer "Long Term" to the first question and "No" to the second, you should see landlord registration task and smoke detector task …

feat: [#188251182] Add essential questions to landlord industry

---

api/src/libs/healthCheck.ts

fix: update url reference

---

CHANGELOG.md
api/src/libs/healthCheck.ts
content/src/roadmaps/license-tasks/animal-shelter-cds.md
content/src/roadmaps/license-tasks/dog-trainer-cds.md
package.json

- **fix: update url reference**
- **chore(release): 2024.31.0 [skip ci]**

release 20241016

---

content/src/roadmaps/license-tasks/animal-shelter-cds.md
content/src/roadmaps/license-tasks/dog-trainer-cds.md

Fix missing malformed metadata.

chore: update content metadata

---

content/src/roadmaps/license-tasks/landlord-registration.md
content/src/roadmaps/license-tasks/short-term-rental-registration.md
content/src/roadmaps/license-tasks/town-mercantile-license.md
content/src/roadmaps/tasks/liquor-license-availability.md
content/src/roadmaps/tasks/register-trade-name.md
content/src/roadmaps/tasks/town-mercantile-license-liquor.md
content/src/roadmaps/tasks/town-mercantile-license.md
web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts

Adds location dependent section to landlord registration tasks. Also adds tests for roadmap builder for landlord industry
This pull request resolves [#188427382](https://www.pivotaltracker.com/story/show/188427382).
1. Register as a Poppy landlord
2. Respond "BOTH" to the first essential question
3. Respond "NO" to the second essential question
4. Select a business structure
5. You can see the short term registration task and the landlord registration task in step 4
6. Each of them should have a location dependent section

feat: [#188427382] Add location dependent section to landlord and short term registration tasks

---

content/src/fieldConfig/housing-registration.json

fix: [#188462617] 'Sorry' removed in Check name error

---

CHANGELOG.md
package.json

* [[#188251182](https://github.com/newjersey/navigator.business.nj.gov/issues/188251182)] fix unique field names for landlord industry questions ([8a32b70](https://github.com/newjersey/navigator.business.nj.gov/commit/8a32b70c77f310e1f7ef2f1fa7523aae14bc998a))
* update url reference ([6a79e99](https://github.com/newjersey/navigator.business.nj.gov/commit/6a79e99d703cfc018a2dac4a6c8bee910e5646e4))
* [[#186084688](https://github.com/newjersey/navigator.business.nj.gov/issues/186084688)] callout alerts are now aria groups ([5bf852c](https://github.com/newjersey/navigator.business.nj.gov/commit/5bf852c6c9d79f13e3fe7f628563c848f449b216))
* [[#186702387](https://github.com/newjersey/navigator.business.nj.gov/issues/186702387)] close button revisions, reversion of previous functionality …

chore(release): 2024.32.0 [skip ci]

---

web/public/mgmt/config.yml
web/src/lib/search/cmsCollections.ts
web/src/lib/search/searchConfig.ts

The search tool was broken it is now fixed. 
This pull request resolves [#188462617](https://www.pivotaltracker.com/story/show/188462617).
This section of code, the search tool is insanely confusing. 
I spend most of the day just trying to understand what in the world was going on. And I learned a lot. 
I got half way through and kinda through that the fact that 2 separate parts of the CMS point to the same .json file was causing issues. This didn't entirely fix the problem and I realized that a field that was in JSON wasn't in the CMS so I added that and it turns out this was actually the issue and the fact that we have 2 separate things referring to the same file isn't an issue at all.  
go to the CMS search tool http://localhost:3000/mgmt/search search for "please"
see no errors
Man …

fix: [#188462617] fixed CMS search

---

api/serverless.ts
api/src/api/externalEndpointRouter.test.ts
api/src/api/formationRouter.test.ts
api/src/api/licenseStatusRouter.test.ts
api/src/api/selfRegRouter.test.ts
api/src/api/taxFilingRouter.test.ts
api/src/api/userRouter.test.ts
api/src/db/DynamoUserDataClient.ts
api/src/db/config/dynamoDbConfig.ts
api/src/domain/newsletter/addNewsletterBatch.test.ts
api/src/domain/types.ts
api/src/domain/user-testing/addToUserTestingBatch.test.ts
api/src/domain/user/encryptTaxIdBatch.test.ts
api/src/functions/encryptTaxId/app.ts
api/src/functions/express/app.ts
api/src/functions/migrateUsersVersion/app.ts
api/src/functions/migrateUsersVersion/index.ts
api/src/functions/updateExternalStatus/app.ts
api/src/libs/migrateUserVersion.ts

This PR implements a Lambda function that automates the migration of users to the most recent schema version every weekend, specifically early Sunday morning.
- Updates `api/serverless.ts` to reference the new lambda function
- Updates the stubUserDataClient in  `api/src/api/externalEndpointRouter.test.ts`
- Updates the stubUserDataClient in `api/src/api/formationRouter.test.ts`
- Updates the stubUserDataClient in `api/src/api/licenseStatusRouter.test.ts`
- Updates the stubUserDataClient in `api/src/api/selfRegRouter.test.ts`
- Updates the stubUserDataClient in `api/src/api/taxFilingRouter.test.ts`
- Updates the stubUserDataClient in`api/src/api/userRouter.test.ts`
-  Updates the stubUserDataClient in`api/src/domain/user/encryptTaxIdBatch.test.ts`
- Refactored …

feat: [#187578804] Add Lambda for weekend user migrations

---

api/serverless.ts

chore: [#187578804] Enable migrateUsersVersion lambda in dev

---

CHANGELOG.md
content/src/roadmaps/license-tasks/alarm-locksmith-business-license.md
content/src/roadmaps/license-tasks/alarm-locksmith-license.md
content/src/roadmaps/license-tasks/distribute-cds.md
content/src/roadmaps/license-tasks/lab-research-cds.md
content/src/roadmaps/license-tasks/manufacture-cds.md
package.json

- **chore(release): 2024.33.0 [skip ci]**

release 20241029

---

content/src/display-content/contextual-information/pbs.md

Update PBS Url to new Url.
This pull request resolves [#188503417](https://www.pivotaltracker.com/story/show/188503417).

feat: [#188503417] update pbs url

---

content/src/roadmaps/industries/residential-landlord.json
web/src/lib/roadmap/fixtures/add-ons/tea-2.json
web/src/lib/roadmap/roadmapBuilder.test.ts
web/src/lib/roadmap/roadmapBuilder.ts

Adds the multiple dwelling question to the residential landlord industry
This pull request resolves [#188520392](https://www.pivotaltracker.com/story/show/188520392).
1. Create a new Poppy in the "Residential Landlord" industry
2. Go to profile and see multiple dwelling question
3. Select "Long term" and "More than 3 units" landlord answers and verify that the "Multiple Dwelling" question only shows up once

feat: [#188520392] Offer multiple dwelling question to residential landlord industry

---

api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v145_add_traveling_circus_or_carnival.ts
content/src/anytime-action-tasks/operating-carnival-fire-permit.md
content/src/fieldConfig/profile.json
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/src/components/dashboard/AnytimeActionDropdown.tsx
web/src/pages/profile.tsx

This pull request resolves [#188521509](https://www.pivotaltracker.com/story/show/188521509).
1. Create a new Oscar business in the "Entertainment" industry
2. You should not see the "Get a Fire Permit for Your Carnival or Circus" anytime action
3. Go to the profile and answer yes to one of or both of the carnival non-essential questions
4. You should see the "Get a Fire Permit for Your Carnival or Circus" anytime action

feat: [#188521509] Filter Carnival fire permit anytime action by non-essential question

---

content/src/display-content/contextual-information/certificate-of-good-standing.md

`certifcate-of-good-standing.md` is being replaced by `good-standing.md`. References to certifcate-of-good-standing have already been updated.

Remove certifcate-of-good-standing.md

---

CHANGELOG.md
package.json

* [[#188414550](https://github.com/newjersey/navigator.business.nj.gov/issues/188414550)] license data for correct business is updated when multiple businesses exist ([f95452c](https://github.com/newjersey/navigator.business.nj.gov/commit/f95452c9a2e917012aae53bcbdebb027181b987c))
* [[#186324885](https://github.com/newjersey/navigator.business.nj.gov/issues/186324885)] agent information checkbox missing proper notification ([278b75a](https://github.com/newjersey/navigator.business.nj.gov/commit/278b75ae6f79c9c9d7173979a73a01f19c5829ff))
* [[#188414550](https://github.com/newjersey/navigator.business.nj.gov/issues/188414550)] update useUserData hook to account for license data discrepancies ([31da67a](https://github.com/newjersey/navigator.business.nj.gov/commit/31da67a84235acf68e7a50a34493 …

chore(release): 2024.34.0 [skip ci]

---

web/src/components/tasks/anytime-action/AnytimeActionElement.tsx

Change the label from form to issuing agency in anytime actions with detail page preview and the element that it renders
This pull request resolves [#188563499](https://www.pivotaltracker.com/story/show/188563499).

chore: [#188563499] Change the label from form to issuing agency

---

web/public/mgmt/config.yml

This pull request resolves [#188574288](https://www.pivotaltracker.com/story/show/188574288).

feat: [#188574288] Add offshore wind sector and investment funding type to funding opportunities

---

CHANGELOG.md
package.json

* [[#188574288](https://github.com/newjersey/navigator.business.nj.gov/issues/188574288)] Update hint for business stage ([2dfcfd4](https://github.com/newjersey/navigator.business.nj.gov/commit/2dfcfd4600eb8f9d66fa1aca457a330b75987960))
* [[#188574288](https://github.com/newjersey/navigator.business.nj.gov/issues/188574288)] Update hint for business stage in funding opps ([0336dc3](https://github.com/newjersey/navigator.business.nj.gov/commit/0336dc3b1fa5389c89a471333c9ddb09914396dd))
* [[#187978144](https://github.com/newjersey/navigator.business.nj.gov/issues/187978144)] [[#188538877](https://github.com/newjersey/navigator.business.nj.gov/issues/188538877)] [[#188538893](https://github.com/newjersey/navigator.business.nj.gov/issues/188538893)] …

chore(release): 2024.35.0 [skip ci]

---

web/src/pages/mgmt/modifyBusiness.tsx

https://www.pivotaltracker.com/story/show/188594556
The goal is to change the ordering of the drop down values so they are in alphabetical order.
Site URL - http://localhost:3000/mgmt/modifyBusiness

chore: [#188594556] sort dropdowns on modify business page

---

web/src/components/njwds/Banner.tsx

Updates the official site link in the official site banner to open in a new window.

chore: open official site banner link in new window

---

cspell.json

chore: spell check fixes

---

web/src/lib/muiTheme.ts

https://www.pivotaltracker.com/story/show/188631414
The intention behind this ticket is to update the styling for all default tabs in the application. The new styling will align with what is noted in the design system with one caveat, the blue line will continue to exist at the bottom instead of the top.

chore: [#188631414] update tag styling

---

web/src/pages/profile.tsx

Enables the vacant building question for up and running Poppies
This pull request resolves [#188599283](https://www.pivotaltracker.com/story/show/188599283).
1. Create a Poppy user in the "real-estate-investor"
2. Move the user through to the up and running state
3. Go to the profile and see the vacant building question

fix: [#188599283] Enable vacant building question for up and running Poppies

---

web/src/components/field-labels/FieldLabelProfile.tsx
web/src/components/profile/ProfileField.tsx
web/src/pages/profile.tsx

Updates the styling for vacant building non-essential question
This pull request resolves [#188599283](https://www.pivotaltracker.com/story/show/188599283).

fix: [#188599283] Update styling for non-essential question

---

web/src/components/tasks/ElevatorRegistrationTask.tsx
web/src/components/tasks/HotelMotelRegistrationTask.tsx
web/src/components/tasks/LicenseTask.tsx
web/src/components/tasks/MultipleDwellingRegistrationTask.tsx
web/src/styles/components/buttons.scss
web/stories/Molecules/Button/Unstyled.stories.tsx

Fixed comments - https://www.pivotaltracker.com/story/show/188526874

chore: [#188526874] fix cta button spacing

---

api/.dependency-cruiser.js
api/src/api/userRouter.test.ts
api/src/api/userRouter.ts
api/src/db/DynamoUserDataClient.ts
api/src/functions/express/app.ts

This pull request resolves [#188540248](https://www.pivotaltracker.com/story/show/188540248).
~The original spec had the email being searched being supplied via request body. I think a GET + query parameter makes more semantic sense for what we’re trying to do here, so updating to that approach.~ As detailed [below](https://github.com/newjersey/navigator.business.nj.gov/pull/9159#discussion_r1868231687), the endpoint is a POST endpoint which takes the email via a JSON request body. This is to ensure that requests don't get cached.
The `findByEmail` method is only getting used here currently, so having it return the first match if there's multiple (which corresponds to the most recently updated match) seems fine for now, although @alexander-littleton's suggestion of a newer …

feat: [#188540248] add check email endpoint

---

web/src/lib/muiTheme.ts

https://www.pivotaltracker.com/story/show/188651126

chore: [#188651126] globally override tabs component alignment

---

content/src/roadmaps/add-ons/nonprofit.json

The nonprofit roadmap is missing a task that instructs the user to create bylaws. This work adds that task to the nonprofit roadmap.
This pull request resolves [ADO Ticket #7649](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7649).
There was an issue in the CMS when content tried to add this. Still need to address that issue. Adding manually to move the work forward.
- Create a new business
- Select "nonprofit" legal structure
- The "Write Your Bylaws" task should be in Step 1 of your roadmap

Add "bylaws" task to nonprofit roadmap add-on

---

content/src/display-content/contextual-information/compost-waste.md
content/src/display-content/contextual-information/construction-and-demo-debris.md
content/src/display-content/contextual-information/hazardous-waste.md
content/src/display-content/contextual-information/medical-waste.md
content/src/fieldConfig/waste-questionnaire-page.json
web/public/mgmt/config.yml
web/src/components/njwds-extended/SecondaryButton.tsx
web/src/components/tasks/environment-questionnaire/CheckWastePermitsQuestionnaire.test.tsx
web/src/components/tasks/environment-questionnaire/CheckWastePermitsQuestionnaire.tsx
web/src/components/tasks/environment-questionnaire/CheckWastePermitsResults.tsx
web/src/styles/base/background-colors.scss
web/src/styles/sass-files/variables.scss

This pull request resolves [#188464297](https://www.pivotaltracker.com/story/show/188464297) and resolves [#188651554](https://www.pivotaltracker.com/story/show/188651554).
Made updates based on review comments in the fix commit and the feat commit includes improvements to the feature based on further discussion with the team.
1) Select `all other industries` during onboarding.
2) The task is found under Step 3 of the roadmap.

fix: [#188464297] update design and content & feat: [#188651554] remove registration modal & amend button text

---

api/src/api/userRouter.test.ts
api/src/api/userRouter.ts
api/src/client/ApiFormationHealth.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v150_remove_needs_nexus_dba_name.ts
shared/src/domain-logic/businessPersonaHelpers.ts
shared/src/profileData.ts
shared/src/test/factories.ts
shared/src/userData.ts
web/src/components/tasks/business-formation/DbaFormationPaginator.tsx
web/src/components/tasks/business-formation/NexusFormation.test.tsx
web/src/components/tasks/business-formation/NexusFormationFlow.tsx
web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx
web/src/components/tasks/business-formation/name/NexusSearchBusinessNameStep.test.tsx
web/src/components/tasks/search-business-name/SearchBusinessNameForm.tsx
web/src/lib/cms/previews/NavBarPreview.tsx
web/src/lib/domain-logic/getNavBarBusinessTitle.test.ts
web/src/lib/domain-logic/getNavBarBusinessTitle.ts

https://www.pivotaltracker.com/story/show/185863575
Refactor away needsNexusDbaName field and create a helper function that determine if it's needed. Updated tests and added a migration file. Comments added as review comments.

chore: [#185863575] Refactor away needsNexusDbaName

---

CHANGELOG.md
content/src/roadmaps/industries/funeral.json
content/src/roadmaps/license-tasks/funeral-registration.md
content/src/roadmaps/license-tasks/professional-planner.md
package.json
web/src/components/tasks/business-formation/review/ReviewBusinessSuffixAndStartDate.tsx

- **fix: will practice law reivew text, always no**
- **chore(release): 2024.38.0 [skip ci]**

release 20241217

---

web/test/factories.ts
web/test/pages/onboarding/onboarding-foreign.test.tsx

https://www.pivotaltracker.com/story/show/188704018
This test fails when the industry from the random fn is the same as the value selected further downstream in the test, but the test is designed assuming the industry changes. The random fn is updated to remove an acceptable industry from the list of possible choices.

fix: [#188704018] update randomHomeBasedIndustry to fix flakey home based industry test

---

web/src/components/LoginEmailCheck.tsx
web/src/components/UserSupportActionCard.tsx
web/src/components/roadmap/MiniRoadmapTask.tsx

This pull request resolves [#188356641](https://www.pivotaltracker.com/story/show/188356641).
Refactored/removed legacyBehavior from <Link> component that was added during the codemod upgrade of Next.js.

chore: [#188356641] refactor <Link> legacyBehavior

---

CHANGELOG.md
content/src/anytime-action-tasks-licenses/code23-osow-30day-permit_1.md
content/src/anytime-action-tasks-licenses/code23-trailer-permit.md
content/src/anytime-action-tasks-licenses/single-trip-osow-permit.md
package.json

- **chore: updating Anytime Actions (Licenses) single-trip-osow-permit (#9312)**
- **chore: updating Anytime Actions (Licenses) code23-trailer-permit (#9308)**
- **chore: updating Anytime Actions (Licenses) code23-trailer-permit (#9310)**
- **chore: updating Anytime Actions (Licenses) code23-osow-30day-permit_1 (#9311)**
- **chore(release): 2024.39.0 [skip ci]**

release 20241224

---

api/src/client/ApiFormationHelpers.ts
shared/src/dateHelpers.test.ts

Fixes some flakiness with formation city responses due to nullish coalescing chain.
This pull request resolves [#188734302](https://www.pivotaltracker.com/story/show/188734302).

fix: [#188734302] make city in formation more reliable

---

content/src/roadmaps/license-tasks/xray-reg.md

Update the metadata formatting so that the x-ray license task appears correctly in the CMS

chore: fix formatting for xray registration license task

---

web/cypress/e2e/auto-tax-filing.spec.ts

chore: fix failing tax filing cypress test

---

web/cypress/support/helpers/helpers.ts

chore: fix cypress - scroll to business structure task before click

---

web/src/components/filings-calendar/FilingsCalendarSingleGrid.test.tsx

chore: fix single grid failing tests due to jan 3 current date

---

scripts/report-industries-and-non-essential-questions.py

This work adds a Python script that maps non-essential questions to the tasks that they add to a user roadmap and outputs the results to a CSV. That CSV can then be manually populated with any remaining values such as `Onboarding Questions` that might be perceived as non-essential questions.
This work was initially requested by @amandabeall via a Slack message [here](https://njcio.slack.com/archives/C02AJKBCH38/p1736367498159039).
This pull request resolves [#188762599](https://www.pivotaltracker.com/story/show/188762599).
The script starts by pulling a list of all industries, checks any non-essential questions, looks up associated add-ons, and then pulls the list of tasks. The values are then output in a CSV that can be manually munged as needed.
The [final …

Create a script to act as a template report for nonessential questions

---

content/src/fieldConfig/env-questionnaire.json
content/src/roadmaps/env-tasks/land-permitting.md

Fixes for the following:
[#188645598](https://www.pivotaltracker.com/story/show/188645598)
[#188684012](https://www.pivotaltracker.com/story/show/188684012)

Land waste fixes

---

CHANGELOG.md
content/src/roadmaps/license-tasks/oos-pharmacy-registration.md
package.json

- **chore(release): 2025.0.0 [skip ci]**

release 20250114

---

.github/pull_request_template.md

Adds the following checklist item to the PR template:

chore: add style guide to PR checklist

---

CHANGELOG.md
package.json

* [[#187166104](https://github.com/newjersey/navigator.business.nj.gov/issues/187166104)] add dependency for cypress accessibility feat ([eb906ea](https://github.com/newjersey/navigator.business.nj.gov/commit/eb906ea5a6a10d0f5c2ee58043cbf05f0c4259f7))
* **deps:** update material-ui ([#9398](https://github.com/newjersey/navigator.business.nj.gov/issues/9398)) ([639fff4](https://github.com/newjersey/navigator.business.nj.gov/commit/639fff41d5f083067a4db05e32732634c11b23be))
* resolve build error by setting empty task arrays to null ([19a0226](https://github.com/newjersey/navigator.business.nj.gov/commit/19a0226822291d1217337ab38200cf5972d2b2f0))
* [[#187166104](https://github.com/newjersey/navigator.business.nj.gov/issues/187166104)] Cypress Automated Accessibility added for onboarding …

chore(release): 2025.1.0 [skip ci]

---

.circleci/config.yml

Change disables the workflow in our Continuous Integration. 
This pull request resolves [#188463509](https://www.pivotaltracker.com/story/show/188463509).

chore: [#188463509] disable workflows in CircleCI temporarily

---

content/src/fieldConfig/env-questionnaire.json

Updated SBAP email.
This pull request resolves [#188809827](https://www.pivotaltracker.com/story/show/188809827).

chore: [#188809827] updated SBAP email

---

web/src/components/tasks/environment-questionnaire/results/ContactDep.tsx

Updated contact information for the media area.
This pull request resolves [#188623677](https://www.pivotaltracker.com/story/show/188623677).

fix: [#188623677] air contact email

---

api/.dependency-cruiser.js
api/serverless.ts
package.json
web/.dependency-cruiser.js
web/cypress/e2e/auto-tax-filing.spec.ts
web/cypress/support/commands.js
web/package.json
web/src/components/LoginEmailCheck.tsx
web/src/lib/auth/sessionHelper.ts
web/src/pages/_app.tsx
yarn.lock

This pull request resolves [#186394392](https://www.pivotaltracker.com/story/show/186394392).
This PR upgrades the project to AWS Amplify v6, aligning with the latest standards and capabilities of the framework. As part of this upgrade, several key changes have been made to ensure compatibility and optimize functionality across both the web and API components.
Notably, the configuration files have been modified to accommodate the updated structure and improve integration with other services. This includes removing obsolete properties, such and refreshHandlers, which are no longer required in v6 due to the improved  token management provided by Amplify.
Additionally, the authentication setup has been updated to utilize session-based authentication. This change enhances security by …

fix(deps): update aws-amplify to v6

---

content/src/display-content/contextual-information/pollutants.md

Amendment to the pollutants contextual info!
This pull request resolves [#188623677](https://www.pivotaltracker.com/story/show/188623677).

fix: [#188623677] amend pollutants contextual info

---

CHANGELOG.md
package.json

* [[#188540268](https://github.com/newjersey/navigator.business.nj.gov/issues/188540268)] Fix routing logic for authenticated login ([d4c5dbe](https://github.com/newjersey/navigator.business.nj.gov/commit/d4c5dbe0af21786fd3efbe60b97aedfe7fb0f052))
* [[#188623677](https://github.com/newjersey/navigator.business.nj.gov/issues/188623677)] air contact email ([064a59c](https://github.com/newjersey/navigator.business.nj.gov/commit/064a59c43e480b619f912739dbc10e9032d7f74e))
* [[#188623677](https://github.com/newjersey/navigator.business.nj.gov/issues/188623677)] amend pollutants contextual info ([1aa9ed0](https://github.com/newjersey/navigator.business.nj.gov/commit/1aa9ed029d21e2381fbe391bc90384877dae79d1))
* [[#188666282](https://github.com/newjersey/navigator.business.nj.gov/issues/188666282)] …

chore(release): 2025.2.0 [skip ci]

---

web/src/pages/onboarding.tsx

By checking `router` instead of `router.isReady`, `onboarding.tsx` was prematurely making client-side routing changes that were preventing the following actions:
1. Updating user data based on `utm_source` query params
2. Skipping onboarding for eligible businesses coming from the starter kits pages with `industry` query params
This pull request resolves [#188826997](https://www.pivotaltracker.com/story/show/188826997)
Run this branch locally and navigate to the following urls with the expected results described:
- http://localhost:3000/onboarding?industry=home-contractor
- onboarding is skipped, routed to dashboard
- http://localhost:3000/onboarding?industry=random
- invalid query param, onboard starts from step one
- http://localhost:3000/onboarding?utm_source=NJEDA
- fundings are …

fix: [#188826997] check router.isReady on onboarding page

---

content/src/fieldConfig/fundings-onboarding.json
shared/src/test/factories.ts
web/src/pages/fundings.tsx
web/test/pages/fundings.test.tsx

Respond to design and PR feedback on fundings onboarding page
This pull request resolves [#188666282](https://www.pivotaltracker.com/story/show/188666282).

fix: [#188666282] add url and additional filtering

---

web/src/components/LoginEmailCheck.tsx
web/src/components/navbar/desktop/NavBarDesktopHomeLogo.tsx
web/src/components/navbar/mobile/NavBarMobileHomeLogo.tsx
web/src/styles/sections/login-page.scss

- bolded font-weight for form label
- base-dark color for paragraph text
This pull request resolves [#188838885](https://www.pivotaltracker.com/story/show/188838885).

fix: [#188838885] Login Page Design QA

---

web/src/components/LoginEmailCheck.tsx
web/src/styles/sections/login-page.scss

- Mobile spacing fixes
This pull request resolves [#188838885](https://www.pivotaltracker.com/story/show/188838885).

fix: [#188838885] Login Page Design QA Follow-ups

---

CHANGELOG.md
package.json

* [[#188838423](https://github.com/newjersey/navigator.business.nj.gov/issues/188838423)] from login page to onboarding working again ([56c9cb4](https://github.com/newjersey/navigator.business.nj.gov/commit/56c9cb4a9327c551d4d571208e39b4fdb04093f0))
* [[#188838885](https://github.com/newjersey/navigator.business.nj.gov/issues/188838885)] Login Page Design QA ([f92d3cb](https://github.com/newjersey/navigator.business.nj.gov/commit/f92d3cb2e6506a817417e2b57b8eae7bd192ca67))
* [[#188844549](https://github.com/newjersey/navigator.business.nj.gov/issues/188844549)] add userId, versionWhenCreated and version to business object ([5a182b7](https://github.com/newjersey/navigator.business.nj.gov/commit/5a182b7361d72179e24850b486ff9c8624e09876))
* added spelling exception for Corpcode …

chore(release): 2025.3.0 [skip ci]

---

web/test/factories.ts
web/test/pages/onboarding/onboarding-foreign.test.tsx

This pull request resolves https://www.pivotaltracker.com/story/show/188858472
I identified the root cause of the flaky test after running it 2000 times and observing a consistent failure pattern under specific conditions:
1.	The initial industry ID returned from the randomHomeBased function is Acupuncture with homeBased value in userdata set to true.
2.	During the next step, when selecting an industry from the dropdown, Acupuncture is excluded.
3.	On the third attempt, the test tries to select Acupuncture again.
This sequence causes the test to fail because Acupuncture with homeBased: true is not a valid scenario (as confirmed in acupuncture.json).
Fix:
To address this, I modified the test to:
•	Initially exclude Acupuncture from being returned by the randomHomeBased function.
•	Ensure …

test: [#188858472] update random home based industry function to allow two industry id to exclude

---

content/src/fieldConfig/business-formation.json
web/public/mgmt/config.yml
web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/BusinessFormationTextBox.tsx
web/src/components/tasks/business-formation/business/AdditionalProvisions.tsx
web/src/components/tasks/business-formation/business/BusinessStep.test.tsx
web/src/components/tasks/business-formation/contacts/Addresses.test.tsx
web/src/components/tasks/business-formation/contacts/Addresses.tsx
web/src/components/tasks/business-formation/contacts/Members.test.tsx
web/src/components/tasks/business-formation/contacts/Signatures.test.tsx
web/src/components/tasks/business-formation/contacts/Signatures.tsx
web/src/styles/sections/members.scss
web/test/helpers/helpers-formation.tsx

We wanted to replace trash and pencil icons with remove and edit text instead for clarity and accessibility reasons
This pull request resolves [#188793304](https://www.pivotaltracker.com/story/show/188793304).
Go into the app and on formation step 2, add some of the optional bottom steps
In the app on step 3 with regards to the signer / members or board of directors section, add and remove some people to see the new outcomes
I did some pretty substantial refactors as this is some of our oldest code and it had some weird mixing of styling vs JS code which is bad separation of concerns. So I refactored to use MediaQueries and CSS grid instead of what it had been before.

feat: [#188793304] replaced trash and penicl icons with text

---

content/src/roadmaps/license-tasks/commercial-pest-applicator-license.md
content/src/roadmaps/license-tasks/pest-applicator-business-license.md

Fixing some metadata that is causing license tasks from rendering correctly in the CMS.

Update metadata for new license tasks

---

web/public/mgmt/config.yml
web/src/lib/domain-logic/sidebarCardsHelpers.test.ts
web/src/lib/domain-logic/sidebarCardsHelpers.ts
web/src/lib/types/types.ts
web/src/lib/utils/markdownReader.ts
web/test/factories.ts

Adds a priority field to CMS fundings and floats those fundings to the top
This pull request resolves [#188862738](https://www.pivotaltracker.com/story/show/188862738).
1. In your local CMS mark some fundings as priority
2. Create an Oscar who can view those fundings
3. Those fundings should appear in the list above other fundings but below certifications

feat: [#188862738] add priority field to CMS Fundings

---

content/src/fieldConfig/njeda-fundings-onboarding.json
web/src/components/data-fields/ExistingEmployees.tsx
web/src/components/data-fields/NumericField.tsx
web/src/pages/njeda.tsx
web/test/pages/njeda.test.tsx

Replaces the "how long has your business been operating" question with employee count question
This pull request resolves [#188877973](https://www.pivotaltracker.com/story/show/188877973).
1. Navigate to localhost:3000/njeda
2. You should see an employee count question box that only accepts numbers
3. You should see an error when that box is not filled out

feat: [#188877973] add employee count question to njeda onboarding page

---

web/src/lib/roadmap/buildUserRoadmap.test.ts
web/src/lib/roadmap/buildUserRoadmap.ts

Remove environment tasks if home based business question is answered and true. 
This pull request resolves [#188853770](https://www.pivotaltracker.com/story/show/188853770).
1) Onboard as an `all other industries` new business.
2) You should see the Air, Waste and Land Tasks as part of the roadmap.
3) After you answer the home-based business question as true, the roadmap shouldn't contain the tasks above anymore.

feat: [#188853770] env task filter home-based businesses

---

content/src/fieldConfig/business-formation.json
web/src/components/tasks/business-formation/contacts/Addresses.tsx
web/src/styles/sections/members.scss

fix: wording issue for icon formation accessibility issues

---

web/src/lib/domain-logic/sidebarCardsHelpers.test.ts
web/src/lib/domain-logic/sidebarCardsHelpers.ts

fix: ensure funding filtering on fundings that expire in the future

---

README.md

Updated the top-level readme to include required installation dependencies.

docs: update readme installation dependencies

---

CHANGELOG.md
package.json

- **Revert "feat: [#188778935] consolidate AWS resources to two environments"**
- **chore: temp prod release**
- **chore(release): 2025.5.0 [skip ci]**

release 20250214

---

api/src/api/selfRegRouter.test.ts
api/src/api/selfRegRouter.ts
api/src/api/userRouter.test.ts
api/src/api/userRouter.ts
api/src/db/migrations/migrations.ts
api/src/db/migrations/v158_login_email_to_lowercase.test.ts
api/src/db/migrations/v158_login_email_to_lowercase.ts
shared/src/userData.ts

* normalized the user email to lowercase in two different locations in the api to fix the login bug: `/users/emailCheck` and `/self-reg`
* added tests in these two locations for the lowercase changes
* made a database migration to change all previous `userData.user.email` entries to lowercase
This pull request resolves [#12673](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12673).
After discussion with a few of the team members it was decided to only change to lowercase in the api layer, rather than have form field validators that changed the input text to lowercase. 
After the migration has run, attempt to login with a version of your email with mixed or upper casing.
This migration is changing the value of the user's email in DynamoDB. There is an assumption …

Normalize emails to lowercase for login/signup

---

.circleci/config.yml

This branch is the start of the new `testing-repo` branch to be used going forward.
**DO NOT DELETE** this branch after this PR is rebased into `main`.
We often reference the `testing` site in our code as `accessibility-testing`. This is a legacy name and is no longer relevant to how the environment is being utilized. This work updates the CI `config.yml` file to reference more relevant names.
This pull request resolves:
ADO: [#13242](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13242)
PT: [#188970824](https://www.pivotaltracker.com/story/show/188970824)
- Create new `testing-repo` branch to be associated with testing site going forward
- Rename references to "Accessibility Testing" to "Testing" in CI configuration files
- Ignore `testing-repo` in …

Update references to 'accessibility-testing' to 'testing'

---

content/src/roadmaps/nonEssentialQuestions.json

Re-adds a missing non-essential question for dental hygienist.

Re-add dental hygienist non-essential question

---

.husky/commit-msg

Husky commit script message now for ado noly

---

web/src/lib/static/admin/findDeadLinks.test.ts
web/src/lib/static/admin/findDeadLinks.ts

fix: [AB#13305] fixed failing integration test for deadlinks.spec.ts

---

shared/src/test/factories.ts
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.test.tsx
web/src/components/tasks/business-formation/contacts/Members.test.tsx

This resolves a flakey test - https://app.circleci.com/pipelines/github/newjersey/navigator.business.nj.gov/35396/workflows/9d70dbaa-6c00-4040-80a5-228845a1fbb2/jobs/174023/tests
I investigated the flaky test and found that the state dropdown has props controlling its behavior, such as including the “out-of-state” option, excluding New Jersey, and removing U.S. territories. The test was flaky because the generator function was selecting an option outside the U.S. that wasn’t actually in the dropdown, causing failures.
To fix this, I updated the generator function to align with the state dropdown component. The function now correctly filters states based on the provided props—allowing “out-of-state” when enabled and excluding New Jersey or territories when specified. This ensures the test …

chore: [AB#4703] update generateStateItem fn

---

api/scripts/populateLocalDynamoDbWithMigrations.ts
api/src/api/externalEndpointRouter.test.ts
api/src/api/formationRouter.test.ts
api/src/api/licenseStatusRouter.test.ts
api/src/api/selfRegRouter.test.ts
api/src/api/taxFilingRouter.test.ts
api/src/api/userRouter.test.ts
api/src/db/DynamoDataClient.test.ts
api/src/db/DynamoDataClient.ts
api/src/domain/types.ts
api/src/functions/migrateUsersVersion/app.ts

The existing function migrateData does not accurately describe its purpose. This function is responsible for migrating users and business objects that are on an outdated version of our system's data model. To improve code readability and maintainability, we are renaming it to migrateOutdatedVersionUsers.
- Renamed migrateData to migrateOutdatedVersionUsers across the codebase.
- Updated all references to use the new function name.
- Verified that unit tests and documentation reflect the change.
Note that this is purely a refactor and no functional changes apply. All tests pass without modifications to logic.
This pull request resolves [#13348](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13348).
- Run the unit tests to confirm expected behavior remains …

chore: [AB#13348] rename migrateData to migrateOutdatedVersionUsers

---

api/src/client/dynamics/license-status/RegulatedBusinessDynamicsLicenseApplicationIdsClient.test.ts
api/src/client/dynamics/license-status/RegulatedBusinessDynamicsLicenseApplicationIdsClient.ts
api/test/helpers.ts
content/src/license-calendar-events/moving-company.md
content/src/roadmaps/industries/pharmacy.json
content/src/roadmaps/license-tasks/moving-company-license.md
shared/src/license.ts
web/src/components/TaskPageSwitchComponent.tsx
web/test/pages/taskUrlSlug.test.tsx

This PR enables the license status check for the "Apply for Your Public Movers License and/or Warehousemen License" task and removes the 3 subtypes (moving only, warehousing only, and both) as they all use the same application (see comments on the ADO ticket).
This pull request resolves [#4988](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/4988).
To make sure the license data comes from Dynamics  instead of MLO, we updated `enabledLicensesSources` in `shared/src/license.ts`.
To add the "check status" tab, we included the moving industry license id to `taskIdsWithLicenseSearchEnabled`,
To make sure that the right license type gets pulled from userData when the user visits the task page, and the right renewal event appears in the calendar, we matched the …

feat: [#187531990 | AB#4988] enable status check for moving industry

---

content/src/roadmaps/industries/pharmacy.json

fix: [AB#0000] fix conflict issue with pharmacy

---

content/src/fieldConfig/njeda-fundings-onboarding.json
web/public/mgmt/config.yml

Updates the CMS variable name in the NJEDA modal to allow for content to update via CMS
This pull request resolves [#13227](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13227).

fix: [AB#13227] update header copy and ability to update copy in cms

---

content/src/anytime-action-license-reinstatements/hvacr-license-reinstatement.md
content/src/anytime-action-tasks/apprenticeship-program-intake.md
content/src/anytime-action-tasks/food-truck-fire-permit.md
content/src/anytime-action-tasks/government-contracting.md
content/src/anytime-action-tasks/healthcare-cds-reinstate.md
content/src/anytime-action-tasks/hot-work-fire-permit.md
content/src/anytime-action-tasks/new-home-warranty-enrollment.md
content/src/anytime-action-tasks/njstart-registration.md
content/src/anytime-action-tasks/pred-registration.md
content/src/anytime-action-tasks/prevailing-wage.md
content/src/anytime-action-tasks/registry-update-brc-amendment.md
content/src/anytime-action-tasks/shelter-cds-reinstatement.md
content/src/anytime-action-tasks/smoke-detector-certificate.md
content/src/anytime-action-tasks/state-contracting.md
content/src/anytime-action-tasks/tax-clearance-certificate.md
content/src/anytime-action-tasks/temporary-space-online-biz-fire-permit.md
cspell.json
web/public/mgmt/config.yml
web/src/components/MenuOptionSelected.tsx
web/src/components/dashboard/AnytimeActionDropdown.test.tsx
web/src/components/dashboard/AnytimeActionDropdown.tsx
web/src/lib/types/types.ts
web/src/styles/components/anytime-action-dropdown.scss

We wanted descriptions added to the anytime action dropdown that were search enabled
Also a hidden meta data field that was also search enabled
This pull request resolves [#7865](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7865).
Get to any time actions (form a business). 
See that there are descriptions
Type in some search text that only appears in a description
See that filtering works correctly
If you want add, some meta data in the CMS
See that the meta data text doesn't appear in the drop down
See that you can search for the meta data text and the filtering works as intended
The ticket requested the addition of meta data content but this content was formatted more like descriptions than actual meta data and would have matched all sorts of weird things …

feat: [AB#7865] implement anytime action descriptions

---

CHANGELOG.md
package.json

* [[#0](https://github.com/newjersey/navigator.business.nj.gov/issues/0) | AB[#0](https://github.com/newjersey/navigator.business.nj.gov/issues/0)] disable flaky test ([f293d57](https://github.com/newjersey/navigator.business.nj.gov/commit/f293d57ed4faefb54cc6541f7c0f060f02f97fd1))
* [[#188887754](https://github.com/newjersey/navigator.business.nj.gov/issues/188887754) | AB[#8670](https://github.com/newjersey/navigator.business.nj.gov/issues/8670)] Fix Anytime Actions Category Spelling ([08e6467](https://github.com/newjersey/navigator.business.nj.gov/commit/08e6467984f7466435e1c474c77a52190f61d831))
* [[#188908973](https://github.com/newjersey/navigator.business.nj.gov/issues/188908973) | AB[#12673](https://github.com/newjersey/navigator.business.nj.gov/issues/12673)] convert email to …

chore(release): 2025.8.0 [skip ci]

---

CHANGELOG.md
content/src/anytime-action-tasks/mvc-register.md
content/src/anytime-action-tasks/mvc-title.md
content/src/roadmaps/add-ons/business-vehicle.json
content/src/roadmaps/add-ons/car-service-high-capacity.json
content/src/roadmaps/industries/car-rental.json
content/src/roadmaps/industries/car-service.json
content/src/roadmaps/industries/food-truck.json
content/src/roadmaps/industries/freight-forwarding.json
content/src/roadmaps/industries/logistics.json
content/src/roadmaps/industries/moving-company.json
content/src/roadmaps/industries/non-medical-transport.json
content/src/roadmaps/industries/school-bus.json
content/src/roadmaps/industries/transportation.json
content/src/roadmaps/industries/trucking.json
content/src/roadmaps/tasks/mvc-registration-task.md
content/src/roadmaps/tasks/mvc-title-task.md
package.json

- **fix: hotfix update MVC-related content**
- **chore(release): 2025.8.1 [skip ci]**

release 20250319

---

CHANGELOG.md
content/src/roadmaps/license-tasks/land-surveyor.md
content/src/roadmaps/license-tasks/special-dental-permit.md
package.json

- **chore(release): 2025.9.0 [skip ci]**

release 20250325

---

CHANGELOG.md
content/src/roadmaps/industries/engineering.json
content/src/roadmaps/license-tasks/land-surveyor-license.md
package.json

- **chore(release): 2025.10.0 [skip ci]**

release 20250402

---

web/public/mgmt/config.yml

Added anytime action category for vehicle related stuff
This pull request resolves [#13633](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13633).

feat: [AB#13633] add anytime action category for vehicle related actions

---

web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepThree.tsx

chore: [AB#7752] remove colon from tax clearance review tab

---

web/src/components/profile/ProfileTab.tsx
web/src/components/profile/ProfileTabNav.tsx
web/src/styles/components/buttons.scss
web/src/styles/components/profile-tab-nav.scss

* updated the styling of the Profile page nav buttons to be in accordance with the most recent designs: [Figma](https://www.figma.com/design/vAa8neaM0JJSmldck5vlBC/Business-Experience-Design-System?node-id=3044-10011)
This pull request resolves [#8294](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/8294).
* moved all styling for this component into the existing file: `profile-tab-nav.scss`
* added an icon prop 
* run test sweet

Update profile nav button styling

---

content/src/fieldConfig/profile.json
web/public/img/bar-chart.svg
web/public/img/edit.svg
web/public/img/folder-open.svg
web/public/img/info-outline.svg
web/src/components/profile/ProfileNoteForBusinessesFormedOutsideNavigator.tsx
web/src/components/profile/ProfileTab.tsx
web/src/components/profile/ProfileTabNav.tsx
web/src/pages/profile.tsx
web/src/styles/components/profile-tab-nav.scss

* Followup PR to [this PR](https://github.com/newjersey/navigator.business.nj.gov/pull/10056) to address QA feedback
This pull request resolves [#8294](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/8294).
* moved all styling for this component into the existing file: `profile-tab-nav.scss`
* added an icon prop 
* run test sweet

chore: [AB#8294] update profile nav button styling

---

web/src/components/tasks/business-formation/contacts/Signatures.tsx

Updated the styling of the Formation Signature and Title fields. Made adjustments to labels, alignment, and mobile/desktop style differences. 
This pull request resolves [#13073](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13073).

chore: [AB#13073] Update Formation Signature Styling

---

api/package.json
api/scripts/fix-documents.mjs
package.json
yarn.lock

Business Documents (formation, certified, and standing) were being erroneously stored in `s3/nj-bfs-user-documents-prod/undefined/<docUrl>`. They should have been stored under the users specific `custom-id` from Cognito. This PR contains the script used to fix those documents. 
This pull request resolves [#13734](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13734).
The script scans the database for businesses that have document URLs containing "undefined" in their path, exports the affected records to CSV for reference, and then fixes each one by moving the S3 objects to the correct location using the user's custom identity ID. The script can either fix all affected businesses or target a specific business ID for remediation.
There are still 4 files in the …

chore: [AB#13734] script for updating docUrls for prod users

---

web/src/components/LegalStructureDropDown.tsx
web/src/components/data-fields/ResponsibleOwnerName.tsx
web/src/components/filings-calendar/tax-access/TaxAccess.tsx
web/src/components/filings-calendar/tax-access/TaxAccessStepOne.tsx
web/src/components/filings-calendar/tax-access/TaxAccessStepTwo.tsx
web/src/styles/components/calendar.scss
web/src/styles/components/errors.scss

Addresses design feedback from reviews for initial PR #10108. 
This pull request resolves [#13987](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13987).
There are a couple outstanding items that would be better addressed in design qa items. Hannah is adding those and will mention to Dillon so we can pull those into an upcoming sprint.

Tax Calendar Access - Address Design QA Feedback

---

web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.test.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceSteps.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/CheckEligibility.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Download.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Requirements.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx

This does some light re-work of the tax clearance anytime action.
n/a
- pulled download page into steps component
- moved steps into a sub directory under the tax clearance component
- step component is now determined by using `props.currentStep` to index an array
- this more closely follows a pattern established in Formation, and eliminates additional logic
- removed Entity ID from the form UI
- pulling this out from the current validation work in #10105 to further minimize changes introduced by that PR
Everything about tax clearance works as it did previously. This is just a reorganizing of logic.

Tax Clearance task screen refactor

---

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
web/src/components/tasks/business-formation/business/BusinessStep.test.tsx

fix: [AB#13890] fixed after hours test flakyness

---

web/cypress/e2e/performance-and-accessability.spec.ts

Examples of flake fails:
PR fail: https://app.circleci.com/pipelines/github/newjersey/navigator.business.nj.gov/37074/workflows/1fafa4a2-f90f-4500-a6ad-9d5c678553e4/jobs/180306
Main fail ([chore: [[AB#12854](https://dev.azure.com/NJInnovation/aee72662-26da-4ded-83e3-7e34127c8f0d/_workitems/edit/12854)] split yaml collection into multiple files](https://github.com/newjersey/navigator.business.nj.gov/commit/d5eca7a10284244f305b9190e8d2c773c02bdcb7) on main): https://app.circleci.com/pipelines/github/newjersey/navigator.business.nj.gov/36872/workflows/06da831e-2f1b-45e5-b8d4-6a768dcb8ef6/jobs/179631
See [this discussion](https://njcio.slack.com/archives/C04J8MTJNS2/p1746041676065879)
This pull request resolves [#0000](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/ …

chore: Skip flaky cypress test

---

content/src/fieldConfig/profile.json
web/src/components/profile/ProfileAddress.tsx

Small tweaks for Design QA 
This pull request resolves [#13775](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13775).

chore: [AB#13775] design qa feedback

---

web/src/components/profile/ProfileTabHeader.tsx
web/src/components/profile/ProfileTabNav.tsx
web/test/pages/profile/profile-starting.test.tsx

Initial Product QA
This pull request resolves [#13775](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13775).

chore: [AB#13775] product qa feedback

---

api/jest-dynalite-config.js
api/src/api/externalEndpointRouter.test.ts
api/src/api/formationRouter.test.ts
api/src/api/licenseStatusRouter.test.ts
api/src/api/selfRegRouter.test.ts
api/src/api/taxFilingRouter.test.ts
api/src/api/userRouter.test.ts
api/src/api/xrayRegistrationRouter.test.ts
api/src/db/DynamoBusinessDataClient.test.ts
api/src/db/DynamoBusinessDataClient.ts
api/src/db/DynamoDataClient.test.ts
api/src/db/DynamoDataClient.ts
api/src/domain/types.ts

This pull request resolves [#7458](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7458).
This PR adds functionality to support retrieving users by business name. The approach involves updating the `dynamoBusinessesDataClient` to include two helper methods: one for finding businesses by an exact name match and another for prefix-based business name search. These helpers enable flexible querying based on how much of the business name is known.
In the dynamoDataClient, I’ve added the `findUsersByBusinessName` and `findUsersByBusinessNamePrefix` methods to call both the dynamoBusinessDataClient and the dynamoUserDataClient, allowing us to first retrieve the relevant business entity or entities and then use that data to find and return the associated user(s).
To …

chore: [AB#7458] add query to get find userWithBusinessName

---

web/src/styles/base/global.scss

This pull request resolves [#13918](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13918).
Add css override for njwds focus state

feat: [AB#13918] update focus state color

---

CHANGELOG.md
content/src/roadmaps/license-tasks/rmw-generator-registration.md
package.json

- **chore(release): 2025.11.0 [skip ci]**

release 20250513

---

content/src/anytime-action-tasks/close-your-business.md
web/decap-config/collections/10-anytime-action.yml
web/src/components/dashboard/AnytimeActionDropdown.test.tsx
web/src/components/dashboard/AnytimeActionDropdown.tsx
web/src/lib/types/types.ts
web/test/factories.ts

This PR adds the ability to add synonyms for anytime action tasks to allow users to search those alternative keywords.
This pull request resolves [#13778](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13778).
To Add a Synonym:
1. Run the app locally and navigate to localhost:3000/mgmt/cms
2. Run the command `yarn cms:proxy`
3. Navigate to the Anytime Action Tasks directory and pick a particular anytime action
4. Scroll to the bottom and add a Synonym for search and hit publish
To Search by Synonym
1. Run the app locally with the `yarn cms:proxy` command as well
2. Go to an already operating business
3. Verify the anytime action tasks you want to search by synonym is in the list (synonyms only work if the task is already in your list)
4. Search for the synonym …

feat: [AB#13778] Add synonyms for anytime action dropdown serach

---

web/src/styles/components/gradient-button.scss

Design QA - Personalize My Tasks button
This pull request resolves [#14239](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14239).

Design QA - Personalize My Tasks button

---

.prettierrc
web/decap-config/config-base.yml

1. **Prettier Configuration Update**: You've simplified the file by: `.prettierrc`
- Consolidating Markdown formatting rules into a single configuration
- Ensuring proper JSON syntax with appropriate quotes and brackets
- Adding specific formatting preferences for code embedded within Markdown files
1. **Configuration Alignment**:
- The YAML configuration in specifies how the CMS should handle content `config-base.yml`
- Your Prettier configuration now properly aligns with these settings to ensure consistent formatting

chore: correct .prettierrc syntax and simplify Markdown formatting rules

---

content/src/page-metadata/page-metadata.json
web/decap-config/collections/01-business-formation.yml
web/decap-config/collections/06-tasks.yml
web/decap-config/collections/12-misc.yml
web/src/lib/search/searchConfig.ts
web/src/pages/mgmt/search.tsx

This PR fixes a bug in the CMS search where certain terms were not returning the expected results. The issue was caused by mismatches between the config.json files and config.yml files. 
This pull request resolves [#13171](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13171).
* fixed any mismatched values and object structures in the yml files
* rather than returning no results when a key couldn't be found in the yml files an error is show to the person using the search and partial results are returned

fix: [AB#13171] updated yml files to match json configs

---

content/src/roadmaps/license-tasks/rmw-generator-registration.md

It needs to be single line or with an indent on the subsequent lines. Will fix the sync in a separate PR

fix: Fix that summaryDescriptionMd was multi-line without an indent

---

web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceSteps.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx

Further fixes for error validation and submit handler functionality of the Tax Clearance Form
This pull request resolves [#13891](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13891).

fix: [AB#13891] change formContext onSubmit for custom onSubmit

---

api/src/client/ApiTaxClearanceCertificateClient.ts
api/src/client/AwsCryptoFactory.test.ts
api/src/domain/user/encryptFieldsFactory.ts
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.test.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceSteps.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx

Addresses a race condition in tax clearance tax id check that was causing unexpected behavior.

Address race condition in tax clearance tax id check

---

content/src/fieldConfig/abc-emergency-trip-permit.json
web/src/components/njwds-extended/LiveChatHelpButton.test.tsx
web/src/components/njwds-extended/LiveChatHelpButton.tsx
web/src/components/tasks/abc-emergency-trip-permit/EmergencyTripPermit.test.tsx
web/src/components/tasks/abc-emergency-trip-permit/EmergencyTripPermit.tsx
web/src/components/tasks/abc-emergency-trip-permit/EmergencyTripPermitWithValidation.test.tsx
web/src/lib/utils/analytics-legacy.ts
web/src/lib/utils/analytics.ts

Make changes as a result of requested changes, mostly to copy.
This pull request resolves [#14467](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14467).
The one interesting thing here is the livechat button- I added an optional onClick prop to allow for more generic analytics use

fix: [AB#14467] Update ETP stepper from ABC feedback

---

web/src/components/tasks/abc-emergency-trip-permit/EmergencyTripPermit.tsx

move help button
This pull request resolves [#14467](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14467).
Move Help Button

fix: [AB#14467] move help button

---

sql/dol_employer_rates.sql

Add dol test script to code base

chore: add dol employer rates script

---

web/src/components/njwds-extended/HorizontalStepper.tsx
web/src/styles/components/stepper.scss

Update stepper to new colors and design.
This pull request resolves [#13919](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13919).

chore: [AB#13919] update stepper colors

---

CHANGELOG.md
package.json

* [AB[#13171](https://github.com/newjersey/navigator.business.nj.gov/issues/13171)] updated yml files to match json configs ([2977b80](https://github.com/newjersey/navigator.business.nj.gov/commit/2977b80f35c83c84e2a7a9181b8cd84a407a4035))
* [AB[#13891](https://github.com/newjersey/navigator.business.nj.gov/issues/13891)] change formContext onSubmit for custom onSubmit ([5b1575c](https://github.com/newjersey/navigator.business.nj.gov/commit/5b1575cdd3a00f9079df0154c4f89929a09de0ef))
* [AB[#13891](https://github.com/newjersey/navigator.business.nj.gov/issues/13891)] handle tax clearance input errors on submit ([7c2c60a](https://github.com/newjersey/navigator.business.nj.gov/commit/7c2c60a7f34dfd5e5a8918420dfa4f8ba4db471e))
* [AB[#14067](https://github.com/newjersey/navigator.business.nj.gov …

chore(release): 2025.12.0 [skip ci]

---

web/src/styles/components/gradient-button.scss

Design fixes for profile accordion
This pull request resolves [#13777](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13777).

fix: [AB#13777] fix gradient in star icon

---

web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.test.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateAlert.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceSteps.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/helpers.ts
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx
web/test/helpers/helpers-testing-library-selectors.ts

A few refactors that involve the tax clearance work. 
Updated the tests to pull out helper functions into the relevant helpers file. Using context rather than passing data via props. Update a few boolean logic pieces to be more readable.

chore: [AB#00000] refactoring tax clearance section

---

web/src/components/data-fields/non-essential-questions/NonEssentialQuestionsSection.test.tsx

Wanted to fix a test regarding nonEssentailQuestionSections
This pull request resolves [#14386](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14386).

feat: [AB#14386] fixed testing issue for nonEssentailQuestionsSection

---

content/src/fieldConfig/dashboard-defaults.json
content/src/fieldConfig/profile.json

This pull request resolves [#14796](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14796).
Change Personalize My Tasks to Personalize My Experience

fix: [AB#14796] Change to Personalize my experience

---

CHANGELOG.md
api/src/libs/logWriter.ts
content/src/roadmaps/license-tasks/individual-producer-license.md
content/src/roadmaps/license-tasks/new-producer-license.md
content/src/roadmaps/license-tasks/store-milk-license.md
package.json
web/src/scripts/webflow/licenseSync.mjs

- **fix: [AB#114979] prevent 'details?.toJSON is not a function' error**
- **chore(release): 2025.13.0 [skip ci]**

release 20250624

---

web/src/lib/types/types.ts

I moved the type but forgot to add the deleted type.
https://github.com/newjersey/navigator.business.nj.gov/pull/10669

feat: remove UpdateQueue from types.ts since it's unused

---

web/src/components/search/ConfigMatchList.tsx
web/src/components/search/MatchList.tsx
web/src/lib/search/searchAnytimeActionLicenseReinstatement.ts
web/src/lib/search/searchAnytimeActionTasks.ts
web/src/lib/search/searchCertifications.ts
web/src/lib/search/searchConfig.ts
web/src/lib/search/searchContextualInfo.ts
web/src/lib/search/searchFundings.ts
web/src/lib/search/searchIndustries.ts
web/src/lib/search/searchLicenseEvents.ts
web/src/lib/search/searchNonEssentialQuestions.ts
web/src/lib/search/searchRenewalCalendarEvents.ts
web/src/lib/search/searchSidebarCards.ts
web/src/lib/search/searchSteps.ts
web/src/lib/search/searchTasks.ts
web/src/lib/search/searchTaxFilings.ts
web/src/lib/search/searchWebflowLicenses.ts
web/src/lib/search/typesForSearch.ts
web/src/pages/mgmt/search.tsx

Currently the search results that are provided in the [custom CMS search tool](https://dev.account.business.nj.gov/mgmt/search) do not include the ability for the content team members to easily navigate to the item in the CMS that corresponds with the search result. This feature adds a link to the item in the CMS that corresponds with the search result. 
This pull request resolves [#14869](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14869).
Future Development Considerations: 
To introduce a more dynamic approach, enforce standard to make the collection names and the directory names the same. This helps us avoid hard coding the collection names.
For the search functionality, some of the collections are not searched through such as "roadmaps" collection and …

14869 cms search link items

---

web/src/components/data-fields/non-essential-questions/CertificationsAndFundingNonEssentialQuestions.test.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx

Adds a loading spinner to the Tax Clearance Form submit buton
This pull request resolves [#14870](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14870).

feat: [AB#14870] add loading spinner to tax clearance

---

web/src/components/profile/ProfileTabPanel.test.tsx
web/src/components/profile/ProfileTabPanel.tsx
web/src/pages/profile.tsx
web/test/pages/profile/profile-helpers.tsx
web/test/pages/profile/profile-owning.test.tsx
web/test/pages/profile/profile-starting.test.tsx

Replace error snackbar with page level alert on Profile
Replace error snackbar with page level alert on Business Profile page
This pull request resolves [#14619](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14619).

fix: [AB#14619] Replace error snackbar with page level alert on Profile 

---

api/package.json

Updates our backend start scripts to enable hot reloading. Backend code changes will be immediately available without completely restarting the application locally.
This pull request resolves [#15104](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15104).
Updated the `yarn start` command to use Serverless's `--reloadHandler` param which will reload the backend with each request.
Start the app, change the backend, see a change immediately.
I'm going to close [#12976](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12976). This was a spike to investigate using Nodemon to do this same thing.
I initially started down this path, but met a series of roadblocks that were incredibly painful. The biggest roadblock being that Serverless was …

Hot hot reload

---

api/src/db/migrations/v167_update_agent_number_or_manual_options.test.ts
api/src/db/migrations/v167_update_agent_number_or_manual_options.ts

Fix to include version within businesses. 
This pull request resolves [#14397](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14397).

fix: [AB#14397] migration 167 to include business version

---

content/src/fieldConfig/business-formation.json
web/src/components/tasks/business-formation/BusinessFormationTextField.tsx
web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx

Updates some design and content items.
This pull request resolves [#14397](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14397).

fix: [AB#14397] Address design and content discrepancies for new registered agent content

---

api/src/db/migrations/v167_update_agent_number_or_manual_options.ts

v167 migration uses the migration script and includes more explicit type definitions, which we like
This pull request resolves [#14397](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14397).

fix: [AB#14397] update migration to follow generator pattern

---

content/src/fieldConfig/abc-emergency-trip-permit.json

Fix copy content in banner.
This pull request resolves [#15167](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/015167).

fix: [AB#15167] fix copy in emergency permit

---

CHANGELOG.md
content/src/roadmaps/license-tasks/well-driller-license.md
package.json

- **chore(release): 2025.15.0 [skip ci]**

release 20250717

---

content/src/fieldConfig/tax-clearance-certificate-shared.json
content/src/fieldConfig/tax-clearance-certificate-step3.json
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateAlert.test.tsx
web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateAlert.tsx

Removed periods from bold text in AnytimeActionTaxClearanceAlert messaging. Also added a line break to the field error messaging. 
This pull request resolves [#15189](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15189).

fix: [AB#15189] changing formatting for tax clearance error message

---

content/src/display-content/contextual-information/service-connections.md
content/src/fieldConfig/env-questionnaire.json
web/decap-config/collections/02-environmental-compliance.yml
web/src/components/njwds-extended/HorizontalStepper.tsx
web/src/components/tasks/environment-questionnaire/EnvPermit.test.tsx
web/src/components/tasks/environment-questionnaire/EnvQuestionnaireStepper.tsx
web/src/lib/domain-logic/routes.ts

Content fixes, adding reroute, and stepper updates.
This pull request resolves [#7218](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7218).

fix: [AB#7218] content, reroute, and stepper update

---

CHANGELOG.md
package.json

* [AB[#14397](https://github.com/newjersey/navigator.business.nj.gov/issues/14397)] updates from content ([ec91b72](https://github.com/newjersey/navigator.business.nj.gov/commit/ec91b72cbf0f9ffa2ad209f760e4e63222d4daee))
* [AB[#15189](https://github.com/newjersey/navigator.business.nj.gov/issues/15189)] changing formatting for tax clearance error message ([ee9cf42](https://github.com/newjersey/navigator.business.nj.gov/commit/ee9cf4284c233e4008229fc2fe0ba994ae286cfb))
* [AB[#15204](https://github.com/newjersey/navigator.business.nj.gov/issues/15204)] Add callout to Step 3 of Emergency Trip Permit ([1675d4b](https://github.com/newjersey/navigator.business.nj.gov/commit/1675d4bb1a32a8cf0c2a5c4958f7f0f5d1ec16b9))
* [AB[#15241](https://github.com/newjersey/navigator.business.nj.gov/issues/1524 …

chore(release): 2025.16.0 [skip ci]

---

web/src/pages/_app.tsx

registration status analytics dimension wasn't triggering correctly 
This pull request resolves [#13423](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13423).
was debugging why the registration_status analytics dimension wasn't triggering correctly due when users signed in. 
You could run local host
Then open GTM and hit preview
Enter localhost address
Then go signin 
Then watch the GTM events and go to data layer in the last event and see that registration_status is Fully Registered
It seems like the API call event changed at some point so this was never getting triggered. 
Feels like we should have some kind of test around that but I'm not sure exactly what.

feat: [AB#13423] fixed registration status enablement

---

.circleci/config.yml
web/cypress/e2e/group_5/taxclearance.spec.ts
web/cypress/support/helpers/helpers.ts

Added new Tax Clearance Cypress Test
This pull request resolves [#13902](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13902/).

feat: [AB#13902] Add Tax Clearance Cypress Test

---

web/decap-config/collections/06-tasks.yml
web/decap-config/collections/12-misc.yml
web/src/lib/cms/previews/EmergencyTripPermitPreview.tsx
web/src/lib/cms/previews/LegalMessagePreview.tsx
web/src/lib/cms/previews/SelfRegistrationPreview.tsx
web/src/pages/mgmt/cms.tsx
web/src/styles/components/alerts.scss

A few more preview improvements
This pull request resolves [#13035](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13035).

13035 live preview stuff more

---

api/src/db/migrations/migrations.ts
api/src/db/migrations/v172_add_cig_license_payment_info.test.ts
api/src/db/migrations/v172_add_cig_license_payment_info.ts
shared/src/cigaretteLicense.ts
shared/src/test/factories.ts
shared/src/userData.ts

Adding payment info to the Cigarette License data object
This pull request resolves [#14214](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14214).
Updated `cigaretteLicenses.ts` objects, added new migrations, and tests for the migration

Cigarette licese payment object

---

content/src/roadmaps/nonEssentialQuestions.json
web/decap-config/collections/05-roadmap.yml

Fixing`NonEssentialQuestions.json`, it was distorted because of a draft being merged after the updates were made causing the updates to be overwritten.

fix: non-essential questions

---

content/src/fieldConfig/passenger-transport-cdl-tab2.json
web/src/components/tasks/passenger-transport-cdl/PassengerTransportCdlQuestion.tsx

This pull request resolves [#14919](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14919).

chore: [#AB14919] add margin to passenger transport screen

---

web/cypress/e2e/group_1_onboarding/onboarding-as-starting-business.spec.ts
web/cypress/support/page_objects/onboardingPageNew.ts

chore: fix failing industry cypress test

---

shared/src/index.ts
web/cypress/support/helpers/helpers.ts
web/src/lib/data-hooks/useConfig.ts
web/stories/Molecules/textfields/OneFieldTextField.stories.tsx

Specifically with importing modules from
`@businessnjgovnavigator/shared/contexts/configContext`

fix: TypeScript module resolution issues

---

CHANGELOG.md
content/src/roadmaps/industries/cemetery.json
content/src/roadmaps/industries/remediation-waste.json
content/src/roadmaps/industries/security.json
content/src/roadmaps/license-tasks/dental-waste-exemption.md
content/src/roadmaps/license-tasks/dental-waste-registration.md
package.json

- **chore(release): 2025.18.0 [skip ci]**

release 20250821

---

web/src/webflow/README.md
web/src/webflow/dropdown.html

Update links generated by the custom Webflow starter kits dropdown from `navigator.business.nj.gov` -> `account.business.nj.gov`.
Add a `README.md` to `web/src/webflow/` explaining this file and the configuration in Webflow.
This pull request resolves [#15475](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15475).
Simple change - just updated the base URL to reference the new domain prefix.
This change has since been deployed to the beta version of the Webflow site. Purposefully not linking.
Navigate to the [Starter Kits page](https://business.nj.gov/starter-kits) of the static site. Select an industry from the "Find Your Industry" dropdown. The "Access My Starter Kit" CTA should have a link pointing to …

feat: [AB#15475] Webflow - update custom dropdown links

---

api/src/libs/healthCheck.ts

chore: testing a breaking self commit

---

api/src/libs/healthCheck.ts

chore: revert self endpoint

---

api/.dependency-cruiser.js
api/package.json
api/src/client/ApiCigaretteLicenseClient.test.ts
api/src/cms-integrity-tests/anytimeActionCategoryUsage.ts
api/src/cms-integrity-tests/runCmsIntegrityTests.ts
api/src/functions/express/app.ts
api/src/libs/awsSns.ts
api/src/libs/ssmUtils.ts
package.json
yarn.lock

We wanted to setup a runtime backend test, that triggers if the CMS is silently breaking. For example if any of the relation widgets are secretly broken we want this to catch those issues and send an informative message to a slack channel. 
This pull request resolves [#14787](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14787).
This took a few different turns. 
First I did a refactor (different commit) to move most of our file reading logic to the shared folder so it could be accessed from the backend. 
Second went into AWS and added a new SNS topic and had our AWS slack chat bot subscribe to that topic. 
Then I downloaded AWS SNS client via yarn to the backend and wrote code to call publishes a message to that SNS topic if we read in files and find that …

feat: [AB#14787] create slack messages for CMS integrity tests

---

api/src/client/ApiCigaretteLicenseClient.test.ts
api/src/client/ApiCigaretteLicenseClient.ts
api/src/client/ApiCigaretteLicenseHelpers.ts
shared/src/cigaretteLicense.ts
web/src/powerautomate/cigLicenseEmailPdf.html

Adds the HTML script for the Send Email Confirmation portion of the PowerAutomate script used for Cigarette License
This pull request resolves [#15656](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15656).

feat: [AB#15656] adding cig license email html

---

CHANGELOG.md
package.json

* [AB[#14930](https://github.com/newjersey/navigator.business.nj.gov/issues/14930)] Step 2 Contact name bugfix ([56380d4](https://github.com/newjersey/navigator.business.nj.gov/commit/56380d48bfa80519749852c6e32e4be82f7dc61e))
* [AB[#14931](https://github.com/newjersey/navigator.business.nj.gov/issues/14931)] correct Suppliers and Start Date Labels ([9a11eda](https://github.com/newjersey/navigator.business.nj.gov/commit/9a11eda25cbe6387d46c44ece6b13dc7c1a1579d))
* [AB[#14931](https://github.com/newjersey/navigator.business.nj.gov/issues/14931)] label correction for step4 cig license ([ce33bc2](https://github.com/newjersey/navigator.business.nj.gov/commit/ce33bc2d744ad70a2e554cc4e48392af54709936))
* [AB[#14932](https://github.com/newjersey/navigator.business.nj.gov/issues/14932)] removing …

chore(release): 2025.20.0 [skip ci]

---

shared/src/dateHelpers.test.ts
shared/src/dateHelpers.ts
web/src/powerautomate/cigLicenseEmailPdf.html

Fixes the date display on the Confirmation page and Review page of Cigarette License. Also updated the HTML for the Send Email confirmation piece of the PowerAutomate Script.
This pull request resolves [#15884](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15884).

fix: [AB#15884] fixing utc date and email html

---

content/scripts/content_collections_to_csv.py

This PR adds a comprehensive Python script for parsing content collection files (Markdown, JSON, YAML) and exporting them to CSV format. The script supports three modes of operation:
1. **Process all collections** - Automatically discovers and processes all content collections from NetlifyCMS configuration
2. **Process specific collection** - Targets a single collection by name with user-friendly field labels
3. **Process directory path** - Fallback mode for direct directory processing when no CMS config is available
The script intelligently extracts structured data from frontmatter in Markdown files, as well as full content from JSON and YAML files. When NetlifyCMS configuration is available, it maps technical field names to user-friendly column headers for better readability.
Key …

feat: [AB#15822] add Python script to parse content collections and generate CSV

---

web/src/lib/cms/fields/nospacefield.tsx
web/src/lib/cms/fields/writeoncereadonlynospacefield.tsx

This PR enhances input validation for CMS fields by adding detection and rejection of unsupported Unicode dash characters. The changes affect two field components:
- `NoSpaceControl`: Enhanced existing validation to include dash character checking
- `WriteOnceReadOnlyNoSpaceControl`: Added proper validation (previously always returned true)
The validation now detects various Unicode dash characters (en dash, em dash, figure dash, etc.) and provides a clear error message directing users to use the standard hyphen (-) character instead. This prevents potential issues with URL generation, routing, or data processing that may not handle these Unicode variants correctly.
This pull request resolves [#15929](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15929).
No …

fix: [AB#15929] add validation for unsupported dash characters in CMS fields

---

web/src/components/navbar/shared-submenu-components.tsx

Add profile icon and remove business link
This pull request resolves [#15998](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15998).

feat: [AB#15998] add profile icon and remove business link

---

.circleci/config.yml
web/test/pages/profile/profile-owning.test.tsx

ECONNRESET errors have been happening sporadically across our unit tests in CircleCI, which has caused tests to flake and held up our automatic dependency upgrades. This does not seem to have anything to do with the test logic itself. This change adds an automatic retry to decrease the chance that an ECONNRESET error causes an otherwise sound change to fail the unit tests.
This pull request resolves [#15907](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15907).
I originally tried turning on automatic retries in Jest by adding
```
if (process.env.CI) {
jest.retryTimes(1);
}
```
to `setupTests.js`. However, I noticed that if a test passes on retry, Jest will not log the initial failure, which is not ideal / undermines our visibility into flaky tests. I tested …

chore: [AB#15907] add automatic rerun to mitigate ECONNRESET failures

---

content/src/fieldConfig/remove-business-modal.json
web/src/components/auth/RemoveBusinessModal.test.tsx
web/src/components/auth/RemoveBusinessModal.tsx

PR fixes for remove business modal
This pull request resolves [#15306](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15306).

fix: [AB#15306] PR fixes for remove business modal

---

api/src/client/ApiTaxClearanceCertificateClient.test.ts
api/src/client/ApiTaxClearanceCertificateClient.ts

Updates the health check to purposefully fail, and anticipate a 400 error code and specific error message from the Tax Clearance Certificate generator service.
This pull request resolves [#16327](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/16327).
- Update the payload provided to the tax clearance certificate generator as a part of the health check
- Anticipate a 400 code and the error message: `ADABase validation failed. Please verify the data submitted and retry.`
- If received, respond that the health check was successful
- Trigger the health check in a cloud environment
- Check logs and confirm the check was successful
This change is not necessarily ideal, but it is being done to accommodate a request from our partners. See [this Slack …

[AB#16327] Update tax clearance certificate health check

---

api/src/client/ApiTaxClearanceCertificateClient.test.ts
api/src/client/ApiTaxClearanceCertificateClient.ts

Follow on to #11713 to address a misconfiguration in the anticipated error response.

chore: [AB#16327] update tax clearance cert health check
