CHANGELOG.md, package.json
* **deps:** upgrade dependencies to the latest version ([8ace195](https://github.com/newjersey/business.nj.gov/commit/8ace195172181e196d7d91416871d1e06dfe7d69))
=> chore(release): 1.1.1 [skip ci]

.circleci/config.yml, CHANGELOG.md, package.json
- build: add global npm setup to prepare release step
- build: fix github installation steps
- chore(release): 1.5.0 [skip ci]
=> release 20211215

web/src/components/Signup.test.tsx, web/src/components/tasks/LicenseTask.test.tsx
Fixing type check errors seen here: https://app.circleci.com/pipelines/github/newjersey/navigator.business.nj.gov/2728/workflows/34efa10c-9fef-45c6-8594-3aa38b60ccd2/jobs/10098/parallel-runs/0/steps/0-112
- `act()` expects a callback of void function, but we are implicitly returning a promise
- `waitFor()` seems like a clearer way to handle this case
- can also fix by doing 
```
await act(async () => {
await resolvedPromise
});
```
=> fix: fix type errors with act() on license and signup tests

CHANGELOG.md, content/src/fieldConfig/config.json
- fix: correct a typo on the landing page
- chore(release): 2.4.2 [skip ci]
=> release 20220316

CHANGELOG.md, package.json
* **deps:** update aws-sdk to v3.67.0 ([41ac37d](https://github.com/newjersey/navigator.business.nj.gov/commit/41ac37d36b4f2342984050c387ff6c0529b05a01))
=> chore(release): 3.2.1 [skip ci]

CHANGELOG.md, package.json
* hide bad material-ui styling on CMS checkboxes ([4e76b27](https://github.com/newjersey/navigator.business.nj.gov/commit/4e76b27fdaaa8ac90118dcf2fc4a0bb9cb4fe61a))
* updating Industry Roadmaps e-commerce ([#2457](https://github.com/newjersey/navigator.business.nj.gov/issues/2457)) ([c302ad9](https://github.com/newjersey/navigator.business.nj.gov/commit/c302ad96d7d55738298bed7f7513f65fef1e411c))
* updating Industry Roadmaps photography ([#2472](https://github.com/newjersey/navigator.business.nj.gov/issues/2472)) ([463cb42](https://github.com/newjersey/navigator.business.nj.gov/commit/463cb42255b2eeeb41ce3b9af7f7d2e0ba993824))
* updating Poppy Onboarding Content business-name ([#2468](https://github.com/newjersey/navigator.business.nj.gov/issues/2468)) …
=> chore(release): 3.4.1 [skip ci]

CHANGELOG.md, package.json, web/src/components/roadmap/RoadmapSidebarCard.tsx
- fix: adjust the progressbar calculation to start at 0
- chore(release): 3.13.1 [skip ci]
=> release 20220629

CHANGELOG.md, package.json
* [[#182621057](https://github.com/newjersey/navigator.business.nj.gov/issues/182621057)] add styling to sectorModalBody ([e9746be](https://github.com/newjersey/navigator.business.nj.gov/commit/e9746be871b7172745545a628085b862d8a150bb))
* [[#182621057](https://github.com/newjersey/navigator.business.nj.gov/issues/182621057)] move funding snackbars to roadmap file ([9310355](https://github.com/newjersey/navigator.business.nj.gov/commit/9310355400cbbba524e6d5d3af037a569646fb51))
* [[#182771680](https://github.com/newjersey/navigator.business.nj.gov/issues/182771680)] add paragraph breaks to review page ([98ae27c](https://github.com/newjersey/navigator.business.nj.gov/commit/98ae27cf15ad47000e51b22c7fa79d69d31e2809))
* [[#182868051](https://github.com/newjersey/navigator.business.nj.gov/issue …
=> chore(release): 5.0.0 [skip ci]

CHANGELOG.md, package.json
* [[#183716181](https://github.com/newjersey/navigator.business.nj.gov/issues/183716181)] needs to register dbaName validation ([bc9fd4a](https://github.com/newjersey/navigator.business.nj.gov/commit/bc9fd4a70168ca2a759b0c812c618173ec32ca1e))
* updating Profile Page profile-fields ([#5306](https://github.com/newjersey/navigator.business.nj.gov/issues/5306)) ([b6e701e](https://github.com/newjersey/navigator.business.nj.gov/commit/b6e701e5b8ba963ef6732121f2d3f1c04fb2850b))
* updating Roadmaps - Industries generic ([#5304](https://github.com/newjersey/navigator.business.nj.gov/issues/5304)) ([0644dcb](https://github.com/newjersey/navigator.business.nj.gov/commit/0644dcb5538b16b6e9d46ea7e10887987bc86165))
* updating Tasks - All detective-agency-license …
=> chore(release): 5.14.0 [skip ci]

api/src/api/guestRouter.test.ts, api/src/api/userRouter.test.ts, api/src/domain/annual-filings/calculateNextAnnualFilingDates.test.ts, api/src/domain/annual-filings/calculateNextAnnualFilingDates.ts, api/src/domain/annual-filings/getAnnualFilings.test.ts, api/src/domain/annual-filings/getAnnualFilings.ts, api/test/helpers.ts
Calculate the next 3 annual tax filing events to be displayed on a user's calendar.
[#184595589](https://www.pivotaltracker.com/story/show/184595589)
- Updated the `calculateNextAnnualFIlingDate` function to return the next 3 years as an array.
- Modified test helper functions to reference this new logic to reduce redundancy.
=> feat: [#184595589] update annual filings logic to return next 3 years

web/src/components/tasks/business-formation/BusinessFormation.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/billing/BillingStep.test.tsx, web/src/components/tasks/business-formation/billing/PaymentTypeTable.tsx, web/src/components/tasks/business-formation/getFieldForApiField.ts, web/test/helpers/helpers-formation.tsx
I've completed the mapping for the registered agent, and the contacts tab
note: within registered agent fields the following fields were not done, let me know if you disagree.
-  State -- logic is hard coded
-  Country -- logic is hard coded
note: within the contacts tab the following fields were not done, let me know if you disagree.
- Gov2GoAnnualReports -- data is a boolean value, unable to get error
- Gov2GoCorpWatch -- data is a boolean value, unable to get error
- ShortGoodStanding -- data is a boolean value, unable to get error
- Certified -- data is a boolean value, unable to get error
Below are the fields that are sent in the post request, can you review and let me know if anything should be mapped? 
ForeignGoodStandingFile: {
Extension - unable to get error
Content- unable to …
=> feat: [#184597648] expand mapping of known api formation errors

content/src/roadmaps/add-ons/interstate-logistics.json
I inadvertently missed adding `interstate-logistics.json`, which "broke" a Cypress test, so this PR is the fix.
https://www.pivotaltracker.com/n/projects/2573455/stories/184675379
N/A
N/A
N/A
=> fix: [#184675379] add logistics JSON inadvertently missed, fixes broken Cypress test

web/src/components/ModifiedContent.tsx, web/src/components/Step.tsx, web/src/components/dashboard/SidebarCardGeneric.tsx, web/src/components/roadmap/MiniRoadmapStep.tsx, web/src/components/tasks/business-formation/BusinessFormationTextField.tsx, web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx, web/src/components/tasks/business-formation/business/Provisions.tsx, web/src/components/tasks/business-formation/contacts/AddressModal.tsx, web/src/components/tasks/business-formation/contacts/Signatures.tsx, web/src/components/tasks/business-formation/review/ReviewPartnership.tsx
Making a seperate component besides our main markdown content renderer to render our special strings like ${oos} and such
Created component, replaced uses of useContentModifiedByUserData and wrapped around some of the previously markdown content that was recently refactored into being strings, https://github.com/newjersey/navigator.business.nj.gov/commit/ae00697013f59640ac49cee09d044204e78ff49e
[#184697588](https://www.pivotaltracker.com/story/show/#184697588)
Check in the various relevent places that we still render the various <b> and <i> tags correctly
Also check that we still render ${oos} strings correctly around the code base in the relevant places
=> Make separate component to parse  in config

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/getErrorStateForField.ts, web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx, web/src/lib/data-hooks/useBusinessNameSearch.ts, web/test/helpers/helpers-formation.tsx
Fix to address the faulty behavior with the wrong in-line error being fired on blur in business name search.
[184306179](https://www.pivotaltracker.com/story/show/184306179)
=> fix: [#184306179] confirm availability in-line error on blur

api/src/domain/tax-filings/taxFilingsInterfaceFactory.test.ts, api/src/domain/tax-filings/taxFilingsInterfaceFactory.ts, api/src/domain/types.ts, shared/src/taxFiling.ts
Separated the `TaxFilingState` into two: `TaxFilingLookupState` and `TaxFilingOnboardingState` to better reflect data the types of `TaxFilingOnboardingResponse` and `TaxFilingLookupResponse` are representing.
[184320737](https://www.pivotaltracker.com/story/show/184320737)
There was an error among the cases of the state within the onboarding function, based on what's being returned in `ApiTaxFilingClient.ts` the onboarding doesn't ever return `PENDING` state, only `SUCCESS`, `FAILED`, and `API_ERROR`, so I removed that case from onboarding.
=> chore: [#184320737] seperate tax filing onboarding and lookup states

web/public/mgmt/config.yml
It seems like the content team wanted a drop down label field so they could keep track of things better between themselves
Go into the CMS locally and see that under tasks - all and task - license tasks webflow on any / all entries their is now a license type drop down at the bottom with 4 fields
=> feat: [#184702190] task screen has new dropdown field license type

web/public/mgmt/config.yml
Ticket from Dev/Content pairing to show name instead of filename in industry dropdown in tasks within the CMS.
[184890192](https://www.pivotaltracker.com/story/show/184890192)
=> chore: [#184890192] display name for industry dropdown in tasks

web/public/mgmt/config.yml
Fix for displaying industry name in tasks.
[184890192](https://www.pivotaltracker.com/story/show/184890192)
=> chore: [#184890192] fix display name for industry dropdown in tasks

api/src/client/ApiFormationClient.test.ts, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/ForeignCertificate.tsx, web/src/components/tasks/business-formation/business/MainBusiness.tsx, web/src/components/tasks/business-formation/business/PracticesLaw.tsx, web/src/components/tasks/business-formation/review/ReviewStep.tsx, web/src/components/tasks/business-formation/validatedFieldsForUser.ts, web/src/lib/utils/helpers.ts
Applies changes made to foreign-c-corp flow in #5603 to the foreign-s-corp flow.
[185008380](https://www.pivotaltracker.com/story/show/185008380)
- Update all checks for business formation type to account for both foreign-c-corp and foreign-s-corp.
- Update tests to more accurately represent the desired workflow.
See previous PR and associated ticket.
=> [#185008380] Update S-Corp Formation

api/src/api/userRouter.test.ts, api/src/api/userRouter.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v112_add_last_visited_formation_page_to_formation_data.ts, api/test/factories.ts, shared/src/formationData.ts, shared/src/userData.ts, web/src/components/filings-calendar/FilingsCalendarTaxAccess.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/components/tasks/business-formation/DbaFormationPaginator.tsx, web/src/components/tasks/business-formation/NexusFormation.test.tsx, web/src/components/tasks/business-formation/billing/BillingStep.test.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.test.tsx, web/src/components/tasks/business-formation/contacts/testHelpers.tsx, web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/lib/UpdateQueue.ts, web/src/lib/types/types.ts, web/test/factories.ts
We wanted to have the application remember the last formation page the user visited so that if they navigate away and come back they will still be on the same step. (This should be reset if the legal structure type is reset). 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/#184306248)
Go to the formation page as a user, navigate to a step via the stepper or the save and continue button
navigate away from this page, 
navigate back
you should not be on the first step but the step you left off on,
got to the profile page and change your legal structure (business structure on the page) (NOTE not all business structure have a formation process)
go to formation and see that the formation step has reset
=> feat: [#184306248] formation remembers last user visited page

web/src/lib/utils/analytics.ts
Update to Google Analytics work to get correct data for `page_name`.
[184478453](https://www.pivotaltracker.com/story/show/184478453)
We're firing the pageview/screen_view event in the useEffect of `_app.tsx`.
```
useEffect(() => {
router.events.on("routeChangeComplete", analytics.pageview);
return () => {
router.events.off("routeChangeComplete", analytics.pageview);
};
}, [router.events]);
```
I don't think the params NextRouter is providing when the pageview callback fires are the ones initially expected. They don't seem to quite match up. I've changed page_name to grab from document.title and just provide the HTML title for now.
I'd like to talk to Mike about what his initial goal was with this implementation before too much changes.
=> [184478453] Fix page_name

web/src/components/LandingPageActionTile.tsx, web/src/components/LandingPageSlider.tsx, web/src/components/LandingPageTiles.test.tsx, web/src/components/LandingPageTiles.tsx, web/src/components/njwds/Hero.tsx, web/src/lib/auth/signinHelper.test.ts, web/src/lib/auth/signinHelper.ts, web/src/lib/domain-logic/routes.ts, web/src/lib/types/types.ts, web/src/pages/index.tsx, web/src/pages/welcome.tsx
As a user visiting navigator.business.nj.gov/welcome, when viewing the welcome page, only the ‘Get Started’ and ‘File for Taxes’ tiles appear. 
[#184998185](https://www.pivotaltracker.com/story/show/184998185)
N/A
Upon visiting navigator.business.nj.gov/welcome, when viewing the welcome page, only the ‘Get Started’ and ‘File for Taxes’ tiles appear. 
Refactored `LandingPageTiles.tsx` and `LandingPageSlider.tsx` to ensure DRY code and use of props to create one source of truth for the tiles.
=> feat: [#184998185] marketing-calendar-welcome-landing-page

shared/src/domain-logic/taskIds.ts, web/src/components/onboarding/IndustryDropdown.tsx, web/src/components/onboarding/OnboardingIndustry.test.tsx, web/src/pages/profile.tsx, web/test/pages/profile.test.tsx
When the user changes their industry and saves their data, the naics code values in the user data are removed, also the determine your naics code task is reset back to not started.
https://www.pivotaltracker.com/story/show/184125120
=> feat: [#184125120] reset naics codes when changing Industry

web/src/components/profile/DevOnlyResetUserDataButton.tsx, web/src/pages/profile.tsx
Create a button to reset the current user's data that is only accessible in a development environment.
[#185109517](https://www.pivotaltracker.com/story/show/185109517)
Resets the userData obj using the `createEmptyUserData` function and then routes the user back to the landing page.
The button currently lives at the bottom of the profile page. Any data entered prior to clicking the "Reset User Data" button should be wiped.
=> chore: [#185109517] create dev-only reset user button

shared/src/formationData.ts, web/src/components/tasks/business-formation/review/ReviewBusinessSuffixAndStartDate.tsx, web/src/components/tasks/business-formation/review/ReviewMainBusinessLocation.tsx, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/components/tasks/business-formation/review/ReviewStep.tsx, web/src/lib/utils/formation-helpers.ts
Fix to only display the address section on review page when it's required or when the user has inputted something into one of the address fields.
[184305929](https://www.pivotaltracker.com/story/show/184305929)
=> fix: [#184305929] review page address section only appears when required

web/src/scripts/webflow/licenseSync.mjs
=> fix: default import for LookupIndustryById in license sync

web/src/pages/index.tsx, web/test/pages/index.test.tsx
Bug fix for the welcome landing page. If a user is on the welcome version on the landing page, then they are not redirected to the webflow landing page.
[#185191909](https://www.pivotaltracker.com/story/show/185191909)
=> fix: [#185191909] no redirect to alt landing if on welcome landing

api/src/client/ApiFormationClient.test.ts, api/src/client/ApiFormationClient.ts
Change request made by ApiFormationClient Content-Type from json to text/plain.
[185206257](https://www.pivotaltracker.com/story/show/185206257)
Should be able to successfully form a Dakota corp with a foreign good standing file up to 3MB in size.
=> Change ApiFormationClient Content-Type to text/plain

CHANGELOG.md, package.json
* [[#185191909](https://github.com/newjersey/navigator.business.nj.gov/issues/185191909)] no redirect to alt landing if on welcome landing ([37e2588](https://github.com/newjersey/navigator.business.nj.gov/commit/37e258801de218e41c1dc926d9181273458d607f))
* broke linting and tests ([98fe27e](https://github.com/newjersey/navigator.business.nj.gov/commit/98fe27e7b26db674e4007050e902cb0cc7b2e09b))
* update fundings sync with new agency mapping IDs ([ccb4eb4](https://github.com/newjersey/navigator.business.nj.gov/commit/ccb4eb4601d857d72ae16df40c4e16afd4fbe6ac))
* updating Fund Opps - Content njeda-historic-property ([#5240](https://github.com/newjersey/navigator.business.nj.gov/issues/5240)) ([0fad60c](https://github.com/newjersey/navigator.business.nj.gov/commit/0fad60cdee4f407d1e9c02f3cefd84 …
=> chore(release): 5.20.0 [skip ci]

CHANGELOG.md, package.json
- fix: disable error outage bar in prod
- chore(release): 5.20.3 [skip ci]
=> release 20230519

web/src/lib/data-hooks/useContentModifiedByUserData.test.ts, web/src/lib/data-hooks/useContentModifiedByUserData.ts
During the Dakota onboarding flow, the Industry question text was not replacing the ${oos} substring correctly. The hook responsible for this behavior has been updated to reference the `updateQueue` over the `userData` object.
[185266819](https://www.pivotaltracker.com/story/show/185266819)
=> Fix ${oos} bug in Dakota onboarding flow

api/src/api/userRouter.test.ts, api/src/api/userRouter.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v116_add_dba_business_name_availability.ts, shared/src/formationData.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/src/components/filings-calendar/FilingsCalendarTaxAccess.test.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.test.tsx, web/src/components/tasks/business-formation/BusinessFormation.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/DbaFormationPaginator.tsx, web/src/components/tasks/business-formation/NexusFormation.test.tsx, web/src/components/tasks/business-formation/billing/BillingStep.test.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.test.tsx, web/src/components/tasks/business-formation/contacts/testHelpers.tsx, web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx, web/src/components/tasks/business-formation/name/DbaNameSearch.tsx, web/src/components/tasks/business-formation/name/NexusSearchBusinessNameStep.test.tsx, web/src/components/tasks/business-formation/name/NexusSearchBusinessNameStep.tsx, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/components/tasks/search-business-name/SearchBusinessNameForm.test.tsx, web/src/components/tasks/search-business-name/SearchBusinessNameForm.tsx, web/src/contexts/businessFormationContext.ts, web/src/lib/UpdateQueue.ts, web/src/lib/data-hooks/useBusinessNameSearch.ts, web/src/lib/types/types.ts, web/test/factories.ts
Updates Dakota formation flow to check if a submitted business name or DBA name has become unavailable since it was originally submitted.
[184306224](https://www.pivotaltracker.com/story/show/184306224)
Builds off the work that currently exists to do this for Oscar and Poppy users. Additionally, includes a partial refactor to consolidate Nexus and DBA business name search.
=> [184306224] Dakota Auto-Name Check During Formation

web/src/components/DeferredLocationQuestion.test.tsx, web/src/components/DeferredLocationQuestion.tsx, web/src/lib/cms/previews/TaskPreview.tsx, web/src/pages/tasks/[taskUrlSlug].tsx, web/test/pages/taskUrlSlug.test.tsx
Adds in fake user data with municipalities for CMS preview rendering
=> fix: [#184836745] generate municipality data for cms preview

shared/src/domain-logic/opportunityFields.ts, shared/src/legalStructure.ts, web/src/components/profile/ProfileOpportunitiesAlert.tsx, web/test/pages/profile.test.tsx
Trade Name businesses should not have a Business Effective Date label and should not have a Business Effective Date picker under Business Profile.
[185337472](https://www.pivotaltracker.com/story/show/185337472)
No changes to dependencies
Unit tests to check for:
1. does display date of formation question when legal structure is undefined
2. does not display date of formation question when legal structure is defined and has a trade name
3. does display date of formation question when legal structure is defined and does not have trade name
**Test as existing business with no legal structure defined**
1. Log in as an existing business with no legal structure defined.
2. Click on the business profile under your name in the top right hand corner
3. Label on top should show "Business Effective …
=> fix: [#185337472] Trade Name businesses should not have a Business Effective Date

web/src/components/filings-calendar/FilingsCalendarTaxAccess.test.tsx, web/src/components/filings-calendar/FilingsCalendarTaxAccess.tsx
In the tax filing calendar component, we are doing a tax filing lookup which was overwriting the municipality data without properly processing it. The fix was adding the processing portion to the component as well so it now doesn't get overwritten.
[#185471630](https://www.pivotaltracker.com/story/show/185471630)
=> fix: [#185471630] tax filing calendar lookup overwriting municipality

web/src/components/SelfRegLink.tsx, web/src/components/TaskHeader.tsx, web/src/components/auth/SignUpModal.tsx, web/src/components/dashboard/Roadmap.tsx, web/src/components/filings-calendar/FilingsCalendar.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.tsx, web/src/components/navbar/NavBarDesktop.tsx, web/src/components/navbar/NavBarPopupMenu.tsx, web/src/components/roadmap/MiniRoadmap.tsx, web/src/components/tasks/business-formation/name/DbaNameSearch.tsx, web/src/components/tasks/business-structure/BusinessStructureTask.tsx, web/src/lib/auth/signinHelper.test.ts, web/src/lib/auth/signinHelper.ts, web/src/lib/types/types.ts, web/src/pages/dashboard.tsx, web/src/pages/loading.tsx, web/src/pages/onboarding.tsx, web/src/pages/profile.tsx, web/src/pages/tasks/[taskUrlSlug].tsx
Continues the Ethan refactor work to stop directing fetching userData from the updateQueue
[184882700](https://www.pivotaltracker.com/story/show/)
As part of the refactor to allow for more than one business for users, we need to stop relying on the updateQueue's definition of userData and rely on the explicit userData object from the hook. This moves almost all remaining references to updateQueue.current() to use the hook
=> refactor: [#184882700] replace userData calls in profile and related files

web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.test.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.tsx
Bug fix to save business name in the tax access modal.
[#185473530](https://www.pivotaltracker.com/story/show/185473530)
=> fix: [#185473530] business name saved in tax access modal

content/src/fieldConfig/business-formation.json, web/src/components/tasks/business-formation/contacts/Addresses.test.tsx, web/src/components/tasks/business-formation/contacts/Addresses.tsx, web/src/components/tasks/business-formation/contacts/ContactsStep.tsx, web/src/components/tasks/business-formation/contacts/Members.tsx
This feature allows user who are Poppies or applicable Dakotas, of LP and Domestic Corporation business structures, to see an inline error (in place of previous banner alert) if there are no signers or if the signers checkbox is not clicked.
[#184198991](https://www.pivotaltracker.com/story/show/184198991)
N/A
N/A
N/A
=> Board directors signer error msg #184198991

content/src/roadmaps/license-tasks/verify-license-massage-therapy.md
Removing duplicate keys from `verify-license-massage-therapy.md` to fix `main`.
=> Remove duplicate meta-data keys from license

CHANGELOG.md, package.json
- chore: update env variable to disable landing page redirect
- chore(release): 5.22.1 [skip ci]
=> release 20230628

package.json, web/package.json, yarn.lock
=> fix: revert storybook-addon-pseudo-states back to v1

content/src/fieldConfig/profile.json
This is a continuation of #5963 based on feedback from a design review.
[184822307](https://www.pivotaltracker.com/story/show/184822307)
The design review asked for license names to be bolded. Names were not bolded because we were using an alternate style due to differences in the content.
There was business structure description override in place for foreign businesses. It appears as though this was in place for the business structure dropdown that was on the profile page. The PR removes those overrides.
=> Remove Business Structure Description overrides

CHANGELOG.md, package.json
- fix: enabling alert outage bar
- chore(release): 5.23.2 [skip ci]
=> release 20230711

content/src/roadmaps/add-ons/cannabis-conditional.json, content/src/roadmaps/add-ons/cpa.json, content/src/roadmaps/add-ons/daycare.json, content/src/roadmaps/add-ons/family-daycare.json, content/src/roadmaps/add-ons/petcare-license.json, content/src/roadmaps/add-ons/real-estate-appraisal-management.json, content/src/roadmaps/add-ons/real-estate-appraiser.json, content/src/roadmaps/task-dependencies.json, web/public/mgmt/config.yml, web/src/lib/async-content-fetchers/fetchTaskByFilename.ts, web/src/lib/roadmap/fixtures/task-dependencies.json, web/src/lib/static/loadTasks.test.ts, web/src/lib/static/loadTasks.ts, web/src/lib/types/types.ts
We had issues where we want a dropdown to pull from both the license task folder and task folder. Since this is not possible in the CMS we will simply have 2 drop downs but this requires some code and test and CMS changes outlined in this story. 
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185355437)
=> License tasks not rendering in cms 2 #185355437

web/src/components/FormationDateModal.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.tsx, web/src/components/onboarding/FieldLabelModal.tsx
=> fix: [#185647571] override default date of formation label in modal

CHANGELOG.md, package.json
* [[#185355437](https://github.com/newjersey/navigator.business.nj.gov/issues/185355437)] license task not rendering in CMS roadmap steps ([0d28061](https://github.com/newjersey/navigator.business.nj.gov/commit/0d28061a1aa4a147df83ff791f5423c724175936))
* [[#185355437](https://github.com/newjersey/navigator.business.nj.gov/issues/185355437)] license task not rendering in CMS, dependencies ([8137b5a](https://github.com/newjersey/navigator.business.nj.gov/commit/8137b5a16c2841e2af7e0b544919231e92fba4a0))
* [[#185629976](https://github.com/newjersey/navigator.business.nj.gov/issues/185629976)] show Unnamed Industry when missing legal structure in NavBar ([0d49276](https://github.com/newjersey/navigator.business.nj.gov/commit/0d492765e31d902818adf0190269af9df37ff5c3))
* …
=> chore(release): 5.23.5 [skip ci]

web/src/components/njwds-extended/UnStyledButton.tsx
Steps to Reproduce
Onboard as Poppy, Oscar or Dakota
Save a Tax ID to the userData
Navigate to business profile
Click show on the hidden Tax ID field
Expected
The plain text Tax ID should be displayed to the user so they can use it as a point of reference.
Current
The click triggers an save which then navigates the user back to dashboard not allowing the user to properly refer to the plain text Tax ID.
[#185617245](https://www.pivotaltracker.com/story/show/)
Added type button to button tag
1. Onboard as Poppy, Oscar or Dakota
2. Save a Tax ID to the userData
3. Navigate to business profile
4. Click show on the hidden Tax ID field
5. Expected - The plain text Tax ID should be displayed to the user so they can use it as a point of reference.
=> fix:[185617245] - fix tax id hide show on profile

web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx, web/src/components/tasks/business-formation/contacts/AddressModal.tsx, web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx
Whenever we are using the city, state, and ZIP Code inputs together in formation and error text renders - the text extends beyond the height of the red bar. I updated the logic so that the text renders within the red bar.
https://www.pivotaltracker.com/story/show/184978365
=> chore: [#184978365] fix grid for city, state, and zip in formation

web/src/components/Content.tsx, web/src/components/PureMarkdownContent.tsx, web/src/lib/cms/editors/greenBox.tsx, web/src/pages/mgmt/cms.tsx
We talked with content and to get around the weird bug where we have back to back green block and switching between markdown and causing them to combine. They preffered a more robust solution to using <br/>, so I added a block for the green text
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185355762)
Go into the app and add the code block via the markdown section 
see that the preview and such works as expected
I wanted to try and do try and do this with just an inner block and no outer block, but while it looks like its probably possible, not worth the effort
=> fix: [#185362965] green box bug fix

content/src/fieldConfig/business-formation.json, shared/src/formationData.ts, shared/src/test/formationFactories.ts, web/public/mgmt/config.yml, web/src/components/tasks/business-formation/business/IsVeteranNonprofit.tsx, web/src/components/tasks/business-formation/review/ReviewIsVeteranNonprofit.tsx, web/src/components/tasks/business-formation/review/ReviewNonprofitProvisions.tsx, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/components/tasks/business-formation/review/ReviewStep.tsx
- [chore: [#185153256] display Not Entered when board members question not entered](https://github.com/newjersey/navigator.business.nj.gov/pull/6138/commits/0907b553c1ed922c290574f50aacd9adfe4ffde9) Before this change, when board member question was undefined, it showed "No, ..." in the review text when it should have shown "Not Entered" (per conversation with Amanda)
- [chore: [#185153256] fix sentence display of provisions questions and remove unnecessary bold](https://github.com/newjersey/navigator.business.nj.gov/pull/6138/commits/ffa067d547ee2e9bd9d2714f8f1cc9e674092b44) Before this change, the sentences that ended with "in this form" / "in the bylaws" were squished against the sentence with no space in between. Also, the way bolding was done was inaccurate and unnecessary. I …
=> Formation refactoring - review section

web/src/components/onboarding/FieldLabelProfile.tsx, web/src/components/profile/ProfileField.tsx, web/src/pages/profile.tsx
Content is requesting we bold the label for home based in profile, it should not be bolded in other places like the dashboard.
=> chore: [#184606533] bold home based alt description text in profile

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/components/tasks/business-formation/contacts/Members.tsx, web/src/lib/utils/helpers.ts
Updated logic to account for the members field error label in the `Contact Step` of formation:
- For a non-profit: the error label needs to be Board of Trustees
- For a corporation: the error label needs to be Board of Directors  
[#185522114](https://www.pivotaltracker.com/story/show/185522114)
=> fix: [#185522114] Board of Directors and Trustees incorrectly labeled as Members in error banner

web/public/img/push-pin.svg, web/src/components/Content.test.tsx, web/src/components/Content.tsx, web/src/components/PureMarkdownContent.tsx, web/src/components/njwds-extended/Alert.tsx, web/src/lib/cms/editors/infoAlert.tsx, web/src/lib/cms/editors/note.tsx, web/src/pages/mgmt/cms.tsx, web/src/styles/components/alerts.scss
We wanted to add a Note block to the CMS capabilities
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185167184)
=> feat: [#185167184] add Note block to cms

content/src/fieldConfig/config.json, web/public/mgmt/config.yml, web/src/components/tasks/business-formation/name/NexusUnavailable.tsx, web/src/lib/domain-logic/getNavBarBusinessTitle.test.ts, web/src/lib/domain-logic/getNavBarBusinessTitle.ts
So for this bug we found 3 things
1. The Nexus DBA we found that the error alert when you have an invalid name and have to create a DBA is confusing -> change to info alert
2. Even if the name was unavailable and we put you into the DBA flow we still update the nave dropdown with the business name -> should be "unamed DBA"
3. After a DBA name is chosen the nav bar drop down still displays normal business name rather than DBA name -> dropdown shows DBA name
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185698190)
=> When adding the business in the start section bug

renovate.json
Disable Renovate bot auto merging.
=> Disable renovate bot automerge

web/src/pages/onboarding.tsx
JS variables used to build the page title were not getting processed correctly. This is an item that was noticed during an accessibility review meeting. 
[#185789032](https://www.pivotaltracker.com/story/show/185789032)
=> Fix onboarding page title string interpolation

web/src/components/onboarding/FieldLabelProfile.tsx
Fix alignment issue between locked labels and tool tip icon on profile.
[#185885539](https://www.pivotaltracker.com/story/show/185885539)
Moved margin-bottom to wrapper div.
=> Fix misaligned locked icons on profile

web/cypress/support/page_objects/onboardingPage.ts, web/src/components/MenuOptionSelected.tsx, web/src/components/MenuOptionUnselected.tsx, web/src/components/onboarding/IndustryDropdown.tsx, web/test/pages/onboarding/helpers-onboarding.tsx, web/test/pages/profile/profile-starting.test.tsx
Updated data test id in `MenuOptionSelected` and `MenuOptionUnselected` to a generic id because it's used in other places other than industry. And updated data test id of industryId using camel case format.
https://www.pivotaltracker.com/story/show/185894552
=> refactor: correct testId for industry dropdown and dropdown list

shared/src/test/formationFactories.ts, web/cypress/support/helpers/factories.ts, web/src/components/StateDropdown.test.tsx, web/src/components/StateDropdown.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/contacts/AddressModal.tsx, web/src/components/tasks/business-formation/contacts/Addresses.test.tsx, web/test/helpers/helpers-formation.tsx
Removed US Terrorities from state dropdown in address modal; US Terrorities are only removed for Poppy.
Added test for foreign state of formation dropdown: dropdown list does not include New Jersey. It was missing.
https://www.pivotaltracker.com/story/show/184749103
https://www.pivotaltracker.com/story/show/185894567
=> feat: [#184749103] remove US Territories from formation state dropdown

content/src/quick-actions/template.md, web/public/mgmt/config.yml, web/src/lib/search/cmsCollections.ts, web/src/lib/search/searchQuickActions.ts, web/src/lib/static/loadQuickActions.ts, web/src/lib/types/types.ts, web/src/lib/utils/markdownReader.ts, web/src/pages/mgmt/search.tsx
Add quick actions to cms.
From a content perspective, I use the template to generate content for quick actions.
Acceptance Criteria
Given than I am a Content team member
When accessing Netlify then I see a detail screen as described in this google doc
and it will be in a new collection
Template is built using this guide: https://docs.google.com/document/d/1qtbb3E6k7ZTx3H-4Lvvm_mkQxE3wAGQ6B9QJ_k-1khQ/edit
Template is added Netlify.
[#185424624](https://www.pivotaltracker.com/story/show/)
Update config.yml for cms to add quick actions
=> feat: [#185424624] add quick actions to cms

shared/src/states.ts, web/src/components/StateDropdown.test.tsx, web/src/components/StateDropdown.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/ForeignStateOfFormation.tsx
[185940288](https://www.pivotaltracker.com/story/show/#185940288)
=> fix: [#185940288] allow Outside of the USA selection for foreign state of formation

content/src/fieldConfig/business-formation.json, web/public/mgmt/config.yml, web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx
[185940232](https://www.pivotaltracker.com/story/show/#185940232)
=> fix: [#185940232] differentiate foreign and domestic legal type labels for formation

web/src/components/FieldEntryAlert.test.tsx, web/src/components/FieldEntryAlert.tsx, web/src/components/njwds-extended/Alert.tsx, web/src/components/profile/ProfileOpportunitiesAlert.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/components/tasks/business-formation/FormationField.tsx, web/src/components/tasks/business-formation/billing/BillingStep.tsx, web/src/components/tasks/business-formation/billing/PaymentTypeTable.tsx, web/src/components/tasks/business-formation/business/BusinessStep.tsx, web/src/components/tasks/business-formation/business/IsVeteranNonprofit.tsx, web/src/components/tasks/business-formation/business/MainBusiness.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressIntl.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx, web/src/components/tasks/business-formation/business/NonprofitProvisions.tsx, web/src/components/tasks/business-formation/business/PartnershipRights.tsx, web/src/components/tasks/business-formation/contacts/ContactsStep.tsx, web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx, web/src/components/tasks/business-formation/contacts/Signatures.tsx, web/src/styles/base/global.scss
- Adds links to the error alert in business formation driving to the fields lower on the page.
- Makes all `usa-links` blue
[#184432488](https://www.pivotaltracker.com/story/show/184432488)
[#184432499](https://www.pivotaltracker.com/story/show/184432499)
Componentize the alert used on profile to highlight opportunity fields, and implement in both the profile and in formation task.
Testing this in the UI requires triggering errors in formation and then clicking the generated links.
=> Add formation task error alert link

web/src/components/onboarding/OnboardingBusinessPersona.tsx, web/test/pages/onboarding/onboarding-owning.test.tsx, web/test/pages/onboarding/onboarding-shared.test.tsx
Make sector selection required for Oscar personas.
[185834867](https://www.pivotaltracker.com/story/show/185834867)
Users start out in GUEST_MODE, when sector selection is not a requirement. I updated the code such that when a user is an OWNING persona, then they will be in GUEST_MODE_OWNING: the point at which sector selection is a requirement.
=> fix: [#185834867] make sector required for Oscar personas

web/src/components/dashboard/OpportunityCard.test.tsx, web/src/components/dashboard/OpportunityCard.tsx, web/src/components/dashboard/SidebarCardsList.test.tsx, web/src/components/dashboard/SidebarCardsList.tsx, web/src/lib/utils/analytics-legacy.ts, web/src/lib/utils/analytics.ts
Added analytics to funding and certification opportunity cards. The analytics fire when the show or hide button within the card is clicked and when the accordion of the hidden card is opened.
I also updated the logic around when the hidden card accordion is rendered. Previously, it only relied on the displayCertifications prop, the conditional was updated. It should rely on both since it contains both opportunity cards.
https://www.pivotaltracker.com/story/show/184415884
=> feat: [#184415884] analytics added to cert and funding cards

api/src/domain/updateSidebarCards.test.ts, api/src/domain/updateSidebarCards.ts, shared/src/domain-logic/sidebarCards.ts, web/src/components/auth/NeedsAccountSnackbar.test.tsx, web/src/components/auth/NeedsAccountSnackbar.tsx, web/src/components/dashboard/SidebarCard.test.tsx, web/src/components/dashboard/SidebarCard.tsx, web/src/components/dashboard/SidebarCardFormationNudge.test.tsx, web/src/components/dashboard/SidebarCardFundingNudge.test.tsx, web/src/components/dashboard/SidebarCardRegisteredForTaxesNudge.test.tsx, web/src/components/dashboard/TwoTabDashboardLayout.test.tsx
Replace usages of raw strings when referencing Sidebar Card IDs with using a key from a defined object instead. Similar to our `ROUTES` pattern
=> refactor: define sidebarCard IDs in object type

web/src/components/tasks/business-formation/FormationField.tsx, web/src/components/tasks/business-formation/review/ReviewForeignCertificate.tsx, web/src/components/tasks/business-formation/review/ReviewIsVeteranNonprofit.tsx, web/src/components/tasks/business-formation/review/ReviewWillPracticeLaw.tsx
There were a couple instances where `ReactElement` was being incorrectly imported from the `rehype-react/lib` package. Nothing seems to have been broken, infact this was probably perfectly fine from a functional perspective.
Updated these 4 instances to import from the `react` library we use throughout our application.
Checked all other imports of `ReactElement` to verify they were coming from the correct library as well.
=> Fix imports to get ReactElement from react library

CHANGELOG.md, package.json
* [[#183536833](https://github.com/newjersey/navigator.business.nj.gov/issues/183536833)] inline error for missing signature for dakota nexus ([6baf460](https://github.com/newjersey/navigator.business.nj.gov/commit/6baf460220e4b5732709ba4237aaf5039e0fc964))
* [[#185834867](https://github.com/newjersey/navigator.business.nj.gov/issues/185834867)] add test coverage for change in persona and operating phase ([cc72856](https://github.com/newjersey/navigator.business.nj.gov/commit/cc72856cbf66ac75c340ab23d10eaec7d9a0b54d))
* [[#185834867](https://github.com/newjersey/navigator.business.nj.gov/issues/185834867)] make sector required for Oscar personas ([99feb36](https://github.com/newjersey/navigator.business.nj.gov/commit/99feb3629407ed54bbf78e9ecaa902995bf94867))
* …
=> chore(release): 5.28.0 [skip ci]

web/src/pages/onboarding.tsx, web/test/pages/onboarding/onboarding-shared.test.tsx
The switch to using `localUpdateQueue` and passing it around is because for the query string users, the updateQueue gets created earlier in the routing useEffect, and gets set to the global context state, but since React state updates are async, it was still undefined in state when we got down to the `completeOnboarding` function, which needs it to be defined in order to finish everything up. So we instead use the return value to reference the queue everywhere as the onboarding routing completes.
[#186025115](https://www.pivotaltracker.com/story/show/#186025115)
=> feat: [#186025115] skip onboarding for industry query strings without essential questions

CHANGELOG.md, package.json
* **deps:** update dependency uuid to v9.0.1 ([864c8fb](https://github.com/newjersey/navigator.business.nj.gov/commit/864c8fbc1711ee3a83f58bc3eebe9fb59197d101))
* **deps:** update material-ui ([eb6e2d7](https://github.com/newjersey/navigator.business.nj.gov/commit/eb6e2d79b47baec57b1b4f9fe9d98ca1e5ca3772))
* [[#184890110](https://github.com/newjersey/navigator.business.nj.gov/issues/184890110)] added displayname to MD files and made filename readonly in CMS ([585e319](https://github.com/newjersey/navigator.business.nj.gov/commit/585e319c1e165c35c51dd8c979a91c4c6c56cf5e))
* [[#184890110](https://github.com/newjersey/navigator.business.nj.gov/issues/184890110)] renamed slug widget to be writeoncereadonly widget as its more descriptive …
=> chore(release): 5.29.0 [skip ci]

content/src/roadmaps/license-tasks/notary-register.md, web/src/components/Content.test.tsx, web/src/components/Content.tsx, web/src/components/PureMarkdownContent.tsx, web/src/lib/cms/editors/infoAlert.tsx
The info alert block has 2 fields: Header and Body
Per our style guide, we'll only use the Body section
The ask:
A quick audit to ensure there is no content in any alert block header
To have the Header field removed to prevent errors in the future
ADO User Story
https://dev.azure.com/dillonsullivan/BFS/_workitems/edit/721
[184376697](https://www.pivotaltracker.com/story/show/)
1) Tested locally by trying to add a infoAlert and made sure the header wasnt there.
=> feat: [#184376697] Remove Header Text Field from Info Alert Block

content/src/fieldConfig/config.json, web/public/mgmt/config.yml, web/src/components/PageSkeleton.tsx, web/src/components/SkipToMainContent.test.tsx, web/src/components/SkipToMainContent.tsx, web/src/lib/utils/analytics-legacy.ts, web/src/lib/utils/analytics.ts
Create a new analytics event to fire `onClick` for "Skip to main content" button.
[184226156](https://www.pivotaltracker.com/story/show/184226156)
- Created an independent component
- Moved copy to config
- Added analytics event
- Added test to confirm event fires
=> Add analytics event to 'Skip to main content'

CHANGELOG.md, package.json
* [[#186136868](https://github.com/newjersey/navigator.business.nj.gov/issues/186136868)] remove esq from top banner ([2338b95](https://github.com/newjersey/navigator.business.nj.gov/commit/2338b9511ceaac2ac351d26f0df7ce40e1cc54c1))
=> chore(release): 5.31.0 [skip ci]

web/src/components/tasks/business-formation/business/ForeignStateOfFormation.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressUs.tsx
It was happening because of an erroneous extra call to `setFieldsInteracted` which was basically setting the field to interacted on mount and causing the API error to consider itself "resolved"
[#186165401](https://www.pivotaltracker.com/story/show/#186165401)
=> fix: [#186165401] correctly show API error for state dropdown in formation

CHANGELOG.md, package.json
* [[#186165401](https://github.com/newjersey/navigator.business.nj.gov/issues/186165401)] correctly show API error for state dropdown in formation ([f75474e](https://github.com/newjersey/navigator.business.nj.gov/commit/f75474e8f0a23d008cf110ce54caaee8dc6759fd))
* [[#184606443](https://github.com/newjersey/navigator.business.nj.gov/issues/184606443)] storybook updates for buttons ([956bcf4](https://github.com/newjersey/navigator.business.nj.gov/commit/956bcf468db525cfd650591017577c30945f6c7e))
* [[#185932056](https://github.com/newjersey/navigator.business.nj.gov/issues/185932056)] padding evening ([eefb211](https://github.com/newjersey/navigator.business.nj.gov/commit/eefb211351287fb65ffa46972adcf6c28e6206f5))
* [[#185932056](https://github.com/newjersey/navigator.business.nj.gov/issues/1 …
=> chore(release): 5.32.0 [skip ci]

web/src/components/navbar/NavBarPopupMenu.test.tsx, web/src/components/navbar/NavBarPopupMenu.tsx, web/src/components/tasks/business-formation/DbaFormationPaginator.tsx, web/src/components/tasks/cannabis/CannabisPriorityRequirements.tsx
A prior story revealed that this new helper function for window.open for a new tab could / shoudl be consolidated across the code base
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/186184213)
=> chore: [#186184213] consolidated instances of window.open

.circleci/config.yml
Update broken links driving to myNJ user profile in lower environments.
myNJ is moving from using a `.us` URL extension to `.gov`. We've made changes in our Cognito configuration to account for this. The team has not cutover to `.gov` yet. Those links redirect to `.us`. Additionally the profile link for `.gov` is not yet live. This will need to change when the cutover is complete. Expected 10 November 2023.
=> chore: update myNJ profile links

web/src/lib/data-hooks/useRoadmap.test.tsx, web/src/lib/data-hooks/useRoadmap.ts
Fix to rebuild roadmap if the steps are empty after discarding the process of starting a new business. 
[#186134528](https://www.pivotaltracker.com/story/show/186134528)
=> chore: [#186134528] empty roadmap bug when discarding new business

content/src/fieldConfig/business-structure-task.json, content/src/fieldConfig/ein.json, content/src/fieldConfig/naics-code.json, web/public/mgmt/config.yml, web/src/components/DeferredLocationQuestion.tsx, web/src/components/Header.tsx, web/src/components/dashboard/SidebarCardGeneric.tsx, web/src/components/data-fields/BusinessStructure.tsx, web/src/components/data-fields/NaicsCode.tsx, web/src/components/data-fields/NexusBusinessNameField.tsx, web/src/components/njwds-extended/UnStyledButton.tsx, web/src/components/tasks/EinDisplay.tsx, web/src/components/tasks/NaicsCodeDisplay.tsx, web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx, web/src/components/tasks/business-formation/review/section/ReviewSection.tsx, web/src/components/tasks/business-structure/BusinessStructureTask.tsx
- make EDIT/Remove button aria-labels more descriptive
- fix styling issue with NAICS Code Edit button (profile)
[186094556](https://www.pivotaltracker.com/story/show/186094556)
Navigate to page in-app, use inspector to check aria-label.
=> More descriptive EDIT button aria-labels

.circleci/config.yml, api/jest.config.ts, jest.config.mjs, jest.config.ts, jest.coverage.ts, jest.shared.ts, package.json, shared/jest.config.ts, web/jest.config.ts, web/test/pages/cms.test.tsx
These changes introduce `jest`-native sharding for tests rather than splitting using CircleCI, the latter of which is not reliable in more recent versions of the `cimg` CircleCI-based Docker image.
Additionally, these changes introduce two additional optimizations:
- Execute unit tests on CircleCI with eight test runners instead of five.
- Compile all tests using `swc` rather than `tsc` (via `ts-jest`), which results in about a 5-10% speedup on its own. (Except for `api`, which continues to require `ts-jest` for now.)
Some quality-of-life changes come through these changes as well:
- No more warnings from Jest about invalid configuration due to centralization for configuration within the root-level Jest configuration file.
`yarn test` should be unaffected by these changes.
`yarn …
=> chore: better split, parallelize, and execute Jest tests in CircleCI

package.json, web/.dependency-cruiser.js, web/package.json, web/src/components/ChecklistTag.tsx, web/src/components/tasks/LicenseStatusReceipt.tsx, yarn.lock
- Added `height` of 2px to the line under “Application Checklist Items”
- Updated permit status icons to those from Material UI
**Mobile**
- Aligned "Permit Status:” and the permit status
- Updated checklist tags to full width
- Updated checklist tags and item name to be left-align 
- Decreased padding between gray container and address/permit status from 40px to 16px
**Accessibility**
- Updated “Application Checklist Items” so it's not an `<h1>` 
- Updated the `<hr>` to be borders instead, so there is no inconsistent announcement as was happening with the `<hr>`
[#186263393](https://www.pivotaltracker.com/story/show/186263393)
=> fix: design-update-for-license-status-check-tab-#186263393

.gitignore, .vscode/settings.json, README.md, content/scripts/get_frontmatter_key.py, content/scripts/test_get_frontmatter_key.py, package.json, requirements.txt
Adding in a script to extract a given key from Markdown frontmatter, then added additional guidance for Python unit testing in the Readme.
You'll need to set up a virtual environment for Python. Follow the steps in the revised Readme.
To test, run `yarn test:python`.
=> chore: add script to extract front matter key from markdown files

api/src/client/ApiFormationClient.test.ts, api/src/client/ApiFormationClient.ts, api/src/libs/logWriter.ts
This switches the `Content-Type` header for all Formation API calls from `application/json`/`text/plain` to always using `text/plain`.
[#186774562](https://www.pivotaltracker.com/story/show/186774562)
This should be visible in dev right away. You should be able to form, where you cannot now.
I also added a dummy logger to help clean up our output when running tests. That was annoying me.
=> feat: [#186774562] switch to text/plain for all formation requests

web/src/components/navbar/NavBar.test.tsx, web/src/components/navbar/NavBarMobile.tsx
**Problem/Undesired Behavior**: 
The hamburger menu is visible, in the mobile layout, when a registered user is onboarding (a second business). 
**Solution**:
The hamburger menu is no longer visible, in the mobile layout, when a registered user is onboarding (a second business).
[#186620499](https://www.pivotaltracker.com/story/show/186620499)
=> fix: [#186620499] no nav menu for onboarding authenticated users

content/src/fieldConfig/business-formation.json
2 spaces were added to some pieces of content that were causing failures when attempting to match strings.
Ran a global search for `(?<=\S)  (?=\S)` to validate no other additional spaces in copy.
=> Fix failing unit tests on main

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/NexusFormation.test.tsx, web/src/components/tasks/business-formation/NexusFormationFlow.tsx
Added functionality so now Dakota Nexus businesses will remember their last visited page in the formation process. 
[#185001723](https://www.pivotaltracker.com/story/show/185001723)
Tracked down why formationData gets reset everyone time the business structure is changed to meet the second AC on the ticket. The functionality and the test lives in the userRouter files. We explicitly reset the formationData to an empty formationData object on business structure change.
=> feat: [#185001723] dakota nexus remembers formation page

api/.dependency-cruiser.js, api/package.json, api/serverless.ts, api/src/api/healthCheckRouter.test.ts, api/src/api/healthCheckRouter.ts, api/src/client/WebserviceLicenseStatusClient.test.ts, api/src/client/WebserviceLicenseStatusClient.ts, api/src/client/WebserviceLicenseStatusProcessorClient.test.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyHealthCheckClient.test.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyHealthCheckClient.ts, api/src/client/dynamics/fire-safety/DynamicsFireSafetyHealthCheckClient.test.ts, api/src/client/dynamics/fire-safety/DynamicsFireSafetyHealthCheckClient.ts, api/src/client/dynamics/fire-safety/DynamicsFireSafetyInspectionClient.ts, api/src/client/dynamics/housing/DynamicsHousingHealthCheckClient.test.ts, api/src/client/dynamics/housing/DynamicsHousingHealthCheckClient.ts, api/src/client/dynamics/license-status/DynamicsLicenseHealthCheckClient.test.ts, api/src/client/dynamics/license-status/DynamicsLicenseHealthCheckClient.ts, api/src/domain/types.ts, api/src/functions/express/app.ts, api/src/functions/express/index.ts, package.json, yarn.lock
The first of two health check-related pull requests. (See "Notes" later for more information.) This adds or modifies the following routes to the API for health checks:
| route | description |
| ----- | ------------ |
| `/health` | [Existing] Self-check to ensure the API is up and running. |
| `/health/webservice/license-status` | Establishes a connection to the Webservice server (for Hub License Status) to ensure the server is online and that we can successfully retrieve data. |
| `/health/dynamics/elevator` | Establishes a connection to the Dynamics server (for Muni Elevator Safety) to ensure the server is online and that we can successfully retrieve data. |
| `/health/dynamics/fire-safety` | Establishes a connection to the Dynamics server (for Muni Fire Safety) to ensure the server is …
=> feat: [#186657856] [#186741011] add new routes for health checks

web/src/components/roadmap/MiniRoadmapTask.tsx, web/src/styles/base/global.scss
[186316001](https://www.pivotaltracker.com/story/show/186316001)
I added a new span for this because we wanted the status read after the task name and not before (where it is visually). 
Navigate to any specific task and turn on your screen reader. When reading the name of the task in the mini-roadmap, it should now read the status as well.
=> feat: [#186316001] Add mini roadmap task status for screen readers

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/components/tasks/business-formation/getErrorStateForField.test.ts, web/src/components/tasks/business-formation/getErrorStateForField.ts, web/src/components/tasks/business-formation/name/BusinessNameStep.tsx
The business name error should no longer render as an `<Alert>`.
1. Remove the `<Alert>` that renders on the top in the Business Name Step.
2. Change the `<Alert>` that renders under the business name field in the Business Name Step to an inline error. 
[#184764052](https://www.pivotaltracker.com/story/show/184764052)
1. Leave the business name empty and move on to other steps in the Business Paginator and the business name no longer renders above (until you're on the Review Step).
2. Enter a business name that already exists and watch the error message render as an inline error.
=> feat: [##184764052] change business name error from alert to inline

.vscode/settings.json
As a part of renovate bot work I was trying to look at the contents of `node_modules`. This was hidden. Now it's not. Yes, I could have just done this on my own machine, but unless you know these directories are hidden, it's not entirely obvious that its controlled by workspace rules.
I also disabled the rulers. That's a personal preference. Generally speaking, I think rules like that should be set on a person's machine and not mandated by the code base. If we want lines to conform to a certain length that should be set in the linter so it actually enforces the rule regardless of the code editor.
=> Removing some VS Code workspace rules

CHANGELOG.md, content/src/roadmaps/tasks/sign-lease-food-truck.md, package.json
- fix: [#187064247] change sign-lease urlSlug so correct task renders for non-food truck industries
- chore(release): 2024.6.1 [skip ci]
=> release 20240216

web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx, web/src/components/tasks/business-formation/name/BusinessNameStep.tsx, web/src/lib/data-hooks/useBusinessNameSearch.ts
This feature affects the business name field when it is focused.
**Before**
- When the user entered a business name and validated it, if the name changed, AND
- When the user entered a business name and validated it, if the user deleted the name, the `AVAILABLE` alert persisted.
**Now**
- When the user enters a business name, validates it, and changes the name, the correct error, _`Confirm the availability of your business name.`_  fires.
- When the user enters a business name, validates it, and deletes the name, the correct error, _`Enter a business name to check availability.`_ fires.
[#186829051](https://www.pivotaltracker.com/story/show/#186829051)
1. Enter a business name and validate it. The `AVAILABLE` alert will render.
2. Change the business name. The error _`Confirm the …
=> feat: [#186829051] show error after business name validation when field is focused

api/src/client/ApiFormationHealth.ts, content/src/fieldConfig/business-formation.json, shared/src/dateHelpers.ts, web/src/components/tasks/business-formation/BusinessFormation.test.tsx, web/src/components/tasks/business-formation/BusinessFormation.tsx, web/src/components/tasks/business-formation/business/BusinessDateValidators.tsx, web/src/components/tasks/business-formation/business/FormationDate.tsx
Users in time zones outside ET run the risk of getting a business effective date set to something that breaks existing validation rules. In many places throughout our application we use `dayJs` to check the current date, but this ends up being relative to the user, not the state of New Jersey. This is a small fix that attempts to fix the most common area where this causes issues: the business effective date field in the business formation task.
[#185761403](https://www.pivotaltracker.com/story/show/185761403)
Utilize the timezone extension to check dates relative to the US Eastern time zone where New Jersey falls.
- Change machine timezone manually to something that will have a date different than US Eastern time. (I used Manila, Philippines as my location, but anything around the …
=> Set initial business effective date relative to NJ local date

web/src/components/data-fields/ForeignBusinessTypeField.tsx, web/test/pages/profile/profile-foreign.test.tsx
When officeInNJ is selected in profile, homebasedBusiness value gets set to false.
[#186781958](https://www.pivotaltracker.com/story/show/186781958)
=> fix: [#186781958] change homebasedBusiness value based on officeInNJ

api/src/api/guestRouter.test.ts, api/src/api/userRouter.test.ts, api/src/domain/annual-filings/getAnnualFilings.test.ts
Update `formationDate` from 3-1-2021 to 4-1-2021 to ensure tests don't fail in a given leap year.
[N/A](https://www.pivotaltracker.com/story/show/)
=> fix: update formationDate to account for leap year errors

web/src/pages/onboarding.tsx, web/test/pages/onboarding/onboarding-shared.test.tsx
Currently, if an authenticated user enters the application using the onboarding flow, their user data may get overwritten. This most commonly occurs when someone uses a link on the static site to re-enter the application. See "Starter Kits" page for common examples of this.
[#187133827](https://www.pivotaltracker.com/story/show/187133827)
Added a check that reroutes the user to the dashboard if they are authenticated but there is no userData. This operates on an assumption that there should never be an instance where the user will not have an account and empty userData in the database.
- Open application
- Complete onboarding so that user data is populated with a business
- authenticate (if not already)
- close all browser windows pointing to application
- attempt to enter the application …
=> Fix userData getting overwritten in onboarding flow

web/src/components/tasks/business-formation/BusinessFormation.test.tsx
[One of out unit tests failed](https://app.circleci.com/pipelines/github/newjersey/navigator.business.nj.gov/26249/workflows/984ca4a2-0ce9-40e1-9b69-836f8665c5dd) due to the time that it ran. The test was expecting the current date, but because of the time `getCurrentDate` returned a different value than `getCurrentDateInNewJersey`.
=> Fix: Change formation test to reference current date in NJ

content/src/fieldConfig/config.json, content/src/fieldConfig/dashboard-snackbars.json, web/public/mgmt/config.yml, web/src/components/TaskProgressCheckbox.test.tsx, web/src/components/TaskProgressCheckbox.tsx, web/src/components/TaskStatusChangeSnackbar.tsx, web/src/components/dashboard/DashboardAlerts.test.tsx, web/src/components/dashboard/DashboardAlerts.tsx
We had a weird case where the TaskProgress Checkbox triggers a redirect and thus we needed to use our redirect alerts instead of our page alerts. 
=> feat: [#186316063] revisions to account for the case where we want a snackbar after page redirect

api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.test.ts, api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.ts, api/src/client/dynamics/license-status/DynamicsLicenseStatusClient.test.ts, api/src/domain/types.ts, api/src/domain/user/updateLicenseStatusFactory.test.ts, api/src/domain/user/updateLicenseStatusFactory.ts
We display license data to users using multiple APIs as a source. Regardless of the data source, the logic should be as close to the same as possible. MLO currently returns the first matching license, but Dynamics will return an error if more than once license is found. This work removes that error and the associated check which results in a single license being returned.
[#187423161](https://www.pivotaltracker.com/story/show/187423161)
Simply removes the error, the associated check for multiple licenses, and updates the associated tests.
License data coming from the Dynamics API should still work. Possibly more license lookups will also result in data being displayed on the frontend.
This is not an exact way for us to display license data, but it is incrementally better than what …
=> Return first matching license from Dynamics license API

web/src/components/njwds-layout/SidebarPageLayout.tsx, web/src/pages/profile.tsx, web/src/styles/base/flex.scss
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/187476824)
I decided to do this using flex. 
The idea is we flex-shrink 0 on the nav section meaning it can't shrink below the size of its content. We set a flex grow 1 on this section so it will grow, and the right nav section we set a flex grow of 10 so it will grow much more and take more of the space.
=> feat: [#187476824] profile side navigation doesn't shrink to wrap

web/src/components/data-fields/tax-id/SingleTaxId.tsx, web/src/components/data-fields/tax-id/TaxId.tsx, web/src/components/tasks/TaxInput.tsx
Updates the error state styling for the NJ Tax ID task so that it is more consistent with other fields in the application.
**Before:**
**After:**
[#187458827](https://www.pivotaltracker.com/story/show/187458827)
Added the error bar, and removed an erroneous `createTheme()` call that was overriding our MUI theme.
=> feat: [#187458827] update save NJ Tax ID error state

CHANGELOG.md, package.json
* [[#187263740](https://github.com/newjersey/navigator.business.nj.gov/issues/187263740)] display one notRegistered/notRegisteredExisting card in for you section ([8cec9a2](https://github.com/newjersey/navigator.business.nj.gov/commit/8cec9a28083b9d730b79691db39a6ac9efad3b86))
* [[#187263740](https://github.com/newjersey/navigator.business.nj.gov/issues/187263740)] update dashboard URL in onboarding-as Cypress tests ([fb92a43](https://github.com/newjersey/navigator.business.nj.gov/commit/fb92a43518f3432186152166b9580e02f100bfac))
* [[#187432057](https://github.com/newjersey/navigator.business.nj.gov/issues/187432057)] manually build industry sync industries and fix license sync filepath ([2ea0cf6](https://github.com/newjersey/navigator.business.nj.gov/commit/2ea0cf6311f87452098f18d223c5df2 …
=> chore(release): 2024.15.0 [skip ci]

api/src/api/elevatorSafetyRouter.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyViolationsClient.test.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyViolationsClient.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyViolationsStatusClient.ts, api/src/client/dynamics/elevator-safety/types.ts, api/src/domain/types.ts, api/src/functions/express/app.ts, content/src/fieldConfig/elevator-registration.json, shared/src/elevatorSafety.ts, web/public/mgmt/config.yml, web/src/components/dashboard/DashboardOnDesktop.tsx, web/src/components/dashboard/DashboardOnMobile.tsx, web/src/components/dashboard/ElevatorViolationsCard.tsx, web/src/lib/api-client/apiClient.ts, web/src/pages/dashboard.tsx, web/src/styles/base/global.scss, web/src/styles/base/height-width.scss
Adds a card to the top of the dashboard if your saved Community Affairs address has violations.
[187553558](https://www.pivotaltracker.com/story/show/187553558)
I added a check to the dashboard and a prop to pass down to the `Mobile` and `Desktop` dashboard. The check will only be run if the user has a community affairs address
Go through account creation and indicate you own an elevator
Fill out the ElevatorRegistration task
Return to dashboard; if the test values have any violations, you will see them on the dashboard when returning there
(can use values in NJ QA Testing doc)
=> feat: [#187553558] add elevator violations card to dashboard if needed

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v134_added_planned_renovation_question_field.ts, content/src/fieldConfig/profile.json, content/src/roadmaps/add-ons/permanent-location-business.json, content/src/roadmaps/add-ons/planned-renovation.json, content/src/roadmaps/tasks/building-permit.md, shared/src/profileData.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/public/mgmt/config.yml, web/src/components/data-fields/RenovationQuestion.tsx, web/src/lib/roadmap/buildUserRoadmap.test.ts, web/src/lib/roadmap/buildUserRoadmap.ts, web/src/pages/profile.tsx, web/test/pages/profile/profile-shared.test.tsx
We wanted to have a profile question that rendered after you answered no to the home base business question call the planned rennovation question. 
If you answer no to the planned rennovation question it should render a "prepare for site rennovation" task on step 3 of your road map
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/185159231)
- Go to profile as Nexus or Starting user
- answer no to the home base business question
- you should see a second question appear as a result of this (the planned renovation question)
- answer yes to this 
- click save
- on step 3 of your road map you should see the "prepare for site renovation" task
=> feat: [#185159231] Renovation Task Conditional CTA display logic

api/src/domain/updateSidebarCards.test.ts, api/src/domain/updateSidebarCards.ts, content/src/display-content/roadmap-sidebar-cards/not-registered-up-and-running.md, shared/src/domain-logic/sidebarCards.ts, web/src/components/dashboard/SidebarCardGeneric.tsx, web/src/pages/dashboard.tsx, web/test/pages/dashboard.test.tsx
The `notRegisteredExistingAccount` nomenclature is misleading: At first glance, it appears as though we already know users have an account with OIT and are nudging users to register. This change allows us to see that the business is already `up-and-running` and the user needs to register to further access the benefits of Business.NJ.gov.
[#187626599](https://www.pivotaltracker.com/story/show/187626599)
=> chore: [#187626599] Update Not-Registered-Existing-Account Nomenclature 

web/src/components/dashboard/SidebarCard.tsx, web/src/components/dashboard/SidebarCardFormationNudge.tsx, web/src/components/dashboard/SidebarCardFundingNudge.tsx, web/src/components/dashboard/SidebarCardGeneric.tsx, web/src/components/dashboard/SidebarCardGoToProfileNudge.tsx, web/stories/Molecules/Cards/SideBarCards.stories.tsx
Small refactor opportunity I noticed while working on a renovate bot ticket. The `card` prop has all this data and most cases we're extracting them and passing them in as individual props.
=> Remove Redundancy in SidebarCardGeneric

web/src/components/njwds-layout/BackButtonForLayout.tsx
The "Back" button's clickable area fills the entire container width. Minimizing this to just wrap the content.
Before:
After:
=> Reduce "Back" button clickable area

api/src/domain/user/updateLicenseStatusFactory.test.ts, api/src/domain/user/updateLicenseStatusFactory.ts, content/src/roadmaps/industries/landscape-architecture.json, web/src/components/TaskPageSwitchComponent.tsx, web/test/pages/taskUrlSlug.test.tsx
Given I am a Poppy or Dakota and I am in the Landscape Architecture industry
When accessing the license task in the roadmap
Then I can check the status of my license with Consumer Affairs Dynamics system
[#187611847](https://www.pivotaltracker.com/story/show/187611847)
1. Access the site as a Poppy or Dakota as a Landscape Architecture (industry).
2. Click the Apply for a Landscape Architect License in the roadmap.
4. Enter the contact information for an expired business.
5. Go back to the dashboard.
6. Click the Deadlines and Opportunities card and complete the information in the modal.
7. Click the Funding Opportunities card.
The quick action tiles will appear on the dashboard.
=> feat: [#187611847] enable landscape architecture license

content/src/fieldConfig/tax-access-modal.json, web/public/mgmt/config.yml, web/src/components/filings-calendar/tax-access-modal/TaxAccessModal.test.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessModalBody.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepOne.tsx
Having some issues with header missing and various conditional text not being renders in our tax modals
[Replace with ticket_id](https://www.pivotaltracker.com/story/show/187652148)
As Oscar click on the show tax calendar or get access to tax calendar button. Go through modal steps and confirm that all drop downs have headers/titles, also that copy changes between steps. 
As Poppy or Dakota, form and then click the get access to tax calendar button. see that copy have Gov2Go text insides (see ticket for more details)
=> fix: [#187652148] resolved issues with see your tax due dates modals

.github/pull_request_template.md
Based on conversation I'm having with Anne in an internal ticket, I'm proposing a solution so that we don't have to see "replace with ticket_id" in our pull request descriptions.
This uses [closing keywords](https://docs.github.com/articles/closing-issues-using-keywords) even though they're not relevant to us as we use Pivotal Tracker, but this aligns us with other teams that use GitHub Issues.
=> chore: encourage ticket ID replacement

requirements.txt, scripts/release-helper.py
Our team follows a trunk-based development paradigm. This means that all work is merged into main when completed. This main branch is then deployed to the `dev` environment where acceptance is completed. In the case where the most recent accepted ticket is not the `HEAD` of the main branch, we need to cut a release behind that point in time. This is currently a manual process where we review the Pivotal Tracker backlog and git log to find a commit ID that is a safe point of release. You can read our [Release Process](https://docs.google.com/document/d/1fJok1iZYrIg8Os3TJ2f07d0JRJIbW5QSKZ0eQ8yqA8s) for a more indepth explanation.
This script intends to help automate the process of checking for a safe point of release.
This pull request resolves …
=> Add script to help manage releases

web/cypress/e2e/onboarding-as-foreign-business.spec.ts, web/cypress/support/page_objects/onboardingPageNew.ts
Updated Cypress Out of state None of the Above desktop and mobile Tests
This pull request resolves [#187166154](https://www.pivotaltracker.com/story/show/187166154)
This pull request resolves [#187166152](https://www.pivotaltracker.com/story/show/187166152)
Run Cypress tests for onboarding Foreign Business
All tests should pass
=> feat: [#187166154][#187166152] Cypress Out of state None of the Above desktop and mobile Tests

web/src/components/dashboard/ElevatorViolationsCard.tsx, web/src/components/njwds-extended/cta/SingleCtaLink.tsx, web/src/components/njwds-layout/ActionBarLayout.tsx, web/src/components/onboarding/OnboardingButtonGroup.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/components/tasks/business-formation/DbaFormationPaginator.tsx, web/src/components/tasks/business-formation/NexusFormationFlow.tsx, web/src/components/tasks/cannabis/CannabisApplicationQuestionsTab.tsx, web/src/components/tasks/cannabis/CannabisApplicationRequirementsTab.tsx, web/src/components/tasks/cannabis/CannabisPriorityRequirements.tsx, web/src/components/tasks/cannabis/CannabisPriorityTypes.tsx, web/src/pages/profile.tsx, web/stories/Molecules/action-bar/DefaultActionBar.stories.tsx, web/stories/Molecules/action-bar/MultiCTA.stories.tsx
https://www.pivotaltracker.com/story/show/187780095
I renamed the reverseInMobile prop to disableReverseOrderInMobile.
I reversed the rendering logic for this prop in the component so the reversing is ignored when optional prop is true
When used if original value was reverseInMobile=TRUE, I added the prop. If it was false I did not add the prop.
=> chore: rename reverseInMobile prop on action bar layout component

api/src/api/userRouter.ts, api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v136_add_user_account_creation_source.ts, content/src/fieldConfig/config.json, shared/src/businessUser.ts, shared/src/municipality.test.ts, shared/src/municipality.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/public/mgmt/config.yml, web/src/components/data-fields/AccountSetupForm.tsx, web/src/lib/domain-logic/routes.ts, web/src/pages/account-setup.tsx, web/src/pages/onboarding.tsx
Adds `businessMunicipality` and `utm_source` as query parameters for onboarding for presetting starting business municipality and account registration source respectively. Also adds a consent checkbox for contact sharing for investNewark source connection
This pull request resolves [#187765182](https://www.pivotaltracker.com/story/show/187765182).
Navigate to `localhost:3000/onboarding?businessMunicipality=Newark&utm_source=investNewark`
Complete onboarding
To verify preset business location, go to profile where Newark should be autoselected
To verify source, inspect userData or go to connect your account to MyNJ page- if `utm_source` is `investNewark` then additional consent question should appear.
You can change the municipality in the query parameter - it will only set a municipality …
=> feat: [#187765182] Add ability to prefill business location and user source from query params

CHANGELOG.md, package.json
* **deps:** update dependency @smithy/node-http-handler to v2.5.0 ([75c5725](https://github.com/newjersey/navigator.business.nj.gov/commit/75c572570561d9e02f4416f469d005ae03928002))
* **deps:** update dependency simple-oauth2 to v5.0.1 ([ca3100d](https://github.com/newjersey/navigator.business.nj.gov/commit/ca3100d3fd54dea6cdae42a64949719123dcadbe))
* [[#187166154](https://github.com/newjersey/navigator.business.nj.gov/issues/187166154)][[#187166152](https://github.com/newjersey/navigator.business.nj.gov/issues/187166152)] Cypress Out of state None of the Above desktop and mobile Tests ([082aedf](https://github.com/newjersey/navigator.business.nj.gov/commit/082aedfcf93a561e48ec73ba9bb982e593d458f5))
=> chore(release): 2024.19.0 [skip ci]

api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.ts, api/src/domain/license-status/searchLicenseStatusFactory.test.ts, api/src/domain/license-status/searchLicenseStatusFactory.ts, api/src/domain/user/updateLicenseStatusFactory.test.ts, api/src/domain/user/updateLicenseStatusFactory.ts, content/src/roadmaps/industries/health-club.json, web/src/components/TaskPageSwitchComponent.tsx, web/test/pages/taskUrlSlug.test.tsx
Enable health club license status check.
This pull request resolves [#187790624](https://www.pivotaltracker.com/story/show/187790624).
1. Access the site as a Poppy or Dakota as a Health Club (industry).
2. Click the `Register Your Business as a Health Club, Spa, Fitness Club, or Gym` task in the roadmap.
3. Enter the contact information for a business.
4. The license status will display for the business.
**NOTE:** There is no reinstatement action (anytime action) for this industry.
=> feat: [#187790624] enable health club license status check

web/src/components/dashboard/HideableTasks.tsx, web/src/components/njwds-extended/SecondaryButton.tsx
**Before:**
**After:**
This pull request resolves [#187415906](https://www.pivotaltracker.com/story/show/187415906).
Worked with Amanda to align on an implementation. This did require removing padding from the hide/show button.
- View application in mobile
- Using a business that has formed, go to dashboard
- scroll down to roadmap to see the Business Tasks heading and hide/show button
=> Keep hide/show roadmap button inline on mobile

web/test/pages/profile/profile-foreign.test.tsx, web/test/pages/profile/profile-helpers.tsx, web/test/pages/profile/profile-owning.test.tsx, web/test/pages/profile/profile-shared.test.tsx, web/test/pages/profile/profile-starting.test.tsx
https://www.pivotaltracker.com/story/show/187815961
There was an issue with how profile tests were loading municipalities leading to a mui autocomplete component error. We updated the test logic to load all possible municipalities from userData. 
Separately, we removed the logic previously added that prevented the failing of tests when the address in oscar profile was added.
=> chore: [#187815961] fix failing profile tests

api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.test.ts, api/src/client/dynamics/license-status/DynamicsLicenseApplicationIdClient.ts, api/src/domain/license-status/searchLicenseStatusFactory.test.ts, api/src/domain/license-status/searchLicenseStatusFactory.ts
1. Update Dynamics `licenseType` to match industry `licenseType`.
2.  Add logic and relevant test to account for the Health Club industry application IDs that do not end in `00`.
This pull request resolves [#187790624](https://www.pivotaltracker.com/story/show/187790624).
=> fix: [#187790624] update Health Club dynamics licenseType and add test for non-00 rgb numbers

api/src/client/ApiFormationClient.ts
This change allows us to make calls to GetFiling again, which now requires that all requests be sent as `text/plain`.
This pull request resolves [#187920482](https://www.pivotaltracker.com/story/show/187920482).
=> fix: [#187920482] requests to GetFiling should be text/plain

content/src/roadmaps/license-tasks/pharmacy-cds.md
For some reason when the `summaryDescriptionMd` field contains quotes the CMS flips out and won't render the content correctly. Removed the quotes, fixed the issue.
=> Update formatting in /license-tasks/pharmacy-cds.md

CHANGELOG.md, package.json
* [[#187754524](https://github.com/newjersey/navigator.business.nj.gov/issues/187754524)] update anytime action horizontal line to be aria hidden ([4e50df8](https://github.com/newjersey/navigator.business.nj.gov/commit/4e50df83c054f9a4e8e3b3ffe74624305f6deaf8))
* [[#187934580](https://github.com/newjersey/navigator.business.nj.gov/issues/187934580)] update investNewark consent copy ([803377c](https://github.com/newjersey/navigator.business.nj.gov/commit/803377c0094539497e9f02752218e14f612aa50c))
* update alertText copy to eliminate typo ([3935998](https://github.com/newjersey/navigator.business.nj.gov/commit/3935998833b7bcf03ae7127d10b779f84999f6c1))
* [[#186084933](https://github.com/newjersey/navigator.business.nj.gov/issues/186084933)] onboarding step header shoudl be read a single …
=> chore(release): 2024.21.0 [skip ci]

web/src/components/dashboard/anytime-actions/AnytimeActionPage.tsx, web/src/components/njwds-layout/PageSkeleton.tsx, web/src/pages/account-setup.tsx, web/src/pages/certification/[certificationUrlSlug].tsx, web/src/pages/dashboard.tsx, web/src/pages/filings/[filingUrlSlug].tsx, web/src/pages/funding/[fundingUrlSlug].tsx, web/src/pages/index.tsx, web/src/pages/licenses/[licenseUrlSlug].tsx, web/src/pages/loading.tsx, web/src/pages/onboarding.tsx, web/src/pages/profile.tsx, web/src/pages/roadmap.tsx, web/src/pages/tasks/[taskUrlSlug].tsx
Moves Navbar into the PageSkeleton component since it is always called from there
This pull request resolves [#187935188](https://www.pivotaltracker.com/story/show/187935188).
I poked around on several of the pages with the navbar and it looks good. I also went to pages which use PageSkeleton and not the navbar and that looks good too
=> refactor: [#187935188] move navbar calls into PageSkeleton as optional

web/src/components/data-fields/RadioQuestion.tsx, web/src/pages/profile.tsx, web/test/pages/profile/profile-foreign.test.tsx, web/test/pages/profile/profile-owning.test.tsx, web/test/pages/profile/profile-starting.test.tsx
Updates the non-essential question to only appear for poppies. This is because Oscars and Dakotas don't see the task that appears based on this. The non-essential question will be re-added once design is settled for those users
This pull request resolves [#187983571](https://www.pivotaltracker.com/story/show/187983571).
=> fix: [#187983571] remove elevator owning non-essential questions for nexus and owning users

web/src/components/njwds/Banner.tsx, web/src/styles/components/banner.scss, web/src/styles/main.scss
When we transitioned to mobile we were eliminating some text. This is a change meant to keep this other text in the mobile version
This pull request resolves [#186092881](https://www.pivotaltracker.com/story/show/186092881).
Go onto local, open in mobile, look at top banner and compare to designs and dev / prod to see how its different
=> feat: [#186092881] header banner, text lost during reflow

api/src/api/housingRouter.ts, api/src/client/dynamics/elevator-safety/DynamicsElevatorSafetyRegistrationStatusClient.test.ts, api/src/client/dynamics/housing/DynamicsHousingClient.test.ts, api/src/client/dynamics/housing/DynamicsHousingHotelMotelRegistrationClient.test.ts, api/src/client/dynamics/housing/DynamicsHousingHotelMotelRegistrationClient.ts, api/src/client/dynamics/housing/DynamicsHousingHotelMotelRegistrationStatusClient.ts, api/src/client/dynamics/housing/DynamicsHousingPropertyInterestClient.test.ts, api/src/client/dynamics/housing/DynamicsHousingPropertyInterestClient.ts, api/src/client/dynamics/housing/types.ts, api/src/domain/types.ts, api/src/functions/express/app.ts, content/src/fieldConfig/housing-registration.json, shared/src/housing.ts, web/public/mgmt/config.yml, web/src/components/TaskPageSwitchComponent.tsx, web/src/components/tasks/CheckHousingRegistrationStatus.tsx, web/src/components/tasks/HotelMotelRegistrationTask.tsx, web/src/components/tasks/HousingRegistrationStatusSummary.tsx, web/src/contexts/configContext.ts, web/src/lib/api-client/apiClient.ts, web/src/lib/types/types.ts
Adds a hotel/motel license status check, that functions similarly to the elevator registration status check
This pull request resolves [#188006371](https://www.pivotaltracker.com/story/show/188006371).
Create an account in the Lodging industry
Answer "Yes" to the hotel/motel non-essential question
See the task in Step 4
Use the Q/A testing doc to get addresses to test
=> feat: [#188006371] add housing hotel motel license status check

web/src/components/dashboard/SidebarCardsContainer.tsx, web/src/components/dashboard/SidebarCardsList.test.tsx, web/src/components/dashboard/SidebarCardsList.tsx, web/src/lib/domain-logic/sidebarCardsHelpers.test.ts, web/src/lib/domain-logic/sidebarCardsHelpers.ts
Switches the order of fundings and certifications in the For You column if the user signed up through an investNewark link. Also moves fundings from investNewark to the top of the fundings list for those users
This pull request resolves [#188049417](https://www.pivotaltracker.com/story/show/188049417).
Signup through this link: http://localhost:3000/onboarding?businessMunicipality=Newark&utm_source=investNewark
Sign up as an Oscar or a Poppy that advances to the up and running stage.
You should see fundings over certifications and the two investNewark fundings at the top of the funding list. The sorting of the rest of the list should remain unchanged.
Creating an account through any other means should not see behavior change
=> feat: [#188049417] Bubble investNewark fundings to top of For You column

web/public/mgmt/config.yml, web/src/lib/cms/fields/nospacefield.tsx, web/src/lib/cms/fields/writeoncereadonlynospacefield.tsx, web/src/pages/mgmt/cms.tsx
https://www.pivotaltracker.com/story/show/188081219
Add trim() to the nospace and the write once widgets. Note: the write once widget name was updated to state no spaces can be added.
=> chore: [#188081219] add trim to nospace and write-once-read-only widgets

web/src/components/onboarding/DevOnlySkipOnboardingButton.tsx
Given the point of the "Skip" button in the onboarding flow is supposed to help us get to our work faster, @FarazA22 added this in the #8193 work. This will automatically select C-corp as the biz structure when you use the "Skip" button in the onboarding flow.
Removed from that PR as feedback from @somabadri
=> Automatically select biz structure for dev skip-onboarding

web/src/components/dashboard/SidebarCardsContainer.tsx, web/src/lib/domain-logic/sidebarCardsHelpers.test.ts, web/src/lib/domain-logic/sidebarCardsHelpers.ts
Bubbles NJEDA fundings to top of For You column if user signed up with NJEDA link
This pull request resolves [#188108319](https://www.pivotaltracker.com/story/show/188108319).
Create an account with this link: http://localhost:3000/onboarding?utm_source=NJEDA
Proceed to being an Operating business
Should see NJEDA fundings above certifications in the For You Column
=> feat: [#188108319] Bubble NJEDA fundings to top of For You column

CHANGELOG.md, package.json
* [[#188073424](https://github.com/newjersey/navigator.business.nj.gov/issues/188073424)] industryOnboardingQuestions widget ([2d763a6](https://github.com/newjersey/navigator.business.nj.gov/commit/2d763a68f75601e1944744bebab8adf91d72afc6))
* **deps:** update dependency axios to v1.7.3 ([f5181ae](https://github.com/newjersey/navigator.business.nj.gov/commit/f5181ae6cf7f30a34ec49aca830acc274030eb34))
* [[#187432804](https://github.com/newjersey/navigator.business.nj.gov/issues/187432804)] add sitemap.xml ([65be529](https://github.com/newjersey/navigator.business.nj.gov/commit/65be52937fcad4c8f64f32bee3ea2d4ab4cd99f5))
* [[#187861895](https://github.com/newjersey/navigator.business.nj.gov/issues/187861895)] unify address error states …
=> chore(release): 2024.24.0 [skip ci]

content/src/fieldConfig/starter-kits.json, web/src/lib/domain-logic/routes.ts, web/src/lib/domain-logic/starterKitsContentModifiers.tsx, web/src/pages/_app.tsx, web/src/pages/starter-kits/[starterKitsUrl].tsx, web/src/pages/starter-kits/index.tsx
We wanted to genericize our industry starter kits page and make it so that we could have specific ones for each industry
This pull request resolves [#187792208](https://www.pivotaltracker.com/story/show/187792208).
Look at the ID's in industry.json
go to 
for example 
http://localhost:3000/starter-kits/generic
or 
http://localhost:3000/starter-kits/cosmetology
I did end up double checking that the code I wrote corresponds to the fields listed by content. 
The industry objects don't have dedicated slug fields but what content wanted corresponding 1 to 1 with the ID field. 
Also their is an acception case for generic here accounted for in the replacement of the token code. I think if it were more than 1 acception I would take a different approach but since its only the generic industry I'm …
=> feat: [#187792208] create industry specific starter kits landing pages

api/src/api/userRouter.test.ts, api/src/api/userRouter.ts, content/src/fieldConfig/profile.json, web/public/mgmt/config.yml, web/src/components/profile/ProfileAddressLockedFields.test.tsx, web/src/components/profile/ProfileAddressLockedFields.tsx, web/src/components/profile/ProfileNewJerseyAddress.test.tsx, web/src/components/profile/ProfileNewJerseyAddress.tsx, web/src/components/tasks/business-formation/BusinessFormation.test.tsx, web/src/components/tasks/business-formation/BusinessFormation.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/contacts/Addresses.test.tsx, web/src/components/tasks/business-formation/contacts/Members.test.tsx, web/src/components/tasks/business-formation/contacts/RegisteredAgent.test.tsx, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/components/tasks/business-structure/BusinessStructureTask.test.tsx, web/src/pages/profile.tsx, web/test/helpers/helpers-formation.tsx, web/test/pages/profile/profile-starting.test.tsx
As a Poppy user, when accessing my business profile, I should see a section for my business address.
This pull request resolves [#187003755](https://www.pivotaltracker.com/story/show/187003755).
1. Enter the site as a Poppy and select an industry.
2. Go to the business profile.
3. Complete the address fields and click the `Save` button.
4. Continue on to form your business.
5. In Step 2 `(Business)`, open the primary business address section. The address that you entered in the profile will populate here.
6. Before completing formation, change the address in the `Business Step` and go back to the profile. The change will persist.
7. Continue with forming your business.
8. Once formation is complete, the address fields in the profile will be disabled/read-only.
=> feat: [#187003755] add full address to poppy profile

shared/jest.config.ts, shared/src/industry.test.ts, shared/src/industry.ts, shared/src/test/factories.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-starting-business.spec.ts, web/cypress/support/helpers/helpers-onboarding.ts, web/cypress/support/helpers/helpers-select-industries.ts, web/src/components/CannabisLocationAlert.test.tsx, web/src/components/data-fields/Industry.test.tsx, web/src/components/data-fields/IndustryDropdown.tsx, web/src/lib/roadmap/buildUserRoadmap.test.ts, web/src/lib/utils/analytics-helpers.test.ts, web/src/lib/utils/starterKits.ts, web/src/pages/mgmt/search.tsx, web/test/factories.ts, web/test/pages/onboarding/helpers-onboarding.tsx, web/test/pages/profile/profile-shared.test.tsx
Currently, we are filtering disabled industries every instance we try to access the full list. This PR adds the filtering to remove industries where `{isEnabled: false}` in `industry.ts`. This is based on the env variable `SHOW_DISABLED_INDUSTRIES` and includes an override for testing purposes and the CMS search page.
This pull request resolves [#188117285](https://www.pivotaltracker.com/story/show/188117285).
=> Add filtering logic into industry.ts to remove disabled industries

api/src/db/migrations/migrations.ts, api/src/db/migrations/v140_modify_home_health_industry.ts, shared/src/userData.ts, web/src/lib/domain-logic/getLicenseCalendarEvents.ts
Fixes for users who still have their industry set to `health-care-services-firm-renewal`. This should ameliorate the dynamic import issue as well as another issue that pops up if their license data does not include licenses.
This pull request resolves [#188214352](https://www.pivotaltracker.com/story/show/188214352).
Ask @seidior for example user data to trigger this.
=> fix: [#188214352] add migration to solve relative import issue

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v142_add_domestic_employer_roadmap_section.ts, content/src/fieldConfig/config.json, content/src/fieldConfig/dashboard-defaults.json, content/src/roadmaps/steps.json, shared/src/userData.ts, web/public/mgmt/config.yml, web/src/components/Step.tsx, web/src/components/dashboard/DashboardOnDesktop.test.tsx, web/src/components/dashboard/DashboardOnDesktop.tsx, web/src/components/dashboard/DashboardOnMobile.test.tsx, web/src/components/dashboard/DashboardOnMobile.tsx, web/src/components/dashboard/helpers.ts, web/src/lib/data-hooks/useRoadmap.test.tsx, web/src/lib/data-hooks/useRoadmap.ts
SMEs reviewing the Domestic Employer industry experience requested some specific changes to the roadmap.
This pull request resolves [#188193453](https://www.pivotaltracker.com/story/show/188193453).
These changes largely use the "Domestic Employer" operating phase to determine what content to render. To handle the roadmap section copy changes I created a new section to be conditionally shown only for Domestic Employers.
Create a business of industry "Domestic Employer". After completing onboarding all of the changes should be immediately visible on the roadmap.
Be sure to test both desktop and mobile, as well as the mini-roadmap.
=> Updates to Domestic Employer experience based on SME feedback

CHANGELOG.md, package.json
* [[#185575919](https://github.com/newjersey/navigator.business.nj.gov/issues/185575919)] add WEB_BASE_URL env var, change favicon based on env ([40ba59d](https://github.com/newjersey/navigator.business.nj.gov/commit/40ba59d940c3ebebbf23c5bf538ac05878f01d97))
* [[#188079164](https://github.com/newjersey/navigator.business.nj.gov/issues/188079164)] Show the License Status Check in Reinstatement Anytime Action ([f3794b8](https://github.com/newjersey/navigator.business.nj.gov/commit/f3794b89a80eaee51917015c5f54547555250b3f))
* [[#188193453](https://github.com/newjersey/navigator.business.nj.gov/issues/188193453)] preserve domestic employer experience in guest mode ([9dfd102](https://github.com/newjersey/navigator.business.nj.gov/commit/9dfd102cb4838c7e381e4b75ef262b5aaecce203))
* …
=> chore(release): 2024.27.0 [skip ci]

yarn.lock
After encountering a build failure during the update of body-parser to version v1.20.3, the issue was identified as being caused by an old version of body-parser that remained in the dependency tree. 
This pull request resolves [#188260856](https://www.pivotaltracker.com/story/show/188260856).
- To resolve the issue, the outdated version was removed, ensuring that only the latest version (v1.20.3) is in use. This fix prevented lockfile modifications during installation, allowing the build process to complete successfully.
=> fix: [#188260856] resolve build Failure after dependency update (body-parser v1.20.3) 

content/src/roadmaps/steps-domestic-employer.json, content/src/roadmaps/steps.json, web/.dependency-cruiser.js, web/public/mgmt/config.yml, web/src/components/starter-kits/StepInfo.tsx, web/src/lib/data-hooks/useRoadmap.test.tsx, web/src/lib/data-hooks/useRoadmap.ts, web/src/lib/roadmap/fixtures/industries/domestic-employer.json, web/src/lib/roadmap/fixtures/steps-domestic-employer.json, web/src/lib/roadmap/roadmapBuilder.test.ts, web/src/lib/roadmap/roadmapBuilder.ts, web/src/pages/mgmt/search.tsx
Resolves an issue with number of roadmap steps being rendered on industry starter kits pages.
This pull request resolves [#188247287](https://www.pivotaltracker.com/story/show/188247287).
In #8534 I introduced a new roadmap section for the Domestic Employer industry. Initially I was filtering steps in the `useRoadmap` hook. This work creates a new `steps-domestic-employer.json` file that represents the roadmap sections only to be used for the Domestic Employer industry.
The previous approach caused an issue on the industry starter kits pages where an incorrect number of steps were being rendered for all industries.
**Before:**
**After:**
**Validating Starter Kits**
- Go to any given industry starter kit
- Scroll to the bottom of the page
- Validate that the correct number of …
=> Domestic-employer updates and starter kits page fix

content/src/fieldConfig/business-formation.json, web/cypress/support/page_objects/businessFormationPage.ts, web/public/mgmt/config.yml, web/src/components/dashboard/AnytimeActionDropdown.tsx, web/src/components/njwds-extended/HorizontalStepper.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.tsx, web/src/lib/utils/helpers.ts, web/src/styles/base/global.scss, web/src/styles/components/stepper.scss, web/test/helpers/helpers-formation.tsx
correct refocus behavior for formation stepper (rather than just scrolling to top, also refocuses on that specific tab step), 
(both via the stepper as navigation and the next / previous buttons at the bottom of the page)
page transitions announced when moving between pages with a screen reader (both via the stepper as navigation and the next / previous buttons at the bottom of the page)
Page descriptions enhanced
Page errors announced when pages have errors (page errors also focused when pages have errors and pages are moved too)
Keyboard only accessibility for stepper fixed
This pull request resolves [#186316380](https://www.pivotaltracker.com/story/show/186316380).
All testing begins by going to the formation page while logged in to access the stepper. 
All testing below should happen …
=> feat: [#186316380] correct refocus behavior for formation stepper and errors

content/src/roadmaps/nonEssentialQuestions.json, web/public/mgmt/config.yml, web/src/components/data-fields/non-essential-questions/NonEssentialQuestion.tsx
Enables embedding contextual links within non-essential questions
This pull request resolves [#188283234](https://www.pivotaltracker.com/story/show/188283234).
Converts non-essential question to Content.
This format `text|contextual-info-text` will be displayed in the CMS as a string, not as a contextual text. Right now this only affects a single NEQ but we might need a follow-up ticket so it properly displays in the CMS
1. Create new Poppy in health care industry
2. Go to profile to see non-essential question
=> feat: [#188283234] Enable contextual info in non essential questions

web/src/components/ModalZeroButton.tsx
We had a few situations where the modals had their close buttons as part of the header and were announced as part of a header (also unelectable by screen readers)
This pull request resolves [#186702387](https://www.pivotaltracker.com/story/show/186702387).
1. Go to formation step 3 contacts
2. turn on your screen reader (cmd + F5)
4. navigate to any of the add trustee, members or signers buttons (via control + option + right arrow)
5. Select this button using (enter)
6. This will trigger a modal to open
7.  (via control + option + right arrow) navigate through the dialog seeing that the header and close button are now distinct
8. Make sure no other random style changes happened
For some reason this element is wrapped in a group before it's diaglog, I investigated this quite a bit, as the …
=> feat: [#186702387] dialog close button isn't part of heading

web/src/components/tasks/business-formation/billing/BillingStep.tsx, web/src/components/tasks/business-formation/billing/FormationChooseNotifications.tsx, web/src/components/tasks/business-formation/business/BusinessNameAndLegalStructure.tsx, web/src/components/tasks/business-formation/contacts/Addresses.tsx, web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx, web/src/components/tasks/business-formation/contacts/Signatures.tsx, web/src/components/tasks/business-formation/name/BusinessNameStep.tsx
Headings in formation jumped from H1 - H3 in some places this is bad and those should go sequentially from H1 - H2
This pull request resolves [#186084688](https://www.pivotaltracker.com/story/show/186084688).
Go to the formation pages and go through each step
use a screen reader to navigate by heading (cmd + option + control + H  and cmd + option + control + shift + H)
And see the heading structure doesn't skip and seems logical
Alternatively use a chrome extension to see that the structure is sound
https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US
Download, then activate, then go to the structure tab
Lots of discussion about when and not using style overrides, but eventually decided that effort could be part of a later ticket and …
=> feat: [#186084688] fixed formation heading structure

web/src/scripts/licenseLoader.mjs
The Webflow `licenseSync` is currently missing the `displayname` field and is incorrectly writing `summaryDescriptionMd` when writing the `webflowId` to the task Markdown file.
This pull request resolves [#188333470](https://www.pivotaltracker.com/story/show/188333470).
1. Create a new license task
2. Run the Webflow license sync
3. Confirm the updated task file renders correctly in the CMS
4. If the new license task is a test file, delete from Webflow
This is a response to multiple requests from the content team to fix files that are rendering incorrectly.
=> Fixes to Webflow licenseSync

CHANGELOG.md, package.json
* [[#186702387](https://github.com/newjersey/navigator.business.nj.gov/issues/186702387)] dialog close button isn't part of heading ([0864e3f](https://github.com/newjersey/navigator.business.nj.gov/commit/0864e3fdcf2e6afa6b0684c68049dd389e0a9210))
=> chore(release): 2024.30.0 [skip ci]

README.md, jest.coverage.ts
This PR addresses the need to re-enable and clarify the process for running code coverage locally as part of identifying areas where new unit tests are needed.
This pull request resolves [#187315425](https://www.pivotaltracker.com/story/show/187315425).
Changes:
- Updated README.md:
Added instructions for running tests locally with coverage reports, specifying that coverage testing is for local use only and should not be run in CI.
- Updated jest.coverage.ts:
Adjusted coverageReporters settings to ensure the code coverage functionality is correctly configured and ready for use by developers.
=> chore: [#187315425] Re-enable code coverage

content/src/roadmaps/license-tasks/cds-healthcare.md, content/src/roadmaps/license-tasks/cemetery-branch.md, content/src/roadmaps/license-tasks/cemetery-certificate.md, content/src/roadmaps/license-tasks/landlord-registration.md, content/src/roadmaps/license-tasks/residential-health-care-facility-license.md, content/src/roadmaps/license-tasks/rooming-boarding-house-license.md, content/src/roadmaps/license-tasks/short-term-rental-registration.md
The Webflow licenseSync job was incorrectly formatting new license tasks. There is already a fix in place to address this going forward. This change is just to update the impacted files and add the missing `displayname` to the markdown file metadata. 
All updated content files should render in the CMS correctly and allow a CMS user to make updates.
Running the CMS proxy I have confirmed that all of these files can be updated via the CMS.
=> Add missing displayname to license-tasks

web/src/components/ModalOneButton.tsx, web/src/components/ModalZeroButton.tsx
We were having some screen reader NVDA specific issues with the dialogs reading all its content when you go into it, rather than letting you move through it after a brief summary. 
This pull request resolves [#186702387](https://www.pivotaltracker.com/story/show/186702387).
Lots of research
turns out that a modals that has a form is suppose to be this way, but a modal with only text content or like confirm or cancel modals are suppose to be read all at once without prompting. 
The pattern desired is to auto focus on the first clickable element (the close button), which will also read out a brief description of the modal and title as such. 
1. login and go to formation step 3 contacts
2. turn on your screen reader
3. if you click add member, a modal will popup
4. You should be focused on …
=> feat: [#186702387] close button revisions

api/.dependency-cruiser.js, api/jest.config.ts, api/scripts/migrateAllUserData.ts, api/src/db/DynamoUserDataClient.test.ts, api/src/db/DynamoUserDataClient.ts, api/src/db/dynamoUserDataMigration.test.ts, api/src/db/migrations/migrations.test.ts, api/src/functions/encryptTaxId/app.ts, api/src/functions/express/app.ts, api/src/functions/updateExternalStatus/app.ts, api/src/libs/logWriter.ts, scripts/remove_dynamodb_types.py
- Added logging to DynamoDB client and associated tests
- Adds scripts to test migrations against a dump of user data
This pull request resolves [#188171973](https://www.pivotaltracker.com/story/show/188171973).
- Added log groups in all AWS workspaces [here](https://github.com/newjersey/innovation-terraform/pull/145).
- Created log events in the DynamoDB client to alert for both successful migration upgrade and failure
- Created a script to strip DynamoDB syntax from a dump of user data
- Created a script to upgrade all users in a data dump
We were able to successfully upgrade all users through the current migration version with no errors. 
To recreate this locally you would need to get a dump of user data from a given cloud environment. Using the scripts added in this PR, you could then …
=> Test migrations against real user data & Add logging to migrations

web/src/components/PageFooter.tsx, web/src/components/njwds/Banner.tsx, web/src/styles/sections/footer.scss
we wanted our header icon to be decorational and ignore and we wanted our footer to read better on NVDA
This pull request resolves [#188057802](https://www.pivotaltracker.com/story/show/188057802).
This is basically impossible to test without using NVDA which I believe no dev has. So just make sure the code looks sane and you can visually confirm that it looks the same / operates the same locally
Not exactly sure why this works, tried many many things and experimented a lot but didn't really get to a clear reaons
=> feat: [#188057802] updated footer and header to align with NJ gov

content/src/mappings/callout-alerts.json, web/public/mgmt/config.yml, web/src/components/njwds-extended/Alert.tsx, web/src/components/njwds-extended/SnackbarAlert.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.test.tsx, web/src/contexts/configContext.ts, web/src/lib/search/cmsCollections.ts
Bascially we wanted the callout inline alerts to be grouped from the perspective of a screen reader
This pull request resolves [#186084688](https://www.pivotaltracker.com/story/show/186084688).
Go to a page with an inline calllout, theres one on step 2 of formation under one of the optional parts below, you do have to open it via the link on the right
use a screen reader to navigate through it and see that it has structure relative to the screen reader
Made a mapping for content such that they can modify these overrides and text completely. 
Also removed the role from this component it's parent handles this already
=> feat: [#186084688] callout alerts are now aria groups

web/src/components/tasks/LicenseTask.test.tsx
A flaky test in the LicenseTask tests would fail part of the time due to `useMockBusiness` generating a business that could not pass the test.
In this case, the test was looking for an missing information error. Sometimes the business generated wouldn't have any of that missing information.
This pull request resolves [#188496271](https://www.pivotaltracker.com/story/show/188496271).
I added:
```
formationData: generateFormationData({
formationFormData: generateFormationFormData({
addressLine1: "",
addressLine2: "",
addressZipCode: "",
}),
}),
```
to `useMockBusiness` to ensure that there will always be missing information to trigger the error for the test.
Run `yarn test LicenseTask` multiple times.
Make sure it passes every time (would recommend at least 3-5 times)
=> fix: [#188496271] Fix flakey License Task Test

api/serverless.ts, api/src/libs/migrateUserVersion.ts
This PR enhances the logging mechanism in the migrateUserVersion function, providing detailed logs for both successful migrations and errors. Additionally, the function is made accessible in the production and staging environments to facilitate smoother migrations and debugging.
This pull request resolves [#187578804](https://www.pivotaltracker.com/story/show/187578804).
- Improved logging for successful migrations and error handling.
- Updated the function access to be available in both production and staging environments.
=> chore: [#187578804] enhance log, make function accessible in prod

content/src/fieldConfig/config.json, web/src/components/njwds-extended/cta/CtaContainer.tsx, web/src/components/tasks/LicenseTask.tsx, web/src/components/tasks/MultipleDwellingRegistrationTask.tsx, web/src/components/tasks/RaffleBingoPaginator.tsx, web/src/styles/components/cta-container.scss, web/src/styles/main.scss
Update the CTA buttons on the License Task to match the current design. (After speaking with design, I also fixed the CTA buttons on the Multiple Dwelling Registration Task.)
This pull request resolves [#188507991](https://www.pivotaltracker.com/story/show/188507991).
I used this as an excuse to clean up some of CSS and utilize the already existing `CtaContainer`. This will hopefully make it easier to (a) keep styling consistent and (b) address some of the styling issues in Firefox.
The spacing for margins and padding are slightly different for FireFox than other browsers (like Chrome). Using `@-moz-document url-prefix()` allows the dev to adjust for those differences.
=> feat: [#188507991] License Task CTA Button Updates

web/src/lib/data-hooks/useUserData.ts, web/src/lib/utils/licenseStatus.test.ts, web/src/lib/utils/licenseStatus.ts
https://www.pivotaltracker.com/story/show/188414550
Logic was added to ensure the correct business was updated with license data. There can be a discrepancy with the currentBusinessId being one value in the db and another in the queue because the user switched their business.
=> fix: [#188414550] license data for correct business is updated when multiple businesses exist

api/src/api/licenseStatusRouter.test.ts, api/src/api/licenseStatusRouter.ts, api/src/client/WebserviceLicenseStatusProcessorClient.test.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v146_remove_haserror_field_from_licensedetails.test.ts, api/src/db/migrations/v146_remove_haserror_field_from_licensedetails.ts, api/src/domain/types.ts, api/src/domain/user/updateLicenseStatusFactory.test.ts, api/src/domain/user/updateLicenseStatusFactory.ts, shared/src/license.ts, shared/src/userData.ts, web/src/components/tasks/LicenseTask.test.tsx, web/src/components/tasks/LicenseTask.tsx, web/src/lib/api-client/apiClient.test.ts, web/src/lib/api-client/apiClient.ts
User Story
As a user that has conducted a license status check search, I want to be informed that no license has been found immediately when viewing the task and the error message persists until the information is updated.
Acceptance Criteria
Given a license search have been conducted
and the check did not find a license
when viewing the license task
then the 'License could not be found..." warning is rendered in the task
and the error persists
dev note: the license status of UNKNOWN is used to trigger the alert, the status changes should be handled in the backend
This pull request resolves [#188443179](https://www.pivotaltracker.com/story/show/188443179).
=> feat: [#188443179] Unsuccessful Business Address & Zipcode License Check Immediate Error State

web/src/components/tasks/CheckLicenseStatus.tsx
Make labels in check license status form bold. 
This pull request resolves [#188448107](https://www.pivotaltracker.com/story/show/188448107).
=> feat: [#188448107] Update License task inputs to match rest of product

CHANGELOG.md, package.json
* [[#188595606](https://github.com/newjersey/navigator.business.nj.gov/issues/188595606)] Electrologist License Status Check, Renewal Events & Reinstatement Quick Actions (MLO) ([b6abf51](https://github.com/newjersey/navigator.business.nj.gov/commit/b6abf5199882cb06347290b19bb5d8e52038cb4f))
=> chore(release): 2024.36.0 [skip ci]

api/src/db/migrations/migrations.test.ts, api/src/db/migrations/v102_rename_tax_registration_nudge.ts, api/src/db/migrations/v103_change_tax_calendar_view_default.ts, api/src/db/migrations/v104_add_needs_nexus_dba_name_field.ts, api/src/db/migrations/v105_add_pet_care_essential_question.ts, api/src/db/migrations/v106_add_pet_care_housing_essential_question.ts, api/src/db/migrations/v108_add_business_name_search_to_formation_data.ts, api/src/db/migrations/v117_add_onboarding_nonprofit.ts, api/src/db/migrations/v122_remove_welcome_and_welcomeupandrunning_sidecards.ts, api/src/db/migrations/v123_remove_account_creation_sidecards.ts, api/src/db/migrations/v135_use_interstate_logistics_and_transport_fields.ts, api/src/db/migrations/v136_add_user_account_creation_source.ts, api/src/db/migrations/v137_add_employment_placement_personal_types.ts, api/src/db/migrations/v138_multi_license_support.ts, api/src/db/migrations/v139_own_carnival_rides.ts, api/src/db/migrations/v141_sync_migrated_and_newly_created_users.ts, api/src/db/migrations/v142_add_domestic_employer_roadmap_section.ts, api/src/db/migrations/v143_add_property_type_and_rental_unit_count.ts, api/src/db/migrations/v144_add_raffle_bingo_games.ts, api/src/db/migrations/v145_add_traveling_circus_or_carnival.ts, api/src/db/migrations/v146_remove_haserror_field_from_licensedetails.ts, api/src/db/migrations/v147_remove_nonprofit_onboarding_field.ts, api/src/db/migrations/v148_add_vacant_building_field.ts, api/src/db/migrations/v95_added_new_tax_calendar_state.ts
Modified a number of the migration generators to reference the correct version number, and added a test to assert that the global var `CURRENT_GENERATOR` is actually looking at the current generator function.
All tests associated with migration information should still pass. There's no manual check needed for this.
Initially wanted to add a test for the `CURRENT_GENERATOR` because updating this value was being overlooked in migration upgrades. Modified the rest of the files just for accuracy. Nothing about this was actually breaking functionality.
This is just cleanup.
=> Cleanup migration generators

README.md, api/scripts/dynamodb-local.sh
Update the DynamoDB download link to the new CloudFront distribution URL to support HTTPS downloads and because the AWS folks have asked us to do so nicely.
Update the Readme to reflect the updated Java requirements.
This pull request resolves [#188640176](https://www.pivotaltracker.com/story/show/188640176).
=> chore: [#188640176] update dynamodb download link [skip ci]

web/src/pages/profile.tsx, web/test/pages/profile/profile-owning.test.tsx
Adds in criteria for the vacant building non essential question to appear to logged in users owning, removed the question from the starting profile because it is now impossible for it to render there
This pull request resolves [#188599283](https://www.pivotaltracker.com/story/show/188599283).
1. Create an Oscar user while signed into MyNJ in the real estate industry sector
2. You  should see the non-essential question in the profile
=> fix: [#188599283] Have vacant building question appear for signed in owning users

CHANGELOG.md, package.json
* [[#188599283](https://github.com/newjersey/navigator.business.nj.gov/issues/188599283)] Correct anytime action dropdown categories ([370a811](https://github.com/newjersey/navigator.business.nj.gov/commit/370a81146727461cee1323f1934e14edfd9c57ed))
* [[#188599283](https://github.com/newjersey/navigator.business.nj.gov/issues/188599283)] Enable vacant building question for up and running Poppies ([7c4158a](https://github.com/newjersey/navigator.business.nj.gov/commit/7c4158a72b9b24551dc9e34c734f7fd39af32a47))
* **deps:** update dependency axios to v1.7.8 ([#9176](https://github.com/newjersey/navigator.business.nj.gov/issues/9176)) ([13e9dd8](https://github.com/newjersey/navigator.business.nj.gov/commit/13e9dd8be3fa7346d1266831332cdd3d778a3895))
* **deps:** update dependency express to …
=> chore(release): 2024.37.0 [skip ci]

content/src/fieldConfig/business-formation.json, web/public/mgmt/config.yml, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/FormationDate.tsx, web/src/components/tasks/business-formation/business/SuffixDropdown.tsx
Dakota Corporations Formation Task - Certificate of Good Standing Error Prevention - Business Designator Copy
Dakota Corporations Formation Task - Certificate of Good Standing Error Prevention - Business Designator Copy
This pull request resolves [#188595628](https://www.pivotaltracker.com/story/show/188595628).
When I am a Dakota Coporation  and I am forming a business I want to see the new copy of "Must Match Certificate of Good standing" to be under the Business Designator label and the "mm/dd/yy" to be under the effective date.  To do this I used a Grid component with the direction of the grid based on if it is a dakota corporation, it uses a column direction.  If it is anything else it will be a row direction.  This fix is implemented in the Suffix dropdown and the formation date …
=> feat: [#188595628] Dakota Corporations Formation Task - Certificate of Good Standing Error Prevention - Business Designator Copy

api/src/functions/express/index.ts
Serverless config change to expose the `/api/users/emailCheck` endpoint. Without this change, I was getting a blanket `401`. We need to be able to call this unauthorized.
This pull request resolves [#188540248](https://www.pivotaltracker.com/story/show/188540248).
Validated by deploying to test.
=> fix: [#188540248] add check email endpoint to serverless config

content/src/fieldConfig/business-structure-prompt.json, web/src/components/njwds-extended/Alert.tsx, web/src/components/tasks/business-structure/BusinessStructureTask.tsx, web/src/components/tasks/business-structure/LegalStructureRadio.tsx
basically we wanted screen readers getting errors on the business structure selection page to get refocused to the error at the top instead of just staying at the bottom of the page. 
This pull request resolves [#187466951](https://www.pivotaltracker.com/story/show/187466951).
Used the scroll to top and focus function I made early which is awesome
Go to the business structure task with a new business. Turn on a screen reader, save without selecting and see that scrolls  to top and reads out information
This was a real weird story in some ways. 
I kinda had a set of weird decision to make in terms of functionality here. I ended up deciding to focus the error group because if I focus any content in the group itself it starts getting super verbose and redundant reading out the group and the …
=> feat: [#187466951] business structure task, error is now auto scroll and screen reader accessible

web/cypress/e2e/auto-tax-filing.spec.ts, web/cypress/support/helpers/helpers.ts, web/cypress/support/page_objects/dashboardPage.ts, web/src/components/Task.tsx, web/src/components/dashboard/SectorModal.test.tsx, web/src/components/dashboard/SectorModal.tsx, web/src/components/dashboard/SidebarCardFundingNudge.test.tsx, web/src/components/dashboard/SidebarCardFundingNudge.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.test.tsx, web/src/components/filings-calendar/tax-access-modal/TaxAccessStepTwo.tsx, web/src/lib/taxation/helpers.ts
If a user inputs both the business name and the tax id, it will automatically file for the tax calendar when setting the business status `UP_AND_RUNNING`.
Added a wiremock in order get around the need to access the api. for a working taxid that will return a calendar, use `1234567890\098`
This pull request resolves [#188507862](https://www.pivotaltracker.com/story/show/188507862).
Create a new business. Add a business name and the tax id `123456789\098` (to satisfy the wiremock) this will return a pending tax calendar.
=> feat: [#188507862] Automatic Tax Calendar Check

api/src/db/DynamoUserDataClient.test.ts, api/src/db/migrations/v150_remove_needs_nexus_dba_name.ts, api/src/db/migrations/v151_extract_business_data.test.ts, api/src/db/migrations/v151_extract_business_data.ts
This change adds userId to the businessesObject to make querying easy in the future. 
This pull request resolves [#188172536](https://www.pivotaltracker.com/story/show/188172536).
- updated the test for migration.
=> fix: [#188172536] add owningUser to v151 migration

package.json, web/package.json, yarn.lock
This ticket resolves a missing dependency related that brings in the missing properties `checkA11y` and `injectAxe`. 
This pull request resolves [#187166104](https://www.pivotaltracker.com/story/show/187166104).
=> fix: [#187166104] add dependency for cypress accessibility feat

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v154_add_business_operating_length_and_nonprofit_status.ts, content/src/fieldConfig/fundings-onboarding.json, shared/src/profileData.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/public/mgmt/config.yml, web/src/components/ModalOneButton.tsx, web/src/components/ModalZeroButton.tsx, web/src/components/dashboard/OpportunityCard.tsx, web/src/contexts/configContext.ts, web/src/lib/auth/signinHelper.ts, web/src/lib/domain-logic/routes.ts, web/src/pages/fundings.tsx, web/test/pages/fundings.test.tsx
- Adds a new onboarding flow with fundings prominently featured
This pull request resolves [#188666282](https://www.pivotaltracker.com/story/show/188666282).
- In a new window/incognito window, navigate to localhost:3000/fundings
- Answer the onboarding questions. If you don't answer either radio question, there will be a popup with a request to finish the onboarding questions
- Click save
- You should be able to click on any funding. Clicking "Back" on the funding or the big button at the top should take you back to the Oscar onboarding sections
=> feat: [#188666282] add new onboarding page for fundings

api/src/api/userRouter.test.ts, api/src/api/userRouter.ts
Prevents the automatic license check from firing if the business has a formation address but no business name.
This pull request resolves [#188671705](https://www.pivotaltracker.com/story/show/188671705) and may resolve [#188820162](https://www.pivotaltracker.com/story/show/188820162).
When pulling user data from the database, we initiate a check for license data if the user has 1) previously queried for license data and successfully returned results or 2) the user has provided a business address. In the 2nd case, when the business does not have a name we run into a bug during the RGB query.
The first step of the RGB license search is to make an API request to get all of the business IDs in the system that have a name _like_ the one we provide. In the case of an empty string, the system …
=> Prevent license auto lookup with empty business name

CHANGELOG.md, package.json
* [[#188666282](https://github.com/newjersey/navigator.business.nj.gov/issues/188666282)] add url and additional filtering ([a2f342b](https://github.com/newjersey/navigator.business.nj.gov/commit/a2f342bab45bfb5b200629a075cea3be0d0a969d))
* [[#188826997](https://github.com/newjersey/navigator.business.nj.gov/issues/188826997)] check router.isReady in onboarding ([4f7e5e3](https://github.com/newjersey/navigator.business.nj.gov/commit/4f7e5e31c51039f71d8dc917be8c546047d053b8))
=> chore(release): 2025.2.1 [skip ci]

web/src/components/LoginEmailCheck.tsx, web/src/components/navbar/mobile/NavBarMobileWrapper.tsx, web/src/styles/sections/login-page.scss
This makes 3 minor updates from design review:
- Hides an `hr` element from screen readers (purely aesthetic, adds noise for SRs)
- Fixes a background color issue with the mobile nav on `/login`
- Fixes a text color issue
This pull request resolves [#188838885](https://www.pivotaltracker.com/story/show/188838885).
These are purely visual changes
=> feat: [#188838885] login page design review updates

web/src/components/LoginEmailCheck.tsx, web/src/components/njwds-extended/UnStyledButton.tsx, web/src/lib/auth/signinHelper.ts
We were having an issue when going to the login page from the webflow site, and then navigating to onboarding via the link on the login, onboarding would break. Specifically it would be on onboarding rather than onboarding page 1 (designated via a query param)
This pull request resolves [#188838423](https://www.pivotaltracker.com/story/show/188838423).
Lots of logging and trying to figure out whey useEffects aren't triggering as desired and figuring out how to get them to work
1. try going directly to /login,
2. click the first link (Sign up and link your myNewJersey account)
3. navigation through onboarding to dashboard
(the same steps will not work on prod)
1. go to landing
2. click login button in nav bar
3. click the first link (Sign up and link your myNewJersey account)
4. navigation …
=> fix: [#188838423] from login page to onboarding working again

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v155_add_user_id_and_version_to_business.test.ts, api/src/db/migrations/v155_add_user_id_and_version_to_business.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/src/lib/domain-logic/addAdditionalBusiness.test.ts, web/src/lib/domain-logic/addAdditionalBusiness.ts, web/test/pages/onboarding/onboarding-additional-business.test.tsx, web/test/pages/profile/profile-starting.test.tsx
Added a migration to add missing fields (`userId`, `version` & `versionWhenCreated`) in the `business` object from previous migrations.
Review the migrations from `v151` onwards to ensure that this migration fixes any missing fields.
=> fix: [#188844549] add userId, versionWhenCreated and version to business object

web/src/lib/domain-logic/routes.ts, web/src/lib/utils/onboardingPageHelpers.ts, web/src/pages/onboarding.tsx, web/test/pages/onboarding/onboarding-shared.test.tsx
This pull request resolves https://www.pivotaltracker.com/story/show/188843468
This ticket introduces a sector-based query that allows users to autocomplete onboarding. By accessing a URL path containing a sector ID query, guest mode users can automatically complete the onboarding process.
Previously, we were unnecessarily creating new user data at random. However, this is redundant due to our existing update queue functionality. The queue effectively maintains the latest version of the data. As long as new values continue to be queued, there should be no issues. This ticket also includes a cleanup to remove the redundant data creation.
The steps work by navigating to the onboarding path with a sector query parameter included. For example - …
=> feat: [#188843468] implement sector query in onboarding

web/cypress/e2e/auto-tax-filing.spec.ts, web/cypress/support/helpers/helpers-select-industries.ts, web/cypress/support/helpers/helpers.ts
This PR addresses some of the flakiness in our Cypress tests through the following:
- Added a `randomNonHomeBasedNonDomesticEmployerIndustry`, as "Domestic Employer" businesses were sometimes the random seed, and that is not a business type that would yield the elements these tests are expecting.
- Added a retry in the first test suite to workaround a race condition. (A new ticket was created to address the race condition)
This pull request resolves [#188895388](https://www.pivotaltracker.com/story/show/188895388).
=> fix: filter out domestic employers for auto-tax-filing e2e tests

web/public/mgmt/config.yml
The CMS uses a widget called a `relation` that is used to create a dropdown or multi-select with values from other collections. By default, the `relation` will show 20 values. The user can search for additional items not displayed in the first 20, but this is not always the most discoverable. Setting this value for all widgets should mitigate any future confusion.
This pull request resolves [#188924188](https://www.pivotaltracker.com/story/show/188924188).
Set `options_length: 500` for all relations in the CMS config file.
Look for a collection that has a relation, all items from the source collection should be visible.
Example:
Look at industry roadmaps. The "Non Essential Questions" section is populated by a multi-select relation. This was the collection that spawned [this conversation …
=> Set options_length: 500 for all relation widgets in the CMS

api/wiremock/__files/webservice-license-status-response.json, content/src/license-calendar-events/oos-pharmacy.md, content/src/roadmaps/add-ons/oos-pharmacy.json, content/src/roadmaps/license-tasks/oos-pharmacy-registration.md, shared/src/license.ts, web/src/components/TaskPageSwitchComponent.tsx, web/src/lib/roadmap/buildUserRoadmap.test.ts, web/src/lib/roadmap/buildUserRoadmap.ts, web/test/pages/taskUrlSlug.test.tsx
Replaces the pharmacy registration license task with a license task specific to out-of-state pharmacies on the roadmap for Dakota Nexus users. In this task, users can also check the status of their license and get events on their calendar for when their license expires and their renewal deadline.
This pull request resolves [#188814053](https://www.pivotaltracker.com/story/show/188814053).
- Enabled license search by adding it to the list in [/TaskPageSwitchComponent.tsx](https://github.com/newjersey/navigator.business.nj.gov/pull/9642/files#diff-596ac947da21161feaebaaa63b7ab72d2dab81af96826f7af5141bcfd365012f)
- Added objects to the Wiremock response to allow us to test the license check locally.
- Added the licenseName field to the registration and renewal md files.
- Created an add-on …
=> feat: [#188814053] add out of state pharmacy license task

.husky/commit-msg
Updated pre commit script to track both pivotal and ADO id's 
This pull request resolves [#8681](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/8681).
Go onto this branch and install
Then try and commit with a variety of manual testing cases
This is correct feat: [#123455 AB#1234] updated some cool stuff
So trie variations that are correct and not correct, try unknown prefixes, try weird ID's, try removing the AB or the # or the number or the message after or whatever.
=> Updated pre-commit scripts to track both Pivotal and ADO tickets

api/src/db/DynamoDataClient.test.ts, api/src/db/DynamoDataClient.ts, api/src/db/DynamoUserDataClient.ts
This PR updates the `getUsersWithOutdatedVersion`  to use current_version dynamically instead of a fixed value. This ensures that the query always reflects the correct version during deployments, including weekend migrations.
Previously, the query used a hardcoded version, which could lead to outdated checks and inconsistent migrations. This update ensures that only users with an outdated version are correctly identified and migrated
Changes:
- Updated the query in getUsersWithOutdatedVersion to use the latestVersion parameter dynamically.
- Improved logging by including current_version for better monitoring.
- Added a unit test to verify that the correct log message is generated when no users need migration.
This pull request resolves …
=> fix: [AB#12799] update query to use current version dynamically

web/cypress/e2e/auto-tax-filing.spec.ts
This test is consistently flaking an causing ❌ in our CI Pipeline. I think we're all on the same page that this test works inconsistently, might have been someone hastily made, and isn't bringing a ton of value. I'd like to disable this until a time when we're able to better address so that we can more confidently rely on CI as an indicator of codebase health and hopefully not introduce additional breaking changes.
Specifically, this test was causing `Integration Tests - Group 4-1` to fail fairly consistently.
=> Disable Auto-Tax Filing Cypress Test

CHANGELOG.md, package.json
* [AB[#12799](https://github.com/newjersey/navigator.business.nj.gov/issues/12799)] update query to use current version dynamically ([b3b3c51](https://github.com/newjersey/navigator.business.nj.gov/commit/b3b3c516af6dfd9eba901a74d4cd8964b6280679))
* add retry to first cypress test as workaround to race condition causing a failure ([d557f09](https://github.com/newjersey/navigator.business.nj.gov/commit/d557f09bca0bf20b4e9301f9f509230dadd249e9))
* align add-on name with file anem for community-rtk-survey ([791bd97](https://github.com/newjersey/navigator.business.nj.gov/commit/791bd97b824c17b3396d533e4afdb9547f09ad16))
* **deps:** update dependency remove-markdown to v0.6.0 ([5d55d95](https://github.com/newjersey/navigator.business.nj.gov/commit/5d55d95e0b84d8c87ab3dbe82ccfe1144f23d029))
* …
=> chore(release): 2025.6.0 [skip ci]

web/src/components/tasks/business-formation/business/AdditionalProvisions.tsx
Added a space `{" "}` between the Additional Provisions header text, and Optional text
This pull request resolves [#12737](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12737) and `#188924007` in Pivotal Tracker
=> fix: [#188924007 | AB#12737] add space in Additional Provisions header

web/src/components/dashboard/AnytimeActionDropdown.test.tsx, web/src/components/dashboard/AnytimeActionDropdown.tsx
This commit modifies the categories and the anytime actions dropdown from being previously sorted by reverse alphabetical order, to instead be sorted by alphabetical order as described in the ticket.
Before:
After:
This pull request resolves [8670](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/8670).
=> feat: [#188887754 | AB#8670] Alphabetize anytime actions dropdown category order

api/.eslintrc.json, web/.eslintrc.json, web/cypress/e2e/business-formation.spec.ts, web/cypress/e2e/check-license-status.spec.ts, web/cypress/e2e/dashboard.spec.ts, web/cypress/e2e/deferred-onboarding.spec.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts
Skipped all tests that are shown to currently be flaking in [CIrcle CI Insights on Main](https://app.circleci.com/insights/github/newjersey/navigator.business.nj.gov/workflows/build-and-test/tests)
This pull request resolves [#13172](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13172).
Added a `.skip` to any flaky tests. 
Tests skipped in this PR:
* `web/cypress/e2e/business-formation.spec.ts` > `Business Formation [feature] [all] [group2]` > `successfully forms an LLC business`
* `web/cypress/e2e/check-license-status.spec.ts` > `check license status [feature] [all] [group4]` > `searches and checks license status`
* `web/cypress/e2e/dashboard.spec.ts` > `Starting a Business` > `verifies the task screen and mini-roadmap displays`
* …
=> Skipping flaky tests

web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx
https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13378
To investigate this bug and the flaky test, I ran it 200 times to identify the cause of the issue. Out of those 200 runs, there were no failures.
While reviewing another test for foreign nexus in this file, I noticed it includes a waitFor to ensure the error message is removed. Given how this test is structured, the likely cause of the flakiness is that Jest attempts to assert the error message’s removal before it has fully disappeared from the DOM.
To address this, I added a waitFor to ensure proper timing. With this change, I don’t see a need to skip these tests for now. We can continue monitoring them and investigate further if failures occur in the future.
=> chore: [AB#13378] add waitfor to flakey business  formation paginator test

web/src/lib/auth/sessionHelper.ts
We were encountering a TooManyRequestsException: Rate exceeded error in our Cypress tests due to repeated calls to the fetchAuthSession API with the forceRefresh flag enabled. This change resolves the issue by removing the forceRefresh flag, preventing unnecessary session refreshes and avoiding rate limit errors.
This pull request resolves [#13379](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13379).
=> fix: [AB#13379] resolve requestException in fetchAuthSession

web/cypress/e2e/dashboard.spec.ts, web/cypress/e2e/deferred-onboarding.spec.ts
Quick fix to skip a flaky test that was missed in the last PR for flaky tests
Added a `.skip` to a group of tests in `deferred-onboarding.spec.ts` and `dashboard.spec.ts`
=> Skip missed flaky tests

api/jest.config.ts, api/test/setupJestDynalite.ts, shared/src/test/setupRandomSeed.ts, web/jest.config.ts, web/src/components/Header.test.tsx, web/src/components/dashboard/SidebarCardsList.test.tsx, web/src/components/data-fields/Industry.test.tsx, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/business/BusinessStep.test.tsx, web/src/components/tasks/business-formation/business/MainBusinessAddressNj.test.tsx, web/src/components/tasks/business-formation/getErrorStateForFormationField.test.ts, web/src/components/tasks/business-formation/review/ReviewStep.test.tsx, web/src/lib/domain-logic/getNavBarBusinessTitle.test.ts, web/test/customJsdomEnvironment.ts, web/test/pages/profile/profile-shared.test.tsx
This commit
- For each test in `web/`, choose a random seed, and seed all subsequent calls to `Math.random()` in the test with the seed
- Logs this randomly chosen seed to the console if the test fails
It also
- Modifies all test names within `web` to be unique
- Refactors the Math.random() seeding code from `api/` to `shared/`, breaking up the jest-dynalite setup in `api/`
This was done for `api` in https://github.com/newjersey/navigator.business.nj.gov/pull/9937. The intention is to do this for cypress as well, but that will take more finagling.
This pull request contributes to [#12716](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12716).
- Seeds each test individually with a different random seed, by doing so in a `beforeEach` specified in the …
=> feat: [AB#12716] Enable reproducing test randomness in `web/`

README.md, api/test/customNodeEnvironment.ts, web/cypress/e2e/multiple-businesses.spec.ts, web/cypress/support/e2e.ts, web/test/customJsdomEnvironment.ts
This commit
- For each Cypress test, choose a random seed, and seed all subsequent calls to `Math.random()` in the test with the seed
- Logs this randomly chosen seed to the console if the test fails
- Documents in the README how to find the random seed and use it to run tests locally
It also skips `multiple-businesses.spec.ts` as we've discussed about skipping flaky tests.
This commit resolves #[12716](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12716).
- Seeds each test individually with a different random seed in a `beforeEach`, and logs if a test fails in an `AfterEach`
This approach differs from those taken for unit tests because the cypress test runner mocha, [unlike the unit test runner jest](https://stackoverflow.com/questions/42000137/check-if-test-f …
=> feat: [AB#12716] Enable reproducing test randomness in Cypress

web/src/lib/auth/signinHelper.test.ts, web/src/lib/auth/signinHelper.ts
Added logic to `onGuestSignin` in `signinHelper.ts` for users coming from `/login` that click `Sign up and link your myNewJersey account`. If onboarding is completed, it will route users to `/account-setup`, if not, it will route to `onboarding`. Added relevant tests to `signinHelper.test.ts`
This pull request resolves [#13427](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13427).
1. Run navigator, click on the `Log In` button with no user data, then click `Sign up and link your myNewJersey account`. Should route directly to `onboarding`
2. Run navigator, click on the `Get Started` button. Complete steps 1 and 2 of onboarding. Directly route to `/login` and click `Sign up and link your myNewJersey account`. Should route directly to  `account-setup`
=> Updated routing from /login to /account-setup for users with completed onboarding

web/next.config.js
[More info](https://developer.chrome.com/docs/devtools/javascript/source-maps) if you haven't utilized source maps before. This can be extremely helpful when stepping through and debugging code that is hard to manually test locally due to mocked services, integrations, etc.
This pull request resolves [#13080](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13080).
Open dev tools on test or dev and `command+p` your way to some files!
=> chore: [AB#13080] enable source maps in the build for testing and dev deploys

content/src/fieldConfig/njeda-fundings-onboarding.json, web/public/mgmt/config.yml, web/src/pages/njeda.tsx, web/test/pages/njeda.test.tsx
This pull request resolves [#13166](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13166).
1. Go to localhost:3000/njeda
2. Sign up for a business in the cannabis industry
3. You should see no fundings and an alert indicating that
=> feat: [AB#13166] add alert when no fundings are applicable on njeda fundings page

api/src/db/DynamoDataClient.ts, api/src/functions/encryptTaxId/app.ts, api/src/functions/express/app.ts, api/src/functions/migrateUsersVersion/index.ts, api/src/functions/updateExternalStatus/app.ts
This PR addresses issues related to provisioned throughput limits on our DynamoDB table, which caused migration failures due to exceeding the configured limits.
1. Reduced batch size from the previous value to 25 to minimize throttling.
2. Updated processBatch to use Promise.allSettled, ensuring partial failures don’t halt the entire migration process.
3. Increased Lambda invocation frequency from a weekly schedule to every 5 minutes daily until all users are migrated in production only. 
4. The previous weekly updates, especially in production, is insufficient to complete the migration in a reasonable timeframe.
5. This change allows us to process users more gradually while working within throughput limits rather than relying on a single large execution.
6. Updated the dataLogger path …
=> fix: [AB#12799] update invocation freq in prod for migrateusersVersion

web/src/components/dashboard/AnytimeActionDropdown.test.tsx, web/src/components/dashboard/AnytimeActionDropdown.tsx
Adds the ability for up and running poppies to see carnival related permits based on answers to non-essential questions
This pull request resolves [#6768](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/6768).
1. Create a Poppy user in the entertainment industry
2. Proceed to up and running
3. Answer yes to the two carnival non-essential questions
4. You should see 2 carnival related Anytime Actions
=> feat: [AB#6768] add carnival permits for up and running poppies

api/src/client/ApiTaxClearanceCertificateClient.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v159_remove_entity_id.ts, content/src/fieldConfig/tax-clearance-certificate-step3.json, shared/src/taxClearanceCertificate.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/public/mgmt/config.yml, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepThree.tsx
We add a migration v159 to remove the field `entityId` from taxClearanceCertificateData. This PR also makes changes to the v158 migration because it was missing `taxClearanceCertificateData`, which was added in v157.
This pull request is a part of [#7713](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7713) (see Dev Notes section), though it does not resolve it.
Ran the migration script to generate the v159 file, then filled in the function `migrate_v158Business_to_v159Business`. Used some intermediary types (prefixed with FOR_MIGRATION_ONLY) to avoid a TS error.
When running the app locally, run `yarn dynamo` and visit localhost:8001 to see inside your local DynamoDB tables. If you view the users table, you should see that your user is at `version: 159` and …
=> Remove entityId from tax clearance data

web/cypress/e2e/profile.spec.ts
This test currently provides no value because we ignore it when it fails. See ticket https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13889 for fixing it.
=> chore: [AB#13889] Skip flaky integration test

api/src/client/ApiTaxClearanceCertificateClient.test.ts, api/src/client/ApiTaxClearanceCertificateClient.ts, shared/src/taxClearanceCertificate.ts, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepThree.tsx
This commit renames SYSTEM_ERROR -> NATURAL_PROGRAM_ERROR, as a prefactor for #[7714](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7714).
`SYSTEM_ERROR` currently specifically refers to the `"Error calling Natural Program. Please try again later."` message returned by the taxation API. I'm understanding that this refers to a service, Natural Program, upstream of the taxation service having an error.
In working on this, I kept seeing `SYSTEM_ERROR` and being confused whether it's our system (api) error, their taxation system error, or the further upstream error. I think it's the last one, but when I see `SYSTEM_ERROR`, my first guess would be our system or their system, not a third up the line.
I think this is important to distinguish as the error path for the …
=> feat: [AB#7714] Tax Clearance rename SYSTEM_ERROR -> NATURAL_PROGRAM_ERROR

package.json, web/package.json, yarn.lock
In working with @jennyverdeyen, we identified a possible issue with our current version of Cypress (v13.7.0) not running on the most recent version of Mac OS. In our testing, it seems more recent versions of Cypress launch and execute without issue. This work upgrades our version of Cypress to hopefully mitigate any further local development issues.
Upgraded dev dependencies in `/package.json` and `web/package.json`. Pushed to remote branch to test CI pipelines.
Cypress tests should run and pass in `local` and in CircleCI.
- Local - pull the code, install the dependencies (install script or `yarn` whatever you like), run Cypress tests locally …
=> Upgrade Cypress to v 14.3.0

.gitignore, package.json, prettier.config.mjs, scripts/merge-decap-config.ts, web/decap-config/collections/00_allCollections.yml, web/decap-config/config-base.yml, web/package.json
NOTE: Before merging, I need to rebase with Main and move everything from the public/config.yml file to the individual .yml files in the decap folder.
https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12854/
This PR adds a script that merges YAML config files for the CMS.
•	It takes a config-base.yaml file and combines it with the .yaml files in the collections/ folder.
•	The result is a single file: web/public/mgmt/config.yml, which is used by the CMS.
The collection files need to start with a two-digit number like 00 or 01. This controls the order they appear in the CMS sidebar. Without this, the sidebar can show things in a random or confusing order.
We also added Prettier scripts to format:
1.	The input YAML files
2.	The final output file
To run everything …
=> chore: [AB#12854] split yaml into multiple files

api/src/client/ApiTaxClearanceCertificateClient.test.ts, api/src/client/ApiTaxClearanceCertificateClient.ts, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceDownload.tsx
This commit
- Throws an explicit error if the taxation service returns a non-array for the certificate, or an empty array
- Uses Node's `URL` instead of `window.URL`
Following up on feedback from https://github.com/newjersey/navigator.business.nj.gov/pull/10087
This commit resolves #[13315](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13315).
=> feat: [AB#13315] Tax Clearance Download PR Feedback

web/src/components/tasks/anytime-action/AnytimeActionSwitchComponent.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateElement.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceDownload.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepOne.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepThree.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceStepTwo.tsx
This pull request resolves [#13772](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13772).
This PR refactors the Tax Clearance Certificate test to replace data-testid usage with more accessible queries using getByRole, wherever applicable.
•	Replaced data-testid selectors with getByRole or similar accessible queries.
•	Updated relevant helper functions to support this transition.
•	In areas like the Review page, where content updates dynamically and no semantic tags are available (e.g. just <div>s), data-testid usage is retained — which is the recommended practice for dynamic text blocks.
•	Within the HorizontalStepper component, used getAllByRole("tab") to interact with the stepper tabs.
•	⚠️ Note: This component currently has an incorrect aria-label, causing …
=> chore: [AB#13772] replace data-testid with preferred matchers for tax clearance cert tests

api/src/db/dynamoUserDataMigration.test.ts, web/cypress/e2e/dashboard.spec.ts, web/src/components/njwds-extended/FileInput.tsx, web/src/components/profile/ProfileErrorAlert.tsx, web/src/lib/auth/sessionHelper.ts, web/src/lib/static/admin/findDeadLinks.test.ts, web/src/lib/static/mockHelpers.ts, web/src/pages/account-setup.tsx, web/test/pages/cms.test.tsx
Existing usages of `ban-ts` without justifying comments seem to have facilitated unintentional propagation of disables in the codebase, see [this discussion](https://njcio.slack.com/archives/C04J8MTJNS2/p1745266548347089?thread_ts=1745266544.420649&cid=C04J8MTJNS2). Added comments to existing usages as a warning not to propagate.
=> chore: [AB#0000] add warning to existing ts disable usages

.husky/commit-msg
Removes the requirement to include a ticket number in the commit message.
n/a
We have historically allowed engineers to make commits without including a ticket number. This work brings that back.
You should be able to make a commit without a ticket ID
EX: `feat: this is my commit`
If you do include a ticket number, we should still enforce the following
EX: `feat: [AB#1234] this is my commit`
=> Remove ticket number requirement from pre-commit

web/src/lib/cms/fields/writeoncereadonlynospacefield.tsx
this is an impromptu bug that came as a result of a content person putting capitals in an ID, 
This broke our system because the ID had capital letters but the file name (which is suppose to match the ID) did not. 
This pull request resolves [#14182](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14182).
I decided to make it so ID's from the content side are forced to be lower case as well. 
Go to the cms locally and try to type in capital letters into the ID field and see that you can't (it automatically lower cases them)
I could have taken the opposite approach and tried to get the filenames to save with uppercase letters but I didn't for a few reasons. 
1) I think this is easier
2) I think decap might controll that so it may be harder to manipulate
3) our …
=> fix: [AB#14182] capitalization contextual info issue for content repo

api/src/api/decryptionRouter.test.ts, api/src/api/decryptionRouter.ts, api/src/client/AwsEncryptionDecryptionFactory.ts, api/src/functions/express/app.ts, content/src/fieldConfig/tax-id.json, web/decap-config/collections/06-tasks.yml, web/src/components/ShowHideToggleButton.tsx, web/src/components/data-fields/tax-id/DisabledTaxId.test.tsx, web/src/components/data-fields/tax-id/DisabledTaxId.tsx, web/src/components/data-fields/tax-id/SingleTaxId.tsx, web/src/components/data-fields/tax-id/SplitTaxId.tsx, web/src/components/data-fields/tax-id/TaxId.test.tsx, web/src/components/data-fields/tax-id/TaxId.tsx, web/src/components/data-fields/tax-id/TaxIdHelpers.ts, web/src/components/tasks/TaxInput.tsx, web/src/components/tasks/TaxTask.test.tsx, web/src/components/tasks/TaxTask.tsx, web/src/contexts/configContext.ts, web/src/lib/api-client/apiClient.ts, web/src/lib/cms/previews/TaxInputPreview.tsx, web/src/lib/utils/encryption.test.ts, web/src/lib/utils/encryption.ts
#[7782](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7782) involves encrypting and building show/hide functionality for the tax pin component. 
Commit 1: refactors the tax id components to pull out and more generically name common functions that would be reused for the tax pin component. 
- Moves and renames `TaxIdDisplayStatus` to more generically be in `ShowHideToggleButton.tsx`
- Pulls out `getTaxIdEncryptionStatus` -> `isEncrypted`
- Pulls out `taxIdInitialDisplay` -> `getInitialShowHideStatus`
Commit 2: renames names around `AWSEncryptionDecryptionFactory`, the `/api/decrypt` endpoint, and the apiClient call to the endpoint to more generically refer to encryption and decryption without specifying `tax`. Does not touch anything higher-level than that, …
=> chore: [AB#7782] Tax Id Prefactor for Tax Pin

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v162_add_hashed_taxid_to_userdata.ts, shared/src/profileData.ts, shared/src/test/factories.ts, shared/src/userData.ts
Adds a migration to add migration to add a hashed tax ID to the userData structure.
This pull request resolves [#14309](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14309).
=> feat: [AB#7867] add migration to add hashed tax ID to userData structure

.prettierrc, web/decap-config/config-base.yml
Reverts newjersey/navigator.business.nj.gov#10314
=> Revert "chore: correct .prettierrc syntax and simplify Markdown formatting rules"

api/src/api/taxClearanceCertificateRouter.test.ts, api/src/api/taxClearanceCertificateRouter.ts, api/src/client/ApiTaxClearanceCertificateClient.test.ts, api/src/client/ApiTaxClearanceCertificateClient.ts, api/src/domain/types.ts, api/src/domain/user/encryptFieldsFactory.test.ts, api/src/domain/user/encryptFieldsFactory.ts, api/src/functions/express/app.ts, shared/src/test/factories.ts, web/src/components/data-fields/TaxPin.test.tsx, web/src/components/data-fields/TaxPin.tsx, web/src/components/data-fields/tax-id/TaxId.test.tsx, web/src/components/data-fields/tax-id/TaxId.tsx, web/src/components/filings-calendar/tax-access/TaxAccessStepTwo.test.tsx, web/src/components/filings-calendar/tax-access/TaxAccessStepTwo.tsx, web/src/components/tasks/TaxInput.tsx, web/src/components/tasks/TaxTask.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/helpers.ts, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/CheckEligibility.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx, web/src/lib/cms/previews/ProfileFieldsPreview.tsx, web/src/pages/profile.tsx, web/stories/Molecules/textfields/OneEncryptedFieldTextField.stories.tsx, web/stories/Molecules/textfields/TwoEncryptedFieldTextField.stories.tsx, web/test/mock/mockEncryptFields.ts, web/test/mock/withStatefulData.tsx, web/test/pages/profile/profile-owning.test.tsx, web/test/pages/profile/profile-starting.test.tsx
Previously, the tax id and tax pin fields on tax clearance were stored as plain text. A prior PR had added the `encryptedTaxId` and `encryptedTaxPin` fields on tax clearance data, but they were not yet in use. Tax id and pin on the profile were already encrypted.
This PR updates the tax id and pin fields in tax clearance to also be encrypted. This involves:
- When the user saves tax clearance data, mask and encrypt the tax id and pin fields
- Decouple the `<TaxId/>` and `<TaxPin/>` components from the assumption that they are always pulling from the profile copy of tax id and tax pin
- Decrypt the encrypted tax id and pin before sending to the taxation API
After this, in both profile and tax clearance, all tax ids and pins should be masked and encrypted at rest while in the database. This …
=> feat: [AB#12793] Encrypt Tax Clearance ID and PIN

web/src/components/tasks/TaxInput.tsx, web/src/components/tasks/TaxTask.test.tsx
Bug was introduced in https://github.com/newjersey/navigator.business.nj.gov/pull/10273#discussion_r2076164682. Turns out there is a situation where we update `business` without unmounting! See https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12793#13715563 for noticing the bug.
Added a test to enforce this behavior.
This pull request resolves #[12793](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/12793).
Previously, 
- enter as poppy
- select business structure
- dashboard task "Register Your Business for State Taxes and Employer Purposes"
- fill in tax id, click save
- you get this weird thing:
Now, it correctly sets to hidden password view on save
=> feat: [AB#12793] Fix password view bug in tax task (separate from profile or tax clearance)

web/src/components/tasks/business-formation/contacts/RegisteredAgent.tsx
There was a character limit error message appearing for the user in relation to the Office City field on the Registered Agent section of the Contacts tab on the Check Available Names and Form Your Business screen. The fix with the smallest overhead was to change the addressCity to show the `name` rather than `displayName`. Increasing the char limit on the validations was not possible because it would cause issues on the Department of Treasury side. 
This pull request resolves [#7327](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7327).
=> fix: [AB#7327] fix agentAddressCity validation

web/src/pages/profile.tsx
PR #10367 accidentally introduced a bug that initialized whether to show/hide the profile tax pin based on the tax pin in tax clearance. It should instead be based on the pin in profile.
Will fast follow with a test, but I wanted to get this fixed before demo tomorrow.
This commit resolves #[7782](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7782).
- New business
- Go to profile, reference numbers, fill in tax pin, hit save
- Should show password view, defaulting to the "Show" button
=> feat: [AB#7782] Fix profile tax pin init view

api/src/client/ApiTaxClearanceCertificateClient.test.ts, api/src/client/ApiTaxClearanceCertificateClient.ts, content/src/fieldConfig/tax-clearance-certificate-step3.json, shared/src/taxClearanceCertificate.ts, web/decap-config/collections/10-anytime-action.yml, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateAlert.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificateAlert.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Review.tsx
Added specific human readable error messages for all possible error responses from the Tax API. 
This pull request resolves [#7751](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7751).
A `getTaxClearanceErrorMessage` function was added to `AnytimeActionTaxClearanceCertificateAlert.tsx`. All of the values returned from this function were added to CMS for easy future updates. Tests were added to assure appropriate error responses are shown. 
1. Run navigator and navigate to `localhost:3000`
2. Login to navigator
3. Select an up and running business
4. From the task dropdown on the dashboard select the option to Get Tax Clearance Certificate
5. Enter the values from `wiremock/.../tax-clearance-success.json`
6. Submit, and you should see the success screen
7. …
=> feat: [AB#7751] tax clearance specific error messges

api/businesses-dynamodb-schema.json, api/src/db/DynamoBusinessDataClient.ts
In #10404 we added the ability to hash a piece of data, and using this functionality to hash the tax ID within the user's `profileData`. This work adds the `hashedTaxId` as a global secondary index on the business table so that DynamoDB can make queries to determine if a tax ID has been previously used.
This pull request resolves [#14310](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14310) a work item in service of completing [#7867](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/7867).
Updated the DynamoDB schema file used by Serverless to configure the business table.
After adding a tax ID in the profile, the hashed tax ID should be available in the user's profile data. When interacting with the database, `hashedTaxId` should …
=> Add hashedTaxId as a global secondary index on business table

api/src/client/AwsCryptoFactory.ts
Storing the salt as an environment variable is causing issues with Serverless deploy. We need to come up with a better solution.
Skipping salt decrypt for now in lower environments.
=> Skip salt decrypt

api/src/client/MyNjSelfRegClient.test.ts, api/src/client/MyNjSelfRegClient.ts
This change adds improved logging for myNJSelfRegError to enhance monitoring and observability of the myNJ login process. Robust logging is essential to make CloudWatch alerts more effective, enabling faster detection of login failures and improving site resilience.
Specifically, this prepares for CloudWatch metric and alarm creation to track drop-offs in user logins, addressing a key site performance concern.
Additionally, the test suite is updated to validate that network failures are properly logged with the myNJSelfRegError tag and that errors are correctly returned.
- Updated api/src/client/MyNjSelfRegClient.ts to enhance error logging with a myNJSelfRegError identifier.
- Added a test in api/src/client/MyNjSelfRegClient.test.ts to validate error logging and handling on network …
=> feat: [AB#8605] add errLog for myNJSelf-Reg and test for fail path

web/src/components/profile/ProfileAddressLockedFields.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/AnytimeActionTaxClearanceCertificate.test.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/CheckEligibility.tsx
Lock BusinessName, Address, and TaxId fields if business has formed. 
This pull request resolves [#13626](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/13626).
Essentially copying over existing logic from Profile page
1. Enter as a starting business
2. Go through formation (enter business name and address in this step)
3. Confirm that Address and BusinessName are locked in the tax clearance anytime action
4. Go to the tax calendar, and enter the taxId to confirm tax calendar
5. Go back to Tax Clearance and confirm that the TaxId is locked
=> feat: [AB#13626] Lock Fields in Tax Clearance

web/src/components/tasks/anytime-action/tax-clearance-certificate/TaxClearanceSteps.tsx, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/Requirements.tsx, web/src/lib/auth/signinHelper.test.ts, web/src/lib/auth/signinHelper.ts, web/src/lib/domain-logic/routes.ts
This adds a returnToLink to the business preferences when a guest user tries to move forward with Tax Clearance steps and are prompted with a sign-in modal.
Note that the returnToLink functionality only works when the guest user *registers* an account, not when they sign in with an existing account, because it is tied to their business data which gets replaced if they log in with an existing user.
This PR also addresses a bug with the returnToLink logic in the signinHelper, where the redirect won't work if the user passes through the account setup page - which occurs in this flow. Now, the returnToLink should be correctly passed to the postSelfReg api call.
This pull request resolves [#14471](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14471).
=> feat: [AB#14471] update returnToLink when showing sign-in/register modal on tax clearance steps

api/serverless.ts, api/src/libs/healthCheck.ts
This PR adds the `API_BASE_URL` environment variable to the Lambda configuration. Previously, the variable was missing, causing the Lambda to default to the fallback (production) API endpoint. With this change, each environment will now correctly use its respective API_BASE_URL, ensuring requests are routed appropriately in lower environments.
=> chore: [AB#0000] update serverless to include API_BASE_URL

web/src/components/njwds-extended/callout/Callout.test.tsx, web/src/components/njwds-extended/callout/CalloutLayout.tsx
We were having an issue where the callout component required body text to use the bulleted icon text attributes. 
This pull request resolves [#14891](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14891).
run the app
run the cms proxy
go into tasks, add a callout block to markdown field
Make it a quick reference callout
see that if you add header text and then add to any of the bottom attributes (the ones with Icon links)
that they render without needing body copy.
=> fix: [AB#14891] callout icon bullets will show without needing body text

api/jest.config.ts
Fixed an issue where health check tests were failing locally due to a missing environment variable. Updated the just.config file to ensure the necessary environment variable is set during local test runs.
=> chore: add API_BASE_URL to process.env in jest config to fix local failing test

web/src/components/data-fields/non-essential-questions/CertificationsAndFundingNonEssentialQuestions.test.tsx, web/src/components/data-fields/non-essential-questions/CertificationsAndFundingNonEssentialQuestions.tsx, web/src/components/profile/PersonalizeYourTasksTab.tsx, web/src/components/profile/profileDisplayLogicHelpers.test.ts, web/src/components/profile/profileDisplayLogicHelpers.ts, web/src/pages/profile.tsx
Adds certifications and fundings questions to Personalize My Tasks accordion
This pull request resolves [#14384](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14384).
1. Go through onboarding and navigate to the profile, and click Personalize My Tasks
2. Click on the Certificatiosn and Funding Accordion
3. If you are a starting business, you should only see the municipality question
4. If you are an operating business, you should see all three questions
=> feat: [AB#14384] Add certifications and funding accordion details

web/src/components/profile/PersonalizeYourTasksTab.test.tsx, web/src/components/profile/PersonalizeYourTasksTab.tsx, web/src/pages/profile.tsx
fix accordion date of formation bug
This pull request resolves [#14383](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14383).
=> fix: [AB#14383] fix accordion date of formation bug

web/src/components/tasks/ElevatorRegistrationTask.test.tsx, web/src/lib/utils/analytics-base.js, web/src/lib/utils/analytics.test.ts, web/src/lib/utils/analytics.ts
The analytics were generally broken (in that data wasn't being passed from code to GTM to GA4). 
This ticket is the code changes involved in solving this.
changes have already been made in GTM to support this and GA4 did not require any changes
NOTE: we will also have to update an environment variable in all environments when this is deployed to get the desired effect as well. 
This pull request resolves [#14270](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14270).
I would say probably don't bother. 
What you would need to do involves running this locally, 
Opening google tag manager,
opening the preview and putting in local host as the address,
then watching events come through and being collected / processed
Then open the GA4 debugger and see that events …
=> feat: [AB#14270] fixing broken analytics

api/src/client/ApiFormationHealth.ts, shared/src/formationData.ts, shared/src/test/formationFactories.ts
This change addresses the health check error from the Formation service. The Formation endpoint expects a contactEmail to be included in the request body, but our healthCheck function was not providing it.
Updated the health check logic to include a placeholder contactEmail in the request body when checking the Formation service. Without the contactEmail, the Formation service responds with an error, causing the health check to fail. This update ensures the expected field is passed, allowing the health check to complete successfully.
=> fix: resolve webservice/formation bug

content/src/anytime-action-tasks/demo-only.md, content/src/roadmaps/industries/demo-only.json, content/src/roadmaps/nonEssentialQuestions.json, web/decap-config/collections/05-roadmap.yml, web/src/components/dashboard/AnytimeActionDropdown.test.tsx, web/src/components/dashboard/AnytimeActionDropdown.tsx, web/src/components/dashboard/Dashboard.tsx, web/src/components/dashboard/anytimeActionsBuilder.test.ts, web/src/components/dashboard/anytimeActionsBuilder.ts, web/src/lib/domain-logic/getNonEssentialQuestionAnytimeActions.test.ts, web/src/lib/domain-logic/getNonEssentialQuestionAnytimeActions.ts, web/src/lib/static/loadAnytimeActionTasks.test.ts, web/src/lib/static/loadAnytimeActionTasks.ts, web/src/lib/types/types.ts, web/src/lib/utils/tasksMarkdownReader.ts, web/test/demoOnly.test.ts, web/test/factories.ts
Users of particular industries are presented with Non-Essential Questions in their Business Profile. Answers to these questions may modify their experience most commonly by adding tasks to their roadmap. This work allows content team members to also add Anytime Actions the same way they may include a roadmap `addOn` to appear to a user.
This pull request resolves [#15159](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15159).
**CMS Changes**
A content team member can add a series of Anytime Actions to a Non-Essential Question.
- Updated the CMS config to include Anytime Action Tasks as a multi-select in the Non-Essential Questions collection
- Added `Anytime Actions[]` to the Non-Essential Question type definition
**End User Changes**
When a user answers "yes" …
=> Add Anytime Actions with Non-Essential questions

web/src/components/dashboard/anytimeActionsBuilder.test.ts, web/src/components/dashboard/anytimeActionsBuilder.ts
The previous PR #10766 incorrectly added anytime actions if the user had provided any answer to a non-essential question. This work properly removes the anytime action if the user responds "no".
This pull request resolves [#15159](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15159).
See "Steps to Test" in #10766.
=> Remove anytime actions when users answer 'no' to non-essential questions

api/src/client/dynamics/license-status/RegulatedBusinessDynamicsLicenseHealthCheckClient.ts
Added a log to continue with the debugging efforts on this issue with RGBDynamicsLicense.
=> chore: add log statement to determine if  accessToken is defined

content/src/renewal-calendar-events/xray-renewal.md, web/decap-config/collections/08-calendar.yml, web/src/lib/search/searchBusinessFormation.ts, web/src/lib/search/searchRenewalCalendarEvents.ts, web/src/pages/mgmt/search.tsx
Certain collections were not showing up in the search result including "Biz Form - DBA Tasks ", "Xray Renewal Calendar and Event", "Roadmaps - Industries"
This pull request resolves [#15014](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15014).
For "Roadmaps - Industries" I added the to the roadmapsCollection so when passed it would be rendered.
For "Xray Renewal Calendar Event", I corrected the incorrectly name filename so it would directed to page
For Business formation, I implemented search function and rendered the matches
Enter "register your business name"
It will output related pages from business formation
=> fix: [AB#15014] Resolve Untracked Sections in CMS

content/src/mappings/sectors.json, content/src/roadmaps/nonEssentialQuestions.json, shared/src/sector.ts, web/decap-config/collections/12-misc.yml, web/src/components/dashboard/AnytimeActionDropdown.tsx, web/src/components/data-fields/non-essential-questions/IndustryBasedNonEssentialQuestionsSection.test.tsx, web/src/components/data-fields/non-essential-questions/IndustryBasedNonEssentialQuestionsSection.tsx, web/src/lib/static/loadAnytimeActionLicenseReinstatements.test.ts, web/src/lib/types/types.ts, web/src/lib/utils/non-essential-questions-helpers.ts, web/src/lib/utils/tasksMarkdownReader.ts, web/src/pages/profile.tsx, web/test/factories.ts
In #10766 we added the ability for a user's response to a Non Essential Question (NEQ) to add an Anytime Action. This work allows a NEQ to be added to a sector. This allows users who enter the application as an "Up and Running" business who only self-identify with a sector to have NEQs and are then granted a richer experience.
Additionally, this adds a specific NEQ to the "Other Services" industry.
This pull request resolves [#15159](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15159).
- Added NEQs to the Sector type definition and CMS config
- Updated `IndustryBasedNonEssentialQuestionsSection` to display NEQs associated with a sector
- Create a new "Up and Running" business in the "Other Services" sector
- Navigate to the business profile
- You should see a …
=> Add Non Essential Questions to industry sectors

api/src/functions/express/app.ts, api/wiremock/__files/cigarette-license-get-order-success.json, api/wiremock/__files/cigarette-license-prepare-payment-fail.json, api/wiremock/__files/cigarette-license-prepare-payment-success.json, api/wiremock/mappings/cigarette-license-get-order-success.json, api/wiremock/mappings/cigarette-license-prepare-payment-fail.json, api/wiremock/mappings/cigarette-license-prepare-payment-success.json, api/wiremock/mappings/cigarette-license-send-email-success.json
Adding a few wiremocks for the three api calls in Cigarette License Client
This pull request resolves [#15504](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15504).
Added a success and fail for the main `prepare-payment` call, with related response json files. For `get-order-by-token` and `send-email` a simple success response was mocked to make front end work easier to work on.
=> chore: [AB#15504] adding wiremocks for cig license

api/serverless.ts
Adding all Cigarette License env vars to `serverless.ts` for local development.
=> fix: [AB#15504] add cig license env vars to serverless

web/src/components/data-fields/address/UnitedStatesAddress.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.tsx
Locks Business Address "State" input field for cigarette license applicants.
This pull request resolves [#14930](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14930).
=> feat: [AB#14930] lock state input for business address in cigarette license step 2

content/src/fieldConfig/cigarette-license-shared.json, web/decap-config/collections/06-tasks.yml, web/src/components/tasks/cigarette-license/CigaretteLicense.tsx, web/src/components/tasks/cigarette-license/CigaretteLicenseAlert.test.tsx, web/src/components/tasks/cigarette-license/CigaretteLicenseAlert.tsx, web/src/components/tasks/cigarette-license/fields/ContactInformation.tsx, web/src/components/tasks/cigarette-license/fields/MailingAddress.tsx, web/src/lib/cms/previews/CigaretteLicensePreview.tsx
Adds a persistent error alert box on the Cigarette License stepper. 
This pull request resolves [#14009](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14009).
Created `CigaretteLicenseAlert.tsx` and corresponding tests. The component has props for `fieldErrors` that are mapped to config display names. If any field in the CigaretteLicense dataformerror map is invalid, it will show a line item for that field. There is also a separate prop for a submission error that would be shown if the `prepare-payment` api call fails. The line items are also anchor tags that point directly to the field in question. 
1. pull down this branch and start the app locally
2. create a new new jersey business
3. navigate to `http://localhost:3000/tasks/cigarette-license`
4. select a …
=> feat: [AB#14009] cig license alert box

web/src/components/data-fields/address/AddressMunicipalityDropdown.tsx, web/src/components/data-fields/address/NewJerseyAddress.tsx, web/src/components/data-fields/address/UnitedStatesAddress.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.test.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.tsx
Adding optional styling and external validators to the `NJAddress` component to make it usable in Cigarette License
=> fix: [AB#14930] update nj address for cig license

web/src/components/data-fields/address/AddressMunicipalityDropdown.tsx, web/src/components/data-fields/address/NewJerseyAddress.tsx, web/src/components/data-fields/address/UnitedStatesAddress.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.test.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.tsx, web/src/components/tasks/cigarette-license/helpers.ts
Reverting `NewJerseyAddress` back to previous state and updating `UnitedStatesAddress` to have a locked state field option. Updating the `getInitialData` function in `web/src/components/tasks/cigarette-license/helpers.ts` to hard code the `addressState` to `NJ`
=> fix: [AB#14930] update AddressComponents for CigLicense

api/.dependency-cruiser.js, api/package.json, api/src/libs/healthCheck.ts, package.json, yarn.lock
Previously, our health check alarms weren’t showing enough context in Slack notifications. The alerts did not clearly display the failing endpoint or the stage, which made it difficult to quickly identify the root cause and its source.
These changes update the health check flow so that metrics are pushed directly to CloudWatch with Endpoint and Stage as dimensions. This allows Slack notifications to clearly render which endpoint failed in which stage, making troubleshooting much faster.
- Added @aws-sdk/client-cloudwatch dependency
- Updated healthCheck method to publish metrics directly instead of relying on "FAIL" log filters
- Added rule in .dependency-cruiser for @aws-sdk/client-cloudwatch
This pull request resolves [#13034](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_w …
=> chore: [AB#13034] update CloudWatch alarm to track endpoint-level errors

api/src/api/cigaretteLicenseRouter.test.ts, api/src/api/cigaretteLicenseRouter.ts, api/src/client/ApiCigaretteLicenseClient.test.ts, api/src/client/ApiCigaretteLicenseClient.ts, api/src/client/ApiCigaretteLicenseHelpers.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v175_add_payment_complete_to_cig_license.test.ts, api/src/db/migrations/v175_add_payment_complete_to_cig_license.ts, api/wiremock/mappings/cigarette-license-send-email-fail.json, content/src/fieldConfig/cigarette-license-confirmation.json, shared/src/cigaretteLicense.ts, shared/src/userData.ts, web/decap-config/collections/06-tasks.yml, web/src/components/tasks/cigarette-license/CigaretteLicense.test.tsx, web/src/components/tasks/cigarette-license/CigaretteLicense.tsx, web/src/components/tasks/cigarette-license/Confirmation.test.tsx, web/src/components/tasks/cigarette-license/Confirmation.tsx, web/src/lib/api-client/apiClient.ts, web/src/lib/domain-logic/routes.ts
This PR handles two pieces of logic: 
1. After payment for Cigarette License is redirected back to MyAccount from Tyler Tech, the application needs to handle the 4 different redirect options. 
2. Once it has been redirectted back successfully, it loads the Confirmation Page and retrieves the order details via TylerTechs api. Depending on how this api call proceeds, the confirmation screen will either show a Loading Spinner, the Confirmation Screen with all order details, or a Try Again screen.
A small migration was also added this PR to add a `paymentComplete` boolean to the `paymentInfo` of the `cigaretteLicenseData`. This boolean is used to keep track of the state when a user has paid for their cigaretteLicense, but has not received their order details yet. 
This pull request resolves …
=> feat: [AB#13453] cig license payment redirect

web/src/components/tasks/cigarette-license/LicenseeInfo.test.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.tsx, web/src/components/tasks/cigarette-license/helpers.test.ts, web/src/components/tasks/cigarette-license/helpers.ts
Locks pre-populated fields for Cigarette License that come from Formation or Tax Calendar lookup. 
This pull request resolves [#14007](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/14007).
If the user has completed their tax calendar lookup, then the TaxID and Business name are pre-populated and locked for Cigarette License. Similarly, if a user has completed formation then the Business Name and Business Address fields are locked. If the address was not filled out during formation then it is not pre-populated and locked. Helper function was added to `web/src/components/tasks/cigarette-license/helpers.ts` that returns a boolean if the Business Address should be locked. 
1. Create a new retail business
2. Go through formation filling out the name and address
3. …
=> feat: [AB#14007] lock cig license fields

content/src/fieldConfig/dashboard-defaults.json, content/src/fieldConfig/header-defaults.json, web/cypress/e2e/auto-tax-filing.spec.ts, web/cypress/e2e/dashboard.spec.ts, web/cypress/e2e/deferred-onboarding.spec.ts, web/cypress/e2e/group_1_onboarding/accessibility.spec.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-existing-business.spec.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-foreign-business.spec.ts, web/cypress/e2e/group_1_onboarding/onboarding-as-starting-business.spec.ts, web/cypress/e2e/guest.spec.ts, web/cypress/e2e/performance-and-accessability.spec.ts, web/cypress/support/helpers/helpers-profile.ts, web/cypress/support/page_objects/dashboardPage.ts, web/decap-config/collections/09-dashboard.yml, web/decap-config/collections/12-misc.yml, web/src/components/Header.test.tsx, web/src/components/dashboard/DashboardHeader.tsx
removed date and profile link from dashboard. This has proven unnecessary given the evolution of the dashboard over time
This pull request resolves [#15109](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15109).
go to dashboard,
see that there is no date and profile link above the personalize button
=> feat: [AB#15109] removed date and profile link from dashbaord

api/src/client/ApiCigaretteLicenseHelpers.test.ts, web/src/components/tasks/anytime-action/tax-clearance-certificate/steps/CheckEligibility.tsx, web/src/components/tasks/cigarette-license/LicenseeInfo.tsx, web/src/components/tasks/cigarette-license/helpers.test.ts, web/src/components/tasks/cigarette-license/helpers.ts, web/src/lib/utils/taskHelpers.test.ts, web/src/lib/utils/taskHelpers.ts
When a user completes formation without entering an address, the Tax Clearance form becomes unusable. The address field appears locked/disabled, preventing user input, but the form cannot be submitted because the address field is required and blank. User has no way to correct this and complete the Tax Clearance process. This PR address that issue. 
This pull request resolves [#15812](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15812).
=> fix: [AB#15812] fix locked tax clearance address fields

content/src/fieldConfig/profile.json, web/decap-config/collections/12-misc.yml, web/src/components/profile/ProfileNoteForBusinessesFormedOutsideNavigator.tsx, web/test/pages/profile/profile-shared.test.tsx
This pull request resolves [#15155](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15155).
Used the newer `miniCallout` CMS component per design's requests for easy configurability without needing devs
1. Go through onboarding
2. Navigate to the profile page.
3. New callout should visible at the top of the profile container
This uses the same `Note for Businesses Formed Outside Navigator` field as before in the CMS, but updates it to using a CMS content component
=> feat: [AB#15155] convert alert on business profile page to callout

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v177_add_business_name_confirmation.test.ts, api/src/db/migrations/v177_add_business_name_confirmation.ts, content/src/fieldConfig/business-formation.json, shared/src/formationData.ts, shared/src/test/formationFactories.ts, shared/src/userData.ts, web/decap-config/collections/01-business-formation.yml, web/src/components/tasks/business-formation/BusinessFormationPaginator.test.tsx, web/src/components/tasks/business-formation/getErrorStateForFormationField.ts, web/src/components/tasks/business-formation/name/BusinessName.tsx, web/src/components/tasks/business-formation/name/BusinessNameStep.test.tsx, web/src/lib/data-hooks/useBusinessNameSearch.ts, web/test/helpers/helpers-formation.tsx
This PR adds a Confirmation Field to the Formation Business Name Step. If the Business Name is changed or blurred it will force reconfirmation and for checking the availability again. 
This pull request resolves [#15921](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15921).
1. Run the app locally
2. Create a business and navigate to the Formation Screen
3. Blur the Business Name field without typing - an error should appear to inform you to enter a name
4. Once a name is entered that error will change to inform you that `Business names must match`
5. Enter a value in the confirmation field - if they match, the error will change to inform you that you need to check the availability of the name
6. All behavior of the `Check Availability` button is the same as …
=> feat: [AB#15921] adding business name confirmation

api/src/client/ApiCigaretteLicenseClient.test.ts, api/src/client/ApiCigaretteLicenseClient.ts, api/src/client/ApiCigaretteLicenseHelpers.test.ts, api/src/client/ApiCigaretteLicenseHelpers.ts, api/src/client/ApiPowerAutomateClientFactory.test.ts, api/src/client/ApiPowerAutomateClientFactory.ts, api/src/client/CigaretteLicenseEmailClient.test.ts, api/src/client/CigaretteLicenseEmailClient.ts, api/src/domain/types.ts, api/src/functions/express/app.ts, api/src/libs/healthCheck.test.ts, api/src/libs/healthCheck.ts, api/src/libs/ssmUtils.ts, shared/src/test/factories.ts
This work includes a refactor to make a standalone Power Automate client factory, pass a cigarette-specific power automate client to our Cigarette License client, and creates a health check for the cigarette-specific power automate client.
This pull request resolves [#15796](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15796).
- Refactored existing integration with Power Automate for the Cigarette License Application logic
- We now have a Power Automate client with a `health` function that can be configured for future Power Automate integrations
- Added a health check for the Power Automate workflow used by the Cigarette License Application
- Refactored the `runHealthChecks` behavior. It appears as though some log messages were not getting properly handled. …
=> chore: [AB#15796] add health check for Power Automate email client

web/src/components/Content.tsx
[Slack thread for context](https://njcio.slack.com/archives/C02AJKBCH38/p1758724413392569)
A malformed link entered into the CMS markdown revealed that our Content component was not handling undefined children gracefully. Empty markdown links like `[](url)` caused runtime crashes with "Cannot read properties of undefined (reading '0')". This adds checks to handle undefined children/link text and displays the URL when link text is missing, ensuring malformed links are visible to content editors rather than silently ignored.
This pull request resolves [#16198](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/16198).
(http://localhost:3000/mgmt/cms#/collections/contextual-information/entries/certificate-of-amendment) and …
=> chore: [AB#16198] improve content link rendering to better handle empty or malformed link markdown

content/src/display-content/business-formation/nexus/authorize-business-entity.md, web/src/components/tasks/business-formation/DbaFormationPaginator.tsx, web/src/components/tasks/business-formation/NexusFormation.test.tsx
Updates the "Authorize my Business" external link on the third step of formation for an out of state business registering a DBA name, and removes the modal that appears upon clicking the "Authorize my Business" CTA button.
This pull request resolves [#15961](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15961).
See the ADO ticket for steps to get to this formation step:
https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15961
=> feat: [AB#15961] remove before you start modal from dba formation step 3

api/src/client/ApiFormationHealth.ts, api/src/db/migrations/migrations.ts, api/src/db/migrations/v178_add_employer_access.ts, content/src/fieldConfig/employer-rates.json, shared/src/contexts/configContext.ts, shared/src/operatingPhase.ts, shared/src/profileData.ts, shared/src/test/factories.ts, shared/src/userData.ts, web/decap-config/collections/12-misc.yml, web/src/components/employer-rates/EmployerRates.test.tsx, web/src/components/employer-rates/EmployerRates.tsx, web/src/components/employer-rates/EmployerRatesQuestions.tsx, web/src/components/employer-rates/EmployerRatesTemporary.tsx, web/src/lib/cms/previews/EmployerRatesPreview.tsx, web/src/pages/mgmt/cms.tsx, web/src/pages/profile.tsx, web/test/pages/profile/profile-shared.test.tsx
This pull request resolves [#15845](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/15845).
The purpose of this PR is to add a new section to the Numbers tab in Profile. This new section will only appear when a user is in the Up and Running and Up and Running Owning phases.
Scope of this PR
•	Added tests for the Up and Running and Up and Running Owning phases.
•	Introduced a new question: “Have you registered for Employer Access?” (a Department of Labor service to get employer contribution rates).
Behavior
•	If the user selects No: show a button linking them to the registration page.
•	If the user selects Yes: show a different button that will trigger an API call.
•	Note: the actual API call will require additional information that will be handled in a future …
=> chore: [AB#15845] add employer access question

api/package.json, api/serverless.ts, package.json, yarn.lock
This PR upgrades the Serverless Framework to version @serverless/typescript@4.18.2 and updates the AWS Lambda runtime for our functions to nodejs22.x.
- Updated the project to use the latest Serverless TypeScript plugin (4.18.2).
- Updated the Lambda runtime in serverless.ts to nodejs22.x, bringing in the newest Node.js runtime supported by AWS.
- Ensures that AwsLambdaRuntime types now include nodejs22.x for TypeScript type safety.
- No functional changes to business logic; this upgrade primarily focuses on runtime and framework improvements.
This pull request resolves [#16180](https://dev.azure.com/NJInnovation/Business%20First%20Stop/_workitems/edit/16180).
=> chore: [AB#16180] upgrade serverless to nodejs22.x base
